### PR TITLE
LPS-164307 Fix ERC and ID fields mapping on ObjectEntries FDSTable

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPS-164307

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
LGTM :)

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:close

**Pull request closed without merging**
