### PR TITLE
LPS-200998 | Revert LPS-173502

### PR DESCRIPTION
**Pull request by guilhermedcamacho**
https://liferay.atlassian.net/browse/LPS-200998

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:object

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM!! :tada:

**Comment by brianchandotcom** [comment]
@guilhermedcamacho @MarinhoFeliphe merged to master and 102

**Pull request closed without merging**
