### PR TITLE
LPS-163415 Sort by the exception text

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://issues.liferay.com/browse/LPS-163415

Follow-up: https://github.com/brianchandotcom/liferay-portal/pull/123581

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:reevaluate:1277401_5133

**Comment by marcelabc** [comment]
ci:forward

**Comment by naraandrade** [comment]
@marcelabc We have some conflicts in this branch :/

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:forward

**Comment by marcelabc** [comment]
ci:forward

**Comment by marcelabc** [comment]
ci:forward

**Comment by naraandrade** [comment]
@marcelabc Could you please check if the failures are related? Thanks :)

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:forward

**Comment by marcelabc** [comment]
ci:forward

**Comment by gabrielwas** [comment]
```
   Executing commands: curl -X POST -u 'test@liferay.com:test' 'http://test-1-31-56.lax.liferay.com:8080/o/object-admin/v1.0/object-definitions/67172/publish'
[beanshell] 2022-09-26 16:42:34.528 ERROR [http-nio-8080-exec-9][ExceptionMapper:68] null
[beanshell] java.lang.NullPointerException: null
[beanshell] 	at com.liferay.portal.security.permission.ResourceActionsImpl._getCompositeModelName(ResourceActionsImpl.java:625) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.security.permission.ResourceActionsImpl._readModelResources(ResourceActionsImpl.java:946) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.security.permission.ResourceActionsImpl.populateModelResources(ResourceActionsImpl.java:479) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.object.internal.deployer.ObjectDefinitionDeployerImpl._readResourceActions(ObjectDefinitionDeployerImpl.java:377) ~[?:?]
```


This is the error :/ Can we try to reproduce it locally? Just take the json provided by the poshi test and run it.
@marcelabc @naraandrade

**Comment by naraandrade** [comment]
@marcelabc I think you can just send the PR directly to Brian now.

**Comment by marcelabc** [comment]
send to brian: https://github.com/brianchandotcom/liferay-portal/pull/123763

**Pull request closed without merging**
