### PR TITLE
LPS-157215 Remove Feature Flag for LPS-159151/LPS-135404

### PR DESCRIPTION
**Pull request by rebsilva**
Related issue: https://issues.liferay.com/browse/LPS-157215

### CODE REVIEW

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:object

**Review by diogocordeiro — APPROVED** [review]
Issues on Objects suite are test fix

**Review by rodrigopaulino — CHANGES_REQUESTED** [review]
Hi, @rebsilva. Thanks a lot for your work here.
I found (`git grep "LPS-135404"`) a bunch of other places where the feature flag LPS-135404 is being referenced.
Could you please search for the commits that introduce them and use `git revert` on them?
Thanks.

**Comment by rebsilva** [comment]
Sure @rodrigopaulino! I think I just reverted from one story and forgot that another one is using the same feature flag, thanks for the heads up!

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:object

**Comment by rebsilva** [comment]
ci:test:relevant

**Review by rodrigopaulino — APPROVED** [review]
Since it had changes, @rebsilva, we should run the whole suite again and ask for QA's review one more time. 🙂
But as far as code goes, this LGTM! 🎉

**Comment by rodrigopaulino** [comment]
ci:test:object

**Comment by rodrigopaulino** [comment]
@diogocordeiro, feel free to mark this as Good to Go after your second review. Thx!

**Comment by rebsilva** [comment]
Hi @rodrigopaulino! Yes I've already run the ci:test:object suit and the results are above, I ran the relevant again because it was failing, thanks!

**Comment by rodrigopaulino** [comment]
> Hi @rodrigopaulino! Yes I've already run the ci:test:object suit after the changes and the results are above, I ran the relevant again because it was failing, thanks!

Oh! Thanks for pointing it out, @rebsilva. Sorry I ran it again. Unfortunately I can't stop it now because CI has a limit of how many pages it can see to stop a suite from running and I believe we already have passed that threshold.
Keep it up!

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:forward

**Comment by rodrigopaulino** [comment]
Manually forwarded: https://github.com/brianchandotcom/liferay-portal/pull/123296

**Pull request closed without merging**
