### PR TITLE
LPS-196320

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
cc @markocikos @dsanz

**Comment by gabrielwas** [comment]
sent here: https://github.com/brianchandotcom/liferay-portal/pull/140860

**Comment by gabrielwas** [comment]
Brian asked for a follow up pull, just sent here: https://github.com/brianchandotcom/liferay-portal/pull/140865

**Comment by marcelabc** [comment]
Brian merged: https://github.com/brianchandotcom/liferay-portal/pull/140860

**Pull request closed without merging**
