### PR TITLE
LPS-186839 Use ObjectFieldBuilder

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:stop

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:object

**Comment by samuelromeiro** [comment]
@mateussgn can you please check the tests for us to forward the PR to Brian? 
The subtasks has been approved in [here](https://liferay.slack.com/archives/C048YNC5GRK/p1687203697420589).

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/136848

the problem was only in the integration test.

cc: @samuelromeiro @mateussgn @evanilson-santana

**Pull request closed without merging**
