### PR TITLE
LPS-193250 Publish all Children Objects in a row during their Root Object publication. Block standalone publication for children Objects

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPS-193250

### CODE REVIEW

**Comment by mateussgn** [comment]
Hey @p-albuquerque,
Can you solve the conflict?

**Review by MarinhoFeliphe — CHANGES_REQUESTED** [review]

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:sf

**Review by MarinhoFeliphe — CHANGES_REQUESTED** [review]

**Comment by MarinhoFeliphe** [comment]
Hi @p-albuquerque I've just asked for one little change,

Nice pull request BTW, good job! :tada:

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:object

**Comment by p-albuquerque** [comment]
Directly sent: https://github.com/brianchandotcom/liferay-portal/pull/140298

**Pull request closed without merging**
