### PR TITLE
[TECHNICAL SUPPORT] LPS-170195 No NotificationRecipient entries created during upgrade because of wrong column

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Motivation
=======
[NotificationRecipientTable](https://github.com/liferay/liferay-portal/blob/master/modules/apps/notification/notification-api/src/main/java/com/liferay/notification/model/NotificationRecipientTable.java) creates the table with the className column.
This is incorrect because the NotificationRecipient model has a className**Id** field instead of className.
Because of this, the insert [statement](https://github.com/liferay/liferay-portal/blob/master/modules/apps/notification/notification-service/src/main/java/com/liferay/notification/internal/upgrade/v3_0_0/NotificationRecipientUpgradeProcess.java#L63) in the upgrade process will fail due to the mismatching columns.

`java.sql.BatchUpdateException: Unknown column 'classNameId' in 'field list'`

No entries will be inserted into the NotificationRecipient table.

https://issues.liferay.com/browse/LPS-170195

Proposed Solution
========
I [switched](https://github.com/liferay-objects/liferay-portal/commit/c8a28dd207c6299d38a0122b979495c28c8a2fb0) className to classNameId in the create table statement in NotificationRecipientTable.java.
However, this will not solve the issue for users who have already upgraded.

Alternative Solutions
========
I considered adding an upgrade process that creates the NotificationRecipient entries after the fact, but because there is no data to establish the NotificationTemplate-NotificationRecipient-NotificationRecipientSetting connection, this is not possible.

Steps to Verify
========
Please consult the linked LPS for reproduction steps.

Thank you and best regards,
István

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
Hello @IstvanD,

I believe we should keep your fix, I check the failures and they're not related except by the one about [semantic-versioning](https://testray.liferay.com/home/-/testray/case_results/2102420517?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2102420242%26cur%3D1%26delta%3D200%26tab%3Druns%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) that I'm not sure if is related, could you please take a look at this one?

Thank you and best regards,
István

**Comment by IstvanD** [comment]
Hi @MarinhoFeliphe 
I have checked the semver failures and they are not related to the fix.

Unfortunately, I cannot send pull requests to Brian directly.
Could you please send it to him?

Thank you and best regards,
István

**Comment by MarinhoFeliphe** [comment]
@IstvanD Sure!

I'll forward it today

Thank you,
Feliphe

**Comment by MarinhoFeliphe** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/127314

**Pull request closed without merging**
