### PR TITLE
LPS-160513 Make sure the parameters have the predefinedValues key

### PR DESCRIPTION
**Pull request by seltong**

### CODE REVIEW

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
The test failures are not related to the solution.

**Comment by seltong** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@seltong see 7b9065ce72ee08037dc07ecc901ee1f361e7376e

**Comment by brianchandotcom** [comment]
@seltong merged to master and the temp branch.

**Comment by seltong** [comment]
I closed this pull request because it was merged to master.

**Pull request closed without merging**
