### PR TITLE
LPS-202602 Unclear error message when creating same relationship name

### PR DESCRIPTION
**Pull request by carolmariaabb**
JIRA Ticket: [LPS-202602](https://liferay.atlassian.net/browse/LPS-202602)

Follow-up: https://github.com/liferay-objects/liferay-portal/pull/2896

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by davisaints** [comment]
No regressions found!

**Comment by davisaints** [comment]
ci:forward:force

**Comment by davisaints** [comment]
ci:forward:force

**Pull request closed without merging**
