### PR TITLE
LPS-170756 Display name and format of attachment field, instead of id

### PR DESCRIPTION
**Pull request by ruben-pulido**
https://issues.liferay.com/browse/LPS-170756

//cc @ealonso

### CODE REVIEW

**Review by guilhermedcamacho — APPROVED** [review]
LGTM!

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Hey @ruben-pulido , please check if the CI errors are related, if they are unrelated, please send this PR directly to Brian. Thanks!

**Comment by guilhermedcamacho** [comment]
Hey @ruben-pulido , I asked the QA team for help and they reported that the errors are not related.

**Comment by marcelabc** [comment]
@ruben-pulido could you let us know when you send the PR to Brian? You can send the PR ticket here :+1: 
Thank you!

**Comment by ruben-pulido** [comment]
Thank you @guilhermedcamacho and @marcelabc 
PR sent to Brian here: https://github.com/brianchandotcom/liferay-portal/pull/127670

**Pull request closed without merging**
