### PR TITLE
LPS-176108

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
-----
In order to allow mapping specific fields for Attachments adds support for new field sets with the following information if the field is an attachment mime type, size, file name and download URL

Proposed solution
-----
Adds supports for a new field set of fields in case the field is an attachment, in that case we are going to add a new field set for each attachment with the following fields:
* Mime type of type text
* Size of type text
* File Name of type text
* Download URL of type URL

We are adding the information of the new fields to ObjectEntryInfoItemFieldValuesProvider and adding the values of the fields to ObjectEntryInfoItemFieldValuesProvider.

This pr also includes some improvements, like adding types to ObjectEntryInfoItemFields, removes unnecessary services and filtering system fields using service method

How to test it
-----
1. Enable FF adding **feature.flag.LPS-176083=true**
2. Create a new object (Ticket)
3. Add an Attachment field to the object
4. Publish the object
5. Adds a ticket
6. Go to a content page and adds a new text fragment
7.  Try to map the ticket

Home_-_Liferay__Editing_

Please let me know if you have any question.

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
@ealonso 

Sorry for the late reply, I'm taking a look.

**Comment by MarinhoFeliphe** [comment]
@ealonso,

I'm getting this issue when I've tried to map any field,

image

````
Caused by: com.liferay.info.exception.NoSuchFormVariationException: Unable to get form variation with key 0
	at com.liferay.object.web.internal.info.item.provider.ObjectEntryInfoItemFormProvider._getInfoForm(ObjectEntryInfoItemFormProvider.java:478) ~[?:?]
	at com.liferay.object.web.internal.info.item.provider.ObjectEntryInfoItemFormProvider.getInfoForm(ObjectEntryInfoItemFormProvider.java:116) ~[?:?]
	... 200 more
````

I'm not sure if the proper fix is this one below:

image

I need to test by using Salesforce storage type to make sure that it won't break anything there.

It's related to [this changes](https://github.com/liferay-objects/liferay-portal/pull/1760/commits/1b9f17ddbf98589cf8fa87165d1e81e9bfcd9241).

**Review by MarinhoFeliphe — CHANGES_REQUESTED** [review]
@ealonso 

I've tested by using Salesforce as storage type, I faced some issues but they're not related with your changes.

Could you please take a look at the case in the comment above, let me know if I'm missing something.

Thanks for these changes!

Best Regards,
Feliphe

**Comment by ealonso** [comment]
Hey @MarinhoFeliphe,

I already fixed it, Could you please take a look again?

**Comment by MarinhoFeliphe** [comment]
@ealonso 

of course, thanks!

**Review by MarinhoFeliphe — CHANGES_REQUESTED** [review]

**Comment by MarinhoFeliphe** [comment]
Resent here: https://github.com/liferay-objects/liferay-portal/pull/1788

**Comment by MarinhoFeliphe** [comment]
@ealonso 

Thanks for your contribution!

**Pull request closed without merging**
