### PR TITLE
LPD-17953 Fix test on KaleoDefinitionVersionLocalServiceTest

### PR DESCRIPTION
**Pull request by thallescezar**
Related issue: https://liferay.atlassian.net/browse/LPD-17953

### CODE REVIEW

**Comment by thallescezar** [comment]
ci:test:stable

**Comment by thallescezar** [comment]
ci:test:object

**Review by pedro-oliveira446 — APPROVED** [review]

**Comment by guilhermedcamacho** [comment]
Hey @thallescezar , can you please move this PR to [liferay-workflow repo](https://github.com/liferay-workflow/liferay-portal/pulls)?

**Comment by thallescezar** [comment]
Created on right repository: https://github.com/liferay-workflow/liferay-portal/pull/1092

**Pull request closed without merging**
