### PR TITLE
LPS-180259 Remove FF of Objects support for entries translation

### PR DESCRIPTION
**Pull request by murilostodolni**
Related issue: https://liferay.atlassian.net/browse/LPS-180259

### CODE REVIEW

**Comment by murilostodolni** [comment]
ci:test:sf

**Review by seltong — APPROVED** [review]
LGTM! :tada:

**Comment by marcelabc** [comment]
I just wanted to let you know that I edited the description to include the "Related Issue" (with the Jira ticket). Please always add this information in your following reviews if you can!

**Review by marcelabc — CHANGES_REQUESTED** [review]
Hi 
I finished my review. Let me know if you have questions :smile:

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Review by naraandrade — APPROVED** [review]

**Comment by murilostodolni** [comment]
ci:test:object

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
Manually forward: https://github.com/brianchandotcom/liferay-portal/pull/141692

**Comment by murilostodolni** [comment]
ci:close

**Pull request closed without merging**
