### PR TITLE
LPS-161987

### PR DESCRIPTION
**Pull request by mbowerman**
Please see the LPS ticket description for context: https://issues.liferay.com/browse/LPS-161987

### CODE REVIEW

**Comment by gabrielwas** [comment]
Thanks for the fix, @mbowerman! LGTM!

**Comment by gabrielwas** [comment]
ci:forward

**Review by gabrielwas — APPROVED** [review]

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
Hey @mbowerman, could you update the PR fixing the semantic versioning?

**Comment by mbowerman** [comment]
Hi @mateussgn I guess I'm confused why a semantic versioning change would be necessary? I am not adding or removing any methods in this pull request.

**Comment by mateussgn** [comment]
I'm sorry @mbowerman, you're right.
I just made the comment based on the test results.

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by samuelromeiro** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
