### PR TITLE
LPD-35168 Binding two trees into one using a relationship

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPD-35168](https://liferay.atlassian.net/browse/LPD-35168)
[LPD-37130](https://liferay.atlassian.net/browse/LPD-37130)

[LPD-35168]: https://liferay.atlassian.net/browse/LPD-35168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LPD-37130]: https://liferay.atlassian.net/browse/LPD-37130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
Hey @marcelabc ,
I just fixed the conflicts !

**Comment by marcelabc** [comment]
Just started reviewing :)

**Comment by marcelabc** [comment]
https://github.com/liferay-objects/liferay-portal/pull/3684

**Pull request closed without merging**
