### PR TITLE
[Technical debt] LPS-172602 Highlight the selected option in the dropdown of Selects

### PR DESCRIPTION
**Pull request by alinedoleron**
**Note: Wait https://github.com/M-IgorFranca/liferay-portal/pull/30 to be merged**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
> ###  ci:test:sf - 0 out of 1 jobs passed in 7 minutes
> Click here for more details.
> #### Base Branch:
> Branch Name: [master](https://github.com/liferay/liferay-portal/tree/master)Branch GIT ID: [355b32b5353421c36984f3516b0648d6f42595d2](https://github.com/liferay/liferay-portal/commit/355b32b5353421c36984f3516b0648d6f42595d2)
> 
> #### Sender Branch:
> Branch Name: [LPS-172602_v4](https://github.com/alinedoleron/liferay-portal/tree/LPS-172602_v4)Branch GIT ID: [b9c4bb5ffa9a5ff527e28eae1b3a5e1fcc9fe098](https://github.com/alinedoleron/liferay-portal/commit/b9c4bb5ffa9a5ff527e28eae1b3a5e1fcc9fe098)
> 
> 0 out of 1jobs PASSED
> #### 1 Failed Jobs:
> * [test-portal-source-format](https://test-1-17.liferay.com/job/test-portal-source-format/6068/)
> 
> ##### For more details click [here](https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/6068/jenkins-report.html).
>      [exec] src/main/resources/META-INF/resources/js/components/ContentContainer/FreeMarkerTemplateEditor.tsx(83,6): error TS2741: Property 'creationLanguageId' is missing in type '\{ children: (\{ label, name \}: ObjectDefinition) => Element; emptyStateMessage: string; items: any[]; label: string; onChangeQuery: Dispatch<SetStateAction<string>>; onSelectItem: (item: ObjectDefinition) => void; query: string; value: string | undefined; \}' but required in type 'AutoCompleteProps<ObjectDefinition>'.
>      [exec] Preflight check failed:
>      [exec] checkTypeScriptTypeArtifacts() failed: Error: Command /opt/dev/projects/github/liferay-portal/modules/node_modules/@liferay/npm-scripts/node_modules/.bin/tsc --emitDeclarationOnly exited with code 2
>      [exec] 
>      [exec] Prettier checked 11 files
>      [exec] 
>      [exec] 
>      [exec] FAILURE: Build failed with an exception.
>      [exec] 
>      [exec] * What went wrong:
>      [exec] Execution failed for task ':packageRunCheckFormat'.
>      [exec] 
>      [exec] 1 of 3 jobs failed
>      [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
>      [exec] error Command failed with exit code 1.
>      [exec] 
>      [exec] > Task :packageRunCheckFormat FAILED
>      [exec] Gradle build finished at 2023-01-13 18:42:38.758.
>      [exec] > Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
>      [exec] 
>      [exec] * Try:
>      [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
>      [exec] 
>      [exec] * Exception is:
>      [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':packageRunCheckFormat'.
>      [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$3(ExecuteActionsTaskExecuter.java:186)
>      [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:268)
>      [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:184)
>      [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:173)

Those failing test won't happen after https://github.com/M-IgorFranca/liferay-portal/pull/30 get merged.

**Comment by alinedoleron** [comment]
> @alinedoleron SF failure.

Hi @naraandrade, this PR depends on https://github.com/M-IgorFranca/liferay-portal/pull/30 code. Igor's PR fixes these failing tests. I added the label `blocked` since it depends on that. Do you think I should store this PR outside object PRs list?

**Comment by naraandrade** [comment]
> > @alinedoleron SF failure.
> 
> Hi @naraandrade, this PR depends on [M-IgorFranca#30](https://github.com/M-IgorFranca/liferay-portal/pull/30) code. Igor's PR fixes these failing tests. I added the label `blocked` since it depends on that. Do you think I should store this PR outside object PRs list?

Since https://github.com/M-IgorFranca/liferay-portal/pull/30 was not reviewed yet and was also waiting for another PR to be merged, I think it's better to close this one for now and wait to open it again later.

**Comment by alinedoleron** [comment]
Thanks, @naraandrade ! I'll do that!

**Pull request closed without merging**
