### PR TITLE
LPD-22720 remove FF

### PR DESCRIPTION
**Pull request by guilhermedcamacho**
Related issue: https://liferay.atlassian.net/browse/LPD-5446

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:forward

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:object

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:report:13985661

**Comment by guilhermedcamacho** [comment]
ci:report:14662549

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:object

**Comment by linolaoj** [comment]
rebased at https://github.com/liferay-objects/liferay-portal/pull/3450

**Pull request closed without merging**
