### PR TITLE
LPS-195028 Return parameterRequired in the MVCResourceCommand

### PR DESCRIPTION
**Pull request by murilostodolni**
Related: https://liferay.atlassian.net/browse/LPS-195028

cc: @rebsilva

### CODE REVIEW

**Review by carolmariaabb — APPROVED** [review]
LGTM! 🎉 

I only suspect that you need to run `gw baselin` because of the changes in the `object-api` module.

**Comment by murilostodolni** [comment]
Thank you @carolmariaabb 

I ran `gw baseline` before send the PR, but nothing was generated :(

**Comment by murilostodolni** [comment]
The semantic versioning errors are not related with the object modules and another errors also not related.

**Comment by murilostodolni** [comment]
ci:forward:force

**Pull request closed without merging**
