### PR TITLE
LPS-164095 Create UserNotificationType and decouple from email notification type

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:stop

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Review by alinedoleron — APPROVED** [review]

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
The QA team checked the failures and they are not related.

**Comment by MarinhoFeliphe** [comment]
resent here: https://github.com/brianchandotcom/liferay-portal/pull/125759

**Pull request closed without merging**
