### PR TITLE
LPS-149119 baseline

### PR DESCRIPTION
**Pull request by marcelabc**
Related Issue: https://issues.liferay.com/browse/LPS-149119

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
@marcelabc Thanks for the baseline!

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
