### PR TITLE
LPS-202709 Make the model builder show controls and mini map even with the sidebars open

### PR DESCRIPTION
**Pull request by rebsilva**
Related issue: https://liferay.atlassian.net/browse/LPS-202709

Hello Reviewer! :cherry_blossom: 

This PR has the purpose to make the mini map and control buttons of the diagram on Model Builder be visible even with the sidebars open; you can see a video with a demo bellow.

If you have any doubts please leave a comment here or contact me on Slack, thanks! 

[Screencast from 29-11-2023 16:00:08.webm](https://github.com/liferay-objects/liferay-portal/assets/60899738/e5cce240-fa0c-49ee-8c6c-a6685253afd4)

### CODE REVIEW

**Comment by alinedoleron** [comment]
Hi @rebsilva! I saw your recording and it's right, but on my machine the mini map get cut. I think we'll need QA team analysis. Maybe is something related to the monitor resolution.

Hi @andreefarias, please could you test on your machine? 💙

**Comment by rebsilva** [comment]
hi @alinedoleron! thanks for your review! yes, it because of the resolution it cuts a little, but you can see that for other sizes it never cuts more than this, and the map can still be seen. i can add more media queries to the code to prevent this, let me know your resolution so i can work on it, thanks!

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
I've added one more media query, could you please see if it works now for you @alinedoleron?

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:object

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
> I've added one more media query, could you please see if it works now for you @alinedoleron?

Hi @rebsilva! Now it looks nice!!! You are fantastic! ✨ 💖 

image

**Comment by rebsilva** [comment]
sent directly to brian: https://github.com/brianchandotcom/liferay-portal/pull/144647

**Pull request closed without merging**
