### PR TITLE
LPS-161335 Fix visual bugs and extract validate logic to be implemented by parent components

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-161335

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:stop

**Comment by naraandrade** [comment]
ci:forward

**Comment by danvb112** [comment]
Sent to: https://github.com/brianchandotcom/liferay-portal/pull/122401

**Pull request closed without merging**
