### PR TITLE
LPD-30676 [Test Fix] CreateObject#ObjectInfoDisplayedOnWorkflowMetrics

### PR DESCRIPTION
**Pull request by larissacribeiro**
Related Issue: [LPD-30676](https://liferay.atlassian.net/browse/LPD-30676)

[LPD-30676]: https://liferay.atlassian.net/browse/LPD-30676?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by rebsilva — APPROVED** [review]
LGTM! :tada: :cherry_blossom:

**Comment by rebsilva** [comment]
ci:test:playwright

**Comment by larissacribeiro** [comment]
The test is now failling, I think there might have been some change that is now breaking this previously created locator, which is used by a function that I was using: 
```
this.workflowAssigned = page
			.getByRole('cell', {name: 'Workflow Definition'})
			.getByTitle('Workflow Definition');
```
I will try to address this issue now, thanks!!

**Comment by larissacribeiro** [comment]
ci:test:sf

**Comment by larissacribeiro** [comment]
ci:test:sf

**Comment by larissacribeiro** [comment]
ci:test:playwright

**Comment by larissacribeiro** [comment]
ci:forward

**Pull request closed without merging**
