### PR TITLE
LPS-205362

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**
Related issue: https://liferay.atlassian.net/browse/LPS-205362

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
Already reviewed by the Core team, see https://github.com/liferay-core-infra/liferay-portal/pull/6487

**Comment by marcelabc** [comment]
Hey @guilhermedcamacho 
Could you review this PR, please? :smile:

**Comment by marcelabc** [comment]
Hey @marianoalvarosaiz 
I just wanted to let you know that I edited the description to include the "Related Issue" (with the Jira ticket). Please always add this information in your following reviews if you can!

**Review by guilhermedcamacho — APPROVED** [review]
LGTM!

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:report:2535174646

**Comment by guilhermedcamacho** [comment]
Based on the CSV report generated by ci:test:object, there are no unique failures.

**Comment by guilhermedcamacho** [comment]
ci:forward:force

**Pull request closed without merging**
