### PR TITLE
LPS-199155 Users are taking time to load in the relationship tab

### PR DESCRIPTION
**Pull request by Marina-Gouveia**
Related issue: [LPS-199155](https://liferay.atlassian.net/browse/LPS-199155)
LPP ticket: [LPP-50857](https://liferay.atlassian.net/browse/LPP-50857)

### CODE REVIEW

**Review by guilhermedcamacho — APPROVED** [review]
LGTM! :tada:

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:object

**Comment by JhossephG** [comment]
ci:test:object

**Comment by JhossephG** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
I've just started reviewing the new changes.

**Review by guilhermedcamacho — APPROVED** [review]

**Comment by guilhermedcamacho** [comment]
Manually forwarded to [brianchandotcom#143333](https://github.com/brianchandotcom/liferay-portal/pull/143333)

**Pull request closed without merging**
