### PR TITLE
LPS-146896,LPS-146897,LPS-147407

### PR DESCRIPTION
**Pull request by mateussgn**
Related issues: 
https://issues.liferay.com/browse/LPS-146896\;
https://issues.liferay.com/browse/LPS-147407.

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:reevaluate:1277401_1932

**Comment by mateussgn** [comment]
ci:reevaluate:1277401_1932

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
@mateussgn @p-albuquerque rebase error 😕

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:reevaluate:1287401_2004

**Comment by gabrielwas** [comment]
Just started reviewing :)

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
resent here: https://github.com/liferay-objects/liferay-portal/pull/460

**Pull request closed without merging**
