### PR TITLE
LPP-52265 Use visitFields instead of mapFields to build repeatable remove button logic

### PR DESCRIPTION
**Pull request by danvb112**

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:forms

**Comment by danvb112** [comment]
Blocked because we are only running the tests to see if the solution is ok to then open the LPD Related

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:forms

**Comment by marcelabc** [comment]
This component belongs to the DDM. 
@danvb112 will resend this PR to the @liferay-forms :smile:

**Pull request closed without merging**
