### PR TITLE
Revert "LPS-147155 Hide relationship field type from DTO when there is not VIEW permission"

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://issues.liferay.com/browse/LPS-148162

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@marcelabc merged.

**Comment by gabrielwas** [comment]
ci:forward

**Comment by gabrielwas** [comment]
ci:stop

**Comment by gabrielwas** [comment]
ci:stop

**Pull request closed without merging**
