### PR TITLE
LPD-31423 - Move ObjectAutoGeneratedLayout#CanDeleteAttachment to Playwright

### PR DESCRIPTION
**Pull request by larissacribeiro**

### CODE REVIEW

**Comment by larissacribeiro** [comment]
ci:test:playwright

**Comment by larissacribeiro** [comment]
ci:test:playwright

**Comment by igor-franca** [comment]
I would like to fix the test "verify if the object entries are displayed when selecting to preview an object entry on a page template" that failed after changing a locator in the page bulder. In order to make sure that changing this function did not cause any unnoticed side effects.

**Comment by igor-franca** [comment]
resent [here](https://github.com/liferay-objects/liferay-portal/pull/3559)

**Pull request closed without merging**
