### PR TITLE
LPD-20523 Create MVCResourceCommand to return all Account Roles to FE

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://liferay.atlassian.net/browse/LPD-20523

### CODE REVIEW

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:report:2550611144

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
