### PR TITLE
LPS-194299 Increase Max Length for VARCHAR Columns

### PR DESCRIPTION
**Pull request by carolmariaabb**
**Task**:
https://liferay.atlassian.net/browse/LPS-194299

**Sub-tasks**:
https://liferay.atlassian.net/browse/LPS-194549
https://liferay.atlassian.net/browse/LPS-194550
https://liferay.atlassian.net/browse/LPS-194551
https://liferay.atlassian.net/browse/LPS-194552
https://liferay.atlassian.net/browse/LPS-194553

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
