### PR TITLE
LPS-184937 Replace comma separator with period separator

### PR DESCRIPTION
**Pull request by DaneszLR**
Hi Team,

Original pull request: https://github.com/liferay-objects/liferay-portal/pull/2139
This new pull request uses the NumberUtil class.

Thank you!
Dani

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Hey @marcelabc ,
Could you help us to review this PR, please? Thank you!

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
I'm analyzing the CI results.

**Comment by marcelabc** [comment]
Since the test (ObjectLayoutLocalServiceTest) is passing locally, I'm going to forward this PR.

**Comment by marcelabc** [comment]
ci:forward:force

**Pull request closed without merging**
