### PR TITLE
LPS-173061 Use parentheses when anding/oring two expressions together so that they get parsed the same way as the OData filter had them

### PR DESCRIPTION
**Pull request by mbowerman**
Ticket: [LPS-173061](https://issues.liferay.com/browse/LPS-173061)

I think we really probably only need to use `withParentheses` on the right-hand expression, but using it on both shouldn't hurt and looks cleaner.

### CODE REVIEW

**Comment by timpak** [comment]
ci:test:object

**Comment by timpak** [comment]
ci:test:relevant

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/128994

**Pull request closed without merging**
