### PR TITLE
LPS-189081 Migrate View Object Definitions page to React

### PR DESCRIPTION
**Pull request by rebsilva**
Related issue: https://liferay.atlassian.net/browse/LPS-189081

Hi reviewer! :cherry_blossom: 

This PR is related to the story **[As an Object Admin, I want to create a new folder](https://liferay.atlassian.net/browse/LPS-185675)** and the commit is composed by:

- Changes the View Object Definitions page to `ViewObjectDefinitions.tsx` React component
- Changes the modals involved on this page to use the state `showModal` instead of `Liferay.fire`

:warning: ATTENTION: This PR is going to be sent **without feature flag** so it needs to be completely tested.

Special thanks to @naraandrade and @danvb112 for helping on this task :clap: 

You can send me a message if you have something to ask, thanks! :purple_heart: 

Previous PR: https://github.com/liferay-objects/liferay-portal/pull/2335

### CODE REVIEW

**Comment by rebsilva** [comment]
We still need confirmation from the QA team if everything is okay to forward

**Comment by Luizcarlosqueiroz** [comment]
ci:test:object

**Comment by Luizcarlosqueiroz** [comment]
Hey! I've check the results, and there is a single tests that is filing (ObjectTranslations#CannotSaveObjectWithoutTranslation). This was introduced after a fix of a regression bug, but this behavior will no longer be supported.
image

**Comment by rebsilva** [comment]
ci:forward

**Pull request closed without merging**
