### PR TITLE
LPS-180487 Default values info alert is missing a link to documentation

### PR DESCRIPTION
**Pull request by diogomelo09**
[LPS-180487](https://issues.liferay.com/browse/LPS-180487)

### CODE REVIEW

**Comment by diogomelo09** [comment]
ci:stop

**Comment by diogomelo09** [comment]
ci:test:sf

**Comment by diogomelo09** [comment]
ci:test:relevant

**Comment by diogomelo09** [comment]
ci:test:object

**Comment by diogomelo09** [comment]
ci:test:sf

**Comment by diogomelo09** [comment]
ci:test:relevant

**Comment by diogomelo09** [comment]
ci:test:relevant

**Review by cgmonte — CHANGES_REQUESTED** [review]
Hi @diogomelo09! Thanks for sending this fix! By the way, I am the one who forgot to add the link, so thanks again. 

Regarding your changes, it is missing a white space between the "enter-a-value-or-use-expressions-to-set-default-values¨ string and the link. You can fix this by adding a `&nbsp;` right before `ClayLink`. Please test it before sending again.

**Comment by larissacribeiro** [comment]
ci:close

**Comment by larissacribeiro** [comment]
Hello, @cgmonte!

Diogo has asked me to handle this PR for him since he's still recovering at home. I've sent the change you requested here: https://github.com/liferay-objects/liferay-portal/pull/2040 :)

**Pull request closed without merging**
