### PR TITLE
LPS-176117 Picklist Key Field Does Not Accept First Character Upper Case

### PR DESCRIPTION
**Pull request by lucasmiranda0**
[LPS-176117](https://issues.liferay.com/browse/LPS-176117) Removing toCamelCase validation, thus the user will be able to type a lower case letter or a upper case letter as the first letter of a word.

### CODE REVIEW

**Comment by lucasmiranda0** [comment]
ci:test:sf

**Comment by lucasmiranda0** [comment]
ci:test:relevant

**Comment by lucasmiranda0** [comment]
ci:test:relevant

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Comment by naraandrade** [comment]
Hi @lucasmiranda0, we'll need to hold this PR for now because there are some discussions going on about what the current behavior should be.

**Comment by naraandrade** [comment]
I'll close this PR for now. Internal discussion [here](https://liferay.slack.com/archives/C026UR5976G/p1678727734029159).

**Pull request closed without merging**
