### PR TITLE
LPS-161614 Enable account restriction after publish when the definition is not account restricted

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**
Related issue: https://issues.liferay.com/browse/LPS-161614

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
I just sycn with master.

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by MarinhoFeliphe** [comment]
This [functional test](https://testray.liferay.com/home/-/testray/case_results/1965402574/history?tab=result&hideFilterPin=true) is flacky, so I ran the relevant one more time.

**Comment by jpince** [comment]
@MarinhoFeliphe can this be manually forwarded, since the failures look unrelated?

**Comment by MarinhoFeliphe** [comment]
My bad, I forgot

Resent [here](https://github.com/brianchandotcom/liferay-portal/pull/122682)

**Pull request closed without merging**
