### PR TITLE
LPS-184447 Make sure the method returns either a valid id or the default value

### PR DESCRIPTION
**Pull request by devpedrotavares**
Related ticked: [LPS-184447](https://issues.liferay.com/browse/LPS-184447)

### CODE REVIEW

**Comment by devpedrotavares** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
ci:test:object

**Comment by devpedrotavares** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
Hey @carolmariaabb,
Could you help me and review this PR, please? :smile: 
Thanks in advance!

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Comment by carolmariaabb** [comment]
@devpedrotavares Please fix the conflicts so we can forward this PR

**Comment by devpedrotavares** [comment]
ci:forward

**Pull request closed without merging**
