### PR TITLE
LPS-166202 Following the same pattern from ObjectDefinitionService

### PR DESCRIPTION
**Pull request by marcelabc**
Follow-up: https://github.com/brianchandotcom/liferay-portal/pull/125618

Related issue: https://issues.liferay.com/browse/LPS-166202

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:reevaluate:1267401_5774

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:reevaluate:1307401_5299

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:reevaluate:1357401_3011

**Comment by marcelabc** [comment]
send  to  bchan: https://github.com/brianchandotcom/liferay-portal/pull/126075

**Pull request closed without merging**
