### PR TITLE
LPS-200287

### PR DESCRIPTION
**Pull request by gabrielwas**
https://liferay.atlassian.net/browse/LPS-200287

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by JhossephG** [comment]
ci:test:upgrade

**Comment by JhossephG** [comment]
ci:test:stop

**Comment by JhossephG** [comment]
ci:stop

**Review by carolmariaabb — APPROVED** [review]

**Comment by gabrielwas** [comment]
ci:test:stable

**Pull request closed without merging**
