### PR TITLE
LPD-33614 Create a parent object entry if the ERC specified in the relationship field does not belong to any existing object entry, during the creation of the related object entry

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPD-33614

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:object

**Review by carolmariaabb — APPROVED** [review]

**Comment by p-albuquerque** [comment]
ci:report:65500886

**Comment by p-albuquerque** [comment]
ci:report:65450551

**Comment by p-albuquerque** [comment]
ci:forward:force

**Comment by p-albuquerque** [comment]
ci:force:forward

**Comment by p-albuquerque** [comment]
ci:force:forward

**Comment by p-albuquerque** [comment]
ci:forward:force

**Comment by p-albuquerque** [comment]
Directly sent: https://github.com/brianchandotcom/liferay-portal/pull/153432

**Pull request closed without merging**
