### PR TITLE
LPS-205179 Open the Sidebar With Object Details After Creating a New Object

### PR DESCRIPTION
**Pull request by igor-franca**
Related [Ticket](https://liferay.atlassian.net/browse/LPS-205179)

### CODE REVIEW

**Review by cgmonte — APPROVED** [review]
LGTM!

**Comment by cgmonte** [comment]
LGTM!

**Comment by cgmonte** [comment]
ci:forward

**Comment by igor-franca** [comment]
ci:test:object

**Comment by igor-franca** [comment]
After carrying out a comparison of the tests performed in the routine with the results of the PR and taking into account the history of the tests, I did not find any failure related to the modifications of this PR.

**Comment by igor-franca** [comment]
ci:forward:force

**Pull request closed without merging**
