### PR TITLE
LPS 189466

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
----
Adds supports for proxy objects in content pages.

Proposed solution
----
This pr includes:

* Adds supports for ExternalReferenceCode InfoItemIdentifier where it is needed.
* Adds supports for Editing Forms into display pages
* Refactor logic to check if the object entry is in a default storage or not, in that way we are going to support other integrations, not only salesforce.

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Review by carolmariaabb — APPROVED** [review]
LGTM 🎉

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
