### PR TITLE
LPS-200494 MALFORMED_QUERY when try to filter by OR operator a Salesforce Proxy Object Account Restricted

### PR DESCRIPTION
**Pull request by jairmedeiros**
it was only necessary to add parentheses to avoid confusing OR and AND.

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
Hey @jairmedeiros , is that possible to improve our integration test to cover this scenario?

**Comment by jairmedeiros** [comment]
ci:test:object

**Comment by jairmedeiros** [comment]
ci:test:relevant

**Review by guilhermedcamacho — APPROVED** [review]

**Comment by guilhermedcamacho** [comment]
Hey @jairmedeiros , as aligned today, I will forward this pull request and you will send a follow-up PR with the improvement of our integration test to cover this scenario.

**Comment by guilhermedcamacho** [comment]
ci:forward:force

**Pull request closed without merging**
