### PR TITLE
LPS-201400 Fix testGetObjectEntries from DefaultObjectEntryManagerImplTest class to Oracle DB

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPS-201400](https://liferay.atlassian.net/browse/LPS-201400)

### CODE REVIEW

**Comment by marcelabc** [comment]
@pedro-oliveira446 Hey Pedro, 
could you assign your reviewer, please?

**Review by mateussgn — APPROVED** [review]
LGTM! 🎉

**Comment by mateussgn** [comment]
Hey @guilhermedcamacho, could you please double-check this PR?

**Review by guilhermedcamacho — APPROVED** [review]

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:object-db

**Comment by guilhermedcamacho** [comment]
Hey @Luizcarlosqueiroz , should this object-db suite run the DefaultObjectEntryManagerImplTest test on different databases?

**Comment by pedro-oliveira446** [comment]
Hey @guilhermedcamacho,
I saw that the test I changed failed on the CI, I'll take a look at it.

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Comment by pedro-oliveira446** [comment]
ci:test:object-db

**Comment by Luizcarlosqueiroz** [comment]
ci:help

**Review by guilhermedcamacho — APPROVED** [review]

**Comment by guilhermedcamacho** [comment]
ci:forward:force

**Pull request closed without merging**
