### PR TITLE
LPS-140286 Form fields cannot be linked to Object relationship field

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPS-140286

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:relevant

**Review by gabrielwas — COMMENTED** [review]
LGTM :)

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:forward

**Comment by guilhermedcamacho** [comment]
ci:forward

**Pull request closed without merging**
