### PR TITLE
LPS-151540 Rename

### PR DESCRIPTION
**Pull request by seltong**
Just waiting to get the CI results

### CODE REVIEW

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/125943

**Pull request closed without merging**
