### PR TITLE
LPS-201599 [FE] Import/Export Object Folder

### PR DESCRIPTION
**Pull request by igor-franca**
Related Previous https://github.com/liferay-objects/liferay-portal/pull/2913

### CODE REVIEW

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by igor-franca** [comment]
I am analyzing the CI result

**Comment by igor-franca** [comment]
ci:test:object

**Comment by igor-franca** [comment]
I chose to analyze the test:object tests that failed in this PR and did not fail in the routine. None of these tests are related to import/export.

However, 15 tests failed with the error `Failed prior to running test`, that is, the tests were not executed successfully. Which makes the result inconclusive, I will run the objects routine again to check if these tests can provide us with any information.

**Comment by igor-franca** [comment]
ci:test:object

**Pull request closed without merging**
