### PR TITLE
LPD-33829 Automate 'Cannot delete only custom object field of published object definition'

### PR DESCRIPTION
**Pull request by larissacribeiro**
Related Issue: [LPD-33829](https://liferay.atlassian.net/browse/LPD-33829)

[LPD-33829]: https://liferay.atlassian.net/browse/LPD-33829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by larissacribeiro** [comment]
ci:test:sf

**Review by igor-franca — APPROVED** [review]
Good work Larissa!

**Comment by igor-franca** [comment]
ci:test:playwright

**Comment by igor-franca** [comment]
ci:forward

**Pull request closed without merging**
