### PR TITLE
LPD-32984 fix playwright tests

### PR DESCRIPTION
**Pull request by victorg1991**
This was caused by https://liferay.atlassian.net/browse/LPD-31855 which breaks the site initializer we use in playwright tests

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
