### PR TITLE
LPS-170051 - The user should not be allowed to sort or filter attachment fields

### PR DESCRIPTION
**Pull request by Artartur**
[LPS-170051](https://issues.liferay.com/browse/LPS-170051)

### CODE REVIEW

**Comment by Artartur** [comment]
[LPS-170051](https://issues.liferay.com/browse/LPS-170051)

**Comment by Artartur** [comment]
ci:test:sf

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by Artartur** [comment]
ci:test:relevant

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Comment by naraandrade** [comment]
Failures are unrelated, as confirmed [here](https://liferay.slack.com/archives/C048YNC5GRK/p1672239760012289).

**Comment by naraandrade** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/128188

**Pull request closed without merging**
