### PR TITLE
LPD-18962 ‘On After Add’ action triggers ‘On After Update’ action when adding a User

### PR DESCRIPTION
**Pull request by marcelabc**
Related LPP: https://liferay.atlassian.net/browse/LPP-52581
Related issue: https://liferay.atlassian.net/browse/LPD-18962

### CODE REVIEW

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:report:2546122889

**Comment by marcelabc** [comment]
ci:report:2546127196

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:object

**Comment by marcelabc** [comment]
ci:report:2546773527

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
