### PR TITLE
LPS-169826 Set listTypeDefinitionId to ObjectField when importing an Object Definition

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-169826

### CODE REVIEW

**Comment by mateussgn** [comment]
I'm investigating the CI results.

**Comment by mateussgn** [comment]
ci:reevaluate:1327401_8009

**Comment by mateussgn** [comment]
ci:test:object

**Comment by mateussgn** [comment]
ci:close

**Comment by mateussgn** [comment]
ci:stop

**Comment by samuelromeiro** [comment]
Resend [here](https://github.com/liferay-objects/liferay-portal/pull/1677).

**Pull request closed without merging**
