### PR TITLE
LPS-152408 Commerce Product Group as System Object

### PR DESCRIPTION
**Pull request by joseabelenda**
Related Issue: https://issues.liferay.com/browse/LPS-152408

.

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @joseabelenda, can you please check if these failures are related to your changes? Thanks

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
resent:https://github.com/liferay-objects/liferay-portal/pull/625

**Pull request closed without merging**
