### PR TITLE
LPS-161750 Cover addObjectEntry and getObjectEntries

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
Hi @marcelabc,

you already review one part of this pull request,

there are these two commits left:

https://github.com/liferay-objects/liferay-portal/pull/1028/commits/068e2b3b7493a51704967106cd95930be92f909a
https://github.com/liferay-objects/liferay-portal/pull/1028/commits/1a280c72bceec791855571c025ac212f05b4ea49

Thank you!

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
