### PR TITLE
LPS-188889 Set object fields translations stories FF type to release

### PR DESCRIPTION
**Pull request by seltong**
Related to: [LPS-188889](https://liferay.atlassian.net/browse/LPS-188889)

### CODE REVIEW

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:object

**Comment by seltong** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:forward:force

**Pull request closed without merging**
