### PR TITLE
LPD-23410

### PR DESCRIPTION
**Pull request by brianikim**
https://liferay.atlassian.net/browse/LPD-23410

Commit: 4d4afcd was discussed with the product team.
Commit: dff256a is something that should serve as a template for all system objects if the system object has unique columns that cannot be applied across all system objects.

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:report:2561293096

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
