### PR TITLE
LPS-163832 Custom fields are not being returned when creating a system object from the API

### PR DESCRIPTION
**Pull request by ccorreagg**
The details in the jira ticket: https://issues.liferay.com/browse/LPS-163832

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
cc/ @4lejandrito

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
Thanks for the fix, @ccorreagg! 

Since we're modifying portal-cache code in this PR, would you mind taking a look here, @guilhermedcamacho and @rafaprax (core team)? 

Also, we're trying to forward [this PR here](https://github.com/liferay-objects/liferay-portal/pull/1096). It modifies some caching code from objects as well. We can check and see if they work well together.

cc @marcelabc

**Comment by rafaprax** [comment]
Hey @ccorreagg, Cold you please forward this pr to the https://github.com/liferay-core-infra repo? Thx

**Comment by ccorreagg** [comment]
> Hey @ccorreagg, Cold you please forward this pr to the https://github.com/liferay-core-infra repo? Thx

Yes, created: https://github.com/liferay-core-infra/liferay-portal/pull/1799

Closing this PR...

**Pull request closed without merging**
