### PR TITLE
LPS-184197 Provide Preview URL metadata for object attachment fields

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-184197

### CODE REVIEW

**Review by guilhermedcamacho — APPROVED** [review]
LGTM! :tada:

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Hey @mateussgn , can you please check or ask to some QA to analyze the CI test results?

**Comment by mateussgn** [comment]
Sure!, I'll ask the QA team to analyze it.

**Pull request closed without merging**
