### PR TITLE
LPD-15616 Allow updating the 'required' attribute of object fields from true to false in published object definitions

### PR DESCRIPTION
**Pull request by devpedrotavares**
Related ticket: [LPD-15616](https://liferay.atlassian.net/browse/LPD-15616)

### CODE REVIEW

**Review by G-Sa — APPROVED** [review]
LGTM

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:object

**Comment by devpedrotavares** [comment]
ci:report:2532133973

**Comment by devpedrotavares** [comment]
ci:forward:force

**Comment by devpedrotavares** [comment]
ci:forward:force

**Pull request closed without merging**
