### PR TITLE
LPS-188075 Picklist doesn't work with proxy objects into the form container

### PR DESCRIPTION
**Pull request by carolmariaabb**
Related Issue: https://liferay.atlassian.net/browse/LPS-188075

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:stable

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:test:stable

**Comment by carolmariaabb** [comment]
ci:reevaluate:1287401_6824

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
