### PR TITLE
LPS-139911 Disable the create relationship tab option on first layout tab creation

### PR DESCRIPTION
**Pull request by eli-rlima**
Hi reviewers,

This PR is referent the last task of the Layout Story.

Thanks for your review time.

### CODE REVIEW

**Comment by eli-rlima** [comment]
ci:test:relevant

**Comment by eli-rlima** [comment]
ci:stop

**Comment by eli-rlima** [comment]
ci:test:sf

**Comment by eli-rlima** [comment]
ci:test:relevant

**Review by interaminense — APPROVED** [review]
LGTM

**Comment by interaminense** [comment]
ci:forward

**Pull request closed without merging**
