### PR TITLE
LPS-169398 IllegalArgumentException occurs when upgrading database with existing custom object

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPS-169398](https://liferay.atlassian.net/browse/LPS-169398)

### CODE REVIEW

**Review by p-albuquerque — APPROVED** [review]
LGTM

**Comment by lucasperj** [comment]
ObjectUpgrade#ViewObjectRelationshipAfterUpgrade7413U33 have passed locally with the changes, 

>      [java] 2023-08-29 14:29:22.846 INFO  [main][UpgradeRecorder:153] Major upgrade finished with result success
>      [java] 
>      [java] Completed Liferay upgrade process in 72 seconds
can you guys please add a commit reactivating the ignored objects upgrade tests (Under **ObjectUpgrade** and **ObjectNotificationsUpgrade** files) ? 

cc/ @Luizcarlosqueiroz @timpak

**Review by guilhermedcamacho — APPROVED** [review]

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
Resent:https://github.com/brianchandotcom/liferay-portal/pull/140039

**Pull request closed without merging**
