### PR TITLE
LPS-171173 Call undeploy method of a removed ObjectDefinitionDeployer with all the existing Objects

### PR DESCRIPTION
**Pull request by ccorreagg**
Followed-up PR from: https://github.com/liferay-headless/liferay-portal/pull/1042

This PR is created to fix this bug: https://issues.liferay.com/browse/LPS-171173

When `portal-vulcan-impl` module is restarted, the `com.liferay.object.rest.internal.deployer.ObjectDefinitionDeployerImpl` class is redeployed as it has dependencies with certain classes of portal-vulcan, causing that all the Objects REST API components that have been registered in OSGi keep unaltered, the references to the registrations are lost as they were kept in private maps, and then, the `_objectDefinitionDeployerServiceTracker` of the class `com.liferay.object.service.impl.ObjectDefinitionLocalServiceImpl` invokes for each ObjectDefinition the method `deploy` once the `ObjectDefinitionDeployerImpl` has been registered, causing that several components are registered as many times as the `ObjectDefinitionDeployerImpl` is redeployed.

To avoid that, apart from calling the `deploy` method for each Object Definition in the Service Tracker of the `ObjectDefinitionLocalServiceImpl` when an `ObjectDefinitionDeployer` has been added, the method `undeploy` will be invoked for each Object Definition in the Service Tracker of the same class when an `ObjectDefinitionDeployer` has been removed.

### CODE REVIEW

**Comment by marcelabc** [comment]
Hey @guilhermedcamacho, could you please review this PR?

**Comment by ccorreagg** [comment]
Hey guys! Any update on this?

**Comment by guilhermedcamacho** [comment]
Hey @ccorreagg, sorry for the delay. I will review it today. thanks!

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:test:relevant

**Review by gabrielwas — APPROVED** [review]

**Comment by gabrielwas** [comment]
ci:test:object

**Comment by gabrielwas** [comment]
ci:forward:force

**Comment by gabrielwas** [comment]
QAs checked relevant and failures are not related. I've also check objects suite results and haven't found related failures.
Manually forwarded to Brian: https://github.com/brianchandotcom/liferay-portal/pull/131515

**Pull request closed without merging**
