### PR TITLE
LPS-196437 Generic error when attempt deleting Uncategorized folder via API

### PR DESCRIPTION
**Pull request by diogomelo09**
[LPS-196437](https://liferay.atlassian.net/browse/LPS-196437?atlOrigin=eyJpIjoiMWExOWM5YWVmM2FlNDkwNjg4ZjM2MGI5NWQ2NDVlMzciLCJwIjoiaiJ9)

### CODE REVIEW

**Comment by marcelabc** [comment]
Hey @carolmariaabb 
Could you review this PR, please? :smile:

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by diogomelo09** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:stable

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:test:stable

**Comment by carolmariaabb** [comment]
ci:test:stable

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
