### PR TITLE
LPS-156259 Block groovy script creation on LXC

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-156259

### CODE REVIEW

**Comment by mateussgn** [comment]
Resend based on https://github.com/brianchandotcom/liferay-portal/pull/121218#issuecomment-1204059778

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
Hey @brianchandotcom, is this what you mean?

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:reevaluate:1267401_4386

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:relevant

**Review by rodrigopaulino — APPROVED** [review]
LGTM! 🎉 
Just resolve the conflicts and this is good to go. 😄

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
A new one will be sent.

**Comment by rodrigopaulino** [comment]
ci:close

**Pull request closed without merging**
