### PR TITLE
LPS-146896,LPS-147407

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issues: 
https://issues.liferay.com/browse/LPS-146896; 
https://issues.liferay.com/browse/LPS-147407.

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:reevaluate:1267401_1848

**Comment by mateussgn** [comment]
ci:reevaluate:1267401_1848

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
Fix ObjectViewUtil changes.

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:close

**Pull request closed without merging**
