### PR TITLE
LPD-30083 Remove FF of Unique Composed Keys

### PR DESCRIPTION
**Pull request by larissacribeiro**
Related Issue: [LPD-30083](https://liferay.atlassian.net/browse/LPD-30083)

[LPD-30083]: https://liferay.atlassian.net/browse/LPD-30083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by larissacribeiro** [comment]
ci:test:relevant

**Comment by larissacribeiro** [comment]
ci:test:object

**Comment by larissacribeiro** [comment]
ci:test:relevant

**Comment by larissacribeiro** [comment]
ci:test:object

**Comment by larissacribeiro** [comment]
ci:test:relevant

**Comment by larissacribeiro** [comment]
ci:test:object

**Comment by linolaoj** [comment]
Hi @larissacribeiro, this feature flag is also on [Language.properties](https://github.com/liferay-objects/liferay-portal/blob/ac66489cafea76ffe2ed1252df0e4aebd4103aa4/modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties#L7449), we need to remove from there too and run the buildLang.

**Comment by larissacribeiro** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:objects

**Comment by linolaoj** [comment]
ci:test:object

**Comment by linolaoj** [comment]
ci:forward

**Comment by linolaoj** [comment]
ci:forward

**Comment by linolaoj** [comment]
ci:forward:force

**Pull request closed without merging**
