### PR TITLE
LPS-163017 Remove comments box from Layout Builder

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-163017

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Review by alinedoleron — APPROVED** [review]
Great job!

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by samuelromeiro** [comment]
@naraandrade @danvb112 the https://github.com/brianchandotcom/liferay-portal/pull/123269 war merged

**Comment by danvb112** [comment]
ci:forward

**Comment by danvb112** [comment]
Sent to: https://github.com/liferay-objects/liferay-portal/pull/1057

**Comment by danvb112** [comment]
Sent to: https://github.com/liferay-objects/liferay-portal/pull/1086

**Pull request closed without merging**
