### PR TITLE
LPS-136090 Date field does not need to be parsed

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-136090

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
@mateussgn is it still persisting the field as a Date in the database? Do you know?

**Comment by mateussgn** [comment]
Yes, it is @gabrielwas. This parsing was kind of an extra step because on [ObjectEntryManagerImpl](https://github.com/liferay-objects/liferay-portal/blob/6622dc1d1d269468437da9efc126bac5be5bdec2/modules/apps/object/object-rest-impl/src/main/java/com/liferay/object/rest/internal/manager/v1_0/ObjectEntryManagerImpl.java#L153) had already a date parsing.

**Comment by gabrielwas** [comment]
@mateussgn perfect then! Thank you!

**Comment by gabrielwas** [comment]
@mateussgn just figured out Javier did it after I implemented that. That's why it stopped working.

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:foward

**Comment by mateussgn** [comment]
ci:forward

**Pull request closed without merging**
