### PR TITLE
LPS-196607 Avoid null pointer and handle scenario where error response only has title

### PR DESCRIPTION
**Pull request by devpedrotavares**
Motivation
Remove Feature Flags for LPS-182728 and LPS-182586

Related issue: https://liferay.atlassian.net/browse/LPS-182728
Related issue: https://liferay.atlassian.net/browse/LPS-182586

Follow up: https://github.com/liferay-objects/liferay-portal/pull/2579
Bug fix: [LPS-196607](https://liferay.atlassian.net/browse/LPS-196607)

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
Hey @devpedrotavares,
rebase error :confused:

**Comment by devpedrotavares** [comment]
Fixed minor conflicts

**Comment by devpedrotavares** [comment]
ci:test:sf

**Comment by devpedrotavares** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
ci:test:sf

**Comment by devpedrotavares** [comment]
ci:test:sf

**Comment by devpedrotavares** [comment]
Fixed minor conflicts

**Comment by devpedrotavares** [comment]
ci:forward:force

**Comment by devpedrotavares** [comment]
ci:stop

**Comment by devpedrotavares** [comment]
Dropped the commit with the changes done by SF, because it seems that there is a problem with SF. It's removing feature-flags from portal.properties that probably shouldn't be removed.

**Comment by devpedrotavares** [comment]
ci:test:sf

**Comment by devpedrotavares** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
ci:test:sf

**Comment by devpedrotavares** [comment]
ci:test:sf

**Comment by devpedrotavares** [comment]
ci:forward:force

**Comment by marcelabc** [comment]
ci:forward:force

**Comment by devpedrotavares** [comment]
Sent directly: https://github.com/brianchandotcom/liferay-portal/pull/141253

**Pull request closed without merging**
