### PR TITLE
LPS-198587 Refactor the MultiSelect component to no longer use BaseSelect

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://liferay.atlassian.net/browse/LPS-198587

### CODE REVIEW

**Comment by danvb112** [comment]
Blocked becaue depends on: https://github.com/liferay-objects/liferay-portal/pull/2735

**Review by naraandrade — APPROVED** [review]

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
I'll send a new PR, since Daniel is on PTO.

**Pull request closed without merging**
