### PR TITLE
LPS-139269 Error messages are not user-friendly when creating an Object and a Field

### PR DESCRIPTION
**Pull request by eli-rlima**
Hi guys,

This is the implementation of mapping of error type returned by server side to language key. The objective is to show a user friendly message when erros occur.

Thanks for your review time.

### CODE REVIEW

**Comment by eli-rlima** [comment]
This is a advance of this PR: #229, I believe that should be closed.

**Comment by eli-rlima** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Just started reviewing :)

**Comment by guilhermedcamacho** [comment]
Resending on #234

**Pull request closed without merging**
