### PR TITLE
LPS-140269 Add conditions when the objectDefinitonId 1 and 2 are equals

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-140269

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Just started reviewing :)

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
