### PR TITLE
LPS-159632 Change the Aggregation filter structure for Date, Picklist and Workflow Statusa

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-159632

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — APPROVED** [review]

**Comment by danvb112** [comment]
ci:forward

**Comment by danvb112** [comment]
ci:forward

**Pull request closed without merging**
