### PR TITLE
[TS] LPS-166196 Unable to return Objects entries with MS SQL Server

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-166196

MS SQL Server throws error:
```
com.microsoft.sqlserver.jdbc.SQLServerException: The column 'c_newOId_' was specified multiple times for '_temp_table_1'. 
```
because the generated SQL in `ObjectEntryLocalServiceImpl.getValuesList` and `ObjectEntryLocalServiceImpl.getValuesList` methods contains the same primary key column from **O_123_test** and **O_123_test_x** tables.

To avoid the error, as primary key columns of both tables has exactly the same name and values, I am removing the primary key of second O_123_test_x table from the select of the SQL query.

Let me know if you have any question

### CODE REVIEW

**Comment by gabrielwas** [comment]
Thanks for the fix, @jorgediaz-lr! LGTM! :D

**Comment by gabrielwas** [comment]
ci:forward

**Comment by jorgediaz-lr** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:reevaluate:1397401_1311

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by jorgediaz-lr** [comment]
I have sent here https://github.com/jorgediaz-lr/liferay-portal/pull/505 a PR with a dummy change in `ObjectEntryLocalServiceImpl.java` and the ci:test:relevant errors where the same, so they seems to be unrelated.

**Comment by jorgediaz-lr** [comment]
Hi @carolmariaabb  @gabrielwas 

I have manually forwarded this to Brian, see https://github.com/brianchandotcom/liferay-portal/pull/125377

**Pull request closed without merging**
