### PR TITLE
LPS-145572 Implement Asset Renderer to preview the object entry in workflow contexts

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**
Story: [LPS-145228](https://issues.liferay.com/browse/LPS-145228)

### CODE REVIEW

**Comment by gabrielwas** [comment]
Just started reviewing :)

**Comment by gabrielwas** [comment]
@MarinhoFeliphe 

1 - Let me know if you agree with the little changes I sent in https://github.com/MarinhoFeliphe/liferay-portal/pull/58
2 - Why can't we use `edit_object_view.jsp` instead of creating a `view_object_view.jsp` ? Is there something I'm missing?

BTW, very good pull! :D

**Comment by MarinhoFeliphe** [comment]
Hi @gabrielwas, thank you for your review, I'm so glad with your feedback :)

1 - The SF command reverted [your changes](https://github.com/MarinhoFeliphe/liferay-portal/pull/58/commits/3595c79a887f37ddf9cf96825dcec8d8339e2860#diff-9693ef747b103458099c90755893045a8f47077e6425b1f0c2634a386769002eL155) in ObjectEntryAssetRenderer, I sent a commit with the [SF changes](https://github.com/liferay-objects/liferay-portal/pull/360/commits/7ac390ea022634a0cb248918aa9cc3395fba01b0).
2 - I took a looking at this approach and I applied by adapting the form.jsp and relatioship.jsp to read only mode and looks good for me, I sent a [commit with this changes](https://github.com/liferay-objects/liferay-portal/pull/360/commits/25e37a7dd69b437fe534ac43327d04cce4af9db0).

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
Just started reviewing :)

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:forward

**Pull request closed without merging**
