### PR TITLE
LPD-31070 It is not possible to create a Many to Many Object Relationship with Oracle DB

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPD-31070](https://liferay.atlassian.net/browse/LPD-31070)

[LPD-31070]: https://liferay.atlassian.net/browse/LPD-31070?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Comment by pedro-oliveira446** [comment]
ci:test:backend

**Comment by linolaoj** [comment]
ci:forward

**Pull request closed without merging**
