### PR TITLE
LPS-171863 Apply to use

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:object

**Comment by naraandrade** [comment]
@pedro-oliveira446 will work on the integration test :)

**Comment by pedro-oliveira446** [comment]
Resent here: https://github.com/liferay-objects/liferay-portal/pull/1698 .

**Pull request closed without merging**
