### PR TITLE
LPD-29802 Integration text fix, changing test logic to set up the UploadServletRequestImpl log level

### PR DESCRIPTION
**Pull request by victorKammerer**
[LPD-29802](https://liferay.atlassian.net/browse/LPD-29802)

[LPD-29802]: https://liferay.atlassian.net/browse/LPD-29802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by victorKammerer** [comment]
ci:test:relevant

**Review by linolaoj — APPROVED** [review]

**Comment by linolaoj** [comment]
Hi @victorKammerer , the change looks ok. Can you just edit the commit message to add the name of the class UploadServletRequestImpl. Also, I see in other parts of the portal (`git grep "LoggerTestUtil.configureLog4JLogger("`) that we use the string name of the class instead of `UploadServletRequestImpl.class.getName()` this can avoid an import of something that is not really needed.

**Comment by victorKammerer** [comment]
Done, @linolaoj!

**Review by linolaoj — APPROVED** [review]

**Comment by linolaoj** [comment]
ci:forward

**Pull request closed without merging**
