### PR TITLE
layout screen

### PR DESCRIPTION
**Pull request by interaminense**
- LPS-138939 Create layout screen
- LPS-138939 Add layout react components
- LPS-138939 Create SidePanelContent component
- LPS-138939 Create CustomSelect component
- LPS-138939 Create Panel component
- LPS-138939 Add util to normalize languageId
- LPS-138939 Add css to nav-link and fix height of side panel content
- LPS-138939 Remove outdated generated types

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@interaminense I merged this in manually @marco-leo fyi

**Comment by interaminense** [comment]
Thanks, Brian! So, I'm gonna close this PR. cc: @guilhermedcamacho

**Pull request closed without merging**
