### PR TITLE
LPS-138214 Display user friendly message in Panel Category Key and Title Field empty options

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPS-138214

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Just started reviewing :)

**Comment by marcelabc** [comment]
We discussed on Slack, he has changes to do related to this work 👍

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
