### PR TITLE
[Playwright test fix] LPD-31952 | LPD-31954

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: 
https://issues.liferay.com/browse/LPD-31952;
https://liferay.atlassian.net/browse/LPD-31954.

**About LPD-31952** 
Proper role name to perform the count:
roleName

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:test:playwright

**Comment by marcelabc** [comment]
Hey @larissacribeiro 
Could you review this PR, please? :smile:

**Comment by p-albuquerque** [comment]
the both tests have passed:
passedTests

**Review by larissacribeiro — APPROVED** [review]
LGTM! 🎉

**Comment by larissacribeiro** [comment]
ci:forward

**Pull request closed without merging**
