### PR TITLE
LPS 189110

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
----
This pr includes some fixes for some issue b400197 and 0a6c091, an ERCInfoItemIdentifier implementation for InfoItemDetailsProvider and the creation of a new class to reuse some common logic, for that one I need to move some code from service to web module.

[Link to the issue](https://issues.liferay.com/browse/LPS-189110)

Please let me know if you have any question.

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:object

**Comment by ealonso** [comment]
ci:test:sf

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Comment by ealonso** [comment]
ci:reevaluate:1377401_12801

**Comment by ealonso** [comment]
manual forward: https://github.com/brianchandotcom/liferay-portal/pull/137067

**Pull request closed without merging**
