### PR TITLE
[TS] LPS-170099 Ensure there is a map available before trying to modify it

### PR DESCRIPTION
**Pull request by jonathanmccann**
When fetching a related object as a user with minimal permissions not all actions are available to them (eg Permissions, Update, Delete). Due to this the `map` might be null. This added check avoids an NPE when dealing with this situation and still allows the actions that the user can perform to be returned.

The full steps are quite long but can be viewed on https://issues.liferay.com/browse/LPS-170099

Please let me know if there are any questions or concerns.

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/127390

**Pull request closed without merging**
