### PR TITLE
LPS-182759 Open a client extension point for ObjectEntryManager

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
thanks @guilhermedcamacho

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:object

**Comment by MarinhoFeliphe** [comment]
ci:forward:force

**Comment by MarinhoFeliphe** [comment]
Failures are not related.

cc: @guilhermedcamacho ]

**Pull request closed without merging**
