### PR TITLE
LPS-139560 It is possible to leave Picklist field empty when creating an Object Picklist field 

### PR DESCRIPTION
**Pull request by eli-rlima**
Hi reviewers!

This PR is related with #138! It resolves the same problem, but with somes refactoring. 

- Corrections in modal validations;
- Added placeholder in Picklist Select;
- Correction in modal state;

It's very similar to #144. I believe that the #138 should be closed.

### CODE REVIEW

**Comment by eli-rlima** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:reevaluate:1277401_374

**Comment by eli-rlima** [comment]
ci:test:sf

**Comment by eli-rlima** [comment]
ci:test:relevant

**Comment by eli-rlima** [comment]
ci:reevaluate:1327401_538

**Comment by interaminense** [comment]
ci:test:relevant

**Review by interaminense — APPROVED** [review]

**Comment by interaminense** [comment]
ci:forward

**Pull request closed without merging**
