### PR TITLE
LPD-27534 Test Fix ManageCustomObjectsWithDifferentRoles

### PR DESCRIPTION
**Pull request by victorKammerer**
[LPD-27534](https://liferay.atlassian.net/browse/LPD-27534)

### CODE REVIEW

**Comment by linolaoj** [comment]
Hi @victorKammerer , can you please squash the commits that are changing the file DefaultObjectEntryManagerImplTest.java to reduce the number of commits of this task?

**Comment by victorKammerer** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:forward

**Pull request closed without merging**
