### PR TITLE
LPS-185721 [FE] Localized object fields can not be required

### PR DESCRIPTION
**Pull request by seltong**
Related issue: [LPS-185721](https://issues.liferay.com/browse/LPS-185721)

### CODE REVIEW

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:object

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — CHANGES_REQUESTED** [review]
Hi @seltong, good job on this PR! Just one change needed. Please remove the changes related to frontend-data-set in the last commit. Those .d.ts files are tricky and we avoid modifying then in other modules that are not ours.

**Comment by seltong** [comment]
ci:test:sf

**Review by naraandrade — APPROVED** [review]

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:object

**Comment by seltong** [comment]
Sent to Brian's repository: https://github.com/brianchandotcom/liferay-portal/pull/135796

**Pull request closed without merging**
