### PR TITLE
LPS 188165

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
----
Fix item selector for proxy objects when we are selecting them on Display Page creation.

Employee_-_Liferay_DXP__Editing_

[Link to the issue](https://liferay.atlassian.net/browse/LPS-188165)

Proposed Solution
----
Adapts logic in ObjectEntryItemSelectorView.java to allow selecting proxy objects, also it splits logic into different classes to make it more readable.

How to test it
---
Step-by-Step:

1. Connect with Salesforce Employee object
2. Create a Display Page for Employees
3. Add some fragments and map
4. Try to select a employee object

After the changes it looks like:

Employee_-_Liferay_DXP__Editing_

Comments
---
At this only the selection is working, so if you select a employee the mapped contents are not changing, I'm working on it right now. 

Regarding the logic related with proxy objects, I don't know how to get some information, so I decided to return empty or null values, please complete it if you know how to do it. IMHO, it can be done in a follow up pr, so I can work in more improvements.

### CODE REVIEW

**Comment by carolmariaabb** [comment]
Hi @ealonso, your changes look good to me. Regarding your comment:

> Regarding the logic related with proxy objects, I don't know how to get some information, so I decided to return empty or null values, please complete it if you know how to do it. IMHO, it can be done in a follow up pr, so I can work in more improvements.

I tried to complete it but I realized it's not as simple as I thought 😢. I will need to discuss with the team the best approach to follow.

- Do you need these changes to continue your improvements?
- I see no problem in forwarding this PR. Can we forward it?

Thanks a lot for your help on this 😄

**Review by carolmariaabb — APPROVED** [review]

**Comment by ealonso** [comment]
@carolmariaabb yes I need it, since I have 20 commits more 😅

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
> @carolmariaabb yes I need it, since I have 20 commits more sweat_smile

I'll talk to the team to align that you need this follow-up as soon as possible to continue your work. Thanks!

**Comment by ealonso** [comment]
Hey @carolmariaabb,

I've only need the code in this pr, I think I misunderstood your question, sorry about that. I don't need the follow up pr from your part.

**Comment by carolmariaabb** [comment]
Excellent! I see now that my question was confusing, sorry.

Thanks!

**Pull request closed without merging**
