### PR TITLE
LPD-30080 Remove FF: LPD-23379 Allow users to configure when to Skip indexer for object entries

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://liferay.atlassian.net/browse/LPD-30080

### CODE REVIEW

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by marcelabc** [comment]
ci:report:28740618

**Comment by marcelabc** [comment]
@carolmariaabb you can ignore this report. This ID is from the build ci:test:object - 2024-07-01.

**Comment by marcelabc** [comment]
ci:report:28705781

**Comment by marcelabc** [comment]
ci:report:28653320

**Comment by marcelabc** [comment]
you can ignore this report. This ID is from the build  ci:test:workflow-metrics - 42839 - 2024-07-01

**Comment by marcelabc** [comment]
ci:report:29313496

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
