### PR TITLE
[TS] LPS-170984 Check predicate null when get object entries

### PR DESCRIPTION
**Pull request by TaiPhamLR**
Dear team,
This PR is for ticket https://issues.liferay.com/browse/LPS-170984 that passed my review. Please help us to review it and leave us your comments.
Thanks a lot.
@sontruongces

### CODE REVIEW

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
Hi @TaiPhamLR, how are you doing? :smile: 
Sorry for the delay in reviewing it! 
Thank you for collaborating with our team!

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
We [double checked the results with QA](https://liferay.slack.com/archives/C048YNC5GRK/p1672947346998709?thread_ts=1672926042.354619&cid=C048YNC5GRK) and it seems that only LocalFile.ObjectActions#CanEditExpression could be a related failure. @marcelabc could you help confirming if this test would be impacted by the changes in this PR? Thanks!

**Comment by marcelabc** [comment]
@naraandrade I would suggest the author of this PR to run locally this test. Thanks!

**Comment by marcelabc** [comment]
Hey @TaiPhamLR,
Could you please run this Poshi test locally: LocalFile.ObjectActions#CanEditExpression?
If you need help, let us know! Thank you :smile:

**Comment by sontruongces** [comment]
> Hey @TaiPhamLR, Could you please run this Poshi test locally: LocalFile.ObjectActions#CanEditExpression? If you need help, let us know! Thank you smile

I run the test on my locale without my change and it failed also so I think it is not related to my change.

cc: @naraandrade

**Comment by naraandrade** [comment]
> > Hey @TaiPhamLR, Could you please run this Poshi test locally: LocalFile.ObjectActions#CanEditExpression? If you need help, let us know! Thank you smile
> 
> I ran the test on my locale without my change and it failed also so I think it is not related to my change.
> 
> cc: @naraandrade

@sontruongces  In this case, you can send the PR directly to BChan. Please, close this one when you do it. Thanks!

**Comment by sontruongces** [comment]
Forwarded to brianchandotcom#128482.
cc: @naraandrade

**Comment by naraandrade** [comment]
> Forwarded to [brianchandotcom#128482](https://github.com/brianchandotcom/liferay-portal/pull/128482). cc: @naraandrade

@sontruongces Did you link the right PR? I only see commits for LPS-172203 in that one.

**Comment by sontruongces** [comment]
> > Forwarded to [brianchandotcom#128482](https://github.com/brianchandotcom/liferay-portal/pull/128482). cc: @naraandrade
> 
> @sontruongces Did you link the right PR? I only see commits for LPS-172203 in that one.

Sorry, my bad. Updated. Thank you!

**Pull request closed without merging**
