### PR TITLE
LPS-148629 Remove FF checking from ObjectDefinition and ListTypeDefinition permissions action

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
Hey @gabrielwas, maybe you should update the `object_definition.json` file to make this assertion work properly.

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:forward

**Pull request closed without merging**
