### PR TITLE
LPS-201315 Add new property in DTO

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://liferay.atlassian.net/browse/LPS-201315
Follow-up: https://github.com/brianchandotcom/liferay-portal/pull/144711

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:forward:force

**Pull request closed without merging**
