### PR TITLE
LPS-190030 Remove feature flag for LPS-179803

### PR DESCRIPTION
**Pull request by carolmariaabb**
Related Issue: https://liferay.atlassian.net/browse/LPS-190030

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:reevaluate:1327401_700

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by timpak** [comment]
I created a new PR that includes the changes from this PR because we needed to make some Poshi changes. See https://github.com/liferay-objects/liferay-portal/pull/2340

**Pull request closed without merging**
