### PR TITLE
LPS-166783 Adapt DefaultFilter to works with MultiselectPicklist Field

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPS-166783

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
LGTM!! :tada:

**Comment by MarinhoFeliphe** [comment]
Very nice, @p-albuquerque!!

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:forward

**Pull request closed without merging**
