### PR TITLE
LPS-164449 Create Date and Modified Date are not working correctly when using HSQL Database Engine 2.3

### PR DESCRIPTION
**Pull request by thienquach87**
Hi @gabrielwas,

After working with liferay-core-infra team on https://github.com/liferay-core-infra/liferay-portal/pull/2337, we decided adding jdbc.default.url=jdbc:hsqldb:${liferay.home}/data/hypersonic/lportal;sql.syntax_ora=true to portal.properties file instead of modifying source to enable on-standard syntax of Oracle , so the source needed to review is only belong to the object part. Could you help to forward my PR to the next process?

Thank you!
Thien

### CODE REVIEW

**Comment by thienquach87** [comment]
ci:test:fs

**Comment by thienquach87** [comment]
ci:test:relevant

**Review by gabrielwas — APPROVED** [review]
LGMT! Thx.

**Comment by gabrielwas** [comment]
ci:forward

**Comment by naraandrade** [comment]
@thienquach87 we have some conflicts in this branch. Could you please take a look? Thanks :)

**Comment by thienquach87** [comment]
@naraandrade
I fixed conflicts.
Btw, you need set the SET DATABASE SQL SYNTAX ORA TRUE to enable support for non-standard syntax of Oracle

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by thienquach87** [comment]
@naraandrade
Do you have any update?

**Comment by naraandrade** [comment]
> @naraandrade Do you have any update?

We'll ask QA to double check the relevant faliures. If they're not related, we can send the PR directly to Brian.

**Comment by danvb112** [comment]
Hey @thienquach87, Our QA team said these failures are common and not related to your changes, so you can send this PR directly to Brian

**Comment by thienquach87** [comment]
@danvb112 
Thank you, I forwarded at https://github.com/brianchandotcom/liferay-portal/pull/126468

**Pull request closed without merging**
