### PR TITLE
LPS-140522 Add ThreadLocal to skip relationship permission

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-140522

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by samuelromeiro** [comment]
Hey @mateussgn and @guilhermedcamacho do you want me to close this PR for you guys to work on it later? I saw that nothing happened in it for the last two weeks.

**Comment by mateussgn** [comment]
Thanks for noticing, @samuelromeiro.
@guilhermedcamacho I think you could review the PR, I'm about to finish my story and get back to this PR.

**Comment by naraandrade** [comment]
@guilhermedcamacho Just leaving a reminder :)

**Comment by marcelabc** [comment]
Hi @mateussgn, 
I had to circumvent a permission involving the Object Entry. I know that your situation is a little different from mine because you want to skip permission in a specific predicate. However, we both want to circumvent something regarding the Object Entry entity.

**Comment by marcelabc** [comment]
Hi @mateussgn,
I solved this bug and I reminded of this one, so I will say a few things, and you decide if it makes sense with your context or not :smile: 

I had to circumvent permission involving the Object Entry. I know your situation is slightly different from mine because you want to skip permission in a specific predicate. However, we both want to circumvent something regarding the Object Entry entity.

In this PR, I created a new folder called Util in object-service and created a class ObjectEntryThreadLocal.java. I preferred to create the Util in the service module because I believe we don't want to expose this Util in the API module. 

I know that a specific Relationship situation motivated these circumvent. Still, I believe that if we are checking something related to Object Entry, so the ThreadLocal class should be related to the entity we want to edit. Does it make sense?

My PR was not reviewed, then my opinion could be wrong :upside_down_face: 
This was my opinion, and I just want to share it with you because I think they are similar problems.

**Comment by samuelromeiro** [comment]
Hey @mateussgn can you analyze the conflicts and resend, please?

**Comment by mateussgn** [comment]
Resent here: https://github.com/liferay-objects/liferay-portal/pull/1699

**Pull request closed without merging**
