### PR TITLE
LPS-164127 Remove unnecessary TName types to use type of LocalizedValues ​​already declared

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-164127

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:forward

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
@danvb112 If the next round of relevant is not successful, you can just send the PR directly to Brian.

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
Sent to: https://github.com/brianchandotcom/liferay-portal/pull/124026

**Pull request closed without merging**
