### PR TITLE
LPS-167508 rename

### PR DESCRIPTION
**Pull request by LuismiBarcos**
Hi Team! I received a request to change the value of the property `NAME_OBJECT_RELATIONSHIP_ERC_FIELD_NAME` and this will affect the values stored in the DB.
I send this PR to you to ensure that what I'm doing makes sense.

Thanks

Changes requested here -> https://github.com/brianchandotcom/liferay-portal/pull/126903#issuecomment-1329112566
___
This PR is to do the rename requested. It also contains the upgrade process for the DB as the rename affects the data stored in the DB.

### CODE REVIEW

**Review by carolmariaabb — APPROVED** [review]
LGTM!

@LuismiBarcos could you please fix the conflicts? Thanks!

**Comment by LuismiBarcos** [comment]
Conflicts fixed and branch rebased

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
Hi @LuismiBarcos, feel free to send this PR directly to Brian. The failures are not related to your changes. Thanks!

**Comment by LuismiBarcos** [comment]
Manually forwarded here https://github.com/brianchandotcom/liferay-portal/pull/127653

**Pull request closed without merging**
