### PR TITLE
LPS-188996 Add integration test to Object Actions with Organization system Object

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
Bug : https://liferay.atlassian.net/browse/LPS-190381
Integration Test : https://liferay.atlassian.net/browse/LPS-188996

### CODE REVIEW

**Review by mateussgn — APPROVED** [review]

**Comment by mateussgn** [comment]
Hey @guilhermedcamacho, could you please double-check this PR?

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Comment by pedro-oliveira446** [comment]
Hi @mateussgn,
I added the Integration tests too, can you review again ?
Sorry about that.

**Comment by mateussgn** [comment]
Sure, I'll review it again.

**Comment by mateussgn** [comment]
Hey @guilhermedcamacho, could you please double-check this PR?

**Review by carolmariaabb — APPROVED** [review]
Great job, @pedro-oliveira446 🎉

I would just improve some predefined values like: 

- `Custom1` to `First Custom Value`
- `test1` to `First Comment`
- `Organization1` to `First Organization` 

And so on.

But as this PR has been in our queue for too long, I prefer to forward it now. Thanks!

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
