### PR TITLE
LPS-163415 Remove comments from layout

### PR DESCRIPTION
**Pull request by seltong**

### CODE REVIEW

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:forward

**Comment by naraandrade** [comment]
@seltong We have some conflicts in this branch. Could you please take a look? Thanks :)

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:stable

**Comment by seltong** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/124082

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/124099

**Pull request closed without merging**
