### PR TITLE
LPS-150294 Replace relationship value from zero to blank when Object Entry has no relationship

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-150294

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Just started reviewing :)

**Comment by marcelabc** [comment]
resend: https://github.com/liferay-objects/liferay-portal/pull/555
@danvb112

**Pull request closed without merging**
