### PR TITLE
LPS-138492 Change the usage of name field to label field in Forms and Display Pages

### PR DESCRIPTION
**Pull request by interaminense**
- LPS-138492 Change the usage of name field to label field in Forms and Display Pages
- LPS-138492 Fix Poshi tests
- LPS-138492 Change the usage of name field to label field when list the object fields in Forms

### CODE REVIEW

**Comment by rodrigocunhaa** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
ci:test:object

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Manually sent to BChan: https://github.com/brianchandotcom/liferay-portal/pull/106831

**Comment by rodrigocunhaa** [comment]
ci:close

**Pull request closed without merging**
