### PR TITLE
LPS-170325 Item table from a picklist is not responsive

### PR DESCRIPTION
**Pull request by vngoliveira**
Related issue [LPS-170325](https://issues.liferay.com/browse/LPS-170325)

### CODE REVIEW

**Comment by vngoliveira** [comment]
ci:test:sf

**Comment by vngoliveira** [comment]
ci:test:sf

**Comment by vngoliveira** [comment]
ci:test:sf

**Comment by vngoliveira** [comment]
ci:test:relevant

**Comment by vngoliveira** [comment]
ci:test:object

**Comment by vngoliveira** [comment]
ci:test:object

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
Hey @vngoliveira, I'll close this PR for now. Feel free to send a new one with the changes requested. Thanks for your contribution :)

**Pull request closed without merging**
