### PR TITLE
LPS-158113 Disable actionLink from RelatedEntries table when it filled with system entries

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPS-158113

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:relevant - Failed due to [Testray Outage](https://liferay.slack.com/archives/C19PWQ74J/p1660253108886939).

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
@marcelabc do we have any estimation for the review?

**Comment by marcelabc** [comment]
Just started reviewing :)

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
