### PR TITLE
LPS-179097 Evaluate Parent Object terms

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPS-179097

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Review by MarinhoFeliphe — CHANGES_REQUESTED** [review]
@p-albuquerque solve the NPE [at this line](https://github.com/liferay-objects/liferay-portal/blob/d1c3cdacb1a703e0293c89b0b9805f1e49feb9e5/modules/apps/object/object-service/src/main/java/com/liferay/object/internal/notification/term/contributor/ObjectDefinitionNotificationTermEvaluator.java#L262) when the parent is system and try to apply the changes that we've discussed.

Thank you!

**Comment by p-albuquerque** [comment]
Resent here: https://github.com/liferay-objects/liferay-portal/pull/1981

**Pull request closed without merging**
