### PR TITLE
LPD-38358 [Test Fix] Clustering#CanCreateVirtualInstanceWithClusteringSecondNode

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://liferay.atlassian.net/browse/LPD-38358

### CODE REVIEW

**Comment by carolmariaabb** [comment]
The test is passing with these changes, as you can see [here](https://github.com/carolmariaabb/liferay-portal/pull/533#issuecomment-2394013891)

**Review by gabrielwas — COMMENTED** [review]
Good job again, @carolmariaabb !

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:stop

**Pull request closed without merging**
