### PR TITLE
LPS-172938 Modify getLocalizableLabel function to use userLanguageId

### PR DESCRIPTION
**Pull request by rebsilva**
Related Issue: https://issues.liferay.com/browse/LPS-172938

### CODE REVIEW

**Comment by rebsilva** [comment]
This is the follow-up of this PR with the changes made https://github.com/liferay-objects/liferay-portal/pull/1648

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
I've checked and the relevant tests failing on this PR are also failing on master. I need the QA team to validate this to be sure, thanks!

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/129170

**Pull request closed without merging**
