### PR TITLE
LPD-19325 Filter by relationship does not work properly through headless api using Postgres

### PR DESCRIPTION
**Pull request by diogomelo09**
[LPD-19325](https://liferay.atlassian.net/browse/LPD-19325) --

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:object-db-integration

**Review by thallescezar — APPROVED** [review]
LGTM :tada:

**Review by linolaoj — APPROVED** [review]

**Comment by linolaoj** [comment]
ci:forward

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:forward:force

**Pull request closed without merging**
