### PR TITLE
LPD-26481 Create a test to ensure the business rule of a postal address object relationship

### PR DESCRIPTION
**Pull request by igor-franca**
Related [Ticket](https://liferay.atlassian.net/browse/LPD-26484)

### CODE REVIEW

**Comment by igor-franca** [comment]
ci:test:sf

**Review by cgmonte — APPROVED** [review]
LGTM!

**Comment by igor-franca** [comment]
ci:test:playwright

**Comment by igor-franca** [comment]
ci:forward

**Pull request closed without merging**
