### PR TITLE
LPS-205115 Retrieve the link to system settings object configuration when guest users exceeds object entry submission limit

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by thallescezar** [comment]
ci:report:2489437739

**Comment by thallescezar** [comment]
ci:report:2489471318

**Comment by MarinhoFeliphe** [comment]
Resent here: https://github.com/liferay-objects/liferay-portal/pull/3059

**Pull request closed without merging**
