### PR TITLE
LPD-1629 The model builder page should not be visible without the proper feature flag: LPS-148856

### PR DESCRIPTION
**Pull request by devpedrotavares**
Related issue: [LPD-1629](https://liferay.atlassian.net/browse/LPD-1629)

### CODE REVIEW

**Review by G-Sa — APPROVED** [review]

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:report:2531015214

**Comment by carolmariaabb** [comment]
ci:report:2530989384

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
