### PR TITLE
LPS-163291 Fix NPE when id is null

### PR DESCRIPTION
**Pull request by guilhermedcamacho**
I asked @timpak to create a functional test to cover the integration with Salesforce, I think it would be more suitable for this kind of bugs related to screens upon ddm form.
Ticket created for this: [LPS-162130 Automate tests for Integrations - Salesforce](https://issues.liferay.com/browse/LPS-162130)

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:object

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:forward

**Pull request closed without merging**
