### PR TITLE
LPD-21119 Refactor MultiSelect component to support new data structure

### PR DESCRIPTION
**Pull request by igor-franca**
Related Issue: [LPD-21119](https://liferay.atlassian.net/browse/LPD-21119)
Previous https://github.com/liferay-objects/liferay-portal/pull/3195

### CODE REVIEW

**Comment by igor-franca** [comment]
ci:test:object

**Comment by igor-franca** [comment]
There are still two tests that need attentio:

1. ObjectNotifications#CanAddAttachment
2. ObjectNotificationsUpgrade#ViewNotificationTemplateAfterUpgrade7413U33

**Comment by igor-franca** [comment]
ci:stop

**Comment by igor-franca** [comment]
The tests have PR related failures. After some investigation, I still wasn't able to achieve the expected result. ⚠️

**Review by danvb112 — APPROVED** [review]
LGTM! :tada:

**Comment by igor-franca** [comment]
Hey, @danvb112. I still need to correct a behavior related to the attachment field in the notification :disappointed:

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
ci:test:relevant

**Review by danvb112 — APPROVED** [review]
LGTM! :tada:

**Comment by igor-franca** [comment]
As there are many failures in tests related to notification with the message:

> WebDriver instance already started for test x

I will run the tests again

**Comment by igor-franca** [comment]
ci:test:relevant

**Comment by igor-franca** [comment]
ci:stop

**Comment by igor-franca** [comment]
A bug was found in the workflow and modifications will be necessary. The next push will add mods to the commit:

> LPD-21119 Fix data sctruture passed to MultipleSelect in portal workflow module

**Comment by igor-franca** [comment]
ci:test:object

**Comment by igor-franca** [comment]
ci:test:relevant

**Comment by igor-franca** [comment]
I'm having difficulty dealing with the failures related to the webdriver, a [thread](https://liferay.slack.com/archives/CD7939WBE/p1712092244162679) was opened yesterday on the poshi channel to try to gather more information.

**Comment by igor-franca** [comment]
ci:stop

**Comment by igor-franca** [comment]
ci:test:object

**Comment by igor-franca** [comment]
After further investigation I believe I was able to understand the root cause of the problem. 
Waiting for test results for confirmation :pray:

**Comment by igor-franca** [comment]
The tests that were being monitored passed successfully. The other tests are unrelated to the modifications.

Furthermore, a series of manual tests were carried out on products that use the multi select component in:

1. Workflow Timers with Notification
2. Workflow Notification
3. Email Notification Attachment
4. User Notification Settings using Role
5. Object Field Aggregation 
6. Object Validation Unique Composite Key
7. Object Custom View Filter
8. Object State Manager

**Comment by igor-franca** [comment]
ci:forward:force

**Comment by igor-franca** [comment]
ci:forward:force

**Pull request closed without merging**
