### PR TITLE
LPS-201391 Add new styles to Model Builder Minimap and Control buttons

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://liferay.atlassian.net/browse/LPS-201391

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:object

**Review by igor-franca — APPROVED** [review]
Good job with this PR @danvb112 !

**Comment by igor-franca** [comment]
ci:test:relevant

**Comment by victorhcunha** [comment]
ci:test:object:nocompile

**Comment by igor-franca** [comment]
ci:forward:force

**Pull request closed without merging**
