### PR TITLE
LPD-21254 If non existent, add target ObjectState from given ListTypeEntryId

### PR DESCRIPTION
**Pull request by devpedrotavares**
Related: [LPD-21254](https://liferay.atlassian.net/browse/LPD-21254)

### CODE REVIEW

**Comment by devpedrotavares** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by devpedrotavares** [comment]
ci:test:sf

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
