### PR TITLE
LPS-164091 Cover searh by usigin integration test

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
The failures are not related.

**Review by rodrigopaulino — APPROVED** [review]
Nice, @MarinhoFeliphe! LGTM.
Could you send this to the U&SM team so they can approve?
I'll close this one, ok? Let us know when this makes into master.
Thx!

**Comment by rodrigopaulino** [comment]
ci:close

**Comment by MarinhoFeliphe** [comment]
Thank you, @rodrigopaulino 

Resent here: https://github.com/liferay-usm/liferay-portal/pull/762

**Pull request closed without merging**
