### PR TITLE
LPS-172582 If the user has permission to trigger the Object Action, the user doesn't need permission with the Object Definition that the Action interacts with

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://issues.liferay.com/browse/LPS-172582

### CODE REVIEW

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Comment by brianchandotcom** [comment]
@marcelabc @carolmariaabb see 30b3c4aaab05b752bbf3022b064275d825453133

merged to master

**Comment by guilhermedcamacho** [comment]
Reopening this PR just to continue the CI result analysis.

**Comment by anabuchmann** [comment]
Just started reviewing :)

**Pull request closed without merging**
