### PR TITLE
LPS-166202 baseline

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://issues.liferay.com/browse/LPS-166202

### CODE REVIEW

**Review by carolmariaabb — APPROVED** [review]
LGTM :tada:

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
I will investigate the unique failures :+1:

**Comment by marcelabc** [comment]
Waiting product team answer a question on Slack :+1:

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
I ran all the integration tests locally, and all passed :+1:

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
