### PR TITLE
LPS-196801 Add the system field column and make the validations

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPS-196801](https://liferay.atlassian.net/browse/LPS-196801)

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Review by naraandrade — APPROVED** [review]

**Comment by pedro-oliveira446** [comment]
Resent [here](https://github.com/brianchandotcom/liferay-portal/pull/141263)

**Pull request closed without merging**
