### PR TITLE
LPS-152720 Ensure unique FDS IDs in objects modules

### PR DESCRIPTION
**Pull request by markocikos**
Related Issue: https://issues.liferay.com/browse/LPS-152720

### References

- [LPS-152720 Ensure unique FDS IDs in objects modules](https://issues.liferay.com/browse/LPS-152720)
- https://github.com/liferay-frontend/liferay-portal/pull/2167

### What is the goal of this PR?

In this PR, we are ensuring FDS IDs are unique in DXP scope. Uniqueness is needed because registries are DXP-wide maps. We are achieving uniqueness by prefixing with portlet key.

In addition, we are making a small cleanup of unnecessary tag attributes. This is unrelated to the goal of the main task.

### What does it look like?

No effect in UI. All FDS instances should continue working the same as before.

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @markocikos, can you please check if these failures are related to your changes? Thanks

**Comment by gabrielwas** [comment]
LGTM! :D Thanks @markocikos

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:forward

**Pull request closed without merging**
