### PR TITLE
LPS-182422 Incorrect object creator at notifications

### PR DESCRIPTION
**Pull request by jgarcialr**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
Hi @jgarcialr,

Thanks for your changes, I've sent a [WIP](https://github.com/jgarcialr/liferay-portal/pull/78) to your repo,

I noticed the issue is still happening for system object definitions.

could you please try to fix it as well? if it's not what is affecting the customer for now or you can't, could you please open another LPS for system object definitions?

Thank you,
Feliphe Marinho

**Comment by MarinhoFeliphe** [comment]
@jgarcialr 

`Which system object did you use to check this issue?`

AccountEntry

`I've seen the wip and you're using objectEntry instead of originalObjectEntry, ...`

the userId inside objectEntry or the original one always will be the creator, so we can get from objectEntry as well.

**Comment by jgarcialr** [comment]
Hi @MarinhoFeliphe ,

I cannot reproduce the issue with the system object, do you have some reproduction steps?.
Maybe I'm missing some steps.

I've activated the feature flag feature.flag.LPS-167253 to have modifiable system objects.
I've created the notification template using ACCOUNTENTRY_CREATOR in the subject.
When try to select it this notification in the ActionBuilder I'm not able to select it for Account Entry objects.

**Comment by MarinhoFeliphe** [comment]
@jgarcialr,

sorry I confused with Bookmarks Entry that is still being developed.

Resent here: https://github.com/brianchandotcom/liferay-portal/pull/134460

Thank you!

**Pull request closed without merging**
