### PR TITLE
LPS-168742 Create Custom sidebar content for FreeMarker Template Editor

### PR DESCRIPTION
**Pull request by danvb112**
Related Issues: 

https://issues.liferay.com/browse/LPS-168742
https://issues.liferay.com/browse/LPS-168331

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by alinedoleron** [comment]
ci:forward

**Comment by danvb112** [comment]
ci:forward

**Comment by danvb112** [comment]
Sent to: https://github.com/brianchandotcom/liferay-portal/pull/126617

**Pull request closed without merging**
