### PR TITLE
LPD-27680 Add missing test.properties for BPM playwright projects

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://liferay.atlassian.net/browse/LPD-27680

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:playwright

**Review by rebsilva — APPROVED** [review]
LGTM! :cherry_blossom:

**Comment by danvb112** [comment]
ci:test:sf

**Review by rebsilva — APPROVED** [review]
LGTM! :tada:

**Comment by rebsilva** [comment]
ci:test:playwright

**Comment by danvb112** [comment]
ci:test:playwright

**Comment by danvb112** [comment]
ci:forward:force

**Pull request closed without merging**
