### PR TITLE
LPS-182940 [FE] Date and Time story

### PR DESCRIPTION
**Pull request by rebsilva**
Related issues:
- https://issues.liferay.com/browse/LPS-182940
- https://issues.liferay.com/browse/LPS-182941
- https://issues.liferay.com/browse/LPS-182942
- https://issues.liferay.com/browse/LPS-182943
- https://issues.liferay.com/browse/LPS-182944

Story link: https://issues.liferay.com/browse/LPS-143068

Summary: This story will allow to add Date & Time fields on objects; it was necessary to extract some functions of the Forms DatePicker to use on Objects. Also, all the utils involved were transformed into Typescript.

OBS: The ci:test:sf will fail because the file with the feature flag creation is in the Backend PR; it needs to be sent before this PR or I will need to create in my own.

### CODE REVIEW

**Review by alinedoleron — COMMENTED** [review]
Just started reviewing :)

**Comment by rebsilva** [comment]
@alinedoleron Thanks for your review! I've pushed some changes, only this code on `PredefinedValuesTable`:

```
const inputAsValue =
		businessType === 'DateTime' ? true : false;
```
and use it on here:

```
{
businessType,
inputAsValue,
label,
name,
value: ''
};
```

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:object

**Comment by rebsilva** [comment]
ci:test:form

**Review by alinedoleron — APPROVED** [review]
LGTM! :purple_heart::blossom:

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:forward:force

**Comment by marcelabc** [comment]
ci:forward:force

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:forward:force

**Comment by marcelabc** [comment]
I believe that the forward:force command is not working because Rebeca did not set the new configuration from Git.

**Comment by marcelabc** [comment]
Resend here: https://github.com/liferay-objects/liferay-portal/pull/2124

**Comment by rebsilva** [comment]
Thanks @marcelabc for taking care of this! :purple_heart:

**Pull request closed without merging**
