### PR TITLE
[Revert PR] LPS-155103

### PR DESCRIPTION
**Pull request by rijema**
Please see this comment: https://issues.liferay.com/browse/LPS-157935?focusedCommentId=2722326&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2722326

Thanks.

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:forward

**Pull request closed without merging**
