### PR TITLE
LPS-185103 | Correct new document type toolbar alignment

### PR DESCRIPTION
**Pull request by jaimelr10**
Motivation
=======
As [the ticket](https://issues.liferay.com/browse/LPS-185103) says, we need to update the CSS since we have made changes in `main`

Proposed Solution
========
As [the ticket](https://issues.liferay.com/browse/LPS-185103) says, we need to  change the margin-top from `contextual-sidebar-content` to `data-engine-form-builder`. This also fixes [this ticket (Elements overlapped when zoom is 200% on 767px resolutions)](https://issues.liferay.com/browse/LPS-165954).

Steps to Verify
========
1. Content & Data
2. Documents and Media
3. New document type
4. View that the toolbar has the proper top margin

Screenshots
========
Before:
image

After:
image

With zoom is 200% on 767px resolutions as said in https://issues.liferay.com/browse/LPS-165954:
image

**Jira Ticket:** https://issues.liferay.com/browse/LPS-185103

### CODE REVIEW

**Comment by marcelabc** [comment]
Hey @cgmonte,
This PR is related to a change in the frontend of the Data Engine. Could you please review it? :smile:

**Review by cgmonte — APPROVED** [review]
LGTM!

**Comment by cgmonte** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
