### PR TITLE
LPD-33369 Add step to download a file from the Attachment field when adding an object entry in a existing playwright test

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://liferay.atlassian.net/browse/LPD-33586

### CODE REVIEW

**Comment by rebsilva** [comment]
i'll review this later today, thanks!

**Comment by rebsilva** [comment]
just started reviewing! :cherry_blossom:

**Review by rebsilva — APPROVED** [review]
LGTM! :tada:

**Comment by rebsilva** [comment]
ci:test:playwright

**Comment by danvb112** [comment]
ci:forward

**Pull request closed without merging**
