### PR TITLE
LPS-137866 Change Long Integer Business Field Type description

### PR DESCRIPTION
**Pull request by mateussgn**
Related Issue: https://issues.liferay.com/browse/LPS-137866

Related issue: https://issues.liferay.com/browse/LPS-137866

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @mateussgn, can you please check if these failures are related to your changes? Thanks

**Comment by liferay-forms** [comment]
Hey @mateussgn, can you please check if these failures are related to your changes? Thanks

**Comment by mateussgn** [comment]
Related to: https://github.com/rodrigocunhaa/liferay-portal/pull/1727

**Comment by mateussgn** [comment]
ci:forward

**Comment by mateussgn** [comment]
ci:stop

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:close

**Pull request closed without merging**
