### PR TITLE
LPS-184883 The Edit action in Objects admin interface is labeled as "View" and uses the wrong icon, which might confuse users

### PR DESCRIPTION
**Pull request by ericthmoritsuka**
Related issue: https://issues.liferay.com/browse/LPS-184883

Julia Lira asked to change the icons from the eye (_view_) to pencil (_edit_) if the user had permission to edit.

~~So, I added a check using _hasUpdateobjectDefinitionPermission_ from _BaseObjectDefinitionsDisplayContext.java_ to check for the permission and set the icon accordingly.~~

So, I added a premission check in the beginning of the method as requested by @guilhermedcamacho and used this boolean instead of calling the method itself.

I talked to Murilo Stodolni and he talked to the team and told me that I could send the fix for the context inside the Object and open a new ticket for the alteration in _ViewObjectDefinitionsDisplayContext_ that requires a little more work.

### CODE REVIEW

**Comment by ericthmoritsuka** [comment]
ci:test:sf

**Comment by ericthmoritsuka** [comment]
ci:test:relevant

**Comment by ericthmoritsuka** [comment]
I pushed a commit to solve the conflict but it seems that I did something wrong. I thought I was going to push a new commit. Instead, I overwrote the previous one and now I only have one commit with the new title and the alterations. Sorry about that.

**Review by guilhermedcamacho — CHANGES_REQUESTED** [review]

**Comment by guilhermedcamacho** [comment]
Hey @ericthmoritsuka , sorry for the delay.
Can you also change the commit message to reflect your changes?
Thanks!

**Comment by ericthmoritsuka** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:object

**Review by guilhermedcamacho — APPROVED** [review]
LGTM :tada:

**Comment by guilhermedcamacho** [comment]
Hey @ericthmoritsuka , we need to wait the QAs investigation regarding CI tests, it seems that we need to adjust some Poshi tests to work accordingly with the new icon (pencil).

**Comment by samuelromeiro** [comment]
Resent here https://github.com/liferay-objects/liferay-portal/pull/2317

**Pull request closed without merging**
