### PR TITLE
LPD-36591 Allow users to unbind objects from root context in the relationship

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**
Related: https://liferay.atlassian.net/browse/LPD-36591

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:object

**Comment by marcelabc** [comment]
ci:report:37336667

**Comment by marcelabc** [comment]
After analyzing the `ci:test:object`, this test failure seems related: com.liferay.object.service.test.ObjectDefinitionLocalServiceTest

**Comment by marcelabc** [comment]
ci:report:37419405

**Comment by marcelabc** [comment]
resent: https://github.com/liferay-objects/liferay-portal/pull/3720

**Pull request closed without merging**
