### PR TITLE
LPS-169369 Replace notificationTemplateId with ERC in ObjectAction

### PR DESCRIPTION
**Pull request by murilostodolni**
Related: https://issues.liferay.com/browse/LPS-169369

### CODE REVIEW

**Comment by murilostodolni** [comment]
Hi @guilhermedcamacho 

The changes don't broke anything. I add integration test to this task. Can you review, please?

**Comment by guilhermedcamacho** [comment]
> Hi @guilhermedcamacho
> 
> Your changes don't broke anything. I add integration test to this task. Can you review, please?

Sure, thanks!

**Review by guilhermedcamacho — APPROVED** [review]
LGTM!

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:forward

**Comment by timpak** [comment]
ci:test:object

**Comment by murilostodolni** [comment]
QA Approved [here](https://liferay.slack.com/archives/C048YNC5GRK/p1672316661830109)

**Comment by murilostodolni** [comment]
Forwarding manually: https://github.com/brianchandotcom/liferay-portal/pull/128296

**Comment by murilostodolni** [comment]
ci:close

**Pull request closed without merging**
