### PR TITLE
LPS-153278 Create Notification Template component

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-153278

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:sf

**Review by alinedoleron — APPROVED** [review]

**Comment by gabrielwas** [comment]
ci:forward

**Pull request closed without merging**
