### PR TITLE
[CLDR] LPD-20669 Fix functional test ObjectFieldsDateAndTime#CanSeeDifferentTimeZone to work with CLDR locale provider

### PR DESCRIPTION
**Pull request by julschong**
Hi Team,
This is for issue: https://liferay.atlassian.net/browse/LPD-20669
This is the same issue as other testcase here: https://github.com/liferay-workflow/liferay-portal/pull/1086

--- Copied from the workflow PR ---
Our current java locale provider is JRE (jdk8 default)
In preparation to make the change to jdk21, we noticed that jdk21 default is CLDR. This made many functional tests fail because display name for timezone, country, format are slightly different.

In the case of this Object test:
The testcase is looking for an option where the label text matches exactly with the text `(UTC -03:00) Brasilia Time` both to select.
This failed test case with CLDR because the label text changed.

Solution:
We can use timezoneId to locate the option with xpath and assert that it is clicked instead.

This works both with JRE and CLDR locally
CI Testing CLDR here: https://github.com/julschong/liferay-portal/pull/1182
This PR will have results for CI Testing with JRE

Thanks!

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:objects

**Comment by julschong** [comment]
ci:test:object

**Comment by julschong** [comment]
ci:test:object-functional

**Comment by julschong** [comment]
[JRE passed](https://testray.liferay.com/home/-/testray/case_results/2551070116?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2551069541%26cur%3D1%26delta%3D200%26tab%3Druns%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by julschong** [comment]
ci:report:2552706550

**Comment by julschong** [comment]
no unique failure on ci:test:object

**Comment by marcelabc** [comment]
ci:forward:force

**Pull request closed without merging**
