### PR TITLE
LPS-193375 Create upgrade process to set the script configuration true by default

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPS-193375](https://liferay.atlassian.net/browse/LPS-193375)

This PR is blocked by https://github.com/liferay-objects/liferay-portal/pull/2521

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
@mateussgn , only the last commit needs review.

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Review by guilhermedcamacho — APPROVED** [review]

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Review by mateussgn — APPROVED** [review]
Just solve the conflict
LGTM! 🎉

**Pull request closed without merging**
