### PR TITLE
LPS-193118 Pass entityModel to SalesforceFilterFactory as well

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPS-193118

### CODE REVIEW

**Review by mateussgn — APPROVED** [review]
LGTM! 🎉

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:object

**Review by guilhermedcamacho — APPROVED** [review]

**Comment by guilhermedcamacho** [comment]
ci:reevaluate:1377401_13717

**Comment by guilhermedcamacho** [comment]
ci:reevaluate:1377401_13717

**Comment by guilhermedcamacho** [comment]
See [brianchandotcom#139119](https://github.com/brianchandotcom/liferay-portal/pull/139119)

**Pull request closed without merging**
