### PR TITLE
LPS-200998 Numeric object fields now accept null values

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Review by gabrielwas — APPROVED** [review]
LGTM!

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:object

**Comment by guilhermedcamacho** [comment]
We decided to follow another approach for this bug, we will revert this [PR](https://github.com/brianchandotcom/liferay-portal/pull/143198)

**Comment by guilhermedcamacho** [comment]
ci:stop

**Comment by guilhermedcamacho** [comment]
See #2830

**Pull request closed without merging**
