### PR TITLE
LPS-143492 Make the Objects notification types more user-friendly on Commerce settings

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-143492

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Hey @danvb112 ,
The test "LocalFile.CPCommerceChannels#RemoveNotificationQueue" failed in every ci round of this PR. Could you verify if it is related, please?

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:forward

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:forward

**Comment by mateussgn** [comment]
Hey @danvb112, those seem to be baseline errors, I suggest you close the PR update your branch, and send it again 😄.

**Comment by danvb112** [comment]
Sent to: https://github.com/liferay-objects/liferay-portal/pull/378

**Pull request closed without merging**
