### PR TITLE
LPD-30339 Store the usePreferredLanguageForGuests in object action parameters

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**
About the exception message, please see this [Slack thread](https://liferay.slack.com/archives/C026UR5976G/p1720463490261719).

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:object

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Review by linolaoj — CHANGES_REQUESTED** [review]
Hi @MarinhoFeliphe , please add the `asserts` related to the objectActions on `testAddObjectActionWithUsePreferredLanguageForGuestsParameter`.

**Comment by MarinhoFeliphe** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/152175

**Pull request closed without merging**
