### PR TITLE
LPS-170647 Add List Type Entry ERC tests

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-170647

### CODE REVIEW

**Comment by mateussgn** [comment]
`com.liferay.list.type.service.test.ListTypeEntryLocalServiceTest` is failing, I'm on it.

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:object

**Comment by murilostodolni** [comment]
ci:close

**Pull request closed without merging**
