### PR TITLE
LPD-34083 Fix model builder right sidebar width resizing

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://liferay.atlassian.net/browse/LPD-34083

### CODE REVIEW

**Review by rebsilva — APPROVED** [review]
LGTM! :tada: :cherry_blossom:

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:object

**Comment by danvb112** [comment]
CI Failures are not related!

**Comment by danvb112** [comment]
ci:forward:force

**Pull request closed without merging**
