### PR TITLE
[TS] LPS-198535 Convert Multi-Select Picklists ListEntry type to ArrayList

### PR DESCRIPTION
**Pull request by gergelyszalay**
Hi Team,

I would like to kindly ask you to review my PR.

Issue: https://liferay.atlassian.net/browse/LPS-198535. When an object has a multiselect picklist field with entries, it can not be edited through Headless Api Patch if we don't include the multiselect values in the request. If we don't add it fails.

Root cause: Multiselect values got new schemas in https://liferay.atlassian.net/browse/LPS-143671, and the validation can not handle that.

Solution: change back the ListEntry type to ArrayList<String> to be able to validate and update the object with an ArrayList.

I was considering creating a validation for ListEntry but it caused more issues, as the ObjectEntryLocalServiceImpl.java is not yet ready to handle ListEntry, and it needs a major change.

Thank you in advance! 
BR,
Gege

### CODE REVIEW

**Comment by gergelyszalay** [comment]
ci:test:relevant

**Comment by gergelyszalay** [comment]
ci:test:objects

**Comment by gergelyszalay** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
@gergelyszalay please see https://github.com/liferay-objects/liferay-portal/pull/2708

**Pull request closed without merging**
