### PR TITLE
LPS-147064 Add button to duplicate Notification Template

### PR DESCRIPTION
**Pull request by gustavolimav**
https://issues.liferay.com/browse/LPS-161552

Adds a duplicate action

Screenshot from 2022-10-25 15-43-59

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
Thanks for the implementation, @gustavolimav! LGTM :D

**Comment by gabrielwas** [comment]
ci:forward

**Pull request closed without merging**
