### PR TITLE
LPS-178473 Fix getRelationshipValue and _getRelationshipId methods and fix matcher Pattern

### PR DESCRIPTION
**Pull request by DaneszLR**
Hi Team!

This pull request is related to https://github.com/liferay-objects/liferay-portal/pull/1941 as a first pull request with a description.
This pull request is also related to https://github.com/liferay-objects/liferay-portal/pull/1956 but with the conflicts resolved and the logic fixed.

Best regards,
Dani

### CODE REVIEW

**Comment by DaneszLR** [comment]
ci:test:sf

**Comment by DaneszLR** [comment]
ci:test:relevant

**Comment by DaneszLR** [comment]
ci:test:object

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:object

**Comment by seltong** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Just started reviewing :)

**Comment by DaneszLR** [comment]
Hi @seltong and @marcelabc. I saw the test failures, but they are a bit strange to me. Could someone from QA look at these tests to confirm that they are relevant?

**Comment by marcelabc** [comment]
Hey @DaneszLR, how are you doing?

Sorry for the delay in reviewing your PR. I've tried to reproduce the issue with this PR (this code), and it is still reproducible. Besides that, I've tried to reproduce and debug your code simultaneously, and the breaking point never reaches ObjectDefinitionGraphQLDTOContributor.getRelationshipValue(). Could you confirm if the GraphQL query is correct on the ticket (step 10), please?

Thanks in advance :smile:

**Comment by DaneszLR** [comment]
Hi @marcelabc,

I have built a fully new and vanilla bundle from this PR, followed the steps and got the result you can see on the picture.
image

Since then I haven't updated it with master (it was updated with it on the day of making the PR), so I'm gonna set up a test branch with everything up to date to see if there been a change, that made the code not work.

**Comment by marcelabc** [comment]
Hey @DaneszLR 
While you are trying to understand this error, I [opened a thread](https://liferay.slack.com/archives/C5E1CRLJY/p1682432830072949) in the headless channel on Slack. I hope they help us :pray: 

I'm closing this PR since this code is not fixing the issue, okay? Feel free to send another one or talk with me on Slack!

**Pull request closed without merging**
