### PR TITLE
LPD-31143 Add support for localization of fields in system objects

### PR DESCRIPTION
**Pull request by marco-leo**

### CODE REVIEW

**Comment by marco-leo** [comment]
Working on Tests

**Comment by marco-leo** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:object

**Comment by marco-leo** [comment]
ci:test:relevant

**Review by gabrielwas — CHANGES_REQUESTED** [review]

**Comment by guilhermedcamacho** [comment]
See [guilhermedcamacho#156](https://github.com/guilhermedcamacho/liferay-portal/pull/156)

**Pull request closed without merging**
