### PR TITLE
LPS-137866 Change Long Integer Business Field Type description

### PR DESCRIPTION
**Pull request by mateussgn**
Related Issue: https://issues.liferay.com/browse/LPS-137866

Related issue: https://issues.liferay.com/browse/LPS-137866

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
Related to: https://github.com/rodrigocunhaa/liferay-portal/pull/1727

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
