### PR TITLE
LPD21575 - Create a new modal to list all failed or successful imported Object definitions

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://liferay.atlassian.net/browse/LPD-21575

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
Starting the review :shipit:

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:sf

**Review by igor-franca — CHANGES_REQUESTED** [review]
Hey @danvb112, nice work here. Just some details.

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
Hey @danvb112 

```
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/object/object-js-components-web/src/main/resources/META-INF/resources/utils/api.ts
     [exec]   466:4  error  Member "message" should be declared before member "title".  @typescript-eslint/member-ordering
     [exec] 
     [exec] ✖ 1 problem (1 error, 0 warnings)
```

**Comment by danvb112** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
ci:test:object

**Review by igor-franca — APPROVED** [review]

**Comment by igor-franca** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:object

**Comment by danvb112** [comment]
I've analyzed the ci results and the failures are not related!

**Comment by danvb112** [comment]
ci:forward:force

**Pull request closed without merging**
