### PR TITLE
LPS-161654 Add definition name when definition label default language doesn't exist in notification template

### PR DESCRIPTION
**Pull request by M-IgorFranca**
Related: https://issues.liferay.com/browse/LPS-161654

### CODE REVIEW

**Comment by M-IgorFranca** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — APPROVED** [review]

**Comment by M-IgorFranca** [comment]
I run the Object Populate#CanMapStringTypeAndViewEntries test locally and it passed successfully. Then I will run ci:reevaluate.

**Comment by M-IgorFranca** [comment]
ci:reevaluate:1377401_4882

**Comment by danvb112** [comment]
ci:forward

**Pull request closed without merging**
