### PR TITLE
COMMERCE-10467 Add extra fields in order message payload to enable conditions in the object actions

### PR DESCRIPTION
**Pull request by luca-pellizzon**

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Comment by carolmariaabb** [comment]
@luca-pellizzon can we forward this PR? Please see https://github.com/liferay-objects/liferay-portal/pull/1525

**Comment by luca-pellizzon** [comment]
@carolmariaabb yes, you can forward it

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
