### PR TITLE
LPS 138035

### PR DESCRIPTION
**Pull request by interaminense**

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Just started reviewing :)

**Comment by interaminense** [comment]
Sent directly to Brian https://github.com/brianchandotcom/liferay-portal/pull/106431

**Pull request closed without merging**
