### PR TITLE
LPD-30081 Remove FF to enable the Support for Account, Organization and Regular Roles in Email Notification Templates

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://liferay.atlassian.net/browse/LPD-30081

### CODE REVIEW

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:test:object
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
I have to fix the Poshi tests with the following errors:

```
com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//div[label[contains(.,'To')]]//input[not(contains(@type,'checkbox'))]"
```
```
com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//div[label[contains(.,'CC')]]//input[not(contains(@type,'checkbox'))]"

```

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by marcelabc** [comment]
ci:report:44587976

**Comment by marcelabc** [comment]
@carolmariaabb os dois bugs foram mergeados por Brian.

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
The SF failure is unrelated. It's also happening in other PRs (see https://github.com/liferay-ac/liferay-portal/pull/1705#issuecomment-2250173868)

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by marcelabc** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
