### PR TITLE
[LPS 165660, LPS-166819] Remove FF for LPS-164998 and LPS-164999

### PR DESCRIPTION
**Pull request by rebsilva**
Related Issues:

- https://issues.liferay.com/browse/LPS-166819
- https://issues.liferay.com/browse/LPS-165660

### CODE REVIEW

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:relevant

**Review by carolmariaabb — APPROVED** [review]
LGTM 🎉

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/125977

**Pull request closed without merging**
