### PR TITLE
LPS-169733

### PR DESCRIPTION
**Pull request by alinedoleron**
Ticket: https://issues.liferay.com/browse/LPS-169733

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — CHANGES_REQUESTED** [review]
Hi @alinedoleron, I was testing your solution and noticed that when I create a view filter using the relationship field and try to view the entries again, the portal crashes :/ Could you check that, please? Thanks :)

**Comment by samuelromeiro** [comment]
Hey @naraandrade, Aline is on vacation. Is it possible to check those failures?

**Comment by naraandrade** [comment]
> Hey @naraandrade, Aline is on vacation. Is it possible to check those failures?

Sure :) I can check it later.

**Comment by naraandrade** [comment]
> Hi @alinedoleron, I was testing your solution and noticed that when I create a view filter using the relationship field and try to view the entries again, the portal crashes :/ Could you check that, please? Thanks :)

Apparently this issue has been already solved by another PR and were not related with this one, so I'll approve it now :)

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Comment by naraandrade** [comment]
Opened a [QA Request ](https://liferay.slack.com/archives/C048YNC5GRK/p1670245322885619)to check if the failures are related.

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/127248

**Pull request closed without merging**
