### PR TITLE
LPS-174543 Allow objects details tab work with system modifiable objects

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-174543

### CODE REVIEW

**Comment by mateussgn** [comment]
Failures are related, I'm fixing them.

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:object

**Review by gabrielwas — APPROVED** [review]
LGTM :)

**Comment by mateussgn** [comment]
ci:close

**Pull request closed without merging**
