### PR TITLE
LPS-206063 Use span instead of a link in the label renderer component

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://liferay.atlassian.net/browse/LPS-206063

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:relevant

**Review by rebsilva — APPROVED** [review]
LGTM! :tada: amazing job @danvb112 and @igor-franca! :cherry_blossom:

**Comment by rebsilva** [comment]
i will test the PR now, i'll let you know if i find something

**Comment by danvb112** [comment]
ci:forward:force

**Pull request closed without merging**
