### PR TITLE
LPD-19861 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://issues.liferay.com/browse/LPD-19861

Hi Objects team!
This pull request aims to allow creating a system object definition with the configurarion 'Show Widget in Page Builder' already marked.
We need this behavior because in https://liferay.atlassian.net/browse/LPD-6541, we are creating a utility page template with some system object definitions as default.

Thanks in advance for reviewing :smile:

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
Hey @carolmariaabb 
Could you review this PR, please? :smile:

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
