### PR TITLE
LPS-157205

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by gabrielwas** [comment]
Depending on https://github.com/brianchandotcom/liferay-portal/pull/120383 to be merged

**Comment by gabrielwas** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/120383https://github.com/brianchandotcom/liferay-portal/pull/120383 is merged

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by timpak** [comment]
ci:test:relevant

**Comment by timpak** [comment]
ci:test:object

**Comment by timpak** [comment]
cI:test:object

**Comment by timpak** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by timpak** [comment]
ci:test:object

**Comment by timpak** [comment]
The results from https://github.com/liferay-objects/liferay-portal/pull/808#issuecomment-1185873634 look good, no failures related to the changes made in the PR. I'm going to forward this and run the objects test suite for traceability.

**Comment by timpak** [comment]
ci:forward

**Comment by timpak** [comment]
Actually, I found an issue hidden in the one of the logs. @gabrielwas can you take a look?

> [exec] com.liferay.object.admin.rest.resource.v1_0.test.ObjectDefinitionResourceTest > testPutObjectDefinitionWithStorageType STARTED
> [beanshell] 2022-07-15 19:58:03.033 WARN  [http-nio-8080-exec-4][BaseExceptionMapper:73] Problem {detail=null, status=Bad Request, title=null, type=null}
> [beanshell] com.liferay.object.exception.ObjectDefinitionStorageTypeException: null
> [beanshell] 	at com.liferay.object.admin.rest.internal.resource.v1_0.ObjectDefinitionResourceImpl.putObjectDefinition(ObjectDefinitionResourceImpl.java:174) ~[?:?]

**Comment by gabrielwas** [comment]
Hey @timpak! This test is actually failing intermittently. I can fix it. But can we forward it first?

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by timpak** [comment]
@gabrielwas, ah I didn't know it was a flaky test. Yeah we can forward. If we run into issues forwarding it, I'll send it manually to BChan.

**Comment by timpak** [comment]
ci:test:object

**Comment by liferay-forms** [comment]
Hey @gabrielwas, can you please check if these failures are related to your changes? Thanks

**Comment by timpak** [comment]
None of the failures are relevant to the changes. ObjectDefinitionStorageTypeException is because of a flaky test. Going to forward this to BChan.

**Comment by timpak** [comment]
ci:forward

**Comment by liferay-forms** [comment]
Hey @gabrielwas, can you please check if these failures are related to your changes? Thanks

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:reevaluate:1307401_3847

**Comment by gabrielwas** [comment]
ci:forward

**Pull request closed without merging**
