### PR TITLE
LPD-22030  If it is a System Object field add the Object field name corresponding to the site default Locale to the labels

### PR DESCRIPTION
**Pull request by evibudai**
Hi Team,
https://liferay.atlassian.net/browse/LPD-22030

Follow-up for this PR: https://github.com/liferay-objects/liferay-portal/pull/3210

The first iteration didn't add the system object fields correct Locale.

Please review!

### CODE REVIEW

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by evibudai** [comment]
hi @carolmariaabb , thanks for starting the review! @G-Sa asked me to do some more tests with multiple languages, so before moving forward I still have to do them.

**Comment by carolmariaabb** [comment]
@evibudai please prioritize forwarding this PR to Brian as the hotfix was already sent with this code.

**Comment by evibudai** [comment]
Forwarded to BChan: https://github.com/brianchandotcom/liferay-portal/pull/149107

**Comment by evibudai** [comment]
@carolmariaabb I tested what @G-Sa asked, and it worked as expected. If there are multiple language labels, they are added too.

I also checked the Testray analysis of relevant. They are not related to the changes.

**Comment by evibudai** [comment]
ci:test:stable

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by evibudai** [comment]
thanks @carolmariaabb ! :)

**Pull request closed without merging**
