### PR TITLE
LPD-16492 Add missing breaking change registry and dummy upgrade steps

### PR DESCRIPTION
**Pull request by guilhermedcamacho**
Related issue: https://issues.liferay.com/browse/LPD-16492

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Hey @p-albuquerque, can you please check the CI results?

**Comment by p-albuquerque** [comment]
Sure! 
Starting verification now...

**Comment by p-albuquerque** [comment]
ci:report:2545256695

**Review by p-albuquerque — APPROVED** [review]

**Comment by p-albuquerque** [comment]
LGTM

**Comment by p-albuquerque** [comment]
ci:forward:force

**Pull request closed without merging**
