### PR TITLE
LPS-165682 Implement Integration Test and Update the ObjectCodeEditorUtil

### PR DESCRIPTION
**Pull request by hongvo2308**
Hi team,
This is the PR for updating https://issues.liferay.com/browse/LPS-165682. 
I have moved the class **ObjectCodeEditorUtil** to module **object-api** for exporting to be able to write the test for it. And I have also updated the function to pass the test. Please review this and let me know if it needs to be updated.
Thank you.

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by hongvo2308** [comment]
Hi 
I have rebased this PR and fixed the conflict. Could you please review it again?
Thank you.

**Comment by naraandrade** [comment]
Hi @hongvo2308, could you please take a look at the SF failures? Thanks :)

**Comment by hongvo2308** [comment]
ci:test:sf

**Comment by hongvo2308** [comment]
Hi @naraandrade 
Yes, I have updated the PR and fixed the formatSource. Could you please review it again?
Thank you very much.

**Comment by hongvo2308** [comment]
Hi
I found that due to the updates in the ticket https://issues.liferay.com/browse/LPS-151540 this PR is no longer correct. I will close this PR, double-check, and send another PR if necessary.
Thank you for your time

**Pull request closed without merging**
