### PR TITLE
LPS-159539 Add format content from To, From, Cc and Bcc fields in Notification

### PR DESCRIPTION
**Pull request by murilostodolni**

### CODE REVIEW

**Comment by murilostodolni** [comment]
@rodrigopaulino can you review, please?

**Comment by murilostodolni** [comment]
ci:test:relevant

**Review by rodrigopaulino — APPROVED** [review]
LGTM! 🎉

**Comment by rodrigopaulino** [comment]
When it passes, @murilostodolni. Please call the forward command. Thx!
Good job!

**Comment by murilostodolni** [comment]
ci:foward

**Comment by murilostodolni** [comment]
ci:forward

**Pull request closed without merging**
