### PR TITLE
LPS-135398 As a object creator, I want to define a field as unique data only

### PR DESCRIPTION
**Pull request by carolmariaabb**
**Related Issues:**
https://issues.liferay.com/browse/LPS-181310
https://issues.liferay.com/browse/LPS-181311
https://issues.liferay.com/browse/LPS-181312

### CODE REVIEW

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by marcelabc** [comment]
Just started reviewing :)

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:reevaluate:1327401_9208

**Comment by carolmariaabb** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/133903

**Pull request closed without merging**
