### PR TITLE
LPS-161260 Add disable to AutoComplete component

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-161260

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
This PR is the solution of a release blocker: https://issues.liferay.com/browse/LPS-161260

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@danvb112 merged to master.

**Pull request closed without merging**
