### PR TITLE
LPS-147425 Use fdsSortItemList to pre-order object entries with custom views

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-147425

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
Hi @mateussgn, could you take a look at the tests please? 😄

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
@mateussgn will investigate the tests failures

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:forward

**Pull request closed without merging**
