### PR TITLE
LPS-197876 The action of a custom Object is not being triggered to send an email template

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPS-197876](https://liferay.atlassian.net/browse/LPS-197876)

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Review by MarinhoFeliphe — CHANGES_REQUESTED** [review]
@pedro-oliveira446 I've provided a WIP [here](https://github.com/MarinhoFeliphe/liferay-portal/pull/235/commits/67632517df7b4d2bd3619ea2bfc955f98e542ebc), please apply these changes instead of these one and double check if everything is working fine.

Thank you!

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM!! :tada:

**Comment by guilhermedcamacho** [comment]
ci:forward

**Pull request closed without merging**
