### PR TITLE
LPS-163600

### PR DESCRIPTION
**Pull request by rodrigopaulino**
https://issues.liferay.com/browse/LPS-163600

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:forward

**Comment by murilostodolni** [comment]
ci:forward

**Comment by rodrigopaulino** [comment]
ci:stop

**Comment by rodrigopaulino** [comment]
ci:close

**Comment by rodrigopaulino** [comment]
Manually forwarded: https://github.com/brianchandotcom/liferay-portal/pull/123499

**Pull request closed without merging**
