### PR TITLE
LPS-174111 Add feature flag to LPS-155659

### PR DESCRIPTION
**Pull request by murilostodolni**
Related: https://issues.liferay.com/browse/LPS-174111

### CODE REVIEW

**Comment by murilostodolni** [comment]
ci:test:sf

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@murilostodolni @carolmariaabb see 9d7c187eefaa93ae658f47369b3694d4fdcc6b16

**Comment by carolmariaabb** [comment]
ci:close

**Pull request closed without merging**
