### PR TITLE
LPS-162139,LPS-162137,LPS-163994

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issues:
[LPS-162137](https://issues.liferay.com/browse/LPS-162137);
[LPS-162139](
https://issues.liferay.com/browse/LPS-162139);
[LPS-163994](https://issues.liferay.com/browse/LPS-163994).

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:stop

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:close

**Pull request closed without merging**
