### PR TITLE
LPS-141499 Display default name of Objects and its Fields, Relationships, Layouts if there isn't translation for the selected Portal language

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPS-141499

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:stop

**Comment by mateussgn** [comment]
ci:stop

**Comment by mateussgn** [comment]
PR Closed manually because CI was not running. @p-albuquerque please comment below the new PR.

**Comment by p-albuquerque** [comment]
New PR sent in: #322

**Pull request closed without merging**
