### PR TITLE
LPS-194293 Integration tests for system object fields

### PR DESCRIPTION
**Pull request by leilanyaragao**
Follow-up: https://github.com/brianchandotcom/liferay-portal/pull/142844

Related issue: [LPS-194293](https://liferay.atlassian.net/browse/LPS-194293)

### CODE REVIEW

**Comment by leilanyaragao** [comment]
ci:test:object

**Comment by leilanyaragao** [comment]
ci:test:relevant

**Review by carolmariaabb — CHANGES_REQUESTED** [review]
@leilanyaragao please fix the conflicts. Thanks!

**Comment by leilanyaragao** [comment]
ci:test:sf

**Comment by leilanyaragao** [comment]
ci:test:object

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
@leilanyaragao the following test is failing only in this PR:

1. [com.liferay.object.service.test.ObjectActionLocalServiceTest](https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/681935/testReport/com.liferay.object.service.test/ObjectActionLocalServiceTest) - [Failed 0 of last 4](https://testray.liferay.com/home/-/testray/case_results/2453863812/history)

Could you please take a look?

Thanks!

**Comment by leilanyaragao** [comment]
ci:test:object

**Comment by leilanyaragao** [comment]
ci:test:relevant

**Comment by leilanyaragao** [comment]
ci:test:sf

**Comment by leilanyaragao** [comment]
ci:test:relevant

**Comment by leilanyaragao** [comment]
ci:test:object

**Comment by leilanyaragao** [comment]
ci:test:sf

**Comment by leilanyaragao** [comment]
ci:test:relevant

**Comment by leilanyaragao** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
@leilanyaragao please fix the conflicts. Thanks!

**Comment by leilanyaragao** [comment]
ci:test:sf

**Comment by leilanyaragao** [comment]
ci:test:relevant

**Comment by leilanyaragao** [comment]
ci:test:object

**Comment by leilanyaragao** [comment]
ci:forward:force

**Comment by leilanyaragao** [comment]
ci:stop

**Comment by leilanyaragao** [comment]
ci:stop

**Comment by leilanyaragao** [comment]
ci:test:sf

**Comment by leilanyaragao** [comment]
ci:test:relevant

**Comment by leilanyaragao** [comment]
ci:test:object

**Pull request closed without merging**
