### PR TITLE
LPS-201520 Follow up #2884

### PR DESCRIPTION
**Pull request by G-Sa**
Follow up from #2884

### CODE REVIEW

**Comment by G-Sa** [comment]
ci:test:object

**Comment by G-Sa** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by G-Sa** [comment]
ci:test:relevant

**Comment by G-Sa** [comment]
ci:test:sf

**Comment by G-Sa** [comment]
ci:test:relevant

**Comment by G-Sa** [comment]
ci:forward:force

**Pull request closed without merging**
