### PR TITLE
LPD-5462 Remove feature flag of LPS-196724

### PR DESCRIPTION
**Pull request by devpedrotavares**
Related ticket: [LPD-5462](https://liferay.atlassian.net/browse/LPD-5462)

### CODE REVIEW

**Review by G-Sa — APPROVED** [review]
LGTM

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
