### PR TITLE
LPS-201936 Placeholder shows 'Select an Option' on Language option

### PR DESCRIPTION
**Pull request by larissacribeiro**
**Related Issue**: [LPS-201936](https://liferay.atlassian.net/browse/LPS-201936)

### CODE REVIEW

**Comment by marcelabc** [comment]
Hey @cgmonte ,
I'm assigning this PR to you because it is frontend. Feel comfortable assigning to anybody from your squad :+1:

**Comment by alinedoleron** [comment]
Hi @larissacribeiro.
Please, could you confirm if the ticket [LPS-201936](https://liferay.atlassian.net/browse/LPS-201936) is related to the fix? Maybe you mixed up the ticket numbers.

Just a print using Portuguese language.
image

Thanks!

**Comment by alinedoleron** [comment]
Oh, got it! No problem @larissacribeiro! 
Thank you, too!

**Comment by larissacribeiro** [comment]
ci:test:sf

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by alinedoleron** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by davisaints** [comment]
Hi @larissacribeiro, I've identified a regression bug caused by this pull request. The regression occurs when trying to edit an object field with the "indexedAsKeyword" parameter set to true.

I've created a video demonstrating the issue: 

https://github.com/liferay-objects/liferay-portal/assets/66960853/ab13e124-d968-4e97-a292-f4d72404bac6


Let me know if you need anything from me.

**Comment by larissacribeiro** [comment]
Thanks, @davisaints!  I just updated it, taking in consideration this scenario.

**Comment by larissacribeiro** [comment]
The issue was in the useEffect, which was trying to set an indexedLanguageId value to the field even with the indexedAsKeyword property set to true. Can you give it another look? Thanks, @alinedoleron!🌷

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
@larissacribeiro The following tests are only failing in this PR:

1. [LocalFile.ObjectUpgrade#ViewObjectFieldAfterUpgrade7413U33
](https://testray.liferay.com/home/-/testray/case_results/2470547047/history?tab=result&hideFilterPin=true)
2. [LocalFile.Object#CanUpdateRelationshipFieldLabelFromNativeObject](https://testray.liferay.com/home/-/testray/case_results/2470547973/history?tab=result&hideFilterPin=true)

**Comment by larissacribeiro** [comment]
Hi @carolmariaabb! 
The second test was related to my changes so I've updated it now, and tested changing the label of all possible fields in object to make sure it still works.
The first one is not related and already failing on master, @alinedoleron will ask the QA's to double check it!

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
@larissacribeiro there seems to be a lot of tests failing just on this PR. Some of them:

1. [LocalFile.CreateObject#CanUpdateFieldNameBeforePublished](https://testray.liferay.com/home/-/testray/case_results/2468175597)
2. [LocalFile.ObjectAutoGeneratedLayout#CannotAddMoreThanLimitOfCharacters](https://testray.liferay.com/home/-/testray/case_results/2468175822)
3. [LocalFile.ObjectModelBuilder#CanUpdateField](https://testray.liferay.com/home/-/testray/case_results/2471089167/history?tab=result&hideFilterPin=true)
4. [LocalFile.ObjectAutoGeneratedLayout#CharacterCountIsDynamic](https://testray.liferay.com/home/-/testray/case_results/2471088606/history?tab=result&hideFilterPin=true)
5. [LocalFile.ObjectFields#CanViewSetMaximumCharactersOption
](https://testray.liferay.com/home/-/testray/case_results/2471087959/history?tab=result&hideFilterPin=true)
6. [LocalFile.ObjectFieldDefaultValue#CanSetPicklistViaInputAsValue
](https://testray.liferay.com/home/-/testray/case_results/2471089189/history?tab=result&hideFilterPin=true
7. [LocalFile.ObjectFieldDefaultValue#CanOnlyAffectNewEntriesByUpdatingConfiguration](https://testray.liferay.com/home/-/testray/case_results/2471089185/history?tab=result&hideFilterPin=true)
8. [LocalFile.ObjectFields#CanUpdateCustomFieldInSystemObject](https://testray.liferay.com/home/-/testray/case_results/2471088045/history?tab=result&hideFilterPin=true)
9. [LocalFile.ObjectCustomViews#CanAddTranslationToColumnLabel](https://testray.liferay.com/home/-/testray/case_results/2471089319/history?tab=result&hideFilterPin=true)

Please adjust your changes and send us another PR.

Thanks!

**Pull request closed without merging**
