### PR TITLE
[TS] LPS-190198 Exporting an object doesn't maintain the ordering of the fields

### PR DESCRIPTION
**Pull request by ricardocousolr**
Hi @liferay-objects team!

This PR is a solution to [LPS-190198](https://liferay.atlassian.net/browse/LPS-190198). 

The issue is that the export of an object doesn't conserve the ordering of the fields so when importing it elsewhere the ordering is alphabetical instead of the specified one.

The solution proposed is to recover the object fields with `getObjectFields` sorted by `createDate`. This will maintain the order in which the fields are shown.

I've noticed that in [LPS-187773](https://liferay.atlassian.net/browse/LPS-187773) the team is working on allowing user to sort the objects and fields, so this new PR might not interact well with that. Maybe the export may need to take into account the ordering of the fields at the time.

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by ricardocousolr** [comment]
Thanks for your comment @carolmariaabb!

I have a small question before deciding whether to open the PTR or not. 

With the changes from https://github.com/brianchandotcom/liferay-portal/pull/137612, you'll get the fields sorted alphabetically by default but then you can choose whether the order is ascending or descending, correct? If so, if you export the object, will the fields be imported in the order they were chosen to be viewed (ascending or descending)?

Thanks!

**Comment by carolmariaabb** [comment]
@ricardocousolr 

The order is `ascending` by default, but you can change this at any time. Please see:

[ascending_order.webm](https://github.com/liferay-objects/liferay-portal/assets/34186632/2a6af22a-a60c-4cc6-86e1-fe7ab22f2f24)

**Comment by ricardocousolr** [comment]
Thank you @carolmariaabb,

I've asked the customer if this new way of displaying the information would work for them or if they'd prefer an extra sorting column. If so I'll create the PTR.

**Comment by ricardocousolr** [comment]
I've created a PTR: https://liferay.atlassian.net/browse/PTR-4134

**Pull request closed without merging**
