### PR TITLE
LPS-163235 Do not delete search term after selected when searching fo…

### PR DESCRIPTION
**Pull request by thienquach87**
Dear Team ,
Please help me review this PR for fixing the ticket [LPS-163235](https://issues.liferay.com/browse/LPS-163235) and leave your feedback. The original PR(https://github.com/thienquach87/liferay-portal/pull/14) was passed my review.
cc: sontruongces

Thanks!
Thien

### CODE REVIEW

**Comment by thienquach87** [comment]
ci:test:relevant

**Comment by thienquach87** [comment]
@sontruongces 
Double check on source format

**Comment by sontruongces** [comment]
ci:test:sf

**Comment by danvb112** [comment]
Hey @thienquach87  and @sontruongces, don't worry about this font format issue, it's being caused by other files from another module, I already submitted a PR (https://github.com/liferay-objects/liferay-portal/pull/1146) to fix this

**Comment by sontruongces** [comment]
Thank @danvb112

**Comment by danvb112** [comment]
Hey @thienquach87  and @sontruongces, I found a little problem in this solution, in fact it fixes the main problem, but once we searched for the option and selected the searched option, if we click outside of select and try to select again, they won't show all the options, you could for please how to solve this too

**Review by danvb112 — CHANGES_REQUESTED** [review]
Hey @thienquach87 and @sontruongces, I found a little problem in this solution, in fact it fixes the main problem, but once we searched for the option and selected the searched option, if we click outside of select and try to select again, they won't show all the options, you could for please how to solve this too

**Comment by sontruongces** [comment]
@danvb112, I updated the code, please help me to review it. Thanks!

**Review by danvb112 — APPROVED** [review]
LGTM! :tada

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:forward

**Comment by danvb112** [comment]
ci:forward

**Comment by danvb112** [comment]
ci:forward

**Comment by danvb112** [comment]
ci:forward

**Comment by sontruongces** [comment]
> Hey @thienquach87 and @sontruongces, could you send this PR directly to Brian Chan? As it is failing for many days in unrelated tests, you can directly submit to him

Thank @danvb112. Resent at brianchandotcom#124845

**Pull request merged**
