### PR TITLE
LPD-26043 Remove the ignore annotation from the ObjectExportImport#CanCancelImport Poshi test

### PR DESCRIPTION
**Pull request by vngoliveira**
[LPD-26043](https://liferay.atlassian.net/browse/LPD-26043)

### CODE REVIEW

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
