### PR TITLE
LPS-159539 Add format content from To, From, Cc and Bcc fields in Notification

### PR DESCRIPTION
**Pull request by murilostodolni**
Related: https://issues.liferay.com/browse/LPS-159539

### CODE REVIEW

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
As discussed offline, this is missing the feature flag commit. 🙂

**Comment by murilostodolni** [comment]
Hi @rodrigopaulino 

i created a new PR with the new commit, please see https://github.com/liferay-objects/liferay-portal/pull/900

**Comment by murilostodolni** [comment]
ci:close

**Pull request closed without merging**
