### PR TITLE
LPS-135870 Make Form Field required when Object Field is required

### PR DESCRIPTION
**Pull request by mlan0**

### CODE REVIEW

**Comment by mlan0** [comment]
ci:stop

**Comment by mlan0** [comment]
ci:test:sf

**Comment by mlan0** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:reevaluate:1277401_236

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:forward

**Pull request closed without merging**
