### PR TITLE
[Technical debt] LPS-172804 Migrate Object's Fields tab to React

### PR DESCRIPTION
**Pull request by alinedoleron**
https://issues.liferay.com/browse/LPS-172804

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:object

**Comment by naraandrade** [comment]
@alinedoleron We will pause the migration of jsp tabs for now, since we have other demands with higher priority. Thanks for your contribution :)

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:object

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:object

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:object

**Pull request closed without merging**
