### PR TITLE
LPS-169220 No error message is displayed When a validation is not valid

### PR DESCRIPTION
**Pull request by diogomelo09**
[LPS-169220](https://issues.liferay.com/browse/LPS-169220)

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:stop

**Comment by naraandrade** [comment]
@diogomelo09 SF failure, can you please take a look at it? Thanks :)

**Comment by diogomelo09** [comment]
ci:test:sf

**Comment by diogomelo09** [comment]
ci:stop

**Comment by diogomelo09** [comment]
ci:test:sf

**Comment by diogomelo09** [comment]
ci:test:relevant

**Comment by diogomelo09** [comment]
ci:reevaluate:131null_6505

**Comment by diogomelo09** [comment]
ci:test:relevant

**Review by p-albuquerque — APPROVED** [review]

**Pull request closed without merging**
