### PR TITLE
LPS-155077 Check feature flag

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:reevaluate:1387401_930

**Comment by guilhermedcamacho** [comment]
ci:reevaluate:1387401_930

**Comment by guilhermedcamacho** [comment]
Sent directly to Brian on [brianchandotcom@118211](https://github.com/brianchandotcom/liferay-portal/pull/118211)

**Pull request closed without merging**
