### PR TITLE
LPS-168355

### PR DESCRIPTION
**Pull request by alinedoleron**
https://issues.liferay.com/browse/LPS-168355

video: [notifications.webm](https://user-images.githubusercontent.com/26491796/202736623-30ce17ac-0698-40b3-96d0-6b5001c405a5.webm)

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Review by cgmonte — APPROVED** [review]
LGTM!

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
