### PR TITLE
[TS] LPS-166675 DB2 Error after deleting a Field from an Object

### PR DESCRIPTION
**Pull request by joseluisbango**
**Relevant issue**: [LPS-166675](https://issues.liferay.com/browse/LPS-166675)

---

Hi @liferay-objects!

There is an issue after deleting a Field from an Object in DB2. This is because, after some alterations, DB2 needs a _table reorganization_. See [LPS-166675](https://issues.liferay.com/browse/LPS-166675), and IBM documentation about [altering tables](https://www.ibm.com/docs/en/db2/11.5?topic=tables-altering) and [SQLCODE=-668](https://www.ibm.com/docs/en/db2/11.5?topic=messages-sql0500-sql0749#sql0668n) for details.

Instead of getting the SQL String from the `DynamicObjectDefinitionTable.java` class, I have changed the logic in `ObjectFieldLocalServiceImpl.java` so that it uses the DB abstraction provided by `com.liferay.portal.kernel.dao.db.DB`. This way, every DB will take care of its specifics. In this case, DB2 will call `reorg` command in [DB2DB#runSQL](https://github.com/liferay/liferay-portal/blob/d5dbe3e5e51aa86f8c5cba36ef367fb570441425/modules/dxp/apps/portal/portal-dao-db/src/main/java/com/liferay/portal/dao/db/DB2DB.java#L238-L247).

What are your views on that?

Thanks!

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by joseluisbango** [comment]
ci:reevaluate:1287401_4961

**Comment by gabrielwas** [comment]
Good fix @joseluisbango! Thanks for this. 

LGTM :heavy_check_mark:

**Review by gabrielwas — APPROVED** [review]

**Comment by gabrielwas** [comment]
ci:forward

**Pull request closed without merging**
