### PR TITLE
LPS-184796 Avoid NPE on export

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by magjed4289** [comment]
ci:test:headless-acceptance

**Comment by MarinhoFeliphe** [comment]
Hi @magjed4289, may I proceed (forward force)?

**Comment by magjed4289** [comment]
Test failures not related with the PR. OK to forward ✅

**Comment by magjed4289** [comment]
ci:forward:force

**Pull request closed without merging**
