### PR TITLE
LPS-144870 Increase schema version

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://issues.liferay.com/browse/LPS-144870

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
LGTM :D

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
