### PR TITLE
[Technical debt] LPS-172895 Migrate Object's State Manager tab to React

### PR DESCRIPTION
**Pull request by alinedoleron**
[LPS-172895](https://issues.liferay.com/browse/LPS-172895) Migrate Object's State Manager tab to React

### CODE REVIEW

**Comment by naraandrade** [comment]
Wait for https://github.com/liferay-objects/liferay-portal/pull/2145

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — CHANGES_REQUESTED** [review]
@alinedoleron Just update this PR according to https://github.com/liferay-objects/liferay-portal/pull/2145. Thanks :)

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:object

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:forward

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
