### PR TITLE
LPS-197185 Handle picklist fields on DTO parsing for external object entries

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**
Hey @guilhermedcamacho these changes are related to display the list entry label for external storage types (Client Extensions),

I'm getting this information from list type entry local service and converted to list entry dto after I fixing the issue I've moved the logic to parse the json provided by the customers to object entry dto converter this this way we can keep the responsibility there.

Please follow the commits.

Thank you!

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Review by guilhermedcamacho — APPROVED** [review]

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Hey @MarinhoFeliphe, the code looks good to me, but I'm in doubt whether it will work when we have a picklist/picklist entry mapped with the third-party system using ERC.

**Comment by guilhermedcamacho** [comment]
ci:forward:force

**Comment by guilhermedcamacho** [comment]
ci:stop

**Comment by guilhermedcamacho** [comment]
I reworded the commit messages with the appropriate ticket and sent directly to [brianchandotcom#145318](https://github.com/brianchandotcom/liferay-portal/pull/145318)

**Pull request closed without merging**
