### PR TITLE
LPS-140405

### PR DESCRIPTION
**Pull request by carolmariaabb**
This is a proposed solution to fix the issue described in [LPS-140405](https://issues.liferay.com/browse/LPS-140405), where an Object created in one Virtual Instance is shown in another Virtual Instance when setting the permissions of some role.

The [ObjectEntriesPanelApp](https://github.com/liferay/liferay-portal/blob/master/modules/apps/object/object-web/src/main/java/com/liferay/object/web/internal/object/entries/application/list/ObjectEntriesPanelApp.java) is being registered [here](https://github.com/liferay/liferay-portal/blob/c42d56486be9cb7fa3c105909ecd06195759d7bc/modules/apps/object/object-web/src/main/java/com/liferay/object/web/internal/deployer/ObjectDefinitionDeployerImpl.java#L295-L304).

Please let me know if it's the only/best solution or if there's something I can do in the Objects code.

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Please do not foward this PR.

Discussion about the fix was started [here](https://liferay.slack.com/archives/CNUCYF7EW/p1647957756575709).

**Comment by liferay-forms** [comment]
Hey @carolmariaabb, can you please check if these failures are related to your changes? Thanks

**Comment by samuelromeiro** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Review by drewbrokke — CHANGES_REQUESTED** [review]
Hi @carolmariaabb, thank you for this change. Overall I like the idea, but I think doing full permission checks in this context will be far more restrictive than intended. I think what is necessary is to add a couple of methods to `PanelAppRegistry` that strictly filter by `companyId` on the companyId.

I'm thinking something along these lines:

```java
public List<PanelApp> getPanelApps(
	long companyId, PanelCategory parentPanelCategory) {

	return getPanelApps(companyId, parentPanelCategory.getKey());
}

public List<PanelApp> getPanelApps(
	long companyId, String parentPanelCategoryKey) {

	return ListUtil.filter(
		getPanelApps(parentPanelCategoryKey),
		panelApp -> {
			Portlet portlet = panelApp.getPortlet();

			long portletCompanyId = portlet.getCompanyId();

			if ((portletCompanyId != CompanyConstants.SYSTEM) &&
				(portletCompanyId != companyId)) {

				return false;
			}

			return true;
		});
}
```

If we had a method like that, I think using them in the places you changed in this pull makes perfect sense.

Thoughts?

**Comment by carolmariaabb** [comment]
HI @drewbrokke,

I totally agree with you. This new method would be perfect for us.

Can I make the changes and request a review again?

**Comment by drewbrokke** [comment]
Please do! Thank you @carolmariaabb!

**Comment by drewbrokke** [comment]
FYI I think that change should also be reviewed by Echo team.

**Pull request closed without merging**
