### PR TITLE
LPS-204513 Loading screen when user should not see any content

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPS-204513

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:object

**Review by guilhermedcamacho — APPROVED** [review]

**Comment by p-albuquerque** [comment]
Checking CI results...

**Comment by p-albuquerque** [comment]
ci:forward:force

**Pull request closed without merging**
