### PR TITLE
LPS-188430, LPS-188428 Add ERC to ObjectLayout and ObjectView

### PR DESCRIPTION
**Pull request by joseabelenda**
Related issue: 
- https://liferay.atlassian.net/browse/LPS-188430
- https://liferay.atlassian.net/browse/LPS-188428

### CODE REVIEW

**Comment by marcelabc** [comment]
cc: @gabrielwas @guilhermedcamacho

**Comment by marcelabc** [comment]
Hey @joseabelenda, 
I just wanted to let you know that I edited the description to include the "Related Issue" (with the Jira ticket). Please always add this information in your following reviews if you can!

**Comment by gabrielwas** [comment]
@joseabelenda could you explain here the motivation for this implementation, please?

**Comment by joseabelenda** [comment]
> @joseabelenda could you explain here the motivation for this implementation, please?

@gabrielwas, we need this to be able to add or update Object Layouts and Views by external reference code.
We created a structure on Site Initializer template for ObjectLayout and ObjectView resources.
Site Initializer will read that resources, get the ObjectDefinition ERC and ObjectLayout/ObjectView ERC to add or update them.

**Pull request closed without merging**
