### PR TITLE
LPS-197753 Prevent linked Object Definitions from being published

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://liferay.atlassian.net/browse/LPS-197753

### CODE REVIEW

**Review by naraandrade — APPROVED** [review]

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:object

**Comment by danvb112** [comment]
ci:forward:force

**Comment by danvb112** [comment]
ci:forward:force

**Comment by danvb112** [comment]
Sent to: https://github.com/brianchandotcom/liferay-portal/pull/142207

**Pull request closed without merging**
