### PR TITLE
LPS-183134 Create indexes for columns of oneToMany relationship

### PR DESCRIPTION
**Pull request by murilostodolni**
Related: https://issues.liferay.com/browse/LPS-183133

### CODE REVIEW

**Comment by marcelabc** [comment]
Hey @carolmariaabb 
Could you review this PR, please? :smile:

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
ci:test:object

**Comment by murilostodolni** [comment]
ci:forward:force

**Pull request closed without merging**
