### PR TITLE
LPS-149094 Remove FF of custom validations through Objects API

### PR DESCRIPTION
**Pull request by marcelabc**
Related Issue: https://issues.liferay.com/browse/LPS-149094

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
