### PR TITLE
LPS-170322 Generic error when creating a picklist's item with same key

### PR DESCRIPTION
**Pull request by vngoliveira**
Related issue [LPS-170322](https://issues.liferay.com/browse/LPS-170322)

### CODE REVIEW

**Comment by vngoliveira** [comment]
ci:test:relevant

**Comment by vngoliveira** [comment]
ci:test:object

**Comment by vngoliveira** [comment]
ci:test:object

**Comment by vngoliveira** [comment]
ci:test:relevant

**Comment by vngoliveira** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:sf

**Pull request closed without merging**
