### PR TITLE
LPS-198290 Remove if clause to verify always the permissions when deleting an object entry

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LPS-198290

### CODE REVIEW

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:object

**Comment by guilhermedcamacho** [comment]
Hey @magjed4289 , it seems there is a unique failure (
[com.liferay.object.service.test.ObjectEntryServiceTest](https://testray.liferay.com/home/-/testray/case_results/2484430699)) in this pull. 
I think we need to apply the same [change](https://github.com/liferay-objects/liferay-portal/pull/3015/commits/74b18e69d68ca083efb6d40bd024716da39a479d) for `ObjectEntryServiceTest#tearDown` method, can you please check this?

**Comment by guilhermedcamacho** [comment]
I'm running the tests again because there was a problem in Master where the virtual instance was not deleted successfully, this impacted our test suite for a few days.

**Comment by magjed4289** [comment]
closing this one and opening https://github.com/liferay-objects/liferay-portal/pull/3073 (with conflicts solved and a test-fix added) cc @4lejandrito @ccorreagg

**Pull request closed without merging**
