### PR TITLE
LPS-163701 Fill id GraphQL property

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-163701

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
@rodrigopaulino Just reviewed it, right? thx

**Comment by mateussgn** [comment]
Hey @gabrielwas, Is there a specific way to do the mutation call? I wasn't able to find mutation for object entries.

Also, I think you shared the wrong link above. Could you send the right one?

**Comment by gabrielwas** [comment]
@mateussgn Couldn't attach the right link, but it's related to line 88 of this same file. 

And it's about trying to update an entry through GraphQL. Could you try it, please? But, anyway, I think we can forward this PR and then amend some code if needed.

**Comment by mateussgn** [comment]
@gabrielwas, about line 88, it`s already being included, if you see the [_for_](https://github.com/liferay-objects/liferay-portal/blob/252c4c321f10ef852cbd866dd7a3effad6d3372c/modules/apps/object/object-rest-impl/src/main/java/com/liferay/object/rest/internal/graphql/dto/v1_0/ObjectDefinitionGraphQLDTOContributor.java#L98-L136) loop right bellow, it includes the system fields.

About the mutation, I understand it is related to updating or creating an entry. However, I don`t think there are mutations created for this situation. Then, I can't do the mutation calls.

I believe we can send this PR while I'm not finding how to make the mutation call.
What do you think?

**Comment by mateussgn** [comment]
@gabrielwas I talked with Keven, and he taught me how to make the mutation call. I was able to validate it, and it's working. Can I forward this PR?

**Comment by gabrielwas** [comment]
@mateussgn Perfect! Thanks you

**Comment by gabrielwas** [comment]
ci:forward

**Pull request closed without merging**
