### PR TITLE
LPS-194431 When managing a folder of objects via Model Builder when we try to Edit in page view it is still possible to interact with the objects in the diagram

### PR DESCRIPTION
**Pull request by Artartur**
Related Issue: [LPS-194431](https://liferay.atlassian.net/browse/LPS-194431)

### CODE REVIEW

**Comment by igor-franca** [comment]
Great job @Artartur! Thank you for this contribution.

**Review by igor-franca — APPROVED** [review]

**Comment by rebsilva** [comment]
just started reviewing! :cherry_blossom:

**Review by rebsilva — CHANGES_REQUESTED** [review]
Good job on this PR @Artartur! There is a minor change:

The language-key `field-successfully-added` on `EditObjectFolder` should be `the-field-was-successfully-added`, can you please change that? Thanks!

**Comment by Artartur** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:object

**Review by rebsilva — APPROVED** [review]
LGTM! Great job @Artartur :tada:

**Pull request closed without merging**
