### PR TITLE
LPS-170026 Typo for Aggregation Filter Types

### PR DESCRIPTION
**Pull request by Valmir-unicap**
Related issue: https://issues.liferay.com/browse/LPS-170026

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Review by carolmariaabb — APPROVED** [review]

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/127509

**Pull request closed without merging**
