### PR TITLE
LPS-162236 Object instance should be searchable by ID

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
Hi @jcampoy,

Could you double check?

Thanks!

**Comment by jcampoy** [comment]
I am going to take a look!

**Comment by jcampoy** [comment]
@MarinhoFeliphe your changes until now are 👍 to me

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/123171

**Comment by MarinhoFeliphe** [comment]
The fails are not related

**Pull request closed without merging**
