### PR TITLE
LPS-199866 Add support to retrieve Object Entries when using Forms by converting the Object Entries to DDMFormValues

### PR DESCRIPTION
**Pull request by carolmariaabb**
Related Issue: https://liferay.atlassian.net/browse/LPS-199866

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by crodriguezy** [comment]
Hi @marcelabc and @carolmariaabb , do you think this could be merged soon? The customer needs it asap
Thank you!

**Comment by carolmariaabb** [comment]
ci:test:stable

**Comment by crodriguezy** [comment]
hello @carolmariaabb , do you think this is good to go?

**Comment by carolmariaabb** [comment]
@crodriguezy I'm waiting for the `stable` suite to pass

**Comment by carolmariaabb** [comment]
ci:test:stable

**Comment by carolmariaabb** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/142827

Same failures from [here](https://liferay.slack.com/archives/C19PWQ74J/p1698392641212619).

**Pull request closed without merging**
