### PR TITLE
LPD-26986 - Test fixes for ObjectCustomValidation

### PR DESCRIPTION
**Pull request by victorKammerer**
[LPD-26986](https://liferay.atlassian.net/browse/LPD-26986) - ObjectCustomValidation#CanValidateGroovyScheduledAction

### CODE REVIEW

**Comment by victorKammerer** [comment]
@gabrielwas Since liferay-objects repo was outdated I forced push with missing commits, and also updated our liferay-portal repository. So, if you want me to open a new PR without this ton of changes, let me know :)

**Comment by gabrielwas** [comment]
LGMT ;) Thx!

**Review by gabrielwas — APPROVED** [review]

**Comment by gabrielwas** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
resent [here](https://github.com/liferay-objects/liferay-portal/pull/3434)

**Pull request closed without merging**
