### PR TITLE
LPS-161750 Create DefaultObjectEntryManagerTest and start to cover the addObjectEntry method

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by michaelhashimoto** [comment]
ci:reevaluate:1277401_4795

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Pull request closed without merging**
