### PR TITLE
LPS-146895 LPS-146896

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issues: 
https://issues.liferay.com/browse/LPS-146895; 
https://issues.liferay.com/browse/LPS-146896

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:reevaluate:1347401_878

**Comment by p-albuquerque** [comment]
I will include the commit of integration tests update yet

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:teste:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:close

**Comment by mateussgn** [comment]
Resent on https://github.com/liferay-objects/liferay-portal/pull/422

**Pull request closed without merging**
