### PR TITLE
LPS-198076 Fix parentheses

### PR DESCRIPTION
**Pull request by murilostodolni**
Related: https://liferay.atlassian.net/browse/LPS-198076

### CODE REVIEW

**Review by naraandrade — APPROVED** [review]

**Comment by murilostodolni** [comment]
ci:test:object

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
Manually forward: https://github.com/brianchandotcom/liferay-portal/pull/141761

**Comment by murilostodolni** [comment]
ci:close

**Pull request closed without merging**
