### PR TITLE
LPS-145902 Display Picklist field options when it is the relationship field

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPS-145902

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @p-albuquerque, can you please check if these failures are related to your changes? Thanks

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Review by danvb112 — APPROVED** [review]
LGTM! :tada:

**Pull request closed without merging**
