### PR TITLE
LPS-142015 Check if navigatedValue is valid before accessing it

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@gabrielwas I merged it manually.

**Comment by jpince** [comment]
https://github.com/brianchandotcom/liferay-portal/compare/03b9cf970ed534d82cc27e368c4eeb4ec0d01643...90ffceaee0621fec4361f8eb3a082328290d2f57

**Comment by rodrigocunhaa** [comment]
ci:test:object

**Comment by rodrigocunhaa** [comment]
ci:test:bundle

**Pull request closed without merging**
