### PR TITLE
LPS-138214 Display user friendly message in Panel Category Key and Title Field empty options

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPS-138214

### CODE REVIEW

**Review by marcelabc — CHANGES_REQUESTED** [review]
As discussed on Slack, Paulo will make some changes in his work 👍

**Comment by p-albuquerque** [comment]
Changes done.

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
