### PR TITLE
LPS-183396 Enable account restriction for Proxy Salesforce object

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://liferay.atlassian.net/browse/LPS-183396

cc: @nNilton @guilhermedcamacho

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
Hi @nNilton, how are you doing?
I did one last change regarding the sort between the Assert methods in the test. Please, see: https://github.com/liferay-objects/liferay-portal/commit/c69146b86d375a519a5452e0920063e224219376

Besides that, I noticed that there are many commits related to the same subject/class/method. Because of that, I would like to give feedback regarding this. As a reviewer, it is better to review all the changes in the original commit that introduced this change. Gathering all the modifications in the original commit makes the review easier to understand.

When creating PR, it is ideal to use the commits to create a story telling about your work. So, splitting the work if it is related is not ideal. Doing this can create confusion for the reviewer.

Let me know if you want to talk about it. :smile:

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by nNilton** [comment]
Thx @marcelabc

**Comment by marcelabc** [comment]
@nNilton will fix some things and resend!
(We chat in Slack)

**Pull request closed without merging**
