### PR TITLE
LPS-165512 Fix return all services in objectDefinition deploy

### PR DESCRIPTION
**Pull request by murilostodolni**
https://issues.liferay.com/browse/LPS-165512

### CODE REVIEW

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
ci:stop

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by murilostodolni** [comment]
ci:test:sf

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
ci:stop

**Comment by murilostodolni** [comment]
ci:close

**Pull request closed without merging**
