### PR TITLE
LPS-162696 Use externalReferenceCode for Salesforce Object name

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:object

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Sent directly to Brian on [brianchandotcom#123043](https://github.com//liferay-portal/pull/123043)

**Pull request closed without merging**
