### PR TITLE
LPS-180788 When created an action in Commerce Product, the product's name won't pass from model to page.

### PR DESCRIPTION
**Pull request by Valmir-unicap**
Related issue: https://issues.liferay.com/browse/LPS-180788

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:test:objects

**Comment by Valmir-unicap** [comment]
ci:test:object

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
@Valmir-unicap I'm not sure if we should follow this approach in your changes,

I mean, the issue seems to be related to the way the update is being performed by the action, so we need to take a look at the point where this update is being performed to understand why it is filling blank in on the other fields like name for example, I believe this issue is being happening from other system entities as well and we need to find the root cause,

I believe you can start debugging at [this point](https://github.com/liferay/liferay-portal/blob/b568ec5be3fee8e6f331fade301e81c538b8a56b/modules/apps/object/object-service/src/main/java/com/liferay/object/internal/action/executor/UpdateObjectEntryObjectActionExecutorImpl.java#L56-L80)

Thank you!

**Review by MarinhoFeliphe — CHANGES_REQUESTED** [review]
Maybe something [here](https://github.com/liferay/liferay-portal/blob/b568ec5be3fee8e6f331fade301e81c538b8a56b/modules/apps/object/object-service/src/main/java/com/liferay/object/internal/action/executor/UpdateObjectEntryObjectActionExecutorImpl.java#L56-L80)

**Pull request closed without merging**
