### PR TITLE
LPS-168854

### PR DESCRIPTION
**Pull request by alinedoleron**
https://issues.liferay.com/browse/LPS-168854

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by timpak** [comment]
ci:test:object

**Comment by cgmonte** [comment]
ci:reevaluate:1327401_6999

**Comment by alinedoleron** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/126579

**Pull request closed without merging**
