### PR TITLE
LPD-26469 Object Relationship Playwright Tests

### PR DESCRIPTION
**Pull request by igor-franca**

### CODE REVIEW

**Comment by igor-franca** [comment]
ci:test:playwright

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
All tests were successful locally and at the IC:

screenshot-1725582989

Source format changes can be viewed here, and by their nature will not affect test results.

Therefore, I will not run the playwright tests again.

**Comment by igor-franca** [comment]
ci:forward

**Comment by larissacribeiro** [comment]
relevant failure is unrelated 🎉

**Comment by larissacribeiro** [comment]
ci:forward:force

**Pull request closed without merging**
