### PR TITLE
LPD-28411 LPD-33634 object-service: remove duplicate externalReferenc…

### PR DESCRIPTION
**Pull request by joshuacords**
…eCode_sortable field from search documents, this is now handled by [ExternalReferenceCodeModelDocumentContributor](https://github.com/liferay/liferay-portal/blob/0f6caee8d748c3090bb5e8da9b70c5b89bfd1ebe/modules/apps/portal-search/portal-search/src/main/java/com/liferay/portal/search/internal/spi/model/index/contributor/ExternalReferenceCodeModelDocumentContributor.java)

[LPD-28411](https://liferay.atlassian.net/browse/LPD-28411)

**Author:** @joshuacords 

From [LPD-28411](https://liferay.atlassian.net/browse/LPD-28411):
> Looks like ObjectsEntryModelDocumentContributor indexes a sortable variant of that field already ... a Task ticket should be created to remove the duplicates from the code base

Could this team confirm this change is fine and no other changes are needed?

[LPD-28411]: https://liferay.atlassian.net/browse/LPD-28411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LPD-28411]: https://liferay.atlassian.net/browse/LPD-28411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:objects

**Comment by joshuacords** [comment]
ci:test:object

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:test:object

**Pull request closed without merging**
