### PR TITLE
LPD-24330

### PR DESCRIPTION
**Pull request by icgsbr**
https://liferay.atlassian.net/browse/LPD-24330

### CODE REVIEW

**Comment by icgsbr** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
@icgsbr, run the CI only after the final reviewer adds the `Dev Approved` label

**Comment by icgsbr** [comment]
ci:stop

**Comment by icgsbr** [comment]
ci:stop

**Comment by icgsbr** [comment]
ci:stop

**Review by devpedrotavares — APPROVED** [review]

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
