### PR TITLE
LPS-170051 - The user should not be allowed to sort or filter attachment fields

### PR DESCRIPTION
**Pull request by Artartur**
[LPS-170051](https://issues.liferay.com/browse/LPS-170051)

### CODE REVIEW

**Comment by Artartur** [comment]
ci:test:sf

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:relevant

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
This is just a follow up for https://github.com/brianchandotcom/liferay-portal/pull/128188. I'll send it directly to BChan.

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/128298

**Pull request closed without merging**
