### PR TITLE
LPS-193944 Error message for duplicated ERC is not descriptive

### PR DESCRIPTION
**Pull request by Artartur**
Related Issue: [LPS-193944](https://liferay.atlassian.net/browse/LPS-193944)

### CODE REVIEW

**Comment by Artartur** [comment]
ci:test:sf

**Review by murilostodolni — APPROVED** [review]
LGTM! God job @Artartur 🎉 

I will run the CI, we need to wait the result to forward, ok?

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
ci:test:object

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by Artartur** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
Resent https://github.com/liferay-objects/liferay-portal/pull/2495

**Comment by carolmariaabb** [comment]
ci:stop

**Pull request closed without merging**
