### PR TITLE
LPS-177224 Fix patch request

### PR DESCRIPTION
**Pull request by henriquelimadotcom**
https://issues.liferay.com/browse/LPS-177224

### CODE REVIEW

**Comment by henriquelimadotcom** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
@henriquelimadotcom, the failed test [com.liferay.object.rest.internal.manager.v1_0.test.DefaultObjectEntryManagerImplTest](https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/421676/testReport/com.liferay.object.rest.internal.manager.v1_0.test/DefaultObjectEntryManagerImplTest) - [Failed 0 of last 25](https://testray.liferay.com/home/-/testray/case_results/2225044253/history) is related to your changes. Could you please fix it? 

To execute the test, you need to run `gw testIntegration --tests com.liferay.object.rest.internal.manager.v1_0.test.DefaultObjectEntryManagerImplTest` in `modules/apps/object/object-rest-test` folder.

Thanks!

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by henriquelimadotcom** [comment]
ci:test:sf

**Comment by henriquelimadotcom** [comment]
ci:test:relevant

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Pull request closed without merging**
