### PR TITLE
LPS-183745 The required fields are not requiring the user to fill in when switching languages ​​in instance settings

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPS-183745](https://issues.liferay.com/browse/LPS-183745)

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Comment by rebsilva** [comment]
just started reviewing! :purple_heart:

**Review by rebsilva — APPROVED** [review]
LGTM! :tada: :cherry_blossom:

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
@rebsilva, 
apparently the failures are unrelated. I will close this one and send it directly to Brian.

**Pull request closed without merging**
