### PR TITLE
LPS-181323 An error message is not displayed when the user adds more than 16 digits to a long integer field

### PR DESCRIPTION
**Pull request by manuelecastro**
[LPS-181323](https://issues.liferay.com/browse/LPS-181323)

### CODE REVIEW

**Review by MarinhoFeliphe — APPROVED** [review]

**Comment by MarinhoFeliphe** [comment]
LGTM!! :tada:

**Comment by MarinhoFeliphe** [comment]
@manuelecastro this test [has failed](https://testray.liferay.com/home/-/testray/case_results/2265223350?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2265220704%26cur%3D1%26delta%3D200%26tab%3Druns%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) because we need to run `gw baseline` in **object-api** module, could you please do this? it will modify some files so you can put this changes in another commit with the message "LPS-181323 Semver".

feel free to contact me if you have any questions.

Thank you,
Feliphe

**Comment by MarinhoFeliphe** [comment]
I've made those changes, [see](https://github.com/brianchandotcom/liferay-portal/pull/133223/commits/fdd30b70d82a425060e57599b54798cdb8752cb6)

**Comment by manuelecastro** [comment]
Thanks for the feedback @MarinhoFeliphe ! I made the `gw baseline` locally, but since you already pushed these changes I guess I don't need to push them too, right?

**Pull request closed without merging**
