### PR TITLE
LPS-167750 Fix DDM multiple select Bugs

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-167750

### CODE REVIEW

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by danvb112** [comment]
ci:test:relevant

**Review by naraandrade — APPROVED** [review]

**Comment by danvb112** [comment]
ci:forward

**Comment by naraandrade** [comment]
ci:forward

**Comment by danvb112** [comment]
Sent to: https://github.com/brianchandotcom/liferay-portal/pull/125925

**Pull request closed without merging**
