### PR TITLE
LPS-193785 Plus button is displayed for a user without the permissions to create objects

### PR DESCRIPTION
**Pull request by Artartur**
Related Issue: [LPS-193785](https://liferay.atlassian.net/browse/LPS-193785)

### CODE REVIEW

**Comment by Artartur** [comment]
ci:stop

**Comment by Artartur** [comment]
ci:test:sf

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:object

**Review by rebsilva — APPROVED** [review]
LGTM! :tada:

**Comment by rebsilva** [comment]
Waiting to BE to review and to add the "Dev Approved" tag

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:reevaluate:1287401_7339

**Comment by marcelabc** [comment]
ci:forward:force

**Pull request closed without merging**
