### PR TITLE
LPS-139284 Test coverage

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:stop

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:forward

**Comment by gabrielwas** [comment]
ci:forward

**Comment by guilhermedcamacho** [comment]
Sent directly to Brian in this [PR](https://github.com/brianchandotcom/liferay-portal/pull/107231)

**Pull request closed without merging**
