### PR TITLE
LPS-172453 Remove the sort icons from the Attachment field

### PR DESCRIPTION
**Pull request by Manda-vit**

### CODE REVIEW

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by Manda-vit** [comment]
ci:test:relevant

**Comment by Manda-vit** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/128687

**Pull request closed without merging**
