### PR TITLE
LPS-155110 Remove system object fields from auto-generated object layouts

### PR DESCRIPTION
**Pull request by mateussgn**
Related issues:
https://issues.liferay.com/browse/LPS-155110
https://issues.liferay.com/browse/LPS-155561

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
Nice work @mateussgn :tada:

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
