### PR TITLE
LPD-25300 Using the role key to fetch roles on BaseNotificationType

### PR DESCRIPTION
**Pull request by rijema**
Hi team, I'm solving this problem https://liferay.atlassian.net/browse/LPD-25300 but I'm wondering if we should create a test only for this case and how it would be. I'm changing the validation we're doing here with the roles as we need the key in the backend and not the title/name, as in custom roles we can make them different. Any inputs?

### CODE REVIEW

**Review by rijema — COMMENTED** [review]
The key value is identified through the externalReferenceCode variable over the items shared with the frontend.

**Comment by igor-franca** [comment]
Hey @rijema, everything is fine with your code. Could you check if this bug also occurs with email notification. 

If so, could you check if we need apply this change in [getEmailNotificationRoles](https://github.com/liferay/liferay-portal/blob/5a773fb05e42f868698bc04289223d93c264e718/modules/apps/notification/notification-web/src/main/resources/META-INF/resources/js/components/SettingsContainer/rolesUtils.ts#L42-L47) .

If a new bug is identified, feel free to submit this fix in another PR or just add a new commit to this PR 😄

**Comment by igor-franca** [comment]
ci:test:object

**Comment by igor-franca** [comment]
ci:test:relevant

**Comment by rijema** [comment]
Some tests seems fake to me, tho. If you don't mind I would like to rerun and compare the suits.

**Comment by rijema** [comment]
ci:test:objects

**Comment by rijema** [comment]
ci:test:object

**Comment by rijema** [comment]
ci:forward

**Pull request closed without merging**
