### PR TITLE
LPS-161381

### PR DESCRIPTION
**Pull request by rodrigopaulino**

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Review by gabrielwas — APPROVED** [review]

**Comment by rodrigopaulino** [comment]
ci:forward

**Comment by rodrigopaulino** [comment]
ci:forward

**Comment by rodrigopaulino** [comment]
ci:forward

**Comment by rodrigopaulino** [comment]
Manually forwarded: https://github.com/brianchandotcom/liferay-portal/pull/122255

**Pull request closed without merging**
