### PR TITLE
LPS-179327 For each section of relationship we will retrieve the relationship terms through the new MVC resource command

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
Task: [LPS-179327](https://issues.liferay.com/browse/LPS-179327)

This PR needs these others to be merge :
https://github.com/liferay-objects/liferay-portal/pull/1888
https://github.com/liferay-objects/liferay-portal/pull/1885

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — CHANGES_REQUESTED** [review]
@pedro-oliveira446 you need to add this [changes](https://github.com/p-albuquerque/liferay-portal/pull/49/commits/8aae096ea56ebab0548f21b307afb04262f30441) to your PR.

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Review by naraandrade — APPROVED** [review]

**Comment by JhossephG** [comment]
ci:test:object

**Comment by pedro-oliveira446** [comment]
ci:forward

**Pull request closed without merging**
