### PR TITLE
Revert "LPS-142256 Create feature flag for exporting/importing objects"

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
LGTM :D

**Comment by marcelabc** [comment]
ci:forward

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:forward

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
@marcelabc the Poshi tests are failing due to this PR. The tests look for the kebab and find the first one (the import/export) when they are supposed to find the entries kebab options.

@rodrigocunhaa can you help us with that?

**Comment by rodrigocunhaa** [comment]
Resent here: https://github.com/liferay-objects/liferay-portal/pull/340

cc: @gabrielwas @marcelabc

**Pull request closed without merging**
