### PR TITLE
LPD-28268

### PR DESCRIPTION
**Pull request by icgsbr**
# Jira ticket
- https://liferay.atlassian.net/browse/LPD-28268

# Additional Information
- The commit https://github.com/liferay-objects/liferay-portal/pull/3452/commits/995b1716deba3e98a08a092bc8f893233552c752, is necessary not only for code quality but in what comes down to structure pattern. It makes the code more optimized.

### CODE REVIEW

**Comment by icgsbr** [comment]
ci:test:sf

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
Hey @icgsbr ,
The backend part is approved. Has someone already reviewed the frontend part (the test)? Would you like some help asking for a review?

**Comment by icgsbr** [comment]
Hi @marcelabc ! I think we're good to go; since a front end engineer took a look at the test with me and had no comments whatsoever.

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by icgsbr** [comment]
ci:test:playwright

**Comment by icgsbr** [comment]
ci:reevaluate:1297401_9949

**Comment by icgsbr** [comment]
Hi @marcelabc, from what I've seen no failures are related to the commits.

Could you please double-check this before forwarding?

**Comment by marcelabc** [comment]
ci:report:22810083

**Comment by marcelabc** [comment]
@icgsbr, please use the command to see the unique failures:
`ci:report:123456`
But remember to double-check the CI. I noticed that this report can be incorrect sometimes.

**Comment by marcelabc** [comment]
I manually checked the playwright tests from Objects and found no unique failure.

**Comment by marcelabc** [comment]
ci:forward

**Comment by marcelabc** [comment]
ci:forward

**Comment by icgsbr** [comment]
ci:reopen

**Comment by icgsbr** [comment]
This ticket is being reopened due to rebase errors [found while merging the PR](https://github.com/brianchandotcom/liferay-portal/pull/151663#issuecomment-2185791260).

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by icgsbr** [comment]
ci:test:sf

**Comment by icgsbr** [comment]
ci:relevant

**Comment by icgsbr** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:playwright

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by icgsbr** [comment]
ci:test:sf

**Comment by icgsbr** [comment]
ci:test:relevant

**Comment by icgsbr** [comment]
ci:test:objects

**Comment by icgsbr** [comment]
ci:test:playwright

**Comment by icgsbr** [comment]
ci:test:object

**Comment by marcelabc** [comment]
ci:report:29444464

**Comment by marcelabc** [comment]
@icgsbr, please ignore this when I run the CI reports. I'm using it for a different purpose.

**Comment by marcelabc** [comment]
ci:report:29473526

**Comment by marcelabc** [comment]
ci:report:30165546

**Comment by marcelabc** [comment]
ci:report:30165544

**Comment by marcelabc** [comment]
ci:report:31082847

**Comment by marcelabc** [comment]
ci:report:31082847

**Comment by marcelabc** [comment]
fixed rebase error here: https://github.com/liferay-objects/liferay-portal/pull/3492

**Pull request closed without merging**
