### PR TITLE
LPD-5446 removal of feature flag of LPS-192957

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:test:object

**Comment by samuelromeiro** [comment]
Blocked because there is still one Story in progress using this FF. Story LPD-6662.

**Comment by linolaoj** [comment]
I'll include a commit to also remove the feature flag of LPD-11179.

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
resending here https://github.com/liferay-objects/liferay-portal/pull/3329

**Pull request closed without merging**
