### PR TITLE
LPS-178347 Add validation to don't permit use expression builder when field is picklist as state

### PR DESCRIPTION
**Pull request by murilostodolni**
Related:
https://issues.liferay.com/browse/LPS-178347

@carolmariaabb could you review this https://github.com/liferay-objects/liferay-portal/pull/1938/commits/1b0a0d7b9ea1eb2fd4830086cf0ac65e9b7632ef and this https://github.com/liferay-objects/liferay-portal/pull/1938/commits/d578e89f6281746053540a32549314543f19ef07 commits, please?

### CODE REVIEW

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
ci:test:object

**Comment by murilostodolni** [comment]
ci:test:relevant

**Review by carolmariaabb — APPROVED** [review]
LGTM! 🎉

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
