### PR TITLE
LPS-173830 Add parameter to url to get all object fields

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-173830

### CODE REVIEW

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:stop

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:object

**Comment by brianchandotcom** [comment]
@danvb112 merged to master

**Pull request closed without merging**
