### PR TITLE
LPS-200594 Unclear error message when editing the ERC from child object 

### PR DESCRIPTION
**Pull request by diogomelo09**
[LPS-200594](https://liferay.atlassian.net/browse/LPS-200594)

### CODE REVIEW

**Comment by diogomelo09** [comment]
ci:test:sf

**Review by cgmonte — APPROVED** [review]
LGTM!

**Comment by cgmonte** [comment]
ci:forward

**Comment by cgmonte** [comment]
ci:force-forward

**Comment by cgmonte** [comment]
ci:forward:force

**Pull request closed without merging**
