### PR TITLE
LPS-160455 Throw exception if the relationship list is null or empty

### PR DESCRIPTION
**Pull request by ccorreagg**
Related issue: https://issues.liferay.com/browse/LPS-162028

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:forward

**Comment by ccorreagg** [comment]
ci:forward

**Comment by michaelhashimoto** [comment]
ci:reevaluate:1287401_4222

**Comment by marcelabc** [comment]
ci:forward

**Comment by marcelabc** [comment]
ci:reevaluate:1357401_2516

**Comment by marcelabc** [comment]
Just started reviewing :)

**Comment by timpak** [comment]
ci:test:bundle

**Pull request closed without merging**
