### PR TITLE
LPD-34732 Incorrect placeholder on expression builder related to autocomplete feature

### PR DESCRIPTION
**Pull request by larissacribeiro**
Related Issue: [LPD-34732](https://liferay.atlassian.net/browse/LPD-34732)

[LPD-34732]: https://liferay.atlassian.net/browse/LPD-34732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by larissacribeiro** [comment]
ci:test:sf

**Comment by larissacribeiro** [comment]
ci:test:sf

**Review by cgmonte — APPROVED** [review]
LGTM!

**Comment by cgmonte** [comment]
ci:test:relevant

**Comment by cgmonte** [comment]
ci:help

**Comment by cgmonte** [comment]
ci:test:object

**Comment by larissacribeiro** [comment]
ci:test:object

**Comment by larissacribeiro** [comment]
ci:test:relevant

**Comment by larissacribeiro** [comment]
failures are unrelated to the changes, they seem to be due to something on 'dnd-td' tables.

**Comment by larissacribeiro** [comment]
ci:forward:force

**Pull request closed without merging**
