### PR TITLE
LPS-145898 Fix error getting a new relationship in GraphQL after creation without restarting the server

### PR DESCRIPTION
**Pull request by javierdearcos**
We found a bug or strange behavior as we were testing object relationships in GraphQL.

When a new relation is created, the GraphQL field is not recognized and causes the query to be invalid until the server is restarted. That is because the GraphQLDTOContributor, that is the object that maps the GraphQL type to the Object Definition type, is created when the ObjectDefinition is deployed, that is, when it is published.

If new fields are added after the publication, these fields are not available in GraphQL, and as the relationship creates the new field, we need to deploy again the ObjectDefinition to be available in runtime without restarting the server.

Please, take a look at the PR to see if I didn't miss any other consequence redeploying the ObjectDefinition, and also to check if this is necessary for some other part of the code. From my understanding, once the ObjectDefinition is published it is not possible to add any new field so we don't have this problem in any other use case.

More information could be found in the Jira ticket: [LPS-145898](https://issues.liferay.com/browse/LPS-145898)

Thank you very much! 🙂

### CODE REVIEW

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
The errors seem related, although I make local tests and everything was working smoothly. 

My only doubt with my reference addition I might have caused a dependency cycle issue as the ObjectDefinitionLocalServiceImpl reference to the ObjectRelationshipLocalService and now the ObjectRelationshipLocalServiceImpl also references the ObjectDefinitionLocalService.

In that case, we need to move the logic to add the field relation field id table column and call to deploy to another place to avoid the issue.

Anyway, I will run the tests again to see if it is not another issue

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
Just started reviewing :)

**Comment by gabrielwas** [comment]
resent in https://github.com/liferay-objects/liferay-portal/pull/380

**Comment by javierdearcos** [comment]
Thank you! 🙂

**Pull request closed without merging**
