### PR TITLE
LPS-150604

### PR DESCRIPTION
**Pull request by SelenaAungst**
Related Issue: https://issues.liferay.com/browse/LPS-150604

https://issues.liferay.com/browse/LPS-150604

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @SelenaAungst, can you please check if these failures are related to your changes? Thanks

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
