### PR TITLE
LPS-164111 Not need

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
Hey @MarinhoFeliphe we have some conflicts in this branch. Could you please take a look? Thanks :)

**Comment by MarinhoFeliphe** [comment]
Resent here: https://github.com/liferay-objects/liferay-portal/pull/1358

**Pull request closed without merging**
