### PR TITLE
LPS-163811 visualization builder label remains the same when editing column label

### PR DESCRIPTION
**Pull request by HenriquePereiraa**
Related Issue: https://issues.liferay.com/browse/LPS-163811

### CODE REVIEW

**Comment by HenriquePereiraa** [comment]
ci:test:relevant

**Comment by HenriquePereiraa** [comment]
ci:test:relevant

**Review by danvb112 — APPROVED** [review]
LGTM! :tada:

**Comment by danvb112** [comment]
ci:forward

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:forward

**Comment by danvb112** [comment]
ci:forward

**Comment by danvb112** [comment]
ci:forward

**Comment by danvb112** [comment]
ci:forward

**Comment by danvb112** [comment]
ci:forward

**Pull request closed without merging**
