### PR TITLE
LPS-166235 Fix visual bug in DDM MultipleSelect trigger

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-166235

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by alinedoleron** [comment]
Hi @danvb112! Did you run `yarn test` on dynamic-data-mapping:dynamic-data-mapping-form-field-type module?

**Comment by danvb112** [comment]
Hey @alinedoleron, Thanks for reminding me, I didn't run the tests before, fixed it now!

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:forward

**Pull request closed without merging**
