### PR TITLE
LPS-202788 Add support for Salesforce Proxy account restriction to work for single entry requests

### PR DESCRIPTION
**Pull request by jairmedeiros**
Related issue: https://liferay.atlassian.net/browse/LPS-202788

### CODE REVIEW

**Comment by marcelabc** [comment]
Hey @jairmedeiros 
I just wanted to let you know that I edited the description to include the "Related Issue" (with the Jira ticket). Please always add this information in your following reviews if you can! :smile:

**Comment by jairmedeiros** [comment]
Thanks @marcelabc!!

**Review by MarinhoFeliphe — CHANGES_REQUESTED** [review]
Just to keep this pull request updated, @jairmedeiros will split this pull requests in two or more.

cc: @marcelabc @marcelabc

**Comment by guilhermedcamacho** [comment]
Hey @jairmedeiros , I suggest you to split this PR like this:

**PR 1** - LPS-202788 Add test cases for testAddObjectEntryWithAccountEntryRestricted1 and testGetObjectEntriesWithAccountEntryRestricted1 _(New tests)_
**PR 2** - LPS-202788 Add support for scope by account get, update, delete single object proxy entry _(New feature, it's important to send the test related to this feature in the same PR)_
**PR 3** - LPS-201146 Add test case for Object Proxy Salesforce boolean field _(New tests)_
**PR 4** - LPS-201147 Add support to use null in filter for object proxy _(New feature, it's important to send the test related to this feature in the same PR)_
**PR 5** - LPS-201147 Add datetime and boolean test case for object proxy _(New tests)_
**PR 6** - LPS-202788 Increase pageSize limit to 2000 for Object Proxy Salesforce (Refactoring, do we already have tests that will ensure that this change has not impacted the things we already have working? otherwise, it is important to submit the test related to this feature in the same PR)

**Comment by guilhermedcamacho** [comment]
I'm closing this PR because you must send the new ones separately.

**Comment by jairmedeiros** [comment]
PR 1 - LPS-202788 Add test cases for testAddObjectEntryWithAccountEntryRestricted1 and testGetObjectEntriesWithAccountEntryRestricted1 (New tests)

https://github.com/liferay-objects/liferay-portal/pull/3166

**Comment by jairmedeiros** [comment]
PR 3 - LPS-201146 Add test case for Object Proxy Salesforce boolean field (New tests)

https://github.com/liferay-objects/liferay-portal/pull/3174

**Comment by jairmedeiros** [comment]
PR 5 - LPS-201147 Add datetime and boolean test case for object proxy (New tests)

https://github.com/liferay-objects/liferay-portal/pull/3176

**Comment by jairmedeiros** [comment]
PR 4 - LPS-201147 Add support to use null in filter for object proxy (New feature, it's important to send the test related to this feature in the same PR)

https://github.com/liferay-objects/liferay-portal/pull/3178

**Comment by jairmedeiros** [comment]
PR 6 - LPS-202788 Increase pageSize limit to 2000 for Object Proxy Salesforce (Refactoring, do we already have tests that will ensure that this change has not impacted the things we already have working? otherwise, it is important to submit the test related to this feature in the same PR)

https://github.com/liferay-objects/liferay-portal/pull/3179

**Comment by jairmedeiros** [comment]
PR 2 - LPS-202788 Add support for scope by account get, update, delete single object proxy entry (New feature, it's important to send the test related to this feature in the same PR)

https://github.com/liferay-objects/liferay-portal/pull/3182

**Pull request closed without merging**
