### PR TITLE
LPS-170568 Add test integration to addObjectDefinition by ERC

### PR DESCRIPTION
**Pull request by murilostodolni**
Related: https://github.com/brianchandotcom/liferay-portal/pull/128127#issuecomment-1366036436

### CODE REVIEW

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
Push force without changes, only rebase to run relevant again.

**Comment by murilostodolni** [comment]
Push force removing code:

```
Assert.assertFalse(_hasTable(objectDefinition.getDBTableName()));
Assert.assertFalse(_hasTable(objectDefinition.getExtensionDBTableName()));
```

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
Push force without changes, only rebase.

**Comment by murilostodolni** [comment]
Forwarding manually: https://github.com/brianchandotcom/liferay-portal/pull/128399

**Comment by murilostodolni** [comment]
ci:close

**Pull request closed without merging**
