### PR TITLE
LPS-176592 buildLang

### PR DESCRIPTION
**Pull request by devpedrotavares**
Related ticket: [LPS-176592](https://issues.liferay.com/browse/LPS-176592)
Obs.: the first 20 commits in this PR have already been approved [here](https://github.com/liferay-objects/liferay-portal/pull/1750). This PR adds 3 commits which implement the mentioned ticket. 
Obs.: edited message, since the base commits got updated

### CODE REVIEW

**Comment by devpedrotavares** [comment]
The sf test is failing because of a missing feature flag that belongs to another story. The same thing happened [here](https://github.com/liferay-objects/liferay-portal/pull/1750).

**Comment by devpedrotavares** [comment]
ci:stop

**Comment by devpedrotavares** [comment]
ci:test:object

**Comment by devpedrotavares** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
Just started reviewing :)

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by devpedrotavares** [comment]
Fixed the conflicts in `portal.properties`

**Comment by devpedrotavares** [comment]
ci:test:sf

**Comment by devpedrotavares** [comment]
The base commits on top of which this PR adds 3 commits were updated as requested by Brian's review. This PR is the new [base](https://github.com/brianchandotcom/liferay-portal/pull/131504). However the commits this PR adds remain unchanged since they were approved.

**Comment by devpedrotavares** [comment]
ci:test:sf

**Comment by devpedrotavares** [comment]
ci:test:object

**Comment by devpedrotavares** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Resent https://github.com/liferay-objects/liferay-portal/pull/1864

**Pull request closed without merging**
