### PR TITLE
Revert "LPS-146896 Create FF for the headless layer"

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @gabrielwas, can you please check if these failures are related to your changes? Thanks

**Comment by liferay-forms** [comment]
Hey @gabrielwas, can you please check if these failures are related to your changes? Thanks

**Comment by liferay-forms** [comment]
Hey @gabrielwas, can you please check if these failures are related to your changes? Thanks

**Comment by mateussgn** [comment]
I had closed because I'm fixing the conflicts.

**Comment by mateussgn** [comment]
ci:close

**Pull request closed without merging**
