### PR TITLE
LPS-167063 Add readOnly label

### PR DESCRIPTION
**Pull request by M-IgorFranca**
Related [ticket](https://issues.liferay.com/browse/LPS-167063)

### CODE REVIEW

**Comment by M-IgorFranca** [comment]
ci:test:sf

**Comment by M-IgorFranca** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by mateussgn** [comment]
ci:forward

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by M-IgorFranca** [comment]
I will try to force the rebase of the master to try to succeed in the tests

**Comment by M-IgorFranca** [comment]
ci:test:relevant

**Comment by M-IgorFranca** [comment]
I will try to force the rebase of the master to try to succeed in the tests(2)

**Comment by M-IgorFranca** [comment]
ci:test:relevant

**Comment by M-IgorFranca** [comment]
The results were [checked with QA](https://liferay.slack.com/archives/C048YNC5GRK/p1668022521376879), I'll send this PR directly to Brian.

**Pull request closed without merging**
