### PR TITLE
LPS-180790

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
@MarinhoFeliphe maybe I broke something. Let me know what you think about the changes.

About the `ObjectActionExecutorKeyException`, maybe Brian will ask us to create inner classes, no? What are the cases he asks for them?

**Comment by gabrielwas** [comment]
@MarinhoFeliphe errors related to the transformUtil. Could you check them, please?

**Comment by MarinhoFeliphe** [comment]
@gabrielwas

> maybe I broke something

I pulled you changes and I'm taking a look at the failures.

> Let me know what you think about the changes.

I prefer this approach (one test for each case), I only use the other one because is the one that Brian usually approve, the times I've tried to use your approach he has denied, but maybe I'm just not understanding the pattern.

> maybe Brian will ask us to create inner classes, no?

he has approved the way we used `ObjectActionExecutorKeyException` so I believe he won't make any changes (or ask for).

> What are the cases he asks for them?

I don't know, for Exceptions I just try to follow the last pattern he accepted, lately he's accepting this way that we've applied.

Thanks for you help!

**Comment by MarinhoFeliphe** [comment]
Resent here: https://github.com/liferay-objects/liferay-portal/pull/2054

**Pull request closed without merging**
