### PR TITLE
LPS-183396 Enable account restriction for Proxy Salesforce object

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:object

**Comment by marcelabc** [comment]
Resend here: https://github.com/liferay-objects/liferay-portal/pull/2264

**Comment by marcelabc** [comment]
Hi @nNilton, how are you doing?
I did one last change regarding the sort between the Assert methods in the test. Please, see: https://github.com/liferay-objects/liferay-portal/pull/2264/commits/c69146b86d375a519a5452e0920063e224219376

Besides that, I noticed that there are many commits related to the same subject/class/method. Because of that, I would like to give feedback regarding this. As a reviewer, it is better to review all the changes in the original commit that introduced this change. Gathering all the modifications in the original commit makes the review easier to understand.

When creating PR, it is ideal to use the commits to create a story telling about your work. So, splitting the work if it is related is not ideal. Doing this can create confusion for the reviewer.

Let me know if you want to talk about it. :smile:

**Pull request closed without merging**
