### PR TITLE
LPS-148242 Not needed

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**
Hi @liferay-objects,

to solve this problem I just needed to match child object definition class name instead of child dynamic object definition table name.

the query below is executed to list the related object entries in relationship tab,

```
select distinct ObjectEntry.*
  from O_20100_Author
  inner join ObjectEntry on ObjectEntry.objectEntryId = O_20100_Author.c_authorId_
  inner join O_20100_Author_x on O_20100_Author_x.c_authorId_ = O_20100_Author.c_authorId_
  inner join R_20100Author_Book_authorBook on R_20100Author_Book_authorBook.c_authorId_ = O_20100_Author.c_authorId_
  where ObjectEntry.groupId = ?
  and ObjectEntry.companyId = ?
  and ObjectEntry.objectDefinitionId = ?
  and R_20100Author_Book_authorBook.c_bookId_ = ?
```

if an user isn't omniadmin and its roles don't have company scope view permission, below condition will be set,
```
and O_20100_Author.c_authorId_ in (select distinct ResourcePermission.primKeyId
							      from ResourcePermission
						           where ResourcePermission.companyId = ?
							      and ResourcePermission.name = ?
						              and ResourcePermission.scope = ?
							      and ResourcePermission.viewActionId = ?
							      and (ResourcePermission.roleId in (?, ?) or ResourcePermission.ownerId = ?));

```
previously the ResourcePermission.name matched the name of the child dynamic object definition table (e.g. O_20100_Author), but there are no object resource permissions with this structure,

now the ResourcePermission.name is matched with the child object definition class name(e.g com.liferay.object.model.ObjectDefinition#42951).

I also opted to solve a disassociation issue in this scenario,

I just validated that if an user doesn't have permission to update a related entry this user won't be able to disassociate it.

https://user-images.githubusercontent.com/42913501/156360999-ea0f1e12-3af2-4c65-8885-3d3101f2cc5d.mp4

### CODE REVIEW

**Review by marcelabc — CHANGES_REQUESTED** [review]
Hi @MarinhoFeliphe,
How are you doing? Thank you for the work!! 
I finished your review and there is only 1 little fix to do 👍  I will add the label to let everybody know of the situation of this PR. When you fix it, please remove the label and let me know 😄

**Comment by MarinhoFeliphe** [comment]
Hi @marcelabc, fine!! and you?

thanks for your review!, I sort these parameters in this [commit](https://github.com/liferay-objects/liferay-portal/pull/456/commits/85447a5bd202d189b4632e256469630ef35fc7c9)

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
Hi @marcelabc,

I don't have permission to remove the label because I'm not a collaborator in liferay-objects.

Could you remove it if there are no actions to do?

Thank you!

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Thanks @MarinhoFeliphe ! Sorry, I forgot about the labels permission 😅

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
