### PR TITLE
LPS-203146 Enable search ObjectEntries by relationship ObjectField when the title ObjectField of the parent ObjectDefinition is different from it ID

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:object

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
See: https://github.com/liferay-objects/liferay-portal/pull/2943

**Pull request closed without merging**
