### PR TITLE
LPS-192181

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:test:stable

**Comment by gabrielwas** [comment]
ci:forward:force

**Comment by gabrielwas** [comment]
Conflict with Brian's master. Rebase resent here: https://github.com/liferay-objects/liferay-portal/pull/2456

**Comment by gabrielwas** [comment]
ci:stop

**Comment by gabrielwas** [comment]
ci:stop

**Pull request closed without merging**
