### PR TITLE
LPS-184706 Add date-picker class inside dropdown-menu

### PR DESCRIPTION
**Pull request by thidspessoa**
Add date-picker class inside dropdown-menu in Objects Filter

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
Closing this PR because I needed to organize the commits, the new PR is [here](https://github.com/liferay-objects/liferay-portal/pull/2113)

**Pull request closed without merging**
