### PR TITLE
LPS-197996 Show folder even when it is empty

### PR DESCRIPTION
**Pull request by alinedoleron**
Ticket: https://liferay.atlassian.net/browse/LPS-197996

### CODE REVIEW

**Review by rebsilva — APPROVED** [review]
LGTM! :tada: :purple_heart:

**Comment by rebsilva** [comment]
ci:test:object

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:forward:force

**Pull request closed without merging**
