### PR TITLE
LPS-182775 Remove FF: LPS-165849 terms of Related Object in Notification Templates

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPS-182775

### CODE REVIEW

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by mateussgn — APPROVED** [review]
LGTM! 🎉

**Comment by mateussgn** [comment]
Hey @MarinhoFeliphe, can you double-check this PR, please?

**Review by naraandrade — CHANGES_REQUESTED** [review]
Wait for https://liferay.slack.com/archives/C026UR5976G/p1689008417888909 to be resolved.

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM!! :tada:

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:forward

**Comment by p-albuquerque** [comment]
ci:forward:force

**Pull request closed without merging**
