### PR TITLE
LPS-148804 Add an action to be triggered manually by the user [FE]

### PR DESCRIPTION
**Pull request by alinedoleron**
- https://issues.liferay.com/browse/LPS-169216
- https://issues.liferay.com/browse/LPS-169217
- https://issues.liferay.com/browse/LPS-169218

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:stop

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Review by cgmonte — APPROVED** [review]
LGTM!

**Comment by alinedoleron** [comment]
Manually forwared: https://github.com/brianchandotcom/liferay-portal/pull/126873

**Pull request closed without merging**
