### PR TITLE
LPS-176087 Remove FF of Bookmarks and Modifiable as system object

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPS-176087](https://liferay.atlassian.net/browse/LPS-176087)
[LPS-197882](https://liferay.atlassian.net/browse/LPS-197882)

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Review by gabrielwas — APPROVED** [review]
LGTM! Great, @pedro-oliveira446 !

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Comment by pedro-oliveira446** [comment]
@gabrielwas, 
I only fixed the conflicts.

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Review by gabrielwas — APPROVED** [review]
LGTM! Thx @pedro-oliveira446

**Comment by pedro-oliveira446** [comment]
ci:forward:force

**Comment by pedro-oliveira446** [comment]
Resent here https://github.com/brianchandotcom/liferay-portal/pull/141784

**Comment by JhossephG** [comment]
ci:reopen

**Pull request closed without merging**
