### PR TITLE
LPS-204443 Field disappear and reappear on screen when creating entries

### PR DESCRIPTION
**Pull request by diogomelo09**
[LPS-204443](https://liferay.atlassian.net/browse/LPS-204443)

### CODE REVIEW

**Review by pedro-oliveira446 — APPROVED** [review]

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:test:stable

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
