### PR TITLE
[TS] LPS-193448 Unable to create an Object Entry with associated required vocabulary

### PR DESCRIPTION
**Pull request by jgarcialr**
Related Issue: https://liferay.atlassian.net/browse/LPS-193448

### CODE REVIEW

**Comment by jgarcialr** [comment]
//cc @crodriguezy

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:object

**Review by carolmariaabb — APPROVED** [review]
LGTM! Following the same pattern from [TaxonomyCategoryExceptionMapper](https://github.com/liferay/liferay-portal/blob/master/modules/apps/headless/headless-delivery/headless-delivery-impl/src/main/java/com/liferay/headless/delivery/internal/jaxrs/exception/mapper/TaxonomyCategoryExceptionMapper.java).

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
