### PR TITLE
LPS-176804

### PR DESCRIPTION
**Pull request by gabrielwas**
Related issue: https://issues.liferay.com/browse/LPS-176804

### CODE REVIEW

**Comment by marcelabc** [comment]
I just wanted to let you know that I edited the description to include the "Related Issue" (with the Jira ticket). Please always add this information in your following reviews if you can!

**Comment by gabrielwas** [comment]
> I just wanted to let you know that I edited the description to include the "Related Issue" (with the Jira ticket). Please always add this information in your following reviews if you can!

Thank you @marcelabc

**Comment by gabrielwas** [comment]
ci:reevaluate:1377401_9500

**Comment by gabrielwas** [comment]
ci:reevaluate:1277401_7141

**Comment by gabrielwas** [comment]
QAs approved it. Forwarding to Brian.

**Comment by gabrielwas** [comment]
Sent https://github.com/brianchandotcom/liferay-portal/pull/131040

**Pull request closed without merging**
