### PR TITLE
LPS-201936 Placeholder shows 'Select an Option' on Language option

### PR DESCRIPTION
**Pull request by larissacribeiro**
**Related Issue**: [**LPS-201936**](https://liferay.atlassian.net/browse/LPS-201936)

Follow up from this pr were some related tests were failling due to my changes: https://github.com/liferay-objects/liferay-portal/pull/2862

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:object

**Comment by marcelabc** [comment]
Hey @cgmonte 
Could you review this PR, please? :smile:

**Comment by cgmonte** [comment]
This is a back-end bug. See comment [here](https://liferay.atlassian.net/browse/LPS-201936?focusedCommentId=2540189).

**Pull request closed without merging**
