### PR TITLE
LPD-38642 [Test Fix] ObjectPersonalData#CanAnonymizeObjectEntries, ObjectPersonalData#CanDeleteObjectEntries

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPD-38642

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:test:object

**Comment by marcelabc** [comment]
Hey @rebsilva 
Could you review this PR, please? :smile:

**Comment by p-albuquerque** [comment]
The tests are passing now:
https://testray.liferay.com/#/project/35392/routines/45357/build/37267800/case-result/37277477
https://testray.liferay.com/#/project/35392/routines/45357/build/37267800/case-result/37277482

**Comment by rebsilva** [comment]
i will take a look later today, thanks!

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
