### PR TITLE
LPS-179097 Evaluate Parent Object terms

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPS-179097

### CODE REVIEW

**Review by MarinhoFeliphe — APPROVED** [review]

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:object

**Comment by MarinhoFeliphe** [comment]
@p-albuquerque could you please run `gw baseline`?

**Comment by p-albuquerque** [comment]
Directly sent in: https://github.com/brianchandotcom/liferay-portal/pull/133295

**Pull request closed without merging**
