### PR TITLE
LPS-163844 Fix Error message is displayed on Object list view when using Default sort

### PR DESCRIPTION
**Pull request by rafaelpdemelo**
LINK LPS: https://issues.liferay.com/browse/LPS-163844

### CODE REVIEW

**Comment by rafaelpdemelo** [comment]
ci:test:sf

**Comment by rafaelpdemelo** [comment]
ci:test:relevant

**Comment by rafaelpdemelo** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
Hi @rafaelpdemelo,

we must not rename `dateCreated` and `dateModified` to `createDate` and `modifiedDate` in `ObjectEntryEntityModel` class because this is the pattern defined by our company's architects for date fields in REST APIs.

date should be a preffix in REST layer and it should be a suffix in DB layer.

the problem is that in somewhere is requesting this API by passing `modifiedDate` instead of `dateModified`, try to find this place, feel free to contact us or slack me if you need support.

Thank you!

**Pull request closed without merging**
