### PR TITLE
LPS-199383 [BE] Create validations in the service layer

### PR DESCRIPTION
**Pull request by gabrielwas**
[LPS-199383](https://liferay.atlassian.net/browse/LPS-199383)

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by victorhcunha** [comment]
ci:test:object

**Comment by gabrielwas** [comment]
ci:stop

**Comment by gabrielwas** [comment]
I'll be changing a tiny thing here

**Comment by gabrielwas** [comment]
Nevermind

**Comment by gabrielwas** [comment]
ci:test:object

**Comment by pedro-oliveira446** [comment]
ci:forward:force

**Pull request closed without merging**
