### PR TITLE
LPS-173893 Revert Notifications Settings

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://issues.liferay.com/browse/LPS-173893

### CODE REVIEW

**Review by murilostodolni — APPROVED** [review]
LGTM! Thank you

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by samuelromeiro** [comment]
Revert no longer needed.

**Pull request closed without merging**
