### PR TITLE
 LPS-194407 Validate ObjectDefinition ERC lenght

### PR DESCRIPTION
**Pull request by murilostodolni**
Follow up: https://github.com/brianchandotcom/liferay-portal/pull/140103#issuecomment-1706776779

@carolmariaabb could you review the last three commits, please?
https://github.com/liferay-objects/liferay-portal/pull/2538/commits/39615ba88dd3fc25a7ff84fc9b8ef3410f8d6667
https://github.com/liferay-objects/liferay-portal/pull/2538/commits/1c296d112763e5cd53c41842953ffa403863b11f
https://github.com/liferay-objects/liferay-portal/pull/2538/commits/bc7bf61549d38b71a4fa42079648170e487f052b

cc @Artartur

### CODE REVIEW

**Review by carolmariaabb — APPROVED** [review]

**Comment by murilostodolni** [comment]
SF not related with this code.

**Comment by murilostodolni** [comment]
ci:stop

**Comment by murilostodolni** [comment]
Force push to rebase with master and fix unrelated SF error.

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
ci:test:object

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
ci:forward:force

**Pull request closed without merging**
