### PR TITLE
LPS-179017 Adapt Structures of NotificationTemplateTerms Resource Commands

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPS-179017

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:test:sf

**Review by carolmariaabb — CHANGES_REQUESTED** [review]
Please see https://github.com/p-albuquerque/liferay-portal/pull/48

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:object

**Comment by naraandrade** [comment]
Just started reviewing :)

**Pull request closed without merging**
