### PR TITLE
LPS-196941 Show the label of the object folder on the header of Model Builder

### PR DESCRIPTION
**Pull request by rebsilva**
Related Issue: https://liferay.atlassian.net/browse/LPS-196941

### CODE REVIEW

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:objects

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward:force

**Pull request closed without merging**
