### PR TITLE
LPS-164927 | LPS-164928

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://issues.liferay.com/browse/LPS-164927
https://issues.liferay.com/browse/LPS-164928

### CODE REVIEW

**Review by rodrigopaulino — APPROVED** [review]
LGTM! 🎉

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by carolmariaabb** [comment]
Blocked because of [LPS-163832](https://issues.liferay.com/browse/LPS-163832)

**Comment by carolmariaabb** [comment]
Also blocked by [LPS-164815](https://issues.liferay.com/browse/LPS-164815)

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:reevaluate:1387401_4131

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:reevaluate:1397401_714

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/124270

**Pull request closed without merging**
