### PR TITLE
LPD-22720 remove feature flag of LPS-192957

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM!! :tada:

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:object

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow

**Comment by linolaoj** [comment]
ci:test:stable

**Comment by linolaoj** [comment]
It needs to be rebased. I'll rebase and resend.

**Comment by linolaoj** [comment]
rebased here https://github.com/liferay-objects/liferay-portal/pull/3347

**Pull request closed without merging**
