### PR TITLE
LPS-137875 LPS-137859 LPS-137876 

### PR DESCRIPTION
**Pull request by interaminense**
- LPS-137875 Set indexed and indexedAsKeyword as default when create an object field
- LPS-137859 Set keyword option by default when enabling searchable in object field
- LPS-137876 Disable searchable button after object is published

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Just started reviewing :)

**Comment by guilhermedcamacho** [comment]
Resent in #54 with one more commit (buildLang)

**Pull request closed without merging**
