### PR TITLE
LPS-193386 Create Integration tests for Object Validation Rules Registry

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://liferay.atlassian.net/browse/LPS-193386

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:object

**Comment by mateussgn** [comment]
ci:test:relevant

**Review by guilhermedcamacho — APPROVED** [review]
LGTM!

**Comment by mateussgn** [comment]
ci:forward

**Comment by mateussgn** [comment]
ci:forward:force

**Pull request closed without merging**
