### PR TITLE
LPS-159354 Implement logic when the aggregation is related to a many to many relationship

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://issues.liferay.com/browse/LPS-159354

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:forward

**Comment by marcelabc** [comment]
ci:forward

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:forward

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
send directly to Brian after talking to him: https://github.com/brianchandotcom/liferay-portal/pull/121443

**Comment by naraandrade** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/121495

**Pull request closed without merging**
