### PR TITLE
LPS-195863

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**
Related issue: https://liferay.atlassian.net/browse/LPS-195863

### CODE REVIEW

**Comment by marcelabc** [comment]
I just wanted to let you know that I edited the description to include the "Related Issue" (with the Jira ticket). Please always add this information in your following reviews if you can!

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
Hey @MarinhoFeliphe,
FYI: Similar to this ticket, André discovered that the "bind" option is available for an unpublish object definition. So, a draft object definition can be bound to an already published root. The ticket is this one: https://liferay.atlassian.net/browse/LPS-196027
I don't know if it is an easy fix, but I'm letting you know  :+1:

**Comment by MarinhoFeliphe** [comment]
Hi @marcelabc, sorry for the late reply,

After QA Team check the failures I'll forward these changes, but as soon as I can I'll send a fix for this issue mentioned.

Thank you!

**Comment by MarinhoFeliphe** [comment]
ci:forward:force

**Pull request closed without merging**
