### PR TITLE
LPS-193257 | LPS-193258

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: 
https://issues.liferay.com/browse/LPS-193257;
https://issues.liferay.com/browse/LPS-193258.

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:object

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:stop

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by victorhcunha** [comment]
ci:test:object

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
Sent directly: https://github.com/brianchandotcom/liferay-portal/pull/141417

**Pull request closed without merging**
