### PR TITLE
LPS-180504 Check if the map is not empty

### PR DESCRIPTION
**Pull request by seltong**
Follow-up: https://github.com/brianchandotcom/liferay-portal/pull/136999

Related issues: [LPS-179931](https://issues.liferay.com/browse/LPS-179931), [LPS-180504](https://issues.liferay.com/browse/LPS-180504)

FF to test the [LPS-180504](https://issues.liferay.com/browse/LPS-180504): `feature.flag.LPS-183882=true`

### CODE REVIEW

**Comment by seltong** [comment]
ci:test:sf

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:reevaluate:1297401_7569

**Comment by carolmariaabb** [comment]
ci:test:stable

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
