### PR TITLE
LPS-173351 Missing upgrades can lead to severe data issues

### PR DESCRIPTION
**Pull request by achaparro**
Related issue: https://issues.liferay.com/browse/LPS-173351

Please, @lucasperj, verify the issue is solved

@marcelabc @carolmariaabb please review the changes since some upgrades were missing

Thank you.

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:upgrade

**Review by carolmariaabb — CHANGES_REQUESTED** [review]
@achaparro why did you delete the [sql/indexes.sql](https://github.com/liferay-objects/liferay-portal/pull/1674/commits/ed17ff6be5b6f077909d343333bc5666630642a3#diff-363d5c2ce1c0519c37de0d4d549ee80faa2b4f11c38c0f3f418d4cd76c773fb4) file?

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
> @achaparro why did you delete the [sql/indexes.sql](https://github.com/liferay-objects/liferay-portal/pull/1674/commits/ed17ff6be5b6f077909d343333bc5666630642a3#diff-363d5c2ce1c0519c37de0d4d549ee80faa2b4f11c38c0f3f418d4cd76c773fb4) file?

Hi  @carolmariaabb, sorry I was doing it fast and forget to remove that change from another pull. It should be fixed now.

I shouldn't take this issue since it is not my component, but I was trying to speed up the resolution since it is blocking our tests.

**Comment by achaparro** [comment]
ci:test:object

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:sf

**Comment by lucasperj** [comment]
@achaparro , Upgrade tests passed on QA perspective. 
Also checked Objects and Relevant, have not noticed any regressions, but please, can someone(@andreefarias / @evanilson-santana / @Luizcarlosqueiroz) from Objects side give a double check? Thank you.

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Review by carolmariaabb — APPROVED** [review]

**Comment by achaparro** [comment]
Hey guys, I have rebased the changes to solve the conflicts

**Comment by carolmariaabb** [comment]
@achaparro Our QA team approved this PR. Please feel free to send this PR directly to Brian.

**Comment by lucasperj** [comment]
PR manualy forwarded here: [brianchandotcom-pull-129625](https://github.com/brianchandotcom/liferay-portal/pull/129625)

**Comment by lucasperj** [comment]
ci:close

**Pull request closed without merging**
