### PR TITLE
LPS-184113 Integration tests for localized object fields

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by samuelromeiro** [comment]
Waiting https://github.com/liferay-objects/liferay-portal/pull/1913 to be merged to see if we're going to need to make changes in this PR.

**Comment by guilhermedcamacho** [comment]
See #2197

**Comment by guilhermedcamacho** [comment]
See #2198

**Comment by guilhermedcamacho** [comment]
See #2199

**Pull request closed without merging**
