### PR TITLE
LPS-203036 Remove the trash icon validation during Object Entries listing

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPS-203036

### CODE REVIEW

**Review by guilhermedcamacho — APPROVED** [review]

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:object

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by mateussandes23** [comment]
ci:test:object

**Comment by p-albuquerque** [comment]
Resent in: https://github.com/liferay-objects/liferay-portal/pull/2919

**Comment by mateussandes23** [comment]
The new one was sent [here](https://github.com/liferay-objects/liferay-portal/pull/2919)

**Pull request closed without merging**
