### PR TITLE
LPS-196211

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
@seltong can you test it after my changes, please?

**Comment by gabrielwas** [comment]
cc @marcelabc

**Comment by seltong** [comment]
Yes, I can do it

**Comment by seltong** [comment]
Hey, @gabrielwas. I tested it manually, it's working as expected

**Comment by gabrielwas** [comment]
resent here: https://github.com/brianchandotcom/liferay-portal/pull/140746

**Comment by gabrielwas** [comment]
Thanks @seltong ! ;)

**Pull request closed without merging**
