### PR TITLE
LPD-26933 Create the object fields by including the external reference code

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:object

**Comment by guilhermedcamacho** [comment]
ci:report:2572474100

**Comment by gabrielwas** [comment]
@guilhermedcamacho  Any updates?

**Comment by guilhermedcamacho** [comment]
ci:test:object

**Comment by guilhermedcamacho** [comment]
ci:forward

**Pull request closed without merging**
