### PR TITLE
LPS-143228 ListType fields must save optionsReferences as HashMap

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-143228

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
Just started reviewing :)

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@mateussgn @gabrielwas see f5ecae1701d696c6d3c847648127a4ced76b2830

**Comment by guilhermedcamacho** [comment]
Hey @mateussgn , as Brian already merged it, I suggest you to check in Brian's repository if Semantic Versioning was fixed in project object-api. See the error in CI results.

**Comment by guilhermedcamacho** [comment]
Already merged by Brian on [f5ecae1](https://github.com/liferay-objects/liferay-portal/commit/f5ecae1701d696c6d3c847648127a4ced76b2830)

**Pull request closed without merging**
