### PR TITLE
LPS-192346

### PR DESCRIPTION
**Pull request by mateussandes23**
Follow up for https://github.com/liferay-objects/liferay-portal/pull/2378

### CODE REVIEW

**Comment by mateussandes23** [comment]
ci:test:sf

**Comment by mateussandes23** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
was reviewed [here](https://github.com/liferay-objects/liferay-portal/pull/2378)

**Comment by mateussandes23** [comment]
ci:test:sf

**Comment by mateussandes23** [comment]
ci:test:object

**Comment by mateussandes23** [comment]
Hey @igor-franca , only one test fails on the last object suit. I updated the PR and run the object routine again to see if there is everything ok with the tests.

**Comment by naraandrade** [comment]
ci:forward:force

**Comment by igor-franca** [comment]
ci:forward:force

**Comment by igor-franca** [comment]
ci:forward:force

**Pull request closed without merging**
