### PR TITLE
LPS-168008 Create methods to include the ERC and companyId of the Object when exporting a form and update the objectDefinitionId when importing a form.

### PR DESCRIPTION
**Pull request by devpedrotavares**
Related issue: [LPS-168008](https://liferay.atlassian.net/browse/LPS-168008)

### CODE REVIEW

**Comment by devpedrotavares** [comment]
ci:test:sf

**Comment by devpedrotavares** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
ci:test:object

**Comment by murilostodolni** [comment]
Sent to: https://github.com/liferay-forms/liferay-portal/pull/2254

**Comment by murilostodolni** [comment]
ci:close

**Pull request closed without merging**
