### PR TITLE
[TS] LPS-199901

### PR DESCRIPTION
**Pull request by crodriguezy**
Related ticket: https://liferay.atlassian.net/browse/LPS-199901

### CODE REVIEW

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:stable

**Comment by crodriguezy** [comment]
Hello @carolmariaabb is there any problem r elated to this changes?

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by crodriguezy** [comment]
hey @carolmariaabb is this ready to be moved forward? it's quite important to merge it into the product to avoid future critical problems.
thank you

**Comment by carolmariaabb** [comment]
Hi @crodriguezy, I'm only waiting for `ci:test:stable` to pass. Feel free to also run `ci:forward:force` when necessary. Thanks!

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
