### PR TITLE
LPS-195215 Import all object definition in uncategorized objectFolder

### PR DESCRIPTION
**Pull request by murilostodolni**
Related: https://liferay.atlassian.net/browse/LPS-195215

### CODE REVIEW

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
Hi @murilostodolni, just to confirm the current behavior: right now, if I import an object with an ERC that already exists in the system (no matter in which folder it is) we are overriding it and moving it for the Uncategorized Folder. Is this aligned with Product? Just to make sure.

**Comment by murilostodolni** [comment]
Hey @naraandrade 

>  just to confirm the current behavior: right now, if I import an object with an ERC that already exists in the system (no matter in which folder it is) we are overriding it and moving it for the Uncategorized Folder. Is this aligned with Product? Just to make sure.

The Product Team requested this behavior in Product Sync.

> PS.: This can affect the current relationships that object has in the system and while moving it to the Uncategorized Folder, would we link it in the other folders it has relationships?

I didn't understand this comment.

**Comment by murilostodolni** [comment]
ci:test:stable

**Comment by naraandrade** [comment]
> Hey @naraandrade
> 
> > just to confirm the current behavior: right now, if I import an object with an ERC that already exists in the system (no matter in which folder it is) we are overriding it and moving it for the Uncategorized Folder. Is this aligned with Product? Just to make sure.
> 
> The Product Team requested this behavior in Product Sync.
> 
> > PS.: This can affect the current relationships that object has in the system and while moving it to the Uncategorized Folder, would we link it in the other folders it has relationships?
> 
> I didn't understand this comment.

Example: We have an object called "Employee" inside a folder named "ABC". "Employee" has relationships with "Department" and "Company" that are also in the "ABC" folder. If I export the JSON for "Employee" and import it in the portal, "Employee" will be moved to the Uncategorized folder and will not exist anymore in the "ABC" folder. My question is, what happens with the relationships it had with "Department" and "Company"? We'll we link the "Employee" object in the "ABC" folder to keep the relationships as they were before?

**Comment by murilostodolni** [comment]
> Example: We have an object called "Employee" inside a folder named "ABC". "Employee" has relationships with "Department" and "Company" that are also in the "ABC" folder. If I export the JSON for "Employee" and import it in the portal, "Employee" will be moved to the Uncategorized folder and will not exist anymore in the "ABC" folder. My question is, what happens with the relationships it had with "Department" and "Company"? Will we link the "Employee" object in the "ABC" folder to keep the relationships as they were before?

Yes, "Employee" object will keep as linked in "ABC" folder. If the user want, he move the "Employee" object back to "ABC" folder.

**Comment by naraandrade** [comment]
> > Example: We have an object called "Employee" inside a folder named "ABC". "Employee" has relationships with "Department" and "Company" that are also in the "ABC" folder. If I export the JSON for "Employee" and import it in the portal, "Employee" will be moved to the Uncategorized folder and will not exist anymore in the "ABC" folder. My question is, what happens with the relationships it had with "Department" and "Company"? Will we link the "Employee" object in the "ABC" folder to keep the relationships as they were before?
> 
> Yes, "Employee" object will keep as linked in "ABC" folder. If the user want, he move the "Employee" object back to "ABC" folder.

Ok, thanks, Murilo!

**Comment by murilostodolni** [comment]
Force push to fix test in front end in this [commit](https://github.com/liferay-objects/liferay-portal/pull/2535/commits/6a1a3a52b4c7093ae5e3658837123edea323a7be).

cc: @naraandrade

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
ci:test:object

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
ci:forward:force

**Comment by murilostodolni** [comment]
ci:close

**Comment by murilostodolni** [comment]
Forwarding manually: https://github.com/brianchandotcom/liferay-portal/pull/140282

**Pull request closed without merging**
