### PR TITLE
[TS] LPS-159590 Keep the WorkflowThreadLocal enabled in ObjectEntryLocalService

### PR DESCRIPTION
**Pull request by TaiPhamLR**
Dear team,
This PR is for ticket https://issues.liferay.com/browse/LPS-159590 that passed my review. Please help me to review it and leave your comments.
Thanks.
cc@hongvo2308

### CODE REVIEW

**Comment by marcelabc** [comment]
Hey @MarinhoFeliphe, 
Could you please review this PR? Thank you! :smile:

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Hi @TaiPhamLR, @hongvo2308, the failures are not related to your changes. Feel free to send this PR directly to Brian. Thanks!

**Comment by hongvo2308** [comment]
Forwarded https://github.com/brianchandotcom/liferay-portal/pull/126838
Thank you.

**Pull request closed without merging**
