### PR TITLE
LPS-140522 Relationship deletion should validate if there are related entries between objects

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-140522

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:test:relevant

**Review by MarinhoFeliphe — CHANGES_REQUESTED** [review]
@mateussgn 

I belive we need to use Service instead of LocalService once we're getting all entries by skiping permission checker, so when it will delete on cascade mode or disassociate we need to check permission [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/object/object-service/src/main/java/com/liferay/object/internal/related/models/ObjectEntry1to1ObjectRelatedModelsProviderImpl.java#L80) and [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/object/object-service/src/main/java/com/liferay/object/internal/related/models/ObjectEntry1to1ObjectRelatedModelsProviderImpl.java#L87) by using Service.

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:relevant

**Review by MarinhoFeliphe — APPROVED** [review]

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
Sent directly to Brian: https://github.com/brianchandotcom/liferay-portal/pull/124796

**Pull request closed without merging**
