### PR TITLE
LPS-156337 Add condition when relationship value is 0

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-156337

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:stop

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@danvb112 I merged this manually and to the temp branch.

**Comment by brianchandotcom** [comment]
@danvb112 see 4d716f45f2c5965feb218f59e2c438123226e840 and 9b249b23797b80f00710a4afa3f83cf625759374

**Pull request closed without merging**
