### PR TITLE
LPS-160807 Remove feature flag

### PR DESCRIPTION
**Pull request by seltong**

### CODE REVIEW

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
Just need to fix the CI error as we commented on Slack :smile:

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
Resent [here](https://github.com/brianchandotcom/liferay-portal/pull/122400)

**Pull request closed without merging**
