### PR TITLE
LPS-148641 Create Default Filter Screen component

### PR DESCRIPTION
**Pull request by danvb112**

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
hey @danvb112, rebase error 😕

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Pull request closed without merging**
