### PR TITLE
LPS-161301 Prevent more than one picklist filter in custom view

### PR DESCRIPTION
**Pull request by M-IgorFranca**
Related https://issues.liferay.com/browse/LPS-161301

### CODE REVIEW

**Comment by M-IgorFranca** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — CHANGES_REQUESTED** [review]
Great job, @M-IgorFranca :) Just one thing: I think it would make more sense if you create the const availableFields starting with the value resulting of the second filter you did here, and then returning it with the filter `.filter(({label}: ObjectField) =>
			stringIncludesQuery(label[defaultLanguageId] as string, query)
		)`.
Thank you!

**Comment by M-IgorFranca** [comment]
> Great job, @M-IgorFranca :) Just one thing: I think it would make more sense if you create the const availableFields starting with the value resulting of the second filter you did here, and then returning it with the filter `.filter(({label}: ObjectField) => stringIncludesQuery(label[defaultLanguageId] as string, query) )`. Thank you!


This is make sence, Done!

**Comment by M-IgorFranca** [comment]
ci:test:sf

**Comment by M-IgorFranca** [comment]
ci:test:relevant

**Comment by M-IgorFranca** [comment]
I ran these tests in my local environment:
LocalFile.ObjectPermission#CanEditItsOwnEntryWithOnlyAddPermission 👍🏾 
LocalFile.ObjectsPopulating#CanMapStringTypeAndViewEntries 👎🏾 

So I'm running the tests again

**Comment by M-IgorFranca** [comment]
ci:test:relevant

**Review by naraandrade — APPROVED** [review]

**Comment by M-IgorFranca** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
@M-IgorFranca you can send it directly to Brian.

**Comment by M-IgorFranca** [comment]
resent [here](https://github.com/brianchandotcom/liferay-portal/pull/122556)

**Pull request closed without merging**
