### PR TITLE
LPS-190948 The Specific Content is missing on Action panel after import the display page template

### PR DESCRIPTION
**Pull request by ruben-pulido**
https://liferay.atlassian.net/browse/LPS-190948

Hi team,

I'm sending this PR for you to review since it modifies ObjectEntntryItemDescriptor in this [commit](https://github.com/liferay-objects/liferay-portal/pull/2390/commits/0c32dbba78e82387e83ef38a159c1aaa1a1a61db)

The PR has already been reviewed by Echo team [here](https://github.com/liferay-echo/liferay-portal/pull/13060) so if it gets your approval it can be forwarded to Brian.

Thanks!

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉
Sorry for the delay in reviewing this PR.

**Comment by marcelabc** [comment]
ci:forward:force

**Comment by marcelabc** [comment]
Hey @ruben-pulido,
The forward command failed. I don't know if you prefer to send this PR manually to Brian or try it again later.

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
