### PR TITLE
LPS-151255 Add condition when label is null in Layout Builder

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-151255

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:forward

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
