### PR TITLE
LPS-194309 Create MVCResourceCommand to return the allowed types of an object relationship

### PR DESCRIPTION
**Pull request by murilostodolni**
Related: https://liferay.atlassian.net/browse/LPS-194309

### CODE REVIEW

**Review by carolmariaabb — APPROVED** [review]
Great job 🎉

**Comment by carolmariaabb** [comment]
@murilostodolni you only need to fix the [Semantic Versioning](https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/636331/testReport/com.liferay.semantic.versioning/SemanticVersioningTest/testSemanticVersioning__apps_object_object_api_/) failure

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
ci:forward:force

**Comment by murilostodolni** [comment]
This PR will be send together with this [PR](https://github.com/liferay-objects/liferay-portal/pull/2460) to avoid conflicts.

**Comment by murilostodolni** [comment]
ci:stop

**Pull request closed without merging**
