### PR TITLE
LPD-35321 String values should be used to validate number conversion.

### PR DESCRIPTION
**Pull request by rijema**
It solves testAddInfoItemInvalidIntegerTooSmall, testAddInfoItemInvalidIntegerTooBig on EditInfoItemStrutsActionTest.

https://liferay.atlassian.net/browse/LPD-35393

No need of an additional test, as we're solving two which already cover the behaviour, right?

The language itself it was not validating properly the value passed by the Content Management team (-2147483649, one value greater than the allowed to int variables), so I did this change to consider a String instead of an int value, which was causing the problem with the integer overflow. The value passed on the tests are now being converted to 0, which is the value expected to be returned if it is out of the var range.

### CODE REVIEW

**Comment by rijema** [comment]
ci:test:sf

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:page-management

**Comment by rijema** [comment]
ci:reevaluate:1287401_10927

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
