### PR TITLE
LPS-168447 | LPS-168446

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://issues.liferay.com/browse/LPS-168447
https://issues.liferay.com/browse/LPS-168446

### CODE REVIEW

**Comment by carolmariaabb** [comment]
Waiting for the headless review: https://github.com/liferay-headless/liferay-portal/pull/867

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:sf

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:reevaluate:1387401_4891

**Comment by carolmariaabb** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/126485

**Pull request closed without merging**
