### PR TITLE
LPS-170706 Restore notificationRecipients lost

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by mbowerman** [comment]
Hi @MarinhoFeliphe,

Thanks for making this fix!

Can we also add https://github.com/mbowerman/liferay-portal/commit/b9696c315a26bb530f02b9f0bff7e3f5f9ab7ab4, though? I think it's very important that we add this. Otherwise, the data loss can still occur if an error occurs during the v3_0_0 upgrade process (for example, if the database connection randomly drops while preparedStatement4 is being executed).

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:forward

**Comment by anabuchmann** [comment]
Just started reviewing :)

**Pull request closed without merging**
