### PR TITLE
LPS-152537 Fix error filtering and aggregating by creator field

### PR DESCRIPTION
**Pull request by javierdearcos**
Related Issue: https://issues.liferay.com/browse/LPS-152537

When using creator with the filter or aggregationTerms URL parameter in Object API calls, the filtering and aggregation does not work.

**Steps to reproduce:**
1. Create a custom object, for example, "Employees", with some fields and publish it
2. Create some objects
3. Make a request to get all objects aggregating by "creator"
```
curl \
	"http://localhost:8080/o/c/employees/?aggregationTerms=creator" \
	-u "test@liferay.com:test"
```

**Expected behavior**: The aggregation information is provided in the facets block
**Result**: The aggregation information is empty

**Investigation**

Investigating the way the Object entries are indexed in ElasticSearch I've found that they are indexed without the "_sortable" suffix, so I've changed the ObjectEntryEntityModel accordingly.

I send you this PR to validate the fix because the other option is to index this information as sortable if sort is also needed for the creator field.

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @javierdearcos, can you please check if these failures are related to your changes? Thanks

**Comment by liferay-forms** [comment]
Hey @javierdearcos, can you please check if these failures are related to your changes? Thanks

**Comment by javierdearcos** [comment]
Errors are not related to the PR.

Trying one more time with relevant

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @javierdearcos, can you please check if these failures are related to your changes? Thanks

**Review by mateussgn — APPROVED** [review]

**Pull request closed without merging**
