### PR TITLE
LPS-160455 buildService

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://issues.liferay.com/browse/LPS-160444
Related issue: https://issues.liferay.com/browse/LPS-160455

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
Hi @marcelabc,

LGTM! :tada:

the relevant is failing because [this place](https://github.com/liferay-objects/liferay-portal/blob/f41681f98284837269c3fa51b5a2c107175e5e37/modules/apps/object/object-service/src/main/java/com/liferay/object/service/impl/ObjectEntryLocalServiceImpl.java#L1675) uses the old signature of `findByODI1_N` method.

**Review by MarinhoFeliphe — CHANGES_REQUESTED** [review]
Hi @marcelabc,

LGTM! tada

the relevant is failing because [this place](https://github.com/liferay-objects/liferay-portal/blob/f41681f98284837269c3fa51b5a2c107175e5e37/modules/apps/object/object-service/src/main/java/com/liferay/object/service/impl/ObjectEntryLocalServiceImpl.java#L1675) uses the old signature of `findByODI1_N` method.

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Thanks @MarinhoFeliphe  for the review and help!
I fixed and added the label "Good to go" okay? 
Let me know if you don't agree or feel free if you want to review it again!

thanks!

**Comment by marcelabc** [comment]
ci:stop

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
RESEND: https://github.com/liferay-objects/liferay-portal/pull/929

**Pull request closed without merging**
