### PR TITLE
LPS-173346 - It's not possible to see the Label Action Name on Custom Action

### PR DESCRIPTION
**Pull request by ericthmoritsuka**
Related Issue: https://issues.liferay.com/browse/LPS-173346

### CODE REVIEW

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Comment by ericthmoritsuka** [comment]
ci:test:relevant

**Comment by ericthmoritsuka** [comment]
ci:test:relevant

**Comment by ericthmoritsuka** [comment]
ci:test:relevant

**Comment by ericthmoritsuka** [comment]
ci:test:object

**Comment by ericthmoritsuka** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Hi @ericthmoritsuka

Don't need to run the ci again 😄 I will ask the QA team to review the existing results. Thanks!

**Comment by marcelabc** [comment]
Hey @ericthmoritsuka :smile: 
When we run the CI a couple of times and there are failures, it is recommended that we analyze the result instead of running again and again. Next time, feel comfortable sharing your doubts and ask for help from our team to investigate with you!
Thank you

**Comment by ericthmoritsuka** [comment]
Thanks @carolmariaabb and @marcelabc. 
As it generally breaks in some jdk things we (here at bug-fixing) generally run it again until it passes. 
I also agree that I should not run it multiple times, it is distressing =D. Sorry about that.

**Comment by carolmariaabb** [comment]
@ericthmoritsuka please see https://github.com/liferay-objects/liferay-portal/pull/1693

**Comment by ericthmoritsuka** [comment]
@carolmariaabb I think I see what went wrong with the tests now. Thank you. I was reading the other files and with this fix, you changed other similar occurrences of the same problem, didn't you?

**Comment by carolmariaabb** [comment]
> @carolmariaabb I think I see what went wrong with the tests now. Thank you. I was reading the other files and with this fix, you changed other similar occurrences of the same problem, didn't you?

@ericthmoritsuka I fixed the poshi tests that were considering the action name instead of the action label and I also enabled the search by action label

**Comment by ericthmoritsuka** [comment]
Awesome, @carolmariaabb. Thanks for enlightening me!

**Pull request closed without merging**
