### PR TITLE
LPS-169854 Notification is created duplicately

### PR DESCRIPTION
**Pull request by daiazius**
Related issue: https://issues.liferay.com/browse/LPS-169854

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Hi @daiazius, we have some conflicts in this branch. Could you take a look, please? Thanks :)

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
@daiazius we had some problems with the SF yesterday, but a PR fixing them was already merged by Brian. Please, rebase your branch with the updated master and force push this PR.

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
