### PR TITLE
LPS-187125

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:object

**Comment by thallescezar** [comment]
Resent here: https://github.com/liferay-objects/liferay-portal/pull/2660

**Comment by thallescezar** [comment]
Resent here: https://github.com/liferay-objects/liferay-portal/pull/2660

**Pull request closed without merging**
