### PR TITLE
LPS-184336, LPS-184877 Create readOnly and readOnlyConditionExpression columns in ObjectField entity

### PR DESCRIPTION
**Pull request by guilhermedcamacho**
Related tickets:
https://issues.liferay.com/browse/LPS-184336
https://issues.liferay.com/browse/LPS-184877

### CODE REVIEW

**Review by p-albuquerque — APPROVED** [review]

**Comment by guilhermedcamacho** [comment]
I only fixed the conflicts with version files (packageinfo).

**Comment by guilhermedcamacho** [comment]
ci:forward:force

**Comment by guilhermedcamacho** [comment]
ci:stop

**Comment by guilhermedcamacho** [comment]
Manually forwarded to [brianchandotcom#135696](https://github.com/brianchandotcom/liferay-portal/pull/135696)

**Pull request closed without merging**
