### PR TITLE
LPD-40990 Clear object action thread local when adding system object entries, the same way it's done for custom object entries

### PR DESCRIPTION
**Pull request by devpedrotavares**
Related ticket: [LPD-40990](https://liferay.atlassian.net/browse/LPD-40990)

[LPD-40990]: https://liferay.atlassian.net/browse/LPD-40990?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by linolaoj — APPROVED** [review]

**Comment by devpedrotavares** [comment]
ci:test:sf

**Comment by devpedrotavares** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
ci:report:60649170

**Comment by devpedrotavares** [comment]
ci:forward

**Pull request closed without merging**
