### PR TITLE
LPS-141285 The system should keep the user on the Layout page when an entry is created in order so see the other tabs

### PR DESCRIPTION
**Pull request by eli-rlima**
Related issue: https://issues.liferay.com/browse/LPS-141285

### CODE REVIEW

**Comment by eli-rlima** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Hey @eli-rlima , can you check if these failing tests are related to your changes?

**Comment by guilhermedcamacho** [comment]
Just started reviewing :)

**Pull request closed without merging**
