### PR TITLE
LPD-15346 Add back properties and classes to apply css styles correctly

### PR DESCRIPTION
**Pull request by rebsilva**
Related Issue: https://liferay.atlassian.net/browse/LPD-15346

### CODE REVIEW

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:object

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:object

**Review by igor-franca — APPROVED** [review]

**Comment by rebsilva** [comment]
after analyzing the ci (even with it being very unstable) the conclusion is that the changes are not related to the failures

**Comment by rebsilva** [comment]
ci:forward:force

**Pull request closed without merging**
