### PR TITLE
LPS-155113 Adapt FDSView to load only custom object fields

### PR DESCRIPTION
**Pull request by mateussgn**
Related issues:
https://issues.liferay.com/browse/LPS-155111
https://issues.liferay.com/browse/LPS-155112
https://issues.liferay.com/browse/LPS-155113
https://issues.liferay.com/browse/LPS-155115

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
