### PR TITLE
LPS-159992 Fix condition in object field upgrade process

### PR DESCRIPTION
**Pull request by seltong**

### CODE REVIEW

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:relevant

**Review by marcelabc — CHANGES_REQUESTED** [review]
This PR needs refactoring because we will need to create another upgrade process to fix this issue :+1: 

Thanks @seltong :smile:

**Comment by mbowerman** [comment]
Hi @marcelabc ,

I understand the need to add a new upgrade process so that customers who have already upgrade to U35 can receive a fix for this issue. However, why not merge this pull request in the meantime? The sooner we can get this pull request into a 7.4 Update, the fewer customers will encounter this issue.

For instance, suppose we were to merge this pull request right now, and it makes it into U39. Then any customer who upgrades directly from U32 to U39 will not encounter this issue. In parallel, we could work on the new Upgrade process. Suppose the new Upgrade process makes its way into U40, then for customers who already upgraded to U35, we can tell them "Upgrade to U40".

On the other hand, if we sit on this fix until the new upgrade process has been created, then it will take longer to get this fix into a 7.4 Update. So in the previous example, if we don't have the new upgrade process ready until U40, then customers directly upgrading from U32 to U39 will still experience the issue, and have to wait until U40 is released for it to be resolved.

**Comment by marcelabc** [comment]
Hi @mbowerman 
Thanks for sharing your opinion with us! I reopened your last PR because we could send it to Brian. I would ask you to write a comment to Brian, so he could understand that other upgrade process is being made to fix the clients who already upgrade to U35. If I see the PR in Brian's queue first, I comment as well.
We cannot reuse this PR because @seltong already started to work on the new upgrade process.

Thank you!

**Comment by mbowerman** [comment]
Hi @marcelabc,

Thanks for the explanation and for forwarding my pull request!

May I ask what the timeline is on the new upgrade process? We may need to provide this new upgrade process as a fix for the client. Originally we were planning on delivering a groovy script to them to fix the faulty data; however, it turns out that they may not have the ability to run groovy scripts in their environment.

**Comment by seltong** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@seltong I merged this manually, please review changes in my origin.

**Comment by mbowerman** [comment]
FYI These appear to be the changes that Brian was referring to (they seem to be under the wrong LPS number): https://github.com/brianchandotcom/liferay-portal/compare/70cdd871a02054fe6cd44b104114a88bae2b8fc0...888f4dd92a5b312f8901d4842f25ce601c7799a1

**Pull request closed without merging**
