### PR TITLE
LPS-196221 Make the condition container visible for onAfterRootUpdate trigger

### PR DESCRIPTION
**Pull request by devpedrotavares**
Related ticket: [LPS-196221](https://liferay.atlassian.net/browse/LPS-196221)

### CODE REVIEW

**Review by murilostodolni — APPROVED** [review]
LGTM!

**Comment by devpedrotavares** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
ci:test:object

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by murilostodolni** [comment]
ci:test:stable

**Comment by murilostodolni** [comment]
ci:forward:force

**Pull request closed without merging**
