### PR TITLE
LPD-31454 - Add Validation for term values inside an Email notification

### PR DESCRIPTION
**Pull request by G-Sa**
Related to: [LPD-31454](https://liferay.atlassian.net/browse/LPD-31454)

[LPD-31454]: https://liferay.atlassian.net/browse/LPD-31454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by linolaoj — CHANGES_REQUESTED** [review]

**Comment by G-Sa** [comment]
ci:test:sf

**Comment by G-Sa** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:forward

**Comment by linolaoj** [comment]
ci:forward

**Pull request closed without merging**
