### PR TITLE
LPS-193260 Hide Publish button in details page for Node Objects

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: 
https://issues.liferay.com/browse/LPS-193260;
https://liferay.atlassian.net/browse/LPS-195932.

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:object

**Review by danvb112 — APPROVED** [review]
LGTM! :tada:

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:object

**Comment by p-albuquerque** [comment]
ci:force:forward

**Pull request closed without merging**
