### PR TITLE
Fix test failure in DataLayoutResourceTest

### PR DESCRIPTION
**Pull request by devpedrotavares**
Related issue: [LPS-193148](https://liferay.atlassian.net/browse/LPS-193148)

### CODE REVIEW

**Comment by devpedrotavares** [comment]
ci:test:sf

**Review by murilostodolni — APPROVED** [review]
LGTM 🎉

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Pull request closed without merging**
