### PR TITLE
LPS-178909 A null value is returned on the body of the template when sent

### PR DESCRIPTION
**Pull request by Valmir-unicap**
Related issue: https://issues.liferay.com/browse/LPS-178909

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
Hello @Valmir-unicap,

the problem [is here](https://github.com/liferay/liferay-portal/blob/cbfb7db0931ba419f06cb897a774910df2bb58ea/modules/apps/object/object-service/src/main/java/com/liferay/object/internal/notification/term/contributor/ObjectDefinitionNotificationTermEvaluator.java#L174-L175), when there isn't a value we're passing null to a string, so this is why we're getting the string "null", could you please try to do check if this value is null if so, retrieve a blank String to avoid the string "null".

Thanks!

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:stop

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM!! :tada:

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by MarinhoFeliphe** [comment]
ci:forward:force

**Comment by MarinhoFeliphe** [comment]
Failures are not related.

**Pull request closed without merging**
