### PR TITLE
pr-340

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:reevaluate:1377401_6520

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
BPM QAs checked the unique failures and they are not related to the changes.

**Comment by gabrielwas** [comment]
Just waiting for this last CI run to finish

**Comment by MarinhoFeliphe** [comment]
Resent here: https://github.com/liferay-objects/liferay-portal/pull/1412

**Comment by naraandrade** [comment]
Based on the last comment of @MarinhoFeliphe, I'll be closing this PR.

**Pull request closed without merging**
