### PR TITLE
LPS-200019 Confirmation message appears even when the object is not moved

### PR DESCRIPTION
**Pull request by diogomelo09**
[LPS-200019](https://liferay.atlassian.net/browse/LPS-200019)

### CODE REVIEW

**Comment by diogomelo09** [comment]
ci:test:sf

**Review by igor-franca — APPROVED** [review]
Good job with this PR

**Comment by igor-franca** [comment]
ci:test:object

**Comment by igor-franca** [comment]
ci:test:relevant

**Comment by igor-franca** [comment]
ci:test:object

**Comment by diogomelo09** [comment]
ci:test:stable

**Comment by igor-franca** [comment]
ci:forward:force

**Comment by diogomelo09** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/142838

**Pull request closed without merging**
