### PR TITLE
LPS-168506 Final fix for "Lock wait timeout exceeded" when trying to create a related entry using ERC as reference

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:object

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Comment by carolmariaabb** [comment]
ci:reevaluate:1357401_3053

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by guilhermedcamacho** [comment]
ci:forward

**Comment by guilhermedcamacho** [comment]
I executed some of the tests that are failing and they passed locally, for example:

- LocalFile.PopulateObjectFormsConfiguration#CanSelectObjectStorageType
- LocalFile.ObjectRelationships#CanAddOneToManyRelationWithNativeObject

Let's try again @carolmariaabb , thanks!

**Comment by guilhermedcamacho** [comment]
The same tests are also failing in another [PR](https://github.com/liferay-objects/liferay-portal/pull/1374#issuecomment-1317934018), we can send this manually if it fails again. @carolmariaabb

**Comment by guilhermedcamacho** [comment]
Sent directly to [brianchandotcom#126388](https://github.com/brianchandotcom/liferay-portal/pull/126388)

**Pull request closed without merging**
