### PR TITLE
LPS-169623 Send notifications to users who have permission to view the entity only

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:relevant

**Review by MarinhoFeliphe — APPROVED** [review]

**Comment by MarinhoFeliphe** [comment]
LGTM!! :tada:

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/127267

**Pull request closed without merging**
