### PR TITLE
LPS-198290 Remove if clause to verify always the permissions when deleting an object entry

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LPS-198290

### CODE REVIEW

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:object

**Comment by guilhermedcamacho** [comment]
ci:report:2531432377

**Comment by guilhermedcamacho** [comment]
ci:report:2532198828

**Review by guilhermedcamacho — APPROVED** [review]
LGTM :tada:

**Comment by guilhermedcamacho** [comment]
Hey @magjed4289 , there are two tests that seems to be unique failures, but I'm not sure if they are actually related, I'll forward this PR and then we can check these tests later.

[PortalLogAssertorTest-modules-integration-mysql57-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/2531442405?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2531432377%26testrayRunId%3D2531441185%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

```
[beanshell]      [exec] com.liferay.object.rest.internal.resource.v1_0.test.ObjectEntryRelatedObjectsResourceTest > testPutObjectEntryRelatedSystemObject PASSED
[beanshell] 2024-01-26 15:37:01.922 ERROR [com.liferay.object.rest.test-executor-thread][ObjectEntryImpl:103] null
[beanshell] com.liferay.object.exception.NoSuchObjectDefinitionException: No ObjectDefinition exists with the primary key 47715
```

[PortalLogAssertorTest-modules-integration-mysql57-jdk8/0/2](https://testray.liferay.com/home/-/testray/case_results/2531442527?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2531432377%26testrayRunId%3D2531441185%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

```
[beanshell]      [exec] com.liferay.object.service.test.ObjectActionLocalServiceTest > testAddObjectActionWithSystemObject STARTED
[beanshell] 2024-01-26 15:01:20.760 ERROR [com.liferay.object.test-executor-thread][ObjectActionEngineImpl:155] null
[beanshell] com.liferay.portal.kernel.exception.DuplicateOrganizationException: There is another organization named Organization1
```

**Comment by guilhermedcamacho** [comment]
ci:forward:force

**Pull request closed without merging**
