### PR TITLE
LPS-160220 Avoid console errors when there is no related models

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://issues.liferay.com/browse/LPS-160220

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Review by carolmariaabb — APPROVED** [review]
LGTM 🥳

**Comment by carolmariaabb** [comment]
ci:reevaluate:1297401_5041

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
