### PR TITLE
LPS-144357 Add page parameter to take all objects definitions

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-144357

### CODE REVIEW

**Comment by danvb112** [comment]
Related Issue: https://issues.liferay.com/browse/LPS-144357

**Comment by danvb112** [comment]
ci:test:relevant

**Review by mateussgn — APPROVED** [review]

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
