### PR TITLE
LPS-162028 Return message with exception details

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://issues.liferay.com/browse/LPS-162028

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Hi @carolmariaabb, 
Let me know if you have any questions! Thank you :smile:

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:reevaluate:1387401_3686

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
