### PR TITLE
LPS-181610 - When adding an picklist-state field to an object with already existing entries, I can't assign a value to these already existing entries

### PR DESCRIPTION
**Pull request by Artartur**
Related Issue: [LPS-181610](https://issues.liferay.com/browse/LPS-181610)
Previous PR: [2071](https://github.com/liferay-objects/liferay-portal/pull/2071)

### CODE REVIEW

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Hi @Artartur, how are you doing?
I did some changes in the code, could you check it please? 
See: https://github.com/liferay-objects/liferay-portal/pull/2150

Let me know if you have questions!

**Comment by Artartur** [comment]
Alright, I've tested it here and it's working normally as the expected behavior requested by the ticket. Thx

**Pull request closed without merging**
