### PR TITLE
LPS-194438 | Extract card from Basic Info to allow reusing the form inputs both on current UI and Model Builder view

### PR DESCRIPTION
**Pull request by ocesar9**
Related Issue: https://liferay.atlassian.net/browse/LPS-194438

### CODE REVIEW

**Review by danvb112 — APPROVED** [review]
LGTM! :tada:

**Comment by danvb112** [comment]
Hey @ocesar9, could you take a look at these conflicts?

**Comment by ocesar9** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by ocesar9** [comment]
Send to -> https://github.com/brianchandotcom/liferay-portal/pull/140128

**Pull request closed without merging**
