### PR TITLE
LPS-180495 Remove Feature flag from LPS-164582

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-180495

### CODE REVIEW

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Comment by mateussgn** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by mateussgn** [comment]
ci:forward:force

**Comment by mateussgn** [comment]
ci:close

**Comment by mateussgn** [comment]
Directly sent: https: https://github.com/brianchandotcom/liferay-portal/pull/132795

**Pull request closed without merging**
