### PR TITLE
LPS-174492 Wrong error message when adding a Picklist with same ERC

### PR DESCRIPTION
**Pull request by diogomelo09**
[LPS-174492](https://issues.liferay.com/browse/LPS-174492)
[liferay-portal/pull/130728](https://github.com/brianchandotcom/liferay-portal/pull/130728)

### CODE REVIEW

**Comment by diogomelo09** [comment]
ci:reevaluate:1267401_7447

**Comment by diogomelo09** [comment]
ci:reevaluate:1267401_7446

**Comment by marcelabc** [comment]
Just started reviewing :)

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by diogomelo09** [comment]
ci:test:relevant

**Comment by diogomelo09** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:reevaluate:1257401_6258

**Comment by marcelabc** [comment]
Hi @diogomelo09,
You can send directly to Brian. QA team approved the results :+1: 
Please, remember to send here the link do Brian's PR

**Pull request closed without merging**
