### PR TITLE
LPD-23909 Skip indexer for object entries

### PR DESCRIPTION
**Pull request by joseabelenda**
Related issue: https://liferay.atlassian.net/browse/LPD-23909

### CODE REVIEW

**Comment by joseabelenda** [comment]
ci:test:object

**Comment by guilhermedcamacho** [comment]
Hey @joseabelenda , I suggest you test this piece of code ([ObjectEntrySingleFormVariationInfoCollectionProvider#_getCollectionInfoPageByIndexer](https://github.com/liferay/liferay-portal/blob/58b9f8ef89040992840fd495d21dbde21ac81cd5/modules/apps/object/object-web/src/main/java/com/liferay/object/web/internal/info/collection/provider/ObjectEntrySingleFormVariationInfoCollectionProvider.java#L405-L412)), it may have issues due to PR changes.

**Comment by guilhermedcamacho** [comment]
ci:test:report 2565214093

**Comment by guilhermedcamacho** [comment]
ci:report:2565214093

**Comment by marcelabc** [comment]
I just wanted to let you know that I edited the description to include the "Related Issue" (with the Jira ticket). Please always add this information to your following reviews!

**Comment by marcelabc** [comment]
@joseabelenda I just wanted to let you know that I edited the description to include the "Related Issue" (with the Jira ticket). Please always add this information to your following reviews!

**Pull request closed without merging**
