### PR TITLE
LPS-154071 Create DefinitionTermContributor

### PR DESCRIPTION
**Pull request by gustavolimav**
https://issues.liferay.com/browse/LPS-154786
https://issues.liferay.com/browse/LPS-154071

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:relevant

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
Just started reviewing :)

**Pull request closed without merging**
