### PR TITLE
LPD-20073 | LPD-20076 Fix import issues

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://liferay.atlassian.net/browse/LPD-20073
https://liferay.atlassian.net/browse/LPD-20076

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by 4lejandrito** [comment]
Hey @carolmariaabb, I am worried about this fix. Let's say we export from UAT with objectDefinitionId = 1234, and then we import in LIVE, and there exists another completely unrelated object definition with id = 1234... it would clash and cause unpredictable errors.

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:report:2548742294

**Comment by carolmariaabb** [comment]
ci:report:2548733918

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/148075

**Pull request closed without merging**
