### PR TITLE
LPS-145912 Create a long term solution on backend to Date is displayed as invalid on the layout page of an entry

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-145912

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
LGTM! 🎉 
@marcelabc Could you check it?

**Review by mateussgn — APPROVED** [review]

**Comment by marcelabc** [comment]
Just started reviewing :)

**Comment by marcelabc** [comment]
FWD: https://github.com/liferay-objects/liferay-portal/pull/371

**Comment by marcelabc** [comment]
@danvb112 Please, see my changes in https://github.com/liferay-objects/liferay-portal/pull/371 and feel free to ask any question 😄

**Pull request closed without merging**
