### PR TITLE
LPS-193943 Error message for maximum number of characters for name does not informs which input is not attending the requirement

### PR DESCRIPTION
**Pull request by larissacribeiro**
**Related Issue**: [**LPS-193943**](https://liferay.atlassian.net/browse/LPS-193943)

### CODE REVIEW

**Comment by larissacribeiro** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
@murilostodolni this PR seems related to https://github.com/liferay-objects/liferay-portal/pull/2514, could you please take a look?

**Comment by murilostodolni** [comment]
Waiting https://github.com/brianchandotcom/liferay-portal/pull/140346 to be merged to review this PR.

**Comment by marcelabc** [comment]
Hey @murilostodolni,
Brian merged this PR: https://github.com/brianchandotcom/liferay-portal/pull/140346

**Comment by murilostodolni** [comment]
Hey @larissacribeiro 
Sorry by delay.

We changed the lang key `only-41-characters-are-allowed` to `only-x-characters-are-allowed` for keep more generic. In this case, we can change this lang key to:

`only-x-characters-are-allowed-in-the-x-field=Only {0} characters are allowed in the {1} field.`

We are using this lang key for _name field_ and _ERC field_. So, you need find all used of `only-x-characters-are-allowed` and add a new parameter for this lang key: name of field. Ok?

I will close this PR because the conflict. Feel free to call me if you have any questions. Thank you.

**Comment by murilostodolni** [comment]
ci:close

**Pull request closed without merging**
