### PR TITLE
LPD-6171 Remove FF to enable the formula field

### PR DESCRIPTION
**Pull request by larissacribeiro**
Related Issue: [**LPD-6171**](https://liferay.atlassian.net/browse/LPD-6171)

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by larissacribeiro** [comment]
ci:test:object

**Review by guilhermedcamacho — APPROVED** [review]
LGTM :tada:

**Comment by guilhermedcamacho** [comment]
Hey @larissacribeiro , can you check the CI results? If everything is ok, please forward the PR to Brian.

**Comment by larissacribeiro** [comment]
Yes, @guilhermedcamacho, I'll do that now. Thanks!

**Comment by larissacribeiro** [comment]
ci:report:23676368

**Comment by larissacribeiro** [comment]
ci:report:23030642

**Comment by larissacribeiro** [comment]
object failures are unrelated

**Comment by larissacribeiro** [comment]
ci:forward:force

**Pull request closed without merging**
