### PR TITLE
LPS-190635 - Fix search fields for Salesforce API

### PR DESCRIPTION
**Pull request by G-Sa**
related to https://liferay.atlassian.net/browse/LPS-190635

### CODE REVIEW

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by G-Sa** [comment]
ci:test:object

**Comment by G-Sa** [comment]
ci:test:relevant

**Comment by G-Sa** [comment]
ci:test:relevant

**Comment by G-Sa** [comment]
ci:test:object

**Comment by marcelabc** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
