### PR TITLE
LPS-145842 Fix the confirmation dialog when deleting an object entry

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-145842

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Please, see https://github.com/liferay-objects/liferay-portal/pull/355 before the forward/review!

**Comment by markocikos** [comment]
@marcelabc This PR was already merged :slightly_smiling_face: I'm guessing Brian pushed it manually, to add bugfix the end-of-week release.

**Comment by danvb112** [comment]
Thank you for letting us know @markocikos, I will close this PR and link them to yours

**Comment by danvb112** [comment]
Sent to: https://github.com/liferay-objects/liferay-portal/pull/355

**Pull request closed without merging**
