### PR TITLE
LPD-35168 Binding two object definition trees using the relationship

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: 
[LPD-35168](https://liferay.atlassian.net/browse/LPD-35168)
[LPD-37130](https://liferay.atlassian.net/browse/LPD-37130)

[LPD-35168]: https://liferay.atlassian.net/browse/LPD-35168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LPD-37130]: https://liferay.atlassian.net/browse/LPD-37130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:object

**Comment by marcelabc** [comment]
@pedro-oliveira446 hey Pedro, can you check my changes? Let me know what you think please :smile:

**Comment by marcelabc** [comment]
ci:report:23731829

**Comment by marcelabc** [comment]
no unique failures in the relevant suite

**Comment by marcelabc** [comment]
ci:report:23731827

**Comment by pedro-oliveira446** [comment]
LGTM! Thank you, @marcelabc !

**Comment by marcelabc** [comment]
no unique failures in the objects suite

**Comment by marcelabc** [comment]
ci:forward:force

**Pull request closed without merging**
