### PR TITLE
LPS-174357 Change repositoires permissions

### PR DESCRIPTION
**Pull request by victorg1991**
Basically set the permission of the repository folder so that guest users can write, this is also done in other places of the portal like https://github.com/liferay/liferay-portal/blob/4d3bc122b25faedfcb739b03f9d88786db72444c/modules/apps/blogs/blogs-service/src/main/java/com/liferay/blogs/service/impl/BlogsEntryLocalServiceImpl.java#L1629-L1640

### CODE REVIEW

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:reevaluate:1257401_6242

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:reevaluate:1377401_9570

**Comment by ealonso** [comment]
Hey @marcelabc,

We are trying to pass the ci for a while, Can someone in QA evaluate if the test results are related with the changes or not?

Regards,
Eudaldo

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
