### PR TITLE
LPS-156059

### PR DESCRIPTION
**Pull request by marco-leo**

### CODE REVIEW

**Comment by marco-leo** [comment]
ci:test:sf

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:test:stable

**Comment by marco-leo** [comment]
ci:stop

**Comment by marco-leo** [comment]
ci:test:stable

**Comment by marco-leo** [comment]
ci:test:sf

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:test:stable

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
https://github.com/liferay-objects/liferay-portal/pull/1067

**Comment by carolmariaabb** [comment]
ci:close

**Pull request closed without merging**
