### PR TITLE
LPD-22968 Do not sanitize Text fields

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
-----
Fix a problem where we are escaping & to &amp in text fields.

[Link to the ticket](https://liferay.atlassian.net/browse/LPD-22968)

Proposed Solution
-----
Do not sanitize fields of type "text", since we should only sanitize HTML fields.

### CODE REVIEW

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
