### PR TITLE
LPS-151504 Disable Account as System Object

### PR DESCRIPTION
**Pull request by gabrielwas**
Related Issue: https://issues.liferay.com/browse/LPS-151504

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:forward

**Pull request closed without merging**
