### PR TITLE
LPS-167265 add the correct parameters to the addObjectStateTransition function

### PR DESCRIPTION
**Pull request by diogomelo09**
[LPS-167265](https://issues.liferay.com/browse/LPS-167265)

### CODE REVIEW

**Comment by diogomelo09** [comment]
ci:test:relevant

**Comment by diogomelo09** [comment]
ci:test:relevant

**Comment by diogomelo09** [comment]
ci:test:relevant

**Comment by diogomelo09** [comment]
ci:test:relevant

**Comment by diogomelo09** [comment]
ci:test:relevant

**Comment by diogomelo09** [comment]
ci:teste:relevante

**Comment by seltong** [comment]
Hi @diogomelo09, sorry for delay.

Your fix looks good to me. :tada:  

Could you please rebase your changes with master and do a push?

**Review by seltong — APPROVED** [review]

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:relevant

**Comment by timpak** [comment]
ci:test:object

**Comment by seltong** [comment]
Hi, @diogomelo09. Could you please send this pull request directly to BC? The test failures are unrelated.

**Pull request closed without merging**
