### PR TITLE
LPS 193896

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
-----
Improves the performance in FileEntryMetadataOpenGraphTagsProvider 

[Link to the ticket](https://liferay.atlassian.net/browse/LPS-193895)
It is related to https://liferay.atlassian.net/browse/LPP-50462

Proposed solution
-----
Adds new methods to DDMFieldLocalServiceImpl to get the specific field value instead of getting all DDMFormValues, to get only one value.

I don't know if it fix the problem, but at least it should help.

Please let me know if you have any question.

### CODE REVIEW

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
