### PR TITLE
LPS-199583 Sidebar changes canvas position when hidden in Model Builder

### PR DESCRIPTION
**Pull request by larissacribeiro**
Related Issue: [LPS-199583](https://liferay.atlassian.net/browse/LPS-199583)

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:object

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by alinedoleron** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
