### PR TITLE
LPD-35506 Replace ObjectModelBuilder#CanViewMultipleObjectDefinitions with a playwright test coverage

### PR DESCRIPTION
**Pull request by igor-franca**
related [ticket](https://liferay.atlassian.net/browse/LPD-35506)

### CODE REVIEW

**Review by cgmonte — APPROVED** [review]
LGTM!

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
ci:test:playwright

**Comment by igor-franca** [comment]
ci:test:relevant

**Comment by igor-franca** [comment]
Everything ok with the Jenkins result:

https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/467596/testReport/

**Comment by igor-franca** [comment]
ci:forward

**Pull request closed without merging**
