### PR TITLE
LPS-192491 Create ObjectFolderItem

### PR DESCRIPTION
**Pull request by murilostodolni**
Related:
https://liferay.atlassian.net/browse/LPS-192491
https://liferay.atlassian.net/browse/LPS-192492
https://liferay.atlassian.net/browse/LPS-192493

### CODE REVIEW

**Review by marcelabc — CHANGES_REQUESTED** [review]
Hi 
I finished my review. Let me know if you have questions :smile:

**Comment by murilostodolni** [comment]
ci:stop

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
ci:test:object

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
ci:forward:force

**Comment by murilostodolni** [comment]
Forwarding manually: https://github.com/brianchandotcom/liferay-portal/pull/139986

**Comment by murilostodolni** [comment]
ci:close

**Pull request closed without merging**
