### PR TITLE
LPS-164439 A zero appears when you create a Layout that is linked to a Long Integer field

### PR DESCRIPTION
**Pull request by vngoliveira**

### CODE REVIEW

**Comment by vngoliveira** [comment]
ci:test:relevant

**Review by seltong — APPROVED** [review]
LGTM! :tada:

**Comment by seltong** [comment]
ci:reevaluate:1277401_5472

**Comment by seltong** [comment]
ci:stop

**Review by seltong — APPROVED** [review]

**Comment by seltong** [comment]
LGTM! :tada:

**Comment by seltong** [comment]
ci:forward

**Comment by seltong** [comment]
ci:forward

**Comment by seltong** [comment]
ci:forward

**Comment by seltong** [comment]
ci:reevaluate:1267401_5634

**Comment by seltong** [comment]
ci:forward

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
> These failures doesn't seem to be related to the fix. Maybe we can send it directly to Brian.

There are some tests failing continually in all the latest results of relevant. I don't think it's safe to send it directly to Brian. We can ask QA to take a look at the results.

**Comment by seltong** [comment]
We've come to the conclusion that these test failures are not related to the fix. I will send this pull request directly to Brian.

cc: @naraandrade, @vngoliveira

**Comment by seltong** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/125360

**Pull request closed without merging**
