### PR TITLE
LPS-182343 Incorrect terms on notification templates settings

### PR DESCRIPTION
**Pull request by Valmir-unicap**
Related issue: https://issues.liferay.com/browse/LPS-182343

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:test:stop

**Comment by Valmir-unicap** [comment]
ci:stop

**Review by alinedoleron — APPROVED** [review]

**Comment by alinedoleron** [comment]
LGTM!

Hi @Valmir-unicap . I've talked to @p-albuquerque and I'll close this PR so that he can work above your fix.
Thanks!

**Pull request closed without merging**
