### PR TITLE
LPS-201121 Create putObjectRelationship endpoint by ERC

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPS-201121](https://liferay.atlassian.net/browse/LPS-201121)

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Review by gabrielwas — CHANGES_REQUESTED** [review]
Check the comments, please

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Review by gabrielwas — CHANGES_REQUESTED** [review]
Tiny change

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Review by gabrielwas — APPROVED** [review]
LGTM! Thx @pedro-oliveira446

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Comment by gabrielwas** [comment]
QA found a related issue. @pedro-oliveira446 is working on a fix.

**Comment by gabrielwas** [comment]
LGTM!

**Comment by victorhcunha** [comment]
ci:test:stable:nocompile

**Comment by pedro-oliveira446** [comment]
ci:forward:force

**Pull request closed without merging**
