### PR TITLE
LPS-162822 Inline, rename and keep it simple

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:reevaluate:1377401_6066

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by mateussgn** [comment]
Resent on https://github.com/liferay-objects/liferay-portal/pull/1323

**Comment by mateussgn** [comment]
ci:close

**Pull request closed without merging**
