### PR TITLE
LPS-185898 Hide oldValue function in readOnly Expression Builder and Make readOnly property not required

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Review by p-albuquerque — APPROVED** [review]

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:object

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:forward:force

**Pull request closed without merging**
