### PR TITLE
LPS-173343 Fix warnings on objects and notifications

### PR DESCRIPTION
**Pull request by rebsilva**
Related Issue: https://liferay.atlassian.net/browse/LPS-173343

### CODE REVIEW

**Comment by rebsilva** [comment]
Don't send this PR yet, the CI is having some issues

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:object

**Review by cgmonte — APPROVED** [review]
LGTM!

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by rebsilva** [comment]
I think @naraandrade still needed to review this, so I will ask her!

**Comment by naraandrade** [comment]
> I think @naraandrade still needed to review this, so I will ask her!

It's ok for me!

**Pull request closed without merging**
