### PR TITLE
LPD 23257 Create Manual and Functional Tests to Cover Recipients Roles in Email Notification Template

### PR DESCRIPTION
**Pull request by igor-franca**
Related [Ticket](https://liferay.atlassian.net/browse/LPD-23257)

### CODE REVIEW

**Comment by rebsilva** [comment]
hi @igor-franca! can you check why the sf is failing?

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
ci:test:sf

**Review by rebsilva — APPROVED** [review]
LGTM! :tada:

**Comment by rebsilva** [comment]
ci:test:playwright

**Comment by rebsilva** [comment]
the erros don't seem related, so i will forward the PR

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
ci:test:playwright

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
ci:test:playwright

**Comment by igor-franca** [comment]
The next update aims to remove the `portletURL` from the email notification template page `goTo` function and perform navigation more similar to what the user would do, first accessing the notification templates page and then creating a new entry using the plus button.

With this, we are modifying a function that had speed and practicality as its focus, and we are bringing navigation closer to how a user would navigate. All this to try to achieve satisfactory results in the CI environment, since all previous requests work very well in the local environment.

**Comment by igor-franca** [comment]
ci:test:playwright

**Comment by igor-franca** [comment]
> The next update aims to remove the `portletURL` from the email notification template page `goTo` function and perform navigation more similar to what the user would do, first accessing the notification templates page and then creating a new entry using the plus button.
> 
> With this, we are modifying a function that had speed and practicality as its focus, and we are bringing navigation closer to how a user would navigate. All this to try to achieve satisfactory results in the CI environment, since all previous requests work very well in the local environment.

Hey @rebsilva, could you check if you approve theses changes?

**Comment by rebsilva** [comment]
taking a look!

**Review by rebsilva — APPROVED** [review]
LGTM! :cherry_blossom:

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:playwright

**Comment by rebsilva** [comment]
ci:test:object-web

**Comment by igor-franca** [comment]
ci:forward:force

**Pull request closed without merging**
