### PR TITLE
LPS-187125

### PR DESCRIPTION
**Pull request by thallescezar**

### CODE REVIEW

**Comment by thallescezar** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by thallescezar** [comment]
ci:test:sf

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM!! :tada:

**Comment by thallescezar** [comment]
Resent here: https://github.com/liferay-objects/liferay-portal/pull/2664

**Pull request closed without merging**
