### PR TITLE
LPD-21707 Fix modal add filter to handle object relationships entries

### PR DESCRIPTION
**Pull request by igor-franca**
Related [Ticket](https://liferay.atlassian.net/browse/LPD-21707)

### CODE REVIEW

**Comment by rebsilva** [comment]
just started reviewing! :cherry_blossom:

**Comment by rebsilva** [comment]
ci:test:playwright

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
My bad, [see](https://github.com/liferay-objects/liferay-portal/compare/218306cc45f85ca2741deb3e864362986e737141..8f572619b292bc5d3472ed56aee263079842dc4b)

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
ci:forward

**Comment by igor-franca** [comment]
ci:forward

**Comment by igor-franca** [comment]
ci:forward:force

**Pull request closed without merging**
