### PR TITLE
LPS-146127 Add support to truncate the text if the field type is a String

### PR DESCRIPTION
**Pull request by rodrigocunhaa**

### CODE REVIEW

**Comment by rodrigocunhaa** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
ci:test:object

**Comment by rodrigocunhaa** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
ci:test:object

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
ci:test:object

**Comment by rodrigocunhaa** [comment]
ci:test:object

**Comment by rodrigocunhaa** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
ci:test:object

**Comment by rodrigocunhaa** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
The failures from object suite are not related.

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:object

**Review by mateussgn — APPROVED** [review]

**Comment by danvb112** [comment]
ci:forward

**Pull request closed without merging**
