### PR TITLE
LPS-180756 Add Object Entry Performance Test

### PR DESCRIPTION
**Pull request by guilhermedcamacho**
Related task: https://issues.liferay.com/browse/LPS-180756

### CODE REVIEW

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:forward:force

**Comment by mateussgn** [comment]
Resend: https://github.com/liferay-objects/liferay-portal/pull/2083

**Pull request closed without merging**
