### PR TITLE
LPS-197592 The exception should be more specific when the user tries to save a published entry as a draft

### PR DESCRIPTION
**Pull request by diogomelo09**
[LPS-197592](https://liferay.atlassian.net/browse/LPS-197592)

### CODE REVIEW

**Comment by diogomelo09** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
hey @devpedrotavares 

This PR is related about story object entry as draft. Could you review it, please?

**Review by devpedrotavares — APPROVED** [review]
Hey @diogomelo09 , we usually put only generated code in "BuildLang" commit.
Other than that, LGTM!

**Comment by diogomelo09** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:forward

**Comment by marcelabc** [comment]
ci:forward

**Comment by diogomelo09** [comment]
ci:forward

**Comment by diogomelo09** [comment]
Resent here: [liferay-portal/pull/142035](https://github.com/brianchandotcom/liferay-portal/pull/142035)

**Pull request closed without merging**
