### PR TITLE
LPS-185009 - It's not possible to import an object after canceling and trying to import a new one

### PR DESCRIPTION
**Pull request by Artartur**
Related Issue: [LPS-185009](https://issues.liferay.com/browse/LPS-185009)

### CODE REVIEW

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
Just started reviewing =)

**Comment by alinedoleron** [comment]
Hi @Artartur, I've tested your solution and it works. However, talking to the team, the correct behavior should be not erasing the file when canceling the File selection if there was already one selected file. 
A possible approach would be using the values stored on the File state and remount the file into onChange event. I was trying to implement it here but I didn't get it working yet. Please, could you try this approach or another you want? 
Feel free to ask if you need some help.

Thanks =)

**Review by alinedoleron — CHANGES_REQUESTED** [review]
Hi @Artartur. I've made a comment above.

**Comment by naraandrade** [comment]
Hey @alinedoleron and @Artartur, I was investigating this issue yesterday and it seems that we may need to change the way the formData is populated to be able to achieve the behavior we want. We cannot always reset the inputFile, as Aline mentioned above, and that is easy to do by just removing the call to clearInputFile inside the onChange. However, if we do that, we keep the inputFile correctly, but the inputFileRef.current.value is not set again and we cannot do this programatically for security reasons (I can give more details if you want).

Let's schedule a chat between us to discuss how to resolve that ticket.

**Comment by Artartur** [comment]
ci:test:sf

**Comment by Artartur** [comment]
ci:test:sf

**Comment by Artartur** [comment]
ci:test:sf

**Comment by Artartur** [comment]
ci:test:sf

**Comment by Artartur** [comment]
ci:test:relevant

**Review by alinedoleron — APPROVED** [review]
LGTM! =D

**Comment by alinedoleron** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
