### PR TITLE
LPS-204581 Picklists are created with an unnecessarily long length in DB

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPS-204581](https://liferay.atlassian.net/browse/LPS-204581)

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Review by p-albuquerque — APPROVED** [review]
LGTM!

**Comment by samuelromeiro** [comment]
Resend https://github.com/liferay-objects/liferay-portal/pull/2995

**Pull request closed without merging**
