### PR TITLE
LPS-157213 Remove aggregation feature flag

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://issues.liferay.com/browse/LPS-157213

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
This PR has to wait for this one to be merged: https://github.com/liferay-objects/liferay-portal/pull/1190#issuecomment-1274803786

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@marcelabc merged to master!

**Pull request closed without merging**
