### PR TITLE
LPD-18757 Disable script management configuration on LXC environment

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**
https://liferay.atlassian.net/browse/LPD-18757

I've used the same approach used for `FreeMarker` notification template (`notification.email.template.enabled`)

### CODE REVIEW

**Review by guilhermedcamacho — APPROVED** [review]
LGTM! :tada:

**Comment by guilhermedcamacho** [comment]
Hey @MarinhoFeliphe , there are conflicting files in this PR, please fix this and run CI tests.

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/148729

**Pull request closed without merging**
