### PR TITLE
LPS-160444, LPS-160455, LPS-160474

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://issues.liferay.com/browse/LPS-160444
Related issue: https://issues.liferay.com/browse/LPS-160455
Related issue: https://issues.liferay.com/browse/LPS-160474

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
The failures are not related.

cc: @gabrielwas

**Comment by MarinhoFeliphe** [comment]
Hi @marcelabc,

I made some changes, could you finish the changes discussed by us in this [pull request](https://github.com/marcelabc/liferay-portal/pull/322/commits/cdfe73393dab65e30f73c5305bc5ddba6d4a79af)

Thanks!

**Review by MarinhoFeliphe — CHANGES_REQUESTED** [review]
Hi @marcelabc,

I made some changes, could you finish the changes discussed by us in this [pull request](https://github.com/marcelabc/liferay-portal/pull/322/commits/cdfe73393dab65e30f73c5305bc5ddba6d4a79af)

Thanks!

**Comment by marcelabc** [comment]
resend: https://github.com/liferay-objects/liferay-portal/pull/962

**Pull request closed without merging**
