### PR TITLE
LPS-151410 Create Account system object

### PR DESCRIPTION
**Pull request by gabrielwas**
Related Issue: https://issues.liferay.com/browse/LPS-151410

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @gabrielwas, can you please check if these failures are related to your changes? Thanks

**Comment by liferay-forms** [comment]
Hey @gabrielwas, can you please check if these failures are related to your changes? Thanks

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
