### PR TITLE
LPS-178056 "NullPointerException" interacting with objects with custom view that have been through the v3_18_0 ObjectFieldUpgradeProcess

### PR DESCRIPTION
**Pull request by carolmariaabb**
Follow-up: https://github.com/liferay-objects/liferay-portal/pull/1851

Related Issue: https://issues.liferay.com/browse/LPS-178056

### CODE REVIEW

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
QA Request: https://liferay.slack.com/archives/C048YNC5GRK/p1678827979432999

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Pull request closed without merging**
