### PR TITLE
LPD-24914 Prevent company-scoped object definitions from being selected when creating manual and dynamic collections.

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://liferay.atlassian.net/browse/LPD-24914

### CODE REVIEW

**Comment by carolmariaabb** [comment]
Waiting for https://liferay.slack.com/archives/C033FH2AW9W/p1721930661399859 to perform further manual testing.

**Comment by carolmariaabb** [comment]
@marcelabc It looks like things are working as expected with these changes

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
