### PR TITLE
LPS-199635 Hide move dropdown item if there is only uncategorized objectFolder

### PR DESCRIPTION
**Pull request by murilostodolni**
Ticket: https://liferay.atlassian.net/browse/LPS-199635

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Review by seltong — APPROVED** [review]
LGTM :tada:

**Comment by G-Sa** [comment]
Resent here #2810

**Pull request closed without merging**
