### PR TITLE
LPS-201785 Modify locator for toggle button

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://liferay.atlassian.net/browse/LPS-201785

@andreefarias

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:object

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:object

**Comment by Tim-Cao** [comment]
ci:test:object

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
Starting the review 🔍

**Comment by Tim-Cao** [comment]
ci:test:object

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
The improvement works for us, however I needed to update some testcases and macros. 

See here: #1242 

Thanks for your collaborations! 🎉

**Comment by Tim-Cao** [comment]
ci:close

**Comment by Tim-Cao** [comment]
https://github.com/liferay-bpm-qa/liferay-portal/pull/1242

**Pull request closed without merging**
