### PR TITLE
LPS-181332 Object definition name cannot have spaces

### PR DESCRIPTION
**Pull request by seltong**

### CODE REVIEW

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:object

**Comment by gabrielwas** [comment]
Won't be needed anymore. A new logic using Batch Engine will be used for this purpose.

cc @seltong @samuelromeiro @MarinhoFeliphe

**Comment by gabrielwas** [comment]
sent here https://github.com/brianchandotcom/liferay-portal/pull/133342

**Pull request closed without merging**
