### PR TITLE
LPD-19573 - Export all objects in a root model as a list

### PR DESCRIPTION
**Pull request by G-Sa**
Related issue: [LPD-19573](https://liferay.atlassian.net/browse/LPD-19573)

### CODE REVIEW

**Comment by G-Sa** [comment]
ci:test:object

**Comment by G-Sa** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:report:2551849047

**Comment by marcelabc** [comment]
waiting the CI analysis :man_technologist:

**Comment by G-Sa** [comment]
ci:test:object

**Comment by G-Sa** [comment]
ci:test:relevant

**Comment by G-Sa** [comment]
ci:test:sf

**Comment by G-Sa** [comment]
ci:test:object

**Comment by G-Sa** [comment]
ci:test:relevant

**Comment by G-Sa** [comment]
ci:test:sf

**Comment by G-Sa** [comment]
ci:stop

**Comment by G-Sa** [comment]
ci:test:relevant

**Comment by G-Sa** [comment]
ci:test:object

**Comment by marcelabc** [comment]
ci:reevaluate:1357401_5539

**Comment by marcelabc** [comment]
ci:report:2552801975

**Comment by marcelabc** [comment]
ci:report:2552804119

**Comment by marcelabc** [comment]
ci:forward:force

**Pull request closed without merging**
