### PR TITLE
LPS-162787 add guest/group permissions to upload documents matching permissions with item selector

### PR DESCRIPTION
**Pull request by jgarcialr**

### CODE REVIEW

**Comment by naraandrade** [comment]
Waiting the decision of internal discussions for this PR to be reviewed.

**Comment by MarinhoFeliphe** [comment]
I'm taking a look

**Comment by MarinhoFeliphe** [comment]
LGTM!! :tada:

**Comment by MarinhoFeliphe** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/123522

sorry for delay!

**Pull request closed without merging**
