### PR TITLE
LPS-156259 Block groovy script creation on LXC

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-156259

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
@mateussgn, could you please take a look at this error? I believe something changed that's causing this error with your code. Thx.

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:reevaluate:1327401_5428

**Comment by mateussgn** [comment]
ci:forward

**Comment by mateussgn** [comment]
ci:forward

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Manually forwarded: https://github.com/brianchandotcom/liferay-portal/pull/122550

**Comment by mateussgn** [comment]
Thank you, @rodrigopaulino!!

**Pull request closed without merging**
