### PR TITLE
LPS-171763 "OneToMany" relationship cannot be changed to 'empty' in object entry

### PR DESCRIPTION
**Pull request by carolmariaabb**
Follow-up: https://github.com/liferay-objects/liferay-portal/pull/1605

https://issues.liferay.com/browse/LPS-171763

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by crodriguezy** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
`CannotUpdateObjectNameAfterPublished` only failing in this PR.

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/128980

**Pull request closed without merging**
