### PR TITLE
LPS-140227 buildService

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://issues.liferay.com/browse/LPS-140227

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM!! :tada:

**Comment by marcelabc** [comment]
ci:forward

**Comment by marcelabc** [comment]
ci:stop

**Pull request closed without merging**
