### PR TITLE
LPS-164461 The User should be able to VIEW the item selector only for these definitions that have VIEW grants

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-164461

Hi Team,
Could you please review this PR?
Thanks! Regards

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
Thanks for the fix @lfbesada! That LGTM :D

**Comment by gabrielwas** [comment]
ci:forward

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
@lfbesada I've seen the same failures in other PRs. I think it's safe to send it directly to Brian. 

Could you pleasemanually forward this PR?

**Comment by lfbesada** [comment]
forwarded to Brian, see: https://github.com/brianchandotcom/liferay-portal/pull/125359

**Pull request closed without merging**
