### PR TITLE
LPS-172608 Disable the mandatory toggle when the relationship field is set to Account Restriction

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-172608

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:object

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:test:object

**Comment by naraandrade** [comment]
ci:test:relevant

**Pull request closed without merging**
