### PR TITLE
LPS-162822 Test Integration

### PR DESCRIPTION
**Pull request by murilostodolni**
Test Integration for this ticket: https://issues.liferay.com/browse/LPS-162822

As requested for Brian in: https://github.com/brianchandotcom/liferay-portal/pull/126954#issuecomment-1329779396

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:stop

**Comment by naraandrade** [comment]
@murilostodolni SF failure

**Comment by murilostodolni** [comment]
Hi @naraandrade this failure is not related to this code. [Link](https://liferay.slack.com/archives/C1SJ64S9X/p1671475153531889) slack for this problem.

**Comment by murilostodolni** [comment]
ci:close

**Pull request closed without merging**
