### PR TITLE
LPS-201938 Accessibility of the clay not works with some select options

### PR DESCRIPTION
**Pull request by Artartur**
Related Issue: [LPS-201938](https://liferay.atlassian.net/browse/LPS-201938)

### CODE REVIEW

**Comment by marcelabc** [comment]
Hey @gabrielwas ,
I'm assigning this PR to you because it is frontend. Feel comfortable assigning to anybody from your squad :+1:

**Comment by alinedoleron** [comment]
Hi @Artartur. If I'm not mistaken, when we select Function as **Count** the Field select should disappear. Am I right? Please could you confirm that? On the PR it is being shown.

**Comment by Artartur** [comment]
ci:test:sf

**Comment by Artartur** [comment]
Hey @alinedoleron, what do you think about this new solution?

**Review by alinedoleron — CHANGES_REQUESTED** [review]
Hi @Artartur, nice Job! The solution looks good to me! 

I have just some adjustments in this file that may not be created by you but it would better be adjusted now. :sweat_smile:

**Comment by Artartur** [comment]
ci:test:sf

**Comment by Artartur** [comment]
ci:test:sf

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by alinedoleron** [comment]
ci:test:relevant

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by victorhcunha** [comment]
ci:reevaluate:1347401_5422

**Comment by victorhcunha** [comment]
ci:test:stable

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
