### PR TITLE
LPS-174544 Allow create the Bookmark object while the portal is loading

### PR DESCRIPTION
**Pull request by seltong**
Related issue: [LPS-174544](https://issues.liferay.com/browse/LPS-174544)

### CODE REVIEW

**Comment by seltong** [comment]
ci:test:sf

**Review by gabrielwas — CHANGES_REQUESTED** [review]

**Comment by seltong** [comment]
ci:test:relevant

**Review by gabrielwas — APPROVED** [review]
LGTM :) Thx @seltong

**Comment by evanilson-santana** [comment]
ci:test:object

**Pull request closed without merging**
