### PR TITLE
LPS-168097

### PR DESCRIPTION
**Pull request by murilostodolni**
https://issues.liferay.com/browse/LPS-168073

### CODE REVIEW

**Comment by murilostodolni** [comment]
ci:test:relevant

**Review by gabrielwas — APPROVED** [review]
LGTM! :heavy_check_mark: Thx!

**Comment by gabrielwas** [comment]
ci:forward

**Comment by murilostodolni** [comment]
Forwarding manually https://github.com/brianchandotcom/liferay-portal/pull/126072

**Comment by murilostodolni** [comment]
ci:close

**Pull request closed without merging**
