### PR TITLE
LPD-20526 Send email notification

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://liferay.atlassian.net/browse/LPD-20526

### CODE REVIEW

**Comment by carolmariaabb** [comment]
I'm sending this PR to anticipate the review but I'm already working on the integration tests.

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
I'm deeply sorry because I could not review your PR on time :disappointed: 
Do you want to ask for someone to review, or do you want to run CI and try to send it to Brian?

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
