### PR TITLE
LPD-29802 [Test Fix] ListTypeDefinitionExportImportTest.testExportImportObjectDefinition

### PR DESCRIPTION
**Pull request by victorKammerer**
[LPD-29802](https://liferay.atlassian.net/browse/LPD-29802)

[LPD-29802]: https://liferay.atlassian.net/browse/LPD-29802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
Hi @victorKammerer, can you please check the source format error?

**Comment by victorKammerer** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
Hi @victorKammerer, this looks good to me. Since it changes a class from portal-impl can you please send the pull request to [liferay-core-infra](https://github.com/liferay-core-infra). You can add a comment with the link to the new pull request so we can keep track of it.

**Comment by victorKammerer** [comment]
[Pull request to liferay-core-infra](https://github.com/liferay-core-infra/liferay-portal/pull/7234)

**Pull request closed without merging**
