### PR TITLE
LPD-35778 Extract the EditObjectRelationshipContent into your own component and reuse it in the Model Builder, removing unnecessary code repetitions

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://liferay.atlassian.net/browse/LPD-35778

Hi @rebsilva, This PR does not need unit or playwright tests since I extracted 1 component and 1 function to reuse them and avoid code repetition, our current tests are enough to see if this change will break anything :smile:

### CODE REVIEW

**Comment by rebsilva** [comment]
i will review this later today, thanks!

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:playwright

**Comment by rebsilva** [comment]
ci:test:object

**Comment by danvb112** [comment]
Ci failures are not related!

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:forward:force

**Pull request closed without merging**
