### PR TITLE
LPS-192303

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
----
Allow editing attachment on display page templates

[Link](https://liferay.atlassian.net/browse/LPS-191357)

Proposed Solution
----
Instead of returning the file name as value for attachments return the file entry id, since we already have all document information, but for the moment it is under LPS-176083 Feature Flag.

Also, fix a problem related with Display Pages, it is because when we get a display page for an ObjectEntry we are using the same ObjectDefinition, so we need to use the object definition of the object entry, it is happening when we call: 

```
BaseAssetDisplayPageFriendlyURLResolver.java

private LayoutDisplayPageObjectProvider<?>
		_getLayoutDisplayPageObjectProvider(
			LayoutDisplayPageProvider<?> layoutDisplayPageProvider,
			long groupId, String friendlyURL, String version) {

		return layoutDisplayPageProvider.getLayoutDisplayPageObjectProvider(
			groupId, _getUrlTitle(friendlyURL), version);
	}
```
this layoutDisplayPageProvider is always the same since we are registering all providers under "l" friendly URL, so we are getting always the same.

Please let me know if you have any question.

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:stable

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:forward:force

**Pull request closed without merging**
