### PR TITLE
LPS-148738  WIP populate the var 'inputObjects' with the object entry values

### PR DESCRIPTION
**Pull request by marcelabc**
Related Issue: https://issues.liferay.com/browse/LPS-148738

Hi developer,
the work before the commit starting with "WIP" is working properly.
the work WIP is not working with all the cases.

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by marcelabc** [comment]
Hi @gabrielwas ,
Possible classes that contain the logic to unmount the rule in separate parameters:
- DDMFormRuleConverterImpl
- ConditionExpressionVisitor
- ActionExpressionVisitor

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @marcelabc, can you please check if these failures are related to your changes? Thanks

**Comment by gabrielwas** [comment]
Just started reviewing :)

**Pull request closed without merging**
