### PR TITLE
LPS-184538 Add integration tests for localized object fields

### PR DESCRIPTION
**Pull request by seltong**
Related issue: [LPS-184538](https://issues.liferay.com/browse/LPS-184538)

### CODE REVIEW

**Comment by seltong** [comment]
Blocked by https://github.com/liferay-objects/liferay-portal/pull/2122

**Comment by marcelabc** [comment]
Hey @seltong, 
Since this issue was merged (https://github.com/brianchandotcom/liferay-portal/pull/135734), is this PR able to review?
Also, could you fix the conflict please? :+1: 
Thank you!

**Comment by seltong** [comment]
Hi @marcelabc,
This pull request is also blocked by https://github.com/brianchandotcom/liferay-portal/pull/135832

**Comment by samuelromeiro** [comment]
@seltong the [PR](https://github.com/brianchandotcom/liferay-portal/pull/135832) was merged.

**Comment by seltong** [comment]
I will resolve the conflicts and update this PR

Thanks, @samuelromeiro and @marcelabc

**Comment by seltong** [comment]
Blocked by https://github.com/liferay-objects/liferay-portal/pull/2190

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:relevant

**Pull request closed without merging**
