### PR TITLE
LPS-201143 In Model Builder change Uncategorized to Default

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPS-201143](https://liferay.atlassian.net/browse/LPS-201143)

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Comment by MarinhoFeliphe** [comment]
Hey @pedro-oliveira446 please resolve the conflicts.

Thanks

**Comment by MarinhoFeliphe** [comment]
Hey @pedro-oliveira446, please work on top of https://github.com/pedro-oliveira446/liferay-portal/pull/68

**Review by MarinhoFeliphe — CHANGES_REQUESTED** [review]
Please see my comments

**Comment by pedro-oliveira446** [comment]
[Resent here](https://github.com/liferay-objects/liferay-portal/pull/3029)

**Pull request closed without merging**
