### PR TITLE
LPD-24800 Make the ThemeDisplay get the Instance default language instead of the Site default language when creating Picklists

### PR DESCRIPTION
**Pull request by rebsilva**
Related Issue: https://liferay.atlassian.net/browse/LPD-24800

### CODE REVIEW

**Comment by rebsilva** [comment]
@gabrielwas could you please assign someone from squad zulu ou bravo to review this since it's a BE PR? thanks a lot!

**Comment by rebsilva** [comment]
the PR is blocked until the PO team [decides](https://liferay.slack.com/archives/C026UR5976G/p1715018291757009) this is the expected behavior

**Review by p-albuquerque — APPROVED** [review]
LGTM!!! 🎉

**Comment by p-albuquerque** [comment]
Just to make clear, this approach is based on [that fix](https://github.com/liferay-objects/liferay-portal/pull/1115).

**Comment by linolaoj** [comment]
ci:forward

**Comment by linolaoj** [comment]
ci:stop

**Comment by linolaoj** [comment]
Hi @rebsilva, can we add a test for this?

**Comment by rebsilva** [comment]
sure @linolaoj, i can add one! but this could take a while since the test involves other components that aren't ours. i will confirm with @gabrielwas if we need to send the test now or if it can be after the solution is on master

**Comment by rebsilva** [comment]
ci:test:object

**Comment by rebsilva** [comment]
the failing tests are not related!

**Comment by rebsilva** [comment]
ci:test:forward

**Comment by rebsilva** [comment]
ci:forward:force

**Pull request closed without merging**
