### PR TITLE
LPS-15335 Implement Functional Test to Validate Deletion of Object Relationships From Different Folders

### PR DESCRIPTION
**Pull request by igor-franca**
Related [ticket](https://liferay.atlassian.net/browse/LPD-15617)

### CODE REVIEW

**Review by cgmonte — APPROVED** [review]
LGTM!

**Comment by cgmonte** [comment]
ci:test:playwright

**Comment by igor-franca** [comment]
After analyzing the error in the CI result, I realized that in the CI environment the test fails, as it cannot find the Lifeay reference.

I opened a [thread](https://liferay.slack.com/archives/C06A59K5D46/p1708361075810429) on the playwright channel to find the best way to resolve this.

**Comment by igor-franca** [comment]
Hey @cgmonte, the test passed successfully 👍🏾

**Review by cgmonte — COMMENTED** [review]
Although playwright is failing, the test added by this PR is passing, so it LGTM!

**Review by cgmonte — APPROVED** [review]

**Comment by igor-franca** [comment]
ci:forward

**Pull request closed without merging**
