### PR TITLE
LPS-195029

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
-----
Remove Feature Flags for LPS-182728 and LPS-182586

Related issue: https://liferay.atlassian.net/browse/LPS-182728
Related issue: https://liferay.atlassian.net/browse/LPS-182586

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Natanaelbenvindo** [comment]
Tests failing only in this PR:

1. com.liferay.account.service.test.AccountEntryLocalServiceTest
2. CaptchaFragment#SubmitTextVerificationViaPressingEnter
3. CaptchaFragment#SubmitVerificationOfReCaptcha
4. com.liferay.info.request.struts.test.EditInfoItemStrutsActionValidationTest
5. ObjectCustomValidation#CanCreateValidationUsingOldValueFunctionInSystemObject
6. ObjectFieldsUniqueValue#CanPreventDuplicateIntegerWhenEditing
7. ObjectFieldsUniqueValue#CanPreventDuplicateText
8. ObjectOldValue#CanCreateValidationUsingOldValueFunctionInSystemObject
9. com.liferay.organizations.service.test.OrganizationLocalServiceTest
10. GeneratePathStructureForEndpoints#CanValidatePathInAPIEndpoint

**Comment by marcelabc** [comment]
Thank you, @ealonso!
The QA team analyzed the situation and discovered this bug: [LPS-196607](https://liferay.atlassian.net/browse/LPS-196607).
The BPM team will work on this ASAP.

**Comment by devpedrotavares** [comment]
Sent here: https://github.com/liferay-objects/liferay-portal/pull/2597

**Pull request closed without merging**
