### PR TITLE
LPS-193933 Fix vulnerability at field label input element

### PR DESCRIPTION
**Pull request by rebsilva**
Related Issue: https://liferay.atlassian.net/browse/LPS-193933

### CODE REVIEW

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:object

**Review by naraandrade — APPROVED** [review]

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:forward:force

**Pull request closed without merging**
