### PR TITLE
LPS-205115 - Change the notification link to redirect to Instance Settings.

### PR DESCRIPTION
**Pull request by thallescezar**
Related issue: https://liferay.atlassian.net/browse/LPS-205115

### CODE REVIEW

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM!! :tada:

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:object

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by thallescezar** [comment]
ci:report:2504525749

**Comment by thallescezar** [comment]
ci:forward:force

**Comment by MarinhoFeliphe** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/146471

**Pull request closed without merging**
