### PR TITLE
LPS-180192 Change field property from enableLocalization to localized

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-180192

### CODE REVIEW

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — CHANGES_REQUESTED** [review]
@danvb112 Should we update the `TranslationContainer` file as well?

**Review by naraandrade — APPROVED** [review]

**Comment by danvb112** [comment]
ci:forward

**Comment by danvb112** [comment]
Sent to: https://github.com/brianchandotcom/liferay-portal/pull/132856

**Pull request closed without merging**
