### PR TITLE
LPS-146481

### PR DESCRIPTION
**Pull request by mbowerman**
Hi Objects Team,

I tested this in PostgreSQL with Strings that were more than 4,000 characters long, and I verified that they were all stored and rendered correctly.

https://issues.liferay.com/browse/LPS-146481

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:stop

**Comment by marcelabc** [comment]
ci:stop

**Comment by marcelabc** [comment]
ci:stop

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
