### PR TITLE
LPS-157123, LPS-156675 Give feedback to the user when integration is not valid

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:forward

**Comment by liferay-forms** [comment]
Hey @guilhermedcamacho, can you please check if these failures are related to your changes? Thanks

**Comment by guilhermedcamacho** [comment]
> Hey @guilhermedcamacho, can you please check if these failures are related to your changes? Thanks

The failures are not related. Thanks!

**Comment by guilhermedcamacho** [comment]
Sent directly to Brian [brianchandotcom#120463](https://github.com/brianchandotcom/liferay-portal/pull/120463)

**Pull request closed without merging**
