### PR TITLE
[IPT] LPS-195394 Modify the URL parameter to get all the data using pageSize=-1

### PR DESCRIPTION
**Pull request by vngoliveira**
Related issue: [LPS-195394](https://liferay.atlassian.net/browse/LPS-195394)
LPP ticket: [LPP-50762](https://liferay.atlassian.net/browse/LPP-50762)

### CODE REVIEW

**Comment by vngoliveira** [comment]
ci:test:relevant

**Comment by vngoliveira** [comment]
ci:test:relevant

**Review by danvb112 — APPROVED** [review]
LGTM! :tada:

**Comment by victorhcunha** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:forward:force

**Pull request closed without merging**
