### PR TITLE
LPS-139014 On the Unmapped Object Required Fields error message it is displaying the Field Name instead of Field Label

### PR DESCRIPTION
**Pull request by mlan0**

### CODE REVIEW

**Comment by mlan0** [comment]
ci:test:relevant

**Comment by mlan0** [comment]
ci:reevaluate:1257401_261

**Review by interaminense — APPROVED** [review]
LGTM!

**Comment by guilhermedcamacho** [comment]
ci:reevaluate:1257401_261

**Comment by guilhermedcamacho** [comment]
Just started reviewing :)

**Comment by guilhermedcamacho** [comment]
Sent directly to Brian in this [PR](https://github.com/brianchandotcom/liferay-portal/pull/107491)

**Pull request closed without merging**
