### PR TITLE
LPD-18344 | LPD-18348 | LPD-18362 | LPD-18374 | LPD-18379

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://liferay.atlassian.net/browse/LPD-18344
https://liferay.atlassian.net/browse/LPD-18348
https://liferay.atlassian.net/browse/LPD-18362
https://liferay.atlassian.net/browse/LPD-18374
https://liferay.atlassian.net/browse/LPD-18379

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:stable

**Comment by carolmariaabb** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/147430

**Pull request closed without merging**
