### PR TITLE
LPS-204578 Do not reload page after deleting or importing an object definition

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://liferay.atlassian.net/browse/LPS-204578

### CODE REVIEW

**Comment by rebsilva** [comment]
just started reviewing :cherry_blossom:

**Review by rebsilva — APPROVED** [review]
LGTM! :tada: i have also tested and everything seems fine, amazing work as always @carolmariaabb!

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
