### PR TITLE
LPS-176005 add feature flag

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPS-176005](https://issues.liferay.com/browse/LPS-176005)

This [commit](https://github.com/brianchandotcom/liferay-portal/pull/131266) was merged, and the FF was not added to portal.properties.

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
