### PR TITLE
LPS-154618,LPS-154616

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: 
https://issues.liferay.com/browse/LPS-154618;
https://issues.liferay.com/browse/LPS-154616;

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
Sent directly to Brian [here](https://github.com/brianchandotcom/liferay-portal/pull/118026)

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Review by guilhermedcamacho — APPROVED** [review]

**Pull request closed without merging**
