### PR TITLE
LPD-17849 Remove Model Builder FF from Tests

### PR DESCRIPTION
**Pull request by igor-franca**
Related [Ticket](https://liferay.atlassian.net/browse/LPD-17849)

### CODE REVIEW

**Comment by igor-franca** [comment]
ci:stop

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
ci:test:playwright

**Review by p-albuquerque — COMMENTED** [review]
I just ask you to run all these integration tests with the command:
$ ```gw testintegration --tests ObjectFolderExportImportTest``` 
On the directory **object/object-test** 
Share the results here, please

**Review by rebsilva — APPROVED** [review]
LGTM! :tada: the frontend side seems fine, but i also ask you to run all the playwright tests to see if everything is working as expected

**Comment by igor-franca** [comment]
> LGTM! 🎉 the frontend side seems fine, but i also ask you to run all the playwright tests to see if everything is working as expected

Hey @rebsilva, the only test that failed was `commerce/commerceMiniCart.spec.ts > mini cart bundle with UOM`.

All Model Builder tests passed successfully.

**Comment by igor-franca** [comment]
> Hi @igor-franca I just ask you to run all these integration tests with the command: $ `gw testintegration --tests ObjectFolderExportImportTest` On the directory **object/object-test** Share the results here, please

Hey @p-albuquerque, I ran this test and got this result:

```
> Task :apps:object:object-test:testIntegration

com.liferay.object.web.internal.portlet.action.test.ObjectFolderExportImportTest STANDARD_OUT
    Loading jar:file:/home/me/dev/projects/bundles/liferay-portal/tomcat-9.0.83/webapps/ROOT/WEB-INF/shielded-container-lib/portal-impl.jar!/system.properties
    Loading jar:file:/home/me/dev/projects/liferay-portal/.m2/com/liferay/portal/com.liferay.portal.impl/99.1.0-SNAPSHOT/com.liferay.portal.impl-99.1.0-SNAPSHOT.jar!/system.properties

com.liferay.object.web.internal.portlet.action.test.ObjectFolderExportImportTest > testExportImportObjectFolder STARTED

com.liferay.object.web.internal.portlet.action.test.ObjectFolderExportImportTest > testExportImportObjectFolder PASSED

> Task :apps:object:object-test:stopTestableTomcat

BUILD SUCCESSFUL in 56s
256 actionable tasks: 186 executed, 70 up-to-date
```


Everything seems to be ok, correct?

**Comment by p-albuquerque** [comment]
LGTM!

**Review by cgmonte — APPROVED** [review]
LGTM!

**Comment by igor-franca** [comment]
ci:forward

**Comment by igor-franca** [comment]
ci:test:stable

**Comment by igor-franca** [comment]
ci:test:stable

**Comment by igor-franca** [comment]
ci:test:stable

**Pull request closed without merging**
