### PR TITLE
LPS-154104 Fix bug Searching on Default Sort modal is broken when pre…

### PR DESCRIPTION
**Pull request by thienquach87**
Fix comment for [liferay-objects#782](https://github.com/liferay-objects/liferay-portal/pull/782)

### CODE REVIEW

**Comment by thienquach87** [comment]
@danvb112, 
 Thanks for your suggestion! I updated code based on your idea. Could you help review it?

**Review by danvb112 — APPROVED** [review]
LGTM! :tada:

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:forward

**Comment by danvb112** [comment]
ci:forward

**Pull request closed without merging**
