### PR TITLE
LPS-164817 Fix Typescript erros in ObjectRelationship.tsx

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-164818

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
@danvb112 Since this test [LocalFile.Object#CanViewObjectAfterRestart](https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/229171//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Object_CanViewObjectAfterRestart_) was not showing up in previous rounds of relevant, if the relevant don't pass this time, you can send the PR directly to Brian.

**Comment by danvb112** [comment]
ci:forward

**Pull request closed without merging**
