### PR TITLE
LPS-175202 Clear object action Ids at the end of delete method

### PR DESCRIPTION
**Pull request by devpedrotavares**
Related issue: [LPS-175202](https://issues.liferay.com/browse/LPS-175202)

### CODE REVIEW

**Review by guilhermedcamacho — APPROVED** [review]
LGTM!

**Comment by guilhermedcamacho** [comment]
Hey @devpedrotavares , can you check if the CI errors are related? Thanks!

**Comment by devpedrotavares** [comment]
Hey @guilhermedcamacho! After analyzing the test results, the failures did not seem related.

**Comment by devpedrotavares** [comment]
Forwarding directly: https://github.com/brianchandotcom/liferay-portal/pull/130198

**Pull request closed without merging**
