### PR TITLE
LPS-200587 | master

### PR DESCRIPTION
**Pull request by leilanyaragao**
Issue: https://liferay.atlassian.net/browse/LPS-200587

### CODE REVIEW

**Comment by leilanyaragao** [comment]
ci:test:relevant

**Comment by leilanyaragao** [comment]
ci:test:object

**Review by seltong — APPROVED** [review]
LGTM :tada:

**Review by seltong — CHANGES_REQUESTED** [review]
After talk to @igor-franca, we concluded that this bug is not in the backend.
We need to delete the field without showing the modal.

**Comment by carolmariaabb** [comment]
Thanks for the updates, @seltong! I'll close this PR and move the task back to In Progress.

**Pull request closed without merging**
