### PR TITLE
LPD-23805 Adding test coverage for where notification link redirects

### PR DESCRIPTION
**Pull request by thallescezar**
Related issue: https://liferay.atlassian.net/browse/LPD-22398

This is a follow-up to add tests for this PR: https://github.com/brianchandotcom/liferay-portal/pull/149574

### CODE REVIEW

**Review by rijema — CHANGES_REQUESTED** [review]

**Comment by linolaoj** [comment]
ci:forward

**Comment by rijema** [comment]
ci:reevaluate:1407401_9385

**Comment by linolaoj** [comment]
ci:forward:force

**Comment by linolaoj** [comment]
ci:forward:force

**Pull request closed without merging**
