### PR TITLE
LPS-149508

### PR DESCRIPTION
**Pull request by marcelabc**
Related Issue: https://issues.liferay.com/browse/LPS-149508

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:forward

**Comment by liferay-forms** [comment]
Hey @marcelabc, can you please check if these failures are related to your changes? Thanks

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
