### PR TITLE
LPS-137442 Save and retrieve optionReference for fields with options

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-137442

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
Hey @gabrielwas, I talked with @rodrigocunhaa and those failures are flaky. You can review it without run relevant again, and if you approve I'll send it directly to Brian.

**Comment by gabrielwas** [comment]
Just started reviewing :)

**Comment by mateussgn** [comment]
ci:test:relevant

**Review by gabrielwas — CHANGES_REQUESTED** [review]

**Comment by mateussgn** [comment]
@gabrielwas, I'll close this one and send a new one refactored.

**Comment by mateussgn** [comment]
ci:close

**Comment by mateussgn** [comment]
Resent on https://github.com/liferay-objects/liferay-portal/pull/80.

**Pull request closed without merging**
