### PR TITLE
LPD-24567 Handle scenario at which the user is guest

### PR DESCRIPTION
**Pull request by devpedrotavares**
https://liferay.atlassian.net/browse/LPD-24567

### CODE REVIEW

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
@devpedrotavares please create an integration test

**Comment by devpedrotavares** [comment]
ci:test:sf

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
ci:forward:force

**Comment by devpedrotavares** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
