### PR TITLE
LPD-16080 Return early to only call executeBatch if at least one batch's been added, to avoid exception when using HSQL

### PR DESCRIPTION
**Pull request by devpedrotavares**
Related ticket: [LPD-16080](https://liferay.atlassian.net/browse/LPD-16080)

### CODE REVIEW

**Review by G-Sa — APPROVED** [review]

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:report:2541306963

**Comment by carolmariaabb** [comment]
ci:report:2541298909

**Comment by devpedrotavares** [comment]
ci:forward:force

**Comment by devpedrotavares** [comment]
ci:forward:force

**Pull request closed without merging**
