### PR TITLE
LPS-194434 Create DuplicateExternalReferenceCodeExceptionMapper

### PR DESCRIPTION
**Pull request by murilostodolni**
Related Issues:
https://liferay.atlassian.net/browse/LPS-193944
https://liferay.atlassian.net/browse/LPS-194434

cc: @Artartur

### CODE REVIEW

**Review by seltong — APPROVED** [review]
LGTM! :tada:

**Comment by marcelabc** [comment]
Hey @carolmariaabb 
Could you review this PR, please? :smile:

**Review by carolmariaabb — APPROVED** [review]
Hey @murilostodolni, this PR LGTM, but it would be good to ask the Headless team for a review!

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
ci:test:object

**Comment by murilostodolni** [comment]
Headless team approved [here](https://liferay.slack.com/archives/C032VGYA2UD/p1696516608362569).

**Comment by murilostodolni** [comment]
ci:test:stable

**Comment by murilostodolni** [comment]
ci:test:stable

**Comment by murilostodolni** [comment]
ci:forward:force

**Pull request closed without merging**
