### PR TITLE
LPS-137442 Save and retrieve optionReference for fields with options

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-137442

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:reevaluate:1307401_194

**Comment by mateussgn** [comment]
I'm already verifying what had caused the failures.

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
Waiting for https://github.com/liferay-frontend/liferay-portal/pull/1441 be merged to run the tests again.

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:forward

**Pull request closed without merging**
