### PR TITLE
LPS-191310 Call runSQL method that takes a connection reference. Because the method without it would not complete the query

### PR DESCRIPTION
**Pull request by devpedrotavares**
Related ticket: [LPS-191310](https://liferay.atlassian.net/browse/LPS-191310)

### CODE REVIEW

**Comment by devpedrotavares** [comment]
ci:test:relevant

**Review by murilostodolni — APPROVED** [review]
LGTM! Great job @devpedrotavares 

We need to send this PR to @liferay-core-infra after @marcelabc's review.

**Review by marcelabc — APPROVED** [review]
LGTM 🎉
Great job! Congrats :smile:

**Comment by devpedrotavares** [comment]
Sent to liferay-core-infra: https://github.com/liferay-core-infra/liferay-portal/pull/5127

**Pull request closed without merging**
