### PR TITLE
LPD-34312

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://liferay.atlassian.net/browse/LPD-34312

### CODE REVIEW

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
The test is now passing:

image

image

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
