### PR TITLE
[TS] LPD-22030 Add the objectField's label value to the site default locales if it's missing and the object definition default locale is not the same

### PR DESCRIPTION
**Pull request by evibudai**
Hi Team,
https://liferay.atlassian.net/browse/LPD-22030

Issue:
Object definition JSON import fails when it has different labels of different language than the instance’s default locale.
For example: when the JSON has labels in German and the instance we are importing to has English as the default language and the default locale is English.

Solution:
I made a tentative for a fix but following our discussion with @carolmariaabb she provided a different approach "the solution should be in the resource layer instead of changing the service layer".

I tested in my local environment and following the fix, the Object definition import was successful.

Please review my PR!

Thank you and best regards,
Évi

### CODE REVIEW

**Review by G-Sa — APPROVED** [review]
LGTM :tada:

**Comment by G-Sa** [comment]
ci:foward

**Comment by G-Sa** [comment]
Hi @evibudai i discussed with @carolmariaabb and we are fowarding this to Brian, feel free to generate the Hotfix to the client since this is an SDH

**Comment by G-Sa** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
