### PR TITLE
LPS-158025 Update json column type to CLOB

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant - Failed due to [Testray Outage](https://liferay.slack.com/archives/C19PWQ74J/p1660253108886939).

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Pull request closed without merging**
