### PR TITLE
LPS-199346 Remove FF - LPS-167253 from poshi tests

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPS-199346](https://liferay.atlassian.net/browse/LPS-199346)

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Comment by pedro-oliveira446** [comment]
ci:forward

**Pull request closed without merging**
