### PR TITLE
LPS-191851 Move the FF of Unique Composed Keys to Release type

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPS-191851

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Hey @p-albuquerque ,
Since you are a member of the BPM team, you are expected to assign someone from the team as the reviewer.
Assigning the reviewer is a way to organize our line and make the review process agile.
If you don't know who to assign, please talk with @guilhermedcamacho .

**Comment by p-albuquerque** [comment]
Hi @marcelabc 
Sorry for the delay. I would like to confirm that there isn't a different process for this type of PR since the content of it has no "technical" changes, it is only to give a title and a description for the FF, both contents defined from the Product crew. For this reason, I'm looking for some clarification about how to conduct this one: if like any regular PR, or different treatment.

**Comment by marcelabc** [comment]
I would say to you to treat any PR that you create as a regular one.

However, there are cases that the PR is "High Priority". Then, you must align with Camacho if the PR can wait the 2 rounds of review process or should follow the regular process.

Thanks!

**Review by pedro-oliveira446 — APPROVED** [review]

**Review by guilhermedcamacho — APPROVED** [review]

**Comment by guilhermedcamacho** [comment]
ci:forward:force

**Pull request closed without merging**
