### PR TITLE
LPS-183792 Adapt integration tests

### PR DESCRIPTION
**Pull request by seltong**
Follow-up: https://github.com/liferay-objects/liferay-portal/pull/2116

Related issue: [LPS-183792](https://issues.liferay.com/browse/LPS-183792)

### CODE REVIEW

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:object

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by seltong** [comment]
Hi, @carolmariaabb. The ci failures seems unrelated, can we open a QA Request for this PR?

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
