### PR TITLE
LPS-193361 Object Relationship as system

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://liferay.atlassian.net/browse/LPS-193361

### CODE REVIEW

**Comment by marcelabc** [comment]
cc: @gabrielwas @G-Sa

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:object

**Comment by victorhcunha** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:object

**Comment by victorhcunha** [comment]
ci:test:object

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by G-Sa** [comment]
ci:test:relevant

**Comment by victorhcunha** [comment]
ci:test:object

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:object

**Comment by marcelabc** [comment]
ci:reevaluate:1257401_3515

**Comment by victorhcunha** [comment]
ci:reevaluate:1257401_3515

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:forward:force

**Comment by marcelabc** [comment]
Rebase error with Brian's branch.
Resend here: https://github.com/liferay-objects/liferay-portal/pull/2634

**Pull request closed without merging**
