### PR TITLE
LPS-179030 Custom Object doesn't save when changing the default language

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPS-179030](https://issues.liferay.com/browse/LPS-179030)

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Comment by marcelabc** [comment]
Just started reviewing :)

**Review by marcelabc — APPROVED** [review]
LGTM 🎉
Sorry about the delay in reviewing this PR :disappointed: 
Feel free to reach me next time to remember anything!

**Comment by marcelabc** [comment]
ci:test:relevant

**Pull request closed without merging**
