### PR TITLE
LPD-33424 Fix playwright test covering use of reactivated object in page item selector

### PR DESCRIPTION
**Pull request by igor-franca**
related [ticket](https://liferay.atlassian.net/browse/LPD-33424)

### CODE REVIEW

**Comment by igor-franca** [comment]
ci:test:playwright

**Comment by igor-franca** [comment]
With this fix, from now on all object playwright tests are showing successful results in CI 🕺🏾✅

**Review by cgmonte — APPROVED** [review]
LGTM!

**Comment by igor-franca** [comment]
ci:forward

**Pull request closed without merging**
