### PR TITLE
LPS-140522 Add ThreadLocal to skip relationship permission

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-140522

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Hi @mateussgn, we have some conflicts in this branch. Could you please take a look? Thanks :)

**Comment by samuelromeiro** [comment]
Hey @mateussgn, I'm closing this PR, since it has conflicts. Can you resend it, please?

**Pull request closed without merging**
