### PR TITLE
LPS-195698 Create validation in the service layer to disallow add, delete and edit

### PR DESCRIPTION
**Pull request by guilhermedcamacho**
[LPS-193364](https://liferay.atlassian.net/browse/LPS-193364)

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:object

**Comment by pedro-oliveira446** [comment]
Resent [here](https://github.com/liferay-objects/liferay-portal/pull/2589)

**Pull request closed without merging**
