### PR TITLE
LPS-167253

### PR DESCRIPTION
**Pull request by marco-leo**
https://issues.liferay.com/browse/LPS-167253

### CODE REVIEW

**Comment by marco-leo** [comment]
ci:test:sf

**Comment by marco-leo** [comment]
ci:test:sf

**Comment by marco-leo** [comment]
ci:test:sf

**Comment by marco-leo** [comment]
ci:test:stable

**Comment by seltong** [comment]
I added a commit [here](https://github.com/seltong/liferay-portal/pull/166) removing unnecessary properties in the .json file

**Comment by marco-leo** [comment]
ci:test:sf

**Comment by marco-leo** [comment]
ci:test:stable

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:test:object

**Comment by seltong** [comment]
Resent here: https://github.com/liferay-objects/liferay-portal/pull/2013

**Pull request closed without merging**
