### PR TITLE
LPS-173109 Fix relationship custom to system in new virtual instance

### PR DESCRIPTION
**Pull request by murilostodolni**
Related: https://issues.liferay.com/browse/LPS-173109

### CODE REVIEW

**Review by carolmariaabb — APPROVED** [review]
LGTM! 

But it would be nice to show this change to the team. It's a significant change.

**Comment by murilostodolni** [comment]
Yes, i agree! I'll wait for result the revelant and object. After i'll show the change to the team. Thanks @carolmariaabb 😄

**Comment by murilostodolni** [comment]
Force push to solve the conflicts.

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
ci:test:object

**Comment by murilostodolni** [comment]
Push force to solve the conflicts.

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
ci:close

**Comment by murilostodolni** [comment]
Force push to solve conflicts.

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
ci:test:object

**Comment by murilostodolni** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by murilostodolni** [comment]
Not sure, but test `com.liferay.object.rest.internal.manager.v1_0.test.DefaultObjectEntryManagerImplTest > testGetObjectEntries` can be related with this changes. I'm investigating...

**Comment by murilostodolni** [comment]
The test `com.liferay.object.rest.internal.manager.v1_0.test.DefaultObjectEntryManagerImplTest > testGetObjectEntries` is flaky. I tested locally and the fail not reproduced. Also, in the Objects suite the test passed [here](https://testray.liferay.com/home/-/testray/case_results/2199467846?tab=history).

**Comment by murilostodolni** [comment]
Investigating the poshi tests that broke. Some tests are related with this changes. The force push is to solve this errors.

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
Force push to solve more tests poshi.

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
ci:test:object

**Comment by murilostodolni** [comment]
ci:stop

**Comment by murilostodolni** [comment]
ci:test:object

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
Fails related with this changes:

[ObjectActions#VerifyTheConditionCardAreHidden](https://testray.liferay.com/home/-/testray/case_results/2200887566?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2200882046%26testrayRunId%3D2200882187%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
[ObjectActions#CanCreateActionUsingGroovyScripWithOnOrderStatusUpdate](https://testray.liferay.com/home/-/testray/case_results/2200886504?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2200882046%26testrayRunId%3D2200882187%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
[ObjectActions#CanCreateActionNotificationWithOnOrderStatusUpdate](https://testray.liferay.com/home/-/testray/case_results/2200887106?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2200882046%26testrayRunId%3D2200882187%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
[ObjectActions#CanCreateActionAddObjectEntryWithOnOrderStatusUpdate](https://testray.liferay.com/home/-/testray/case_results/2200885094?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2200882046%26testrayRunId%3D2200882187%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

**Comment by murilostodolni** [comment]
QA CI Reject [here](https://liferay.slack.com/archives/C048YNC5GRK/p1677158607502209?thread_ts=1675860704.416849&cid=C048YNC5GRK)

**Comment by murilostodolni** [comment]
ci:close

**Pull request closed without merging**
