### PR TITLE
LPS-144895 Integration tests

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:reevaluate:1287401_1502

**Comment by mateussgn** [comment]
Hey @gabrielwas, can I run the CI again? Or are you planning to update this PR, because had conflicts?

**Comment by gabrielwas** [comment]
@mateussgn I'll check it. Thanks :)

**Pull request closed without merging**
