### PR TITLE
LPS-197463 Show the hidden objectDefiniton2 when creating the relationship in model builder

### PR DESCRIPTION
**Pull request by igor-franca**
Related Issue: https://liferay.atlassian.net/browse/LPS-197463

### CODE REVIEW

**Comment by igor-franca** [comment]
Hey @rebsilva, can you check my comments here and see if you agree with the changes made?

**Review by rebsilva — APPROVED** [review]
LGTM! :tada:

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:object

**Comment by igor-franca** [comment]
Checking test results

**Comment by igor-franca** [comment]
We have many broken tests because a locator was changed in another [PR](https://github.com/brianchandotcom/liferay-portal/pull/146277).
I'd rather wait for this PR to revert so I can run the tests again.

**Comment by samuelromeiro** [comment]
PR https://github.com/brianchandotcom/liferay-portal/pull/146278 merged. 
Can you take a look @igor-franca?

**Comment by igor-franca** [comment]
ci:test:relevant

**Comment by igor-franca** [comment]
ci:test:object

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
I performed a rebase with the master to obtain a locator correction for some tests. I will run the tests again, as many failures were related to this locator.

**Comment by igor-franca** [comment]
ci:test:object

**Comment by igor-franca** [comment]
ci:test:relevant

**Comment by igor-franca** [comment]
Upon reviewing the issues in this pull request, I observed several concerns, particularly with //a and //span locators, which are currently in the process of being addressed.

I conducted thorough manual tests to assess the functionality of the introduced features. Additionally, I successfully executed all model builder tests.

In light of these evaluations, I am inclined to proceed with advancing this PR, under the assumption that the aforementioned locators remain unaltered in the context of the current pull request.

**Comment by igor-franca** [comment]
ci:forward:force

**Comment by igor-franca** [comment]
ci:forward:force

**Pull request closed without merging**
