### PR TITLE
LPS-178211 Use new termName key on clipboard function

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-178211

### CODE REVIEW

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
@danvb112 SF failure, please take a look.

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:forward

**Pull request closed without merging**
