### PR TITLE
[TECHNICAL SUPPORT] LPS-155103 Identifying upload as a object field

### PR DESCRIPTION
**Pull request by rijema**
Click [here](https://issues.liferay.com/browse/LPS-155103) to see the LPS

### CODE REVIEW

**Comment by rijema** [comment]
ci:test:relevant

**Comment by rijema** [comment]
ci:reevaluate:1267401_3328

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:forward

**Pull request closed without merging**
