### PR TITLE
LPS-202602 Unclear error message when creating same relationship name

### PR DESCRIPTION
**Pull request by davisaints**
**JIRA Ticket: [LPS-202602](https://liferay.atlassian.net/browse/LPS-202602)**

## Proposed solution:
Proposed_solution

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by davisaints** [comment]
ci:test:object

**Comment by davisaints** [comment]
Related failures:
* [com.liferay.object.service.test.ObjectRelationshipLocalServiceTest](https://testray.liferay.com/home/-/testray/case_results/2467248025)
* [CreateObject#CannotCreateDuplicatedRelationshipName](https://testray.liferay.com/home/-/testray/case_results/2467249304)

@carolmariaabb I'm fixing these tests

**Comment by carolmariaabb** [comment]
@davisaints please see https://github.com/liferay-objects/liferay-portal/pull/2900

**Pull request closed without merging**
