### PR TITLE
LPD-8485 / LPD-8486 / LPD-8487 Remove unused Reference

### PR DESCRIPTION
**Pull request by diogomelo09**
[LPD-8485](https://liferay.atlassian.net/browse/LPD-8485) / [LPD-8486](https://liferay.atlassian.net/browse/LPD-8486) / [LPD-8487](https://liferay.atlassian.net/browse/LPD-8487)

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Comment by pedro-oliveira446** [comment]
These references have been placed on purpose, let's analyze to see if we can remove them.

https://github.com/brianchandotcom/liferay-portal/pull/119404/commits/ff80296df73e3e6246f1f881cb8656b9d046948e
https://github.com/liferay-headless/liferay-portal/pull/1268/commits/6d5e1d8490c13b3f79e92a8e84a5aa12f4c9e9df

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:headless

**Comment by guilhermedcamacho** [comment]
Hey @pedro-oliveira446, I took a look at the commits and there is no indication that they were added for other reasons (as a workaround). Let's analyze the CI results and then we can make a decision. Thanks!

**Comment by guilhermedcamacho** [comment]
ci:report:2535362247

**Comment by guilhermedcamacho** [comment]
ci:report:2535369155

**Comment by guilhermedcamacho** [comment]
ci:report:2535509082

**Comment by guilhermedcamacho** [comment]
ci:test:object

**Comment by guilhermedcamacho** [comment]
ci:test:headless

**Comment by guilhermedcamacho** [comment]
ci:test:playwright

**Comment by guilhermedcamacho** [comment]
See #3146

**Pull request closed without merging**
