### PR TITLE
LPS-191280 - Adapt the code to show multiple validations Alerts

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://liferay.atlassian.net/browse/LPS-191280

### CODE REVIEW

**Review by naraandrade — CHANGES_REQUESTED** [review]
@danvb112 LGTM! Just left a little suggestion :)

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Review by naraandrade — APPROVED** [review]

**Comment by danvb112** [comment]
Sent to: https://github.com/brianchandotcom/liferay-portal/pull/138467

**Pull request closed without merging**
