### PR TITLE
LPS-162085 baseline

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://issues.liferay.com/browse/LPS-162085

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:forward

**Comment by gabrielwas** [comment]
ci:reevaluate:1287401_4488

**Comment by gabrielwas** [comment]
@marcelabc can you focus on this PR, please?

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
@marcelabc We have som conflicts in this branch :/

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:forward

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
@marcelabc Could you please check if the failures are related? Thanks :)

**Comment by marcelabc** [comment]
ci:forward

**Comment by marcelabc** [comment]
Send directly: https://github.com/brianchandotcom/liferay-portal/pull/123700

**Pull request closed without merging**
