### PR TITLE
LPS-166722 update object entry if it existis

### PR DESCRIPTION
**Pull request by linolaoj**
Related issue: https://issues.liferay.com/browse/LPS-166722

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:forward

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
@linolaoj Feel free to send this PR directly to Brian.. The failure is not related to your changes. Thanks!

**Comment by linolaoj** [comment]
pull request sent here https://github.com/brianchandotcom/liferay-portal/pull/126966

**Pull request closed without merging**
