### PR TITLE
LPS-158960 InfoListRenderer should get custom object fields

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-158960

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:test:relevant

**Review by gabrielwas — APPROVED** [review]

**Comment by timpak** [comment]
ci:test:object

**Comment by timpak** [comment]
Hey @mateussgn and @gabrielwas,
I tested the fix locally and got a NPE after adding the Object to the Collection Display. See my [comment on the ticket](https://issues.liferay.com/browse/LPS-158960?focusedCommentId=2729071&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2729071) with more details.

**Comment by mateussgn** [comment]
Hey @timpak , I've tested removing the fix commits locally, and this exception is still thrown.

I believe this is another bug. If you could, please open another ticket for this new one.

**Comment by mateussgn** [comment]
ci:close

**Comment by mateussgn** [comment]
I closed it because is already on master.

**Pull request closed without merging**
