### PR TITLE
LPS-199095 Prevent modifiable system object definitions from being used in Form Container using permissions instead of providing an incomplete IF implementation

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPS-199095

Hi Team :hand: 
Yesterday we found [this bug](https://liferay.atlassian.net/browse/LPS-199081) caused by [this commit](https://github.com/liferay-echo/liferay-portal/commit/1e76b332bca37fe8fb9b4d17e1f5ec838d36edc7).
It has been solved from our components in a simple way ([related PR](https://github.com/liferay-echo/liferay-portal/pull/14003/files)), but we are worried that it will cause other problems.
That is why I come to propose an alternative implementation that I have verified achieves the same objective and is more secure and aligned with the Info Framework.
Please could you take it into consideration?
Thank you so much!
Regards

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:test:stable

**Comment by lfbesada** [comment]
ci:test:stable

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
@lfbesada Please feel free to send this PR directly to Brian if necessary. Thanks!

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/142528

**Pull request closed without merging**
