### PR TITLE
LPS-159525 Make Predefined Values table a FDS

### PR DESCRIPTION
**Pull request by rebsilva**
Related Issue: https://issues.liferay.com/browse/LPS-159525

### CODE REVIEW

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Review by alinedoleron — APPROVED** [review]
Amazing job, @rebsilva!! :star_struck:

**Comment by alinedoleron** [comment]
ci:forward

**Pull request closed without merging**
