### PR TITLE
LPS-194846 Create new UniqueCompositeKeyObjectValidationRuleEngineImpl

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://liferay.atlassian.net/browse/LPS-194846

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:object

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:object

**Comment by mateussgn** [comment]
ci:stop

**Comment by guilhermedcamacho** [comment]
ci:stop

**Comment by mateussgn** [comment]
ci:stop

**Review by guilhermedcamacho — APPROVED** [review]

**Comment by JhossephG** [comment]
ci:test:object

**Comment by JhossephG** [comment]
ci:test:relevant

**Comment by JhossephG** [comment]
Only missing run the baseline on the mentioned modules in the Slack thread

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:object

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:object

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:forward:force

**Comment by mateussgn** [comment]
ci:forward:force

**Comment by mateussgn** [comment]
ci:forward:force

**Pull request closed without merging**
