### PR TITLE
LPS-199155 Users are taking time to load in the relationship tab

### PR DESCRIPTION
**Pull request by guilhermedcamacho**
Related issue: [LPS-199155](https://liferay.atlassian.net/browse/LPS-199155)
LPP ticket: [LPP-50857](https://liferay.atlassian.net/browse/LPP-50857)

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:object

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by JhossephG** [comment]
ci:test:object

**Comment by guilhermedcamacho** [comment]
Hey @Marina-Gouveia, I think I found a bug when we have more than two pages, the third page is not showing the right entries. Can you check that?

**Comment by Marina-Gouveia** [comment]
see (https://github.com/liferay-objects/liferay-portal/pull/2780)

**Pull request closed without merging**
