### PR TITLE
LPS-205137 Create Upgrade Step for long length in DB

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPS-205137](https://liferay.atlassian.net/browse/LPS-205137)

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:object

**Review by MarinhoFeliphe — CHANGES_REQUESTED** [review]
hey @pedro-oliveira446 in order to merge this pr the backport needs to be merged, otherwise we cannot make sure that those version are the right one you should define as a dummy.

Thank you!

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:upgrade

**Comment by pedro-oliveira446** [comment]
Hey @MarinhoFeliphe,
This PR isn't blocked anymore. Can you review it, please ?
I made this changes based on this branches : [Q3](https://github.com/liferay/liferay-portal-ee/blob/release-2023.q3/modules/apps/object/object-service/src/main/java/com/liferay/object/internal/upgrade/registry/ObjectServiceUpgradeStepRegistrator.java) and [Q4](https://github.com/liferay/liferay-portal-ee/blob/release-2023.q4/modules/apps/object/object-service/src/main/java/com/liferay/object/internal/upgrade/registry/ObjectServiceUpgradeStepRegistrator.java)

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM!! :tada:

**Comment by pedro-oliveira446** [comment]
Resent here : https://github.com/brianchandotcom/liferay-portal/pull/146342

**Pull request closed without merging**
