### PR TITLE
LPS 190083

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
-----
As part of integration of proxy objects with Content Pages adds supports to Contend Display fragment

Proposed solution
-----
Update **ObjectEntryRowInfoItemRenderer** to supports proxy objects and service builder objects.

Also modify necessary classes on content pages to supports selecting and rendering proxy objects into content display fragment, that means adds supports for ExternalReferenceCode.

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:reevaluate:1257401_1834

**Comment by ealonso** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
