### PR TITLE
LPS-170700 For each entry make sure that the user has the proper account role and permission to VIEW othis entry

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**
**WIP**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:object

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by timpak** [comment]
ci:test:object

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by timpak** [comment]
ci:test:object

**Comment by timpak** [comment]
ci:test:object:norebase

**Comment by timpak** [comment]
ci:test:object

**Comment by timpak** [comment]
ci:test:object:norebase

**Comment by timpak** [comment]
ci:test:object

**Comment by MarinhoFeliphe** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/128187

**Pull request closed without merging**
