### PR TITLE
LPS-184361 Is not possible delete a Object inactive that have a entry added

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPS-184361](https://issues.liferay.com/browse/LPS-184361)

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
