### PR TITLE
LPS-198535

### PR DESCRIPTION
**Pull request by carolmariaabb**
Follow-up: https://github.com/liferay-objects/liferay-portal/pull/2701

Related Issue: https://liferay.atlassian.net/browse/LPS-198535

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:object

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
