### PR TITLE
[Technical debt] LPS-171817 Fix some localization issues of Relationships, Layouts and Notifications Templates

### PR DESCRIPTION
**Pull request by igor-franca**
[Related](https://issues.liferay.com/browse/LPS-171816)

### CODE REVIEW

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:test:object

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by igor-franca** [comment]
ci

**Comment by igor-franca** [comment]
resent [here](https://github.com/brianchandotcom/liferay-portal/pull/129134)

**Pull request closed without merging**
