### PR TITLE
LPS-166129 Remove feature flag for LPS-158672

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://issues.liferay.com/browse/LPS-166129

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:reevaluate:1377401_5767

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:reevaluate:1327401_6293

**Comment by carolmariaabb** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/124984

**Pull request closed without merging**
