### PR TITLE
LPS-172063 Create ModalImportWarning component instead of use the openModal function

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-172063

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:object

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Comment by danvb112** [comment]
ci:forward

**Comment by danvb112** [comment]
Sent to: https://github.com/brianchandotcom/liferay-portal/pull/128863

**Pull request closed without merging**
