### PR TITLE
LPS-164176 Use Autocomplete component instead of Select for Picklist fields in Modal to add a field

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-164176

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Review by naraandrade — APPROVED** [review]

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
@danvb112 I think maybe this test [LocalFile.ObjectPortlet#CanAddEntryWithoutSelectingPicklist](https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/200638//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ObjectPortlet_CanAddEntryWithoutSelectingPicklist_) could be related with your changes. Could you take a look at it? Thanks :)

**Comment by anabuchmann** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
@danvb112 @anabuchmann were you able to analyse if the failures are related to the PR?

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:reevaluate:1397401_1301

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by danvb112** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
@danvb112 I've seen the same [failures](https://github.com/liferay-objects/liferay-portal/pull/1125#issuecomment-1293404034) in other PRs. 

Feel free to manually forward this PR to Brian

**Comment by danvb112** [comment]
Sent to: https://github.com/brianchandotcom/liferay-portal/pull/125399

**Pull request closed without merging**
