### PR TITLE
LPS-164020

### PR DESCRIPTION
**Pull request by alinedoleron**
Tickets:
https://issues.liferay.com/browse/LPS-164022
https://issues.liferay.com/browse/LPS-164020
https://issues.liferay.com/browse/LPS-164021

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:forward

**Comment by alinedoleron** [comment]
ci:forward

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
The current code will be sent into this https://github.com/liferay-objects/liferay-portal/pull/1179

**Pull request closed without merging**
