### PR TITLE
LPD-16420 [Must Add] [P3] Automate LPP-49119

### PR DESCRIPTION
**Pull request by diogomelo09**
[LPD-16420](https://liferay.atlassian.net/browse/LPD-16420)

### CODE REVIEW

**Review by thallescezar — APPROVED** [review]
LGTM!

**Comment by linolaoj** [comment]
LGTM

**Review by linolaoj — APPROVED** [review]

**Comment by linolaoj** [comment]
ci:test:forward

**Comment by linolaoj** [comment]
ci:forward

**Comment by linolaoj** [comment]
ci:forward:force

**Pull request closed without merging**
