### PR TITLE
LPD-34176

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:object

**Review by guilhermedcamacho — APPROVED** [review]

**Comment by gabrielwas** [comment]
Failures not related

**Comment by gabrielwas** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/153763

**Comment by brittneyq** [comment]
ci:reevaluate:1277401_12454

**Pull request closed without merging**
