### PR TITLE
LPS-191688 Enhance ObjectEntryManager tests. Create tests to supported filter expressions for Salesforce Objects

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPS-191688

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Review by mateussgn — APPROVED** [review]
LGTM! 🎉

**Comment by mateussgn** [comment]
Hey @guilhermedcamacho, could you please double-check this PR?

**Comment by guilhermedcamacho** [comment]
See #2490

**Pull request closed without merging**
