### PR TITLE
LPS-174356 Button to delete (Trash icon) fields on the Action card not works

### PR DESCRIPTION
**Pull request by kiwm**
Related issue: https://issues.liferay.com/browse/LPS-174356

### CODE REVIEW

**Comment by kiwm** [comment]
ci:test:relevant

**Comment by kiwm** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — CHANGES_REQUESTED** [review]
Hi @kiwm, this isn't the ideal solution because labels are not unique but names are, so we should base the addition and removal of fields on their names. You can fix the bug described in the ticket by just adding the name information inside `predefinedValues`. You can do so adding the name property like below, in the useMemo that defines `items` values:

```
label: (
	<div className="lfr-object-web__predefined-values-table-field">
		{getLocalizableLabel(creationLanguageId, label, name)}

		{objectFieldsMap.get(name)?.required === true && (
			<span className="lfr-object-web__predefined-values-table-reference-mark">
				<ClayIcon symbol="asterisk" />
			</span>
		)}
	</div>
),

name,

newValue: (
	<div ...
```

Remember to also update the `Item` interface to accept the `name` property as a `string` instead of `JSX.Element`.

**Comment by naraandrade** [comment]
I'm going to close this PR for now. Please, send a new one with the requested changes. Thanks!

**Pull request closed without merging**
