### PR TITLE
LPS-140233 Remove objectEntries that have any relationship from list

### PR DESCRIPTION
**Pull request by danvb112**
RElated Issue: https://issues.liferay.com/browse/LPS-140233

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
@danvb112 @mateussgn hey guys... we have a PR from Marcela that will change the behavior of getting entries in the Item Selector. As soon as this PR gets in, we can review it, ok?

Thx :D

**Comment by danvb112** [comment]
Ok, Thanks @gabrielwas! :smile:

**Comment by mateussgn** [comment]
Alright!! @marcelabc told me about it. That's why I didn't take a look at this one here.
Thanks @gabrielwas !!

**Comment by marcelabc** [comment]
This ticket will be fixed by https://github.com/liferay-objects/liferay-portal/pull/547.

**Pull request closed without merging**
