### PR TITLE
LPS-136451 Not necessary to make object field's name lower case

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-136451

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
LGTM :D

**Comment by gabrielwas** [comment]
ci:forward

**Pull request closed without merging**
