### PR TITLE
LPS-203975 Add Move and Export features to Model Builder

### PR DESCRIPTION
**Pull request by rebsilva**
Related Issue: https://liferay.atlassian.net/browse/LPS-203975

Resent from https://github.com/liferay-objects/liferay-portal/pull/3032 and already reviewed

### CODE REVIEW

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:object

**Comment by rebsilva** [comment]
ci:test:object

**Comment by rebsilva** [comment]
i've tested and everything seems fine, just waiting for the ci results now

**Comment by rebsilva** [comment]
waiting for this PR https://github.com/liferay-objects/liferay-portal/pull/3045 to enter so i can run the tests again

**Comment by samuelromeiro** [comment]
The https://github.com/liferay-objects/liferay-portal/pull/3045 is merged. 
Can you take a look at this PR, @rebsilva?

**Comment by rebsilva** [comment]
sure, taking a look now @samuelromeiro! :cherry_blossom:

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:object

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:object

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:object

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by igor-franca** [comment]
ci:test:object

**Comment by igor-franca** [comment]
ci:test:object

**Comment by igor-franca** [comment]
After analyzing the relevant tests through comparison with the test routine and history, I cannot see any new test failures caused by these changes.

However, we have dozens of object tests that fail due to:
It failed before running the test, so I'm choosing to run the tests again.

**Comment by rebsilva** [comment]
running tests again after testray has been fixed :game_die:

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:object

**Comment by rebsilva** [comment]
ci:test:stable

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
since the ci is very unstable due [this problem](https://liferay.slack.com/archives/C19PWQ74J/p1706117450543409) and the changes don't seem related, i will follow @gabrielwas recommendation to forward the PR as long as the stable is not failing

**Comment by rebsilva** [comment]
ci:forward:force

**Pull request closed without merging**
