### PR TITLE
LPS-173059 Test Integration

### PR DESCRIPTION
**Pull request by murilostodolni**
Related: https://issues.liferay.com/browse/LPS-173059

### CODE REVIEW

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
Force push to baseline

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
Force push to solve the conflicts.

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
Force push to add feature flag to solve the ci error.

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
ci:test:object

**Comment by murilostodolni** [comment]
Forwarding manually: https://github.com/brianchandotcom/liferay-portal/pull/130282

**Comment by murilostodolni** [comment]
ci:close

**Pull request closed without merging**
