### PR TITLE
LPD-30995 Ensure that the list of notification terms and freeMarker variables is being rendered completely

### PR DESCRIPTION
**Pull request by igor-franca**
Related Tickets:

[LPD-30999](https://liferay.atlassian.net/browse/LPD-30999)
[LPD-30995](https://liferay.atlassian.net/browse/LPD-30995)

[LPD-30999]: https://liferay.atlassian.net/browse/LPD-30999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LPD-30995]: https://liferay.atlassian.net/browse/LPD-30995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by igor-franca** [comment]
ci:test:playwright

**Review by cgmonte — APPROVED** [review]
LGTM!

**Comment by cgmonte** [comment]
Hey @igor-franca forget to comment on the PR approval: your commit is not verified.

**Comment by igor-franca** [comment]
The next push seeks to rebase with liferay-portal, removing existing commits from Brian's branch to avoid the SF error:

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
ci:forward

**Comment by igor-franca** [comment]
ci:reopen

**Pull request closed without merging**
