### PR TITLE
LPS-172147 Move declaration of REQUIRED_MSG to costants.ts and call it in all needed places

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-172391

### CODE REVIEW

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by danvb112** [comment]
ci:test:relevant

**Review by naraandrade — APPROVED** [review]

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:forward

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:forward

**Comment by danvb112** [comment]
ci:forward

**Comment by Luizcarlosqueiroz** [comment]
ci:test:object

**Comment by danvb112** [comment]
Sent to: https://github.com/brianchandotcom/liferay-portal/pull/129165

**Pull request closed without merging**
