### PR TITLE
LPS-148845 Permit to view entries with Author column on Default Sort

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-148845

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
@mateussgn can we try to use the "creator" string as it is instead of modifying portal-kernel? Just putting the literal string there?

**Comment by mateussgn** [comment]
Sure!
Thanks for the tip!

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:forward

**Pull request closed without merging**
