### PR TITLE
LPS-176584 Adapt Structures of NotificationTemplateTerms to new GeneralTerms Component

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPS-176584

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:stop

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Review by MarinhoFeliphe — APPROVED** [review]

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:object

**Comment by JhossephG** [comment]
Sorry the lot of modifies at the labels, I thought that a behavior are a bug but in a conversation with the dev was said that this behavior are expected

**Comment by p-albuquerque** [comment]
Direct sent: https://github.com/brianchandotcom/liferay-portal/pull/131276

**Pull request closed without merging**
