### PR TITLE
LPS-179577 Modify TYPES return on deletion function on ObjectLayoutBox file

### PR DESCRIPTION
**Pull request by vngoliveira**
Related issue [LPS-179577](https://issues.liferay.com/browse/LPS-179577)

### CODE REVIEW

**Review by danvb112 — APPROVED** [review]
LGTM! :tada: 

Good job on this Issue @vngoliveira!

**Comment by danvb112** [comment]
ci:forward

**Comment by danvb112** [comment]
ci:forward

**Comment by sirfabios** [comment]
Hi @vngoliveira 
Single flaw in this PR, in the daily routine are passing:
CreateObject#CanCreateManyToManyRelationship
ObjectRelationships#CanCreateObjectWithRelationshipParameter
ObjectRelationships#CannotRelateAnEntryWithItself
CreateObject#RelationshipFieldAutomaticallyCreated
ObjectRelationships#CanCreateOneToManyForNativeObject

The other tests were already failing.

**Comment by vngoliveira** [comment]
Sent to Brian Chan: [liferay-portal-pull 132994](https://github.com/brianchandotcom/liferay-portal/pull/132994)

**Pull request closed without merging**
