### PR TITLE
LPS-164952 Prevent the Formula field from being used in the predefined values ​​table and as a Default Sort in View

### PR DESCRIPTION
**Pull request by danvb112**
Related Issues: 
https://issues.liferay.com/browse/LPS-164952
https://issues.liferay.com/browse/LPS-164954

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:relevant

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by danvb112** [comment]
ci:forward

**Comment by danvb112** [comment]
ci:forward

**Pull request closed without merging**
