### PR TITLE
LPS-156969

### PR DESCRIPTION
**Pull request by alinedoleron**
This PR implements the changes requested by @danvb112 on [PR-1014](https://github.com/liferay-objects/liferay-portal/pull/1014)

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:relevant

**Review by danvb112 — APPROVED** [review]
LGTM! Thank you for doing this @alinedoleron!  :tada:

**Comment by danvb112** [comment]
ci:forward

**Comment by danvb112** [comment]
ci:forward

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/123276

**Pull request closed without merging**
