### PR TITLE
LPD-16413 Adding new test scenario to cover onAfterUpdate action with attachment object fields

### PR DESCRIPTION
**Pull request by thallescezar**
Related issue: https://liferay.atlassian.net/browse/LPD-23329

### CODE REVIEW

**Comment by thallescezar** [comment]
ci:test:sf

**Comment by thallescezar** [comment]
ci:test:sf

**Comment by thallescezar** [comment]
ci:forward

**Comment by linolaoj** [comment]
ci:forward:force

**Comment by gabrielwas** [comment]
resent https://github.com/liferay-objects/liferay-portal/pull/3310

**Pull request closed without merging**
