### PR TITLE
LPS-197755 Throw the exception cause of ModelListenerException so that it is treated properly

### PR DESCRIPTION
**Pull request by devpedrotavares**
Related ticket: [LPS-197755](https://liferay.atlassian.net/browse/LPS-197755)

### CODE REVIEW

**Review by murilostodolni — APPROVED** [review]
LGTM!

I believe we will need send this PR to USM team.

**Review by carolmariaabb — APPROVED** [review]
Hi @devpedrotavares and @murilostodolni,

The USM team no longer exists. I'm not sure which repository we need to send this PR. We can ask in the `#t-user-management` channel.

**Comment by devpedrotavares** [comment]
> Hi @devpedrotavares and @murilostodolni,
> 
> The USM team no longer exists. I'm not sure which repository we need to send this PR. We can ask in the `#t-user-management` channel.

Thanks, I asked [here](https://liferay.slack.com/archives/CNUCYF7EW/p1697046287659869)

**Comment by devpedrotavares** [comment]
Waiting for clarification on the expected behavior on the [thread](https://liferay.slack.com/archives/C026UR5976G/p1697230213090219)

**Comment by devpedrotavares** [comment]
Sent to commerce: https://github.com/liferay-commerce/liferay-portal/pull/4337

**Pull request closed without merging**
