### PR TITLE
LPS-170656 External reference code is not validated before creating an entry

### PR DESCRIPTION
**Pull request by diogomelo09**
[LPS-170656](https://issues.liferay.com/browse/LPS-170656)

### CODE REVIEW

**Review by p-albuquerque — APPROVED** [review]

**Comment by diogomelo09** [comment]
ci:test:relevant

**Comment by diogomelo09** [comment]
ci:reevaluate:1357401_3236

**Comment by marcelabc** [comment]
Just started reviewing :)

**Comment by diogomelo09** [comment]
ci:test:relevant

**Pull request closed without merging**
