### PR TITLE
LPS-194445 - Integrate field with the right sidebar on Object Model Builder

### PR DESCRIPTION
**Pull request by danvb112**
Related Issues:

https://liferay.atlassian.net/browse/LPS-194436
https://liferay.atlassian.net/browse/LPS-194439
https://liferay.atlassian.net/browse/LPS-194442
https://liferay.atlassian.net/browse/LPS-195354
https://liferay.atlassian.net/browse/LPS-195855
https://liferay.atlassian.net/browse/LPS-194445

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
From the backend part, looks good to me!
Thx @murilostodolni

**Comment by gabrielwas** [comment]
For this one, we must alert the QAs to test the details and fields tab with and without the FF on, ok?

**Review by gabrielwas — APPROVED** [review]

**Comment by danvb112** [comment]
Sent to: https://github.com/liferay-objects/liferay-portal/pull/2629

**Pull request closed without merging**
