### PR TITLE
LPS-144848 Create Custom view

### PR DESCRIPTION
**Pull request by alinedoleron**
- LPS-144848 Create index.tsx
- LPS-144852 Create context to custom view
- LPS-144849 Create basic info component
- LPS-144850 Create View Builder Component
- LPS-145410 Implement Drag and Drop to View Builder List
- LPS-144847 Create “Add Columns” modal
- LPS-144848 Build lang
- LPS-144848 Create EditObjectViewMVCRenderCommand
- LPS-144848 Integrate with back-end

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by danvb112** [comment]
Sent to https://github.com/liferay-objects/liferay-portal/pull/346

**Pull request closed without merging**
