### PR TITLE
LPS-185605 Fix wrong use of Tabs on Objects System Fields side panel

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-185605

### CODE REVIEW

**Comment by danvb112** [comment]
This PR must wait this another [PR](https://github.com/brianchandotcom/liferay-portal/pull/135607) be merged on master

**Comment by danvb112** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
Just started reviewing =)

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by alinedoleron** [comment]
ci:forward

**Comment by alinedoleron** [comment]
ci:forward:force

**Pull request closed without merging**
