### PR TITLE
LPS-166764 Add power function in ObjectCodeEditorUtil class

### PR DESCRIPTION
**Pull request by seltong**
Just running ci

### CODE REVIEW

**Comment by seltong** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
As @seltong mentioned, just waiting to get the CI results. Forwarded to Brian directly here: https://github.com/brianchandotcom/liferay-portal/pull/125488

**Comment by seltong** [comment]
ci:relevant

**Comment by seltong** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
CI passed :partying_face: Closing this PR. Thanks, @seltong!

**Pull request closed without merging**
