### PR TITLE
LPD-30995

### PR DESCRIPTION
**Pull request by igor-franca**
Related Tickets:

[LPD-30999](https://liferay.atlassian.net/browse/LPD-30999)
[LPD-30995](https://liferay.atlassian.net/browse/LPD-30995)

[LPD-30999]: https://liferay.atlassian.net/browse/LPD-30999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LPD-30995]: https://liferay.atlassian.net/browse/LPD-30995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
ci:test:playwright

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
ci:test:playwright

**Comment by igor-franca** [comment]
ci:stop

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
ci:test:playwright

**Review by rebsilva — APPROVED** [review]
LGTM! :tada:

**Comment by igor-franca** [comment]
ci:relevant

**Comment by igor-franca** [comment]
ci:test:relevant

**Comment by igor-franca** [comment]
ci:test:relevant

**Comment by igor-franca** [comment]
ci:test:object

**Comment by igor-franca** [comment]
ci:report:54978146

**Comment by igor-franca** [comment]
ci:forward

**Pull request closed without merging**
