### PR TITLE
LPS-175751 Remove FF for LPS-173537

### PR DESCRIPTION
**Pull request by rebsilva**
Related Issue: https://issues.liferay.com/browse/LPS-175751

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
@rebsilva please fix the SF failure

**Comment by rebsilva** [comment]
Sure @carolmariaabb! I will make a cherry-pick of this commit and then force push. Thanks for your review! :purple_heart:

**Comment by rebsilva** [comment]
ci:stop

**Review by carolmariaabb — APPROVED** [review]
LGTM! Thanks, @rebsilva 😄

**Comment by carolmariaabb** [comment]
ci:reevaluate:1377401_10298

**Comment by rebsilva** [comment]
The QA team already approved this PR, btu since I did a rebase to fix a conflict, I will trigger the tests again, thanks!

**Comment by rebsilva** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
