### PR TITLE
LPS-165579 When importing an object an error message appears

### PR DESCRIPTION
**Pull request by diogomelo09**
A Feature Flag conditional was added to "ObjectDefinitionResourceImpl.java" to make the import message behave as expected and for it to stop entering the exception.

### CODE REVIEW

**Comment by diogomelo09** [comment]
ci:test:relevant

**Comment by diogomelo09** [comment]
ci:test:relevant

**Comment by diogomelo09** [comment]
ci:test:relevant

**Comment by diogomelo09** [comment]
I locally ran the two poshi tests that are giving errors and realized that the errors have no relation to what I modified. The tests fail when at some point they log out of the portal and they cannot log in again.

**Comment by diogomelo09** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
LGTM! 🎉

**Comment by mateussgn** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
