### PR TITLE
LPS-160215 Open modals on the full screen and not inside the sidepanel on objects

### PR DESCRIPTION
**Pull request by rebsilva**
Related Issue: https://issues.liferay.com/browse/LPS-160215

Hello Reviewers!

This is a PR for the technical debt to change the way modals are opening on objects; previously the `ModalAddColumns` was the first one to be changed and we were advised to fix the remaining ones when possible.

**Main Goal:** Open modals on the full screen and not inside the side-panel on objects.

**Main Changes:** 

1. The modals are being called using `parentWindow.Liferay.fire` with their respective props; 
2. I've added the props `modalType` and `showModal` to differenciate between add/edit modals and to enable the user to view the modal on the screen, respectively;
3. A prop called `openEditModal` was created on `BuilderScreen` and `BuilderListItem` so we could separate the calls of add/edit modals with more clarity;
4. The modals are now using a general `useState` to reduce the creation/usage of many states inside the code. The states that are still being created separately need to be that way so I didn't change them;
5. The `dispatch` and other props that depends on `useViewContext()` are being sent to the modals via props now, because if we call them inside the modals like before they won't find the context right away (the modal is first prepared with "empty" or default props to only open with the required props when inside the respective context).

**Modals affected**:

- ModalEditViewColumn
- ModalAddFilter
- ModalAddDefaultSortColumn
- ModalAddColumns

If you have any concerns or doubts about this please let me know, thank you for your time!

OBS: A lot of poshi tests will fail because of the paths of the modals that changed, we will need help from QA side to fix this.

Screenshot from 2022-10-06 10-03-56

### CODE REVIEW

**Comment by rebsilva** [comment]
This PR was previously reviewed by @danvb112 so I'm sending a new one with the changes he asked. https://github.com/liferay-objects/liferay-portal/pull/1168

Also looking into some tests before, the only that is failing by theses changes is `ObjectCustomViews#CanSeeRenamedColumnOnViewBuilder`, I will ask the QA team to help on this (seems like a path issue).

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:stop

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:object

**Review by danvb112 — APPROVED** [review]
LGTM! :tada:

**Comment by danvb112** [comment]
This PR is blocked because it depends on https://github.com/brianchandotcom/liferay-portal/pull/125871

**Comment by samuelromeiro** [comment]
Hey @danvb112, the https://github.com/brianchandotcom/liferay-portal/pull/125871 was merged. 
Can you check the conflicts and resend this PR, please?

**Pull request closed without merging**
