### PR TITLE
LPS-135486 Create one ItemSelectorView for each Object definition

### PR DESCRIPTION
**Pull request by mlan0**

### CODE REVIEW

**Comment by mlan0** [comment]
ci:test:sf

**Comment by mlan0** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:relevant
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:stop

**Comment by guilhermedcamacho** [comment]
Hey @mlan0 , as we talked about some changes in objectEntryLocalService after rebase, I'm changing the label to Changes Required

**Comment by mlan0** [comment]
ci:test:sf

**Comment by mlan0** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Pull request closed without merging**
