### PR TITLE
LPD-26044 Add test to assert that it is possible to publish an imported object definition

### PR DESCRIPTION
**Pull request by devpedrotavares**
Related ticket: [LPD-26044](https://liferay.atlassian.net/browse/LPD-26044)

### CODE REVIEW

**Review by carolmariaabb — APPROVED** [review]

**Comment by devpedrotavares** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
ci:report:18188742

**Comment by devpedrotavares** [comment]
ci:forward:force

**Comment by devpedrotavares** [comment]
ci:forward

**Pull request closed without merging**
