### PR TITLE
LPS-164430

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPS-164430

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Review by MarinhoFeliphe — APPROVED** [review]

**Comment by gabrielwas** [comment]
ci:reevaluate:1317401_5246

**Comment by brianchandotcom** [comment]
@p-albuquerque merged to master and U45

**Comment by p-albuquerque** [comment]
ci:close

**Pull request closed without merging**
