### PR TITLE
LPS-193937 Empty message after search at move object to another folder modal is not aligned

### PR DESCRIPTION
**Pull request by larissacribeiro**
Related Issue: [LPS-193937](https://liferay.atlassian.net/browse/LPS-193937)

### CODE REVIEW

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by alinedoleron** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by alinedoleron** [comment]
ci:forward:force

**Pull request closed without merging**
