### PR TITLE
LPS-157168 Upgrade process

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://issues.liferay.com/browse/LPS-157168
[Aggregation Mock Link](https://www.figma.com/file/LJTlp63zShNRA5hiN5ZdJz/34-LPS-149049-autofill-a-field-with-formulas-considering-values?node-id=2059%3A128080)
[Aggregation Functions and Operators Link](https://liferay.atlassian.net/wiki/spaces/DXPL/pages/2053505487/Aggregation+-+Functions+and+Operators)

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:forward

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
