### PR TITLE
LPS-160923 Follow lexicon standards on base select default input

### PR DESCRIPTION
**Pull request by interaminense**
Related issue: https://issues.liferay.com/browse/LPS-160923

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Review by danvb112 — APPROVED** [review]
LGTM! :tada:

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/127050

**Pull request closed without merging**
