### PR TITLE
LPS-192669 Accounts cannot be deleted if the Account Object has a relationship with an inactive Object

### PR DESCRIPTION
**Pull request by mbowerman**
Create a new InactiveObjectDefinitionDeployer interface to deploy only those services that are needed for inactive object definitions.

Ticket: [LPS-192669](https://liferay.atlassian.net/browse/LPS-192669)

See [PTR-4182](https://liferay.atlassian.net/browse/PTR-4182) for further context.

### CODE REVIEW

**Review by pedro-oliveira446 — APPROVED** [review]
LGTM!

**Comment by MarinhoFeliphe** [comment]
@mbowerman the next step to forward this pull request is to wait for the tests to run, so we'll take a look to see if there are any related failures,

Thanks for your contribution!

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:object

**Comment by mateussandes23** [comment]
Hey @mbowerman, I realized some points:

1. The relevant suit had all the tests aborted showing this message:
`Build "functional-tomcat90-mysql57-chrome100-jdk8/0/12" invoked at https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master).
[beanshell] Jenkins reported generated in 224 ms
     [echo] test-portal-acceptance-pullrequest-downstream(master)/functional-tomcat90-mysql57-chrome100-jdk8/0/12 invoked time: Aug 08, 2023 8:08:00 PM PDT
[beanshell] java.util.ConcurrentModificationException
[beanshell] 	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
[beanshell] 	at java.util.ArrayList$Itr.next(ArrayList.java:851)
[beanshell] 	at com.liferay.jenkins.results.parser.BaseBuild.getDownstreamBuilds(BaseBuild.java:836)
[beanshell] 	at com.liferay.jenkins.results.parser.BaseBuild.getFailedDownstreamBuilds(BaseBuild.java:3030)
[beanshell] 	at com.liferay.jenkins.results.parser.PullRequestPortalTopLevelBuild.getResult(PullRequestPortalTopLevelBuild.java:96)
[beanshell] 	at com.liferay.jenkins.results.parser.BaseBuild.getJenkinsReportTableRowElement(BaseBuild.java:3249)
[beanshell] 	at com.liferay.jenkins.results.parser.TopLevelBuild.getJenkinsReportTopLevelTableElement(TopLevelBuild.java:1543)
[beanshell] 	at com.liferay.jenkins.results.parser.TopLevelBuild.getJenkinsReportBodyElement(TopLevelBuild.java:1243)
[beanshell] 	at com.liferay.jenkins.results.parser.TopLevelBuild.getJenkinsReportElement(TopLevelBuild.java:500)
[beanshell] 	at sun.reflect.GeneratedMethodAccessor209.invoke(Unknown Source)`

2. The object routine have has 65 aborted but it's a ci issue you can see this on this [thread](https://liferay.slack.com/archives/CL3TWSMHQ/p1691566130473619). I will trigger the suits and wait for the new results.

**Comment by mateussandes23** [comment]
ci:test:object

**Comment by mateussandes23** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:object

**Comment by mateussandes23** [comment]
Hey @mbowerman taking a look on the results of suits I found some unique fails they are:

- [CanUpdatedToUnpublishedStatus](https://testray.liferay.com/home/-/testray/case_results/2404628651)
- [CanAssociateAnyTypeOfAccount](https://testray.liferay.com/home/-/testray/case_results/2404503600/history?tab=result&hideFilterPin=true)

Do you mind to take a look on this?

**Comment by jpince** [comment]
@mateussandes23 for CanUpdatedToUnpublishedStatus, it looks like the test failed to click on "API Builder" in the Control Panel. Do you believe this is caused by Michael's changes?

**Comment by mbowerman** [comment]
I don't even see an "API Builder" in the Control Panel, whether my changes are deployed or not.

**Comment by mbowerman** [comment]
For the second failure, the report seems to indicate that it failed because the "Account" system object did not appear in the Objects UI. I did not reproduce this problem in my testing. Although, when I reproduced the issue the first time (on an earlier revision of master), I saw that I needed to reindex everything just to get the system objects (including "Account") to appear in the UI, which I thought was very odd. But this was without my changes deployed.

**Comment by mateussandes23** [comment]
Hey @mbowerman and @jpince, sorry for the delay to answer, I was engaged on other tasks. I did another test and don't face this failure too. You guys can forward the PR.

**Comment by carolmariaabb** [comment]
ci:test:stable

**Comment by MarinhoFeliphe** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/139350

**Pull request closed without merging**
