### PR TITLE
LPD-25711 - Allow bound objects entries to be managed entirely if user can update Root entry

### PR DESCRIPTION
**Pull request by G-Sa**
Related to [LPD-27466](https://liferay.atlassian.net/browse/LPD-27466) and [LPD-27468](https://liferay.atlassian.net/browse/LPD-27468)

### CODE REVIEW

**Comment by G-Sa** [comment]
ci:test:object

**Comment by G-Sa** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by G-Sa** [comment]
ci:report:16781008

**Comment by marcelabc** [comment]
ci:report:16752831

**Comment by marcelabc** [comment]
Please, investigate the following tests:
- com.liferay.object.service.test.ObjectActionLocalServiceTest > testAddObjectAction
- PortalLogAssertorTest-modules-integration-mysql57-jdk8/0/0

Please, run all test modules from Objects locally before resending the PR :+1:

**Comment by G-Sa** [comment]
ci:test:sf
ci:test:sf

**Comment by G-Sa** [comment]
ci:test:relevant
ci:test:relevant

**Comment by G-Sa** [comment]
ci:test:object

**Comment by marcelabc** [comment]
ci:report:18153037

**Comment by marcelabc** [comment]
Hey @G-Sa 
Can you analyze the unique failures from the [testray-results-18153037.csv](https://test-1-30.liferay.com/userContent/jobs/generate-testray-csv/builds/127/testray-results-18153037.csv) and run locally the integration tests from object-rest-test (specially DefaultObjectEntryManagerImplTest) ?

**Comment by G-Sa** [comment]
> Hey @G-Sa Can you analyze the unique failures from the [testray-results-18153037.csv](https://test-1-30.liferay.com/userContent/jobs/generate-testray-csv/builds/127/testray-results-18153037.csv) and run locally the integration tests from object-rest-test (specially DefaultObjectEntryManagerImplTest) ?

Hi @marcelabc , i could not reproduce the failure from DefaultObjectEntryManagerImplTest. Also, both poshi tests that failed weren't related to these changes either.

**Comment by G-Sa** [comment]
ci:test:object

**Comment by G-Sa** [comment]
ci:test:relevant

**Comment by G-Sa** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:report:19527651

**Comment by G-Sa** [comment]
ci:test:object

**Comment by G-Sa** [comment]
ci:test:relevant

**Comment by G-Sa** [comment]
ci:test:sf

**Comment by G-Sa** [comment]
ci:report:20513664

**Comment by marcelabc** [comment]
ci:forward:force

**Pull request closed without merging**
