### PR TITLE
LPS-171435 Translation on System Fields is not working with the auto generated view

### PR DESCRIPTION
**Pull request by manuelecastro**
[LPS-171435](https://issues.liferay.com/browse/LPS-171435)

**Description:**
Custom translation on System Fields is not working with the auto-generated view and when changed to a custom view, only custom translations are working.

**Proposed solution:**

**For the first case(auto-generated view):** the issue is that when the `_addAllObjectFields` method is called, it only sets the _Label Key_ as the `fieldLabel`, so when a custom translation is set the method ignores it. The solution found for this case was to add a method(`_filterLabel`) that filters the _Label_ and if it matches a _System Field_, it returns its _label key_ and return the original _Label_ if it doesn't. This method was added to a loop to check each `objectField.getName()` and assign it to the appropriate local variable that will be added as the `fieldLabel` in each `_addNonbjectField` calls.

**For the second case(custom view):** the issue for this case is the other way around. When the `getFDSTableSchema` method is called, it only sets the `objectField.getLabel()` as the `fieldLabel`, so when a _System Field_ is set, it won't get its _Label Key_ and therefore, won't translate it if it's not a custom translation. The solution for this case was to use the same `_filterLabel` method to filter the `label` parameter so it returns the _Label Key_ if that's the case.

### CODE REVIEW

**Comment by manuelecastro** [comment]
ci:test:relevant

**Comment by manuelecastro** [comment]
ci:stop

**Comment by manuelecastro** [comment]
ci:reevaluate:1297401_6080

**Comment by manuelecastro** [comment]
ci:reevaluate:1387401_5564

**Comment by carolmariaabb** [comment]
Hi @manuelecastro, just to let you know that I'm already working on this PR, but I found the expected behavior a bit strange so I'm going to talk to the person responsible for opening this ticket.

Thanks!

**Comment by carolmariaabb** [comment]
@manuelecastro please see https://github.com/liferay-objects/liferay-portal/pull/1624

**Comment by carolmariaabb** [comment]
ci:close

**Comment by manuelecastro** [comment]
@carolmariaabb Ok! Thanks for the review! :smile:

**Pull request closed without merging**
