### PR TITLE
LPS-152408 Commerce Product Group as System Object

### PR DESCRIPTION
**Pull request by joseabelenda**

### CODE REVIEW

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
Waiting PM validation about the fields that are needed for now

cc: @samuelromeiro

**Comment by gabrielwas** [comment]
@joseabelenda @gleicelisbino could you help us with adding [these fields](https://issues.liferay.com/browse/LPS-151766) to the implementation? Thanks!

**Pull request closed without merging**
