### PR TITLE
LPS-170647 Add List Type Entry ERC tests

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-170647

### CODE REVIEW

**Comment by mateussgn** [comment]
I'm investigating CI results.

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:reevaluate:1277401_6666

**Comment by mateussgn** [comment]
ci:reevaluate:1377401_8346

**Comment by mateussgn** [comment]
ci:test:object

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:close

**Comment by guilhermedcamacho** [comment]
Hey @mateussgn , as we discussed, something wrong happens with your rebase in this branch, it lost Brian's changes.
I will close this PR and review the correct one in your [repo](https://github.com/mateussgn/liferay-portal/pull/81), thanks!

**Pull request closed without merging**
