### PR TITLE
LPD-33174 - Remove Common XSS vulnerabilities from calendar events

### PR DESCRIPTION
**Pull request by G-Sa**
Related to: [LPD-33174](https://liferay.atlassian.net/browse/LPD-33174)

[LPD-33174]: https://liferay.atlassian.net/browse/LPD-33174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by G-Sa** [comment]
ci:test:sf

**Review by linolaoj — APPROVED** [review]

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:test:calendar

**Comment by linolaoj** [comment]
Hi @G-Sa , the calendar errors are not related.

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:forward

**Pull request closed without merging**
