### PR TITLE
LPD-2081 Relationship edges are shown when only one of the nodes is visible

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: [LPD-2081](https://liferay.atlassian.net/browse/LPD-2081)

### CODE REVIEW

**Comment by rebsilva** [comment]
just started reviewing! :cherry_blossom:

**Review by rebsilva — APPROVED** [review]
LGTM! great job @larissacribeiro and @danvb112! :tada: :cherry_blossom:

**Comment by rebsilva** [comment]
some tests failed as `Failed prior to running test` and i don't think they are related, but you can double check locally just to make sure @danvb112

**Comment by danvb112** [comment]
ci:forward:force

**Pull request closed without merging**
