### PR TITLE
LPS-203975 Add Move and Export features to Model Builder

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://liferay.atlassian.net/browse/LPS-203975

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:stable

**Comment by rebsilva** [comment]
i'll rebase and test the PR to forward it soon

**Comment by rebsilva** [comment]
resent here https://github.com/liferay-objects/liferay-portal/pull/3043

**Pull request closed without merging**
