### PR TITLE
LPS-194852 Allow delete system object definitions in deletion process of companies

### PR DESCRIPTION
**Pull request by seltong**
Follow-up: https://github.com/liferay-objects/liferay-portal/pull/2518

### CODE REVIEW

**Comment by seltong** [comment]
ci:test:object

**Comment by seltong** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by seltong** [comment]
ci:forward:force

**Comment by seltong** [comment]
Sent to Brian's repository: https://github.com/brianchandotcom/liferay-portal/pull/141027

**Pull request closed without merging**
