### PR TITLE
LPD-37530 Apply same logic used for POST: fill the site default locale using the default locale of the object definition

### PR DESCRIPTION
**Pull request by devpedrotavares**
Related ticket: [LPD-37530](https://liferay.atlassian.net/browse/LPD-37530)

[LPD-37530]: https://liferay.atlassian.net/browse/LPD-37530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by guilhermedcamacho — APPROVED** [review]
LGTM :tada:

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:object

**Comment by devpedrotavares** [comment]
ci:forward

**Pull request closed without merging**
