### PR TITLE
LPD-35168 Binding two trees into one using a relationship

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPD-35168](https://liferay.atlassian.net/browse/LPD-35168)
[LPD-37130](https://liferay.atlassian.net/browse/LPD-37130)

[LPD-35168]: https://liferay.atlassian.net/browse/LPD-35168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LPD-37130]: https://liferay.atlassian.net/browse/LPD-37130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by pedro-oliveira446** [comment]
This [failure](https://testray.liferay.com/#/project/35392/routines/45357/build/27467867/case-result/27476136) appears to be related to the PR.

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Comment by pedro-oliveira446** [comment]
Resent [here](https://github.com/liferay-core-infra/liferay-portal/pull/7479)

**Pull request closed without merging**
