### PR TITLE
LPS-160392 Filter non reverse Relationships when we add an Aggregation field

### PR DESCRIPTION
**Pull request by danvb112**
Related issue: https://issues.liferay.com/browse/LPS-160392

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Comment by danvb112** [comment]
ci:forward

**Pull request closed without merging**
