### PR TITLE
LPS-191936 object-service: System fields are not searchable in the same way that custom fields are so there is no need to iterate through them

### PR DESCRIPTION
**Pull request by gustavolimav**
https://liferay.atlassian.net/browse/LPS-191936

context:
https://liferay.atlassian.net/browse/PTR-4136?focusedCommentId=2421558
https://github.com/liferay-search/liferay-portal/pull/1008#pullrequestreview-1552739777
https://liferay.slack.com/archives/C026NQPV6TV/p1690483726737609

### CODE REVIEW

**Comment by gustavolimav** [comment]
https://github.com/liferay-search/liferay-portal/pull/1008#pullrequestreview-1552739777

Changed to true

**Review by gabrielwas — APPROVED** [review]
LGTM :) Thx @gustavolimav

**Comment by gabrielwas** [comment]
ci:reevaluate:1317401_8865

**Comment by gustavolimav** [comment]
@gabrielwas can I force forward it?

**Comment by gabrielwas** [comment]
@gustavolimav I'll just ask QAs to double check it.

**Comment by gabrielwas** [comment]
@gustavolimav just notice we already have a QA approved.

**Comment by gabrielwas** [comment]
ci:forward:force

**Pull request closed without merging**
