### PR TITLE
LPS-194852 Modifiable system object definitions must not be used in Form Container

### PR DESCRIPTION
**Pull request by seltong**
Related issues: 

- [LPS-194852](https://liferay.atlassian.net/browse/LPS-194852)
- [LPS-193809](https://liferay.atlassian.net/browse/LPS-193809)

### CODE REVIEW

**Comment by seltong** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
I believe I should only review this commit: https://github.com/liferay-objects/liferay-portal/pull/2518/commits/7eaa140c372052ee113fcf7cc7677461788ff92f
Is that correct, @seltong ?

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by seltong** [comment]
> I believe I should only review this commit: [7eaa140](https://github.com/liferay-objects/liferay-portal/commit/7eaa140c372052ee113fcf7cc7677461788ff92f) Is that correct, @seltong ?

Here we have the last 4 commits to review.
You can start reviewing from [this commit](https://github.com/liferay-objects/liferay-portal/pull/2518/commits/40719df9b55edf1a427f9bbdc3a01cae7cde6ea0)

**Comment by seltong** [comment]
ci:test:sf

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:object

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:reevaluate:1257401_3365

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
@marcelabc @seltong I believe we can forward this PR. The changes are minor risks are low.

cc @samuelromeiro @guilhermedcamacho

**Comment by seltong** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/140921

**Pull request closed without merging**
