### PR TITLE
[TS] LPS-175799

### PR DESCRIPTION
**Pull request by crodriguezy**
Related issue: https://issues.liferay.com/browse/LPS-175799

### CODE REVIEW

**Comment by marcelabc** [comment]
Just started reviewing :)

**Comment by marcelabc** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉
Hi @crodriguezy,
I analyzed the CI results and there are no unique failures. Fell comfortable to send directly to Brian, okay? Thanks.

**Comment by crodriguezy** [comment]
Ok @marcelabc , thanks!

**Pull request closed without merging**
