### PR TITLE
LPS-171354 The not mandatory field prevent from continuing with the flow

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
https://issues.liferay.com/browse/LPS-171354

### CODE REVIEW

**Comment by marcelabc** [comment]
Just started reviewing :)

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by pedro-oliveira446** [comment]
@marcelabc I realized this fix generates a problem, here is the video. This should be treated in another LPS or in the same one ? 

https://user-images.githubusercontent.com/79122660/210634415-6943789a-b770-4c14-8fd2-38f5dd61e208.mp4

**Comment by marcelabc** [comment]
Hi @pedro-oliveira446,
Good job in the investigation :clap: 
Do you think you could create another solution, so this new bug does not occur? We cannot approve knowing that it is causing another bug...

**Comment by naraandrade** [comment]
@pedro-oliveira446 I'm leaving a reminder so you can try to find another solution for this issue. 
@marcelabc I'll close this PR for now and return the ticket to "In Progress". Thanks :)

**Pull request closed without merging**
