### PR TITLE
LPS-147100 Fix functional tests

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://issues.liferay.com/browse/LPS-147100

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:stop

**Comment by marcelabc** [comment]
ci:stop

**Comment by marcelabc** [comment]
It is blocked because @rodrigocunhaa will help me to fix some functional tests!

**Comment by rodrigocunhaa** [comment]
Resent here: https://github.com/liferay-objects/liferay-portal/pull/439

**Pull request closed without merging**
