### PR TITLE
LPS-157213 Remove aggregation feature flag

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://issues.liferay.com/browse/LPS-157213

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
@marcelabc can you resend it right after the aggregation validation from QAs? Thx

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
@marcelabc can you take a look at this failures?

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:reevaluate:1267401_4662

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:reevaluate:1287401_4098

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Resent here: https://github.com/liferay-objects/liferay-portal/pull/979

**Pull request closed without merging**
