### PR TITLE
 LPS-167967 Harmonize util class names

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://issues.liferay.com/browse/LPS-167967

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Waiting the @gabrielwas opinion about this on Slack :+1:

**Comment by carolmariaabb** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/126031

**Pull request closed without merging**
