### PR TITLE
LPS-165682 Use the correct property name in groovy script

### PR DESCRIPTION
**Pull request by hongvo2308**
Hi,
This is the PR for the ticket https://issues.liferay.com/browse/LPS-165682. Please help me to review this and leave your comments.
Thank you.

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
@hongvo2308 I've seen the same failures in other PRs. I think it's safe to send it directly to Brian.

Could you please manually forward this PR?

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by hongvo2308** [comment]
@carolmariaabb 
Yes, I have forwarded this one to https://github.com/brianchandotcom/liferay-portal/pull/125420.
Thank you.

**Pull request closed without merging**
