### PR TITLE
LPS-158366 Fix upgrade step, set variables

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-158366

Thank you a lot for your collaboration, @gabrielwas!

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by timpak** [comment]
ci:stop

**Comment by gabrielwas** [comment]
sent here https://github.com/brianchandotcom/liferay-portal/pull/120617

**Comment by vicnate5** [comment]
@gabrielwas @mateussgn Please have your QA review the test results here before sending.

The upgrade is broken on the latest results

PostgreSQL
```
     [java] 2022-07-20 17:50:14.008 INFO  [main][UpgradeProcess:113] Failed upgrade process com.liferay.object.internal.upgrade.v3_18_0.ObjectFieldUpgradeProcess in 13 ms
     [java] 2022-07-20 17:50:14.019 ERROR [main][UpgradeStepRegistratorTracker:221] Failed upgrade process for module com.liferay.object.service
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: org.postgresql.util.PSQLException: ERROR: syntax error at end of input
     [java]   Position: 513
```

DB2
```
     [java] 2022-07-20 17:46:52.759 INFO  [main][UpgradeProcess:113] Failed upgrade process com.liferay.object.internal.upgrade.v3_18_0.ObjectFieldUpgradeProcess in 2 ms
     [java] 2022-07-20 17:46:52.763 ERROR [main][UpgradeStepRegistratorTracker:221] Failed upgrade process for module com.liferay.object.service
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-104, SQLSTATE=42601, SQLERRMC=END-OF-STATEMENT;ield.system_ = true);), DRIVER=4.24.92
```

Oracle DB
```
     [java] 2022-07-20 17:47:19.604 INFO  [main][UpgradeProcess:113] Failed upgrade process com.liferay.object.internal.upgrade.v3_18_0.ObjectFieldUpgradeProcess in 1 ms
     [java] 2022-07-20 17:47:19.608 ERROR [main][UpgradeStepRegistratorTracker:221] Failed upgrade process for module com.liferay.object.service
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: java.sql.SQLSyntaxErrorException: ORA-00907: missing right parenthesis
```

SQL Server
```
     [java] 2022-07-20 17:37:48.417 INFO  [main][UpgradeProcess:113] Failed upgrade process com.liferay.object.internal.upgrade.v3_18_0.ObjectFieldUpgradeProcess in 1 ms
     [java] 2022-07-20 17:37:48.422 ERROR [main][UpgradeStepRegistratorTracker:221] Failed upgrade process for module com.liferay.object.service
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near ')'.
```

**Pull request closed without merging**
