### PR TITLE
LPD-25643 Add draft parent object definition when importing relationship object field

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://liferay.atlassian.net/browse/LPD-25643

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Review by marcelabc — COMMENTED** [review]
Overall, LGTM 🎉
One concern: I believe the same situation can happen in a UPDATE object definition. Don't we need to apply the same logic that you implemented in [ObjectDefinitionResourceImpl.java](https://github.com/liferay-objects/liferay-portal/pull/3342/files#diff-05788445836e16c530386e55062a7c76a71e8ce4d60428c58cee9b01a1b50966) in this [part of the code](https://github.com/liferay/liferay-portal/blob/master/modules/apps/object/object-admin-rest-impl/src/main/java/com/liferay/object/admin/rest/internal/resource/v1_0/ObjectDefinitionResourceImpl.java#L637-L639) related to the update?

Since this work is urgent, we can talk with Claudio to understand his scenario. In the worst scenario, we can improve later.

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/150282

**Pull request closed without merging**
