### PR TITLE
LPS-182589

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Review by guilhermedcamacho — APPROVED** [review]
LGTM!

**Comment by anabuchmann** [comment]
Just started reviewing :)

**Comment by gabrielwas** [comment]
ci:reevaluate:1327401_9321

**Comment by gabrielwas** [comment]
Failed test possibly related to https://github.com/liferay-objects/liferay-portal/pull/2062.

I'll forward this PR and keep watching

**Comment by gabrielwas** [comment]
Forwarded here https://github.com/brianchandotcom/liferay-portal/pull/134327

**Pull request closed without merging**
