### PR TITLE
LPS-169752 When the title field is a system field the asset title is null on the My Workflow Tasks

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
https://issues.liferay.com/browse/LPS-169752

### CODE REVIEW

**Review by p-albuquerque — CHANGES_REQUESTED** [review]
Create a private method to execute asserts between `date` and `timestamp` types
Organize the asserts in alphabetical order.

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Review by p-albuquerque — APPROVED** [review]
LGTM

**Comment by p-albuquerque** [comment]
Fix the conflicts and send manually to brian

**Comment by pedro-oliveira446** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/127453

**Pull request closed without merging**
