### PR TITLE
LPS-181760 Link to doco inconsistent and not in right spots

### PR DESCRIPTION
**Pull request by larissacribeiro**
**Related Issue**: [**LPS-181760**](https://liferay.atlassian.net/browse/LPS-181760)

### CODE REVIEW

**Comment by larissacribeiro** [comment]
Test suites aren't working, it has already been fixed but we need to wait for the PR to be merged into master.
I'll monitor in order to retrigger the test suites when possible!

**Comment by larissacribeiro** [comment]
ci:test:object

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by larissacribeiro** [comment]
ci:test:relevant

**Comment by larissacribeiro** [comment]
ci:stop

**Comment by larissacribeiro** [comment]
ci:stop

**Comment by larissacribeiro** [comment]
ci:test:sf

**Comment by larissacribeiro** [comment]
ci:test:relevant

**Comment by larissacribeiro** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
