### PR TITLE
LPS-171258

### PR DESCRIPTION
**Pull request by murilostodolni**
Follow-up: https://github.com/liferay-objects/liferay-portal/pull/1518

### CODE REVIEW

**Comment by murilostodolni** [comment]
ci:stop

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
Sent to: https://github.com/liferay-objects/liferay-portal/pull/1532

**Pull request closed without merging**
