### PR TITLE
LPS-150523 SF

### PR DESCRIPTION
**Pull request by gabrielwas**
Related Issue: https://issues.liferay.com/browse/LPS-150523

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @gabrielwas, can you please check if these failures are related to your changes? Thanks

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @gabrielwas, can you please check if these failures are related to your changes? Thanks

**Comment by marcelabc** [comment]
I'm running the tests locally

**Comment by marcelabc** [comment]
The last commit broke the tests. I'm fixing to resend.

**Pull request closed without merging**
