### PR TITLE
LPS-142244 Add URL and Secret fields in modal add action

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-142244

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Review by guilhermedcamacho — APPROVED** [review]
LGTM (backend changes)

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Review by miltonmc — APPROVED** [review]
LGTM!

**Comment by guilhermedcamacho** [comment]
ci:forward

**Pull request closed without merging**
