### PR TITLE
LPS 136736

### PR DESCRIPTION
**Pull request by interaminense**
- LPS-136736 Create editing screen to update object field
- LPS-136736 buildLang

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
ci:test:relevant

**Pull request closed without merging**
