### PR TITLE
LPS-165103 Add item and button save is active for the user without permission to update on the Picklist

### PR DESCRIPTION
**Pull request by locpham97**
Hi team,
Please help me review this request.[LPS-165103](https://issues.liferay.com/browse/LPS-165103)
Thanks.
cc: @Vy-CES

### CODE REVIEW

**Comment by Vy-CES** [comment]
ci:test:sf

**Comment by Vy-CES** [comment]
ci:test:sf

**Comment by Vy-CES** [comment]
ci:test:sf

**Comment by Vy-CES** [comment]
Hey @danvb112, are you working on this? is there anything you want me to do on my end :D?

**Comment by marcelabc** [comment]
ci:test:relevant

**Review by danvb112 — CHANGES_REQUESTED** [review]
Hey @Vy-CES, The first time I saw your PR it had three commits, one of them modifying something in the `Frontend DataSet ` table, was there any reason for you to remove it? I think he was very important for your solution, without him your solution doesn't work anymore. 

Other than that, the rest of your PR looks good to me!

**Comment by Vy-CES** [comment]
Hey @danvb112  the reason I removed it is because thought it belonged to the frond-end team.

Now, I realized without this commit, it will stop the screen if the picklist has items.

Anyway, I've readded the commit, please review it and give me your comment. Thanks

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
Hey @Vy-CES, I spoke with Marko Čikoš he is responsible for the FDS code, to see if he can review this part of your PR from here or if you will have to send a new PR there

**Comment by Vy-CES** [comment]
Hey @danvb112 , great! thank you for letting me know.

**Review by markocikos — APPROVED** [review]
The part in `frontend-data-set-web` looks good to me!

**Comment by naraandrade** [comment]
ci:forward

**Comment by naraandrade** [comment]
The results were [checked with QA](https://liferay.slack.com/archives/C048YNC5GRK/p1667940624232439), I'll send this PR directly to Brian.

**Pull request closed without merging**
