### PR TITLE
LPS-141285 Keeps the user on the layout page when an entry is created in order to see the other tabs

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Resent here with the Poshi tests fixed: https://github.com/liferay-objects/liferay-portal/pull/247

**Pull request closed without merging**
