### PR TITLE
LPD-15603 Get portalURL variable from http request

### PR DESCRIPTION
**Pull request by devpedrotavares**
Related issue: [LPD-15603](https://liferay.atlassian.net/browse/LPD-15603)

### CODE REVIEW

**Review by marcelabc — APPROVED** [review]
LGTM :tada:

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:object

**Comment by devpedrotavares** [comment]
ci:test:sf

**Comment by devpedrotavares** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
ci:test:object

**Comment by devpedrotavares** [comment]
ci:report:2534130442

**Comment by devpedrotavares** [comment]
ci:report:2534138147

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by devpedrotavares** [comment]
ci:forward:force

**Pull request closed without merging**
