### PR TITLE
LPS-189460 Add new NotificationQueueEntryUpgradeProcess to set the NotificationQueueEntry.companyId

### PR DESCRIPTION
**Pull request by seltong**
Follow-up: https://github.com/brianchandotcom/liferay-portal/pull/138148

Related issue: [LPS-189460](https://liferay.atlassian.net/browse/LPS-189460)

### CODE REVIEW

**Review by murilostodolni — APPROVED** [review]
LGTM

**Comment by seltong** [comment]
ci:test:stable

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:stable

**Comment by seltong** [comment]
The ci relevant failures don't seem related. Can I run ci forward, @marcelabc?

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:reevaluate:1297401_7735

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:object

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:object

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:object

**Comment by seltong** [comment]
ci:relevant

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:forward:force

**Pull request closed without merging**
