### PR TITLE
LPS-162972 Unable to define the searchable options for a new field added to already published objects

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
Hi @marcelabc, 
I've noticed that those tests that are failing haven't any relationship with my changes, can you take a look on this?

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Review by danvb112 — APPROVED** [review]
LGTM!

**Comment by marcelabc** [comment]
Just started reviewing :)

**Review by marcelabc — APPROVED** [review]
LGTM 🎉
Hey @MrJohn1911 , great job!
I just reordered [here](https://github.com/liferay-objects/liferay-portal/pull/1203/commits/e80f790e4c76152d27056957b8ea00ea7c757241) because Brian likes alphabetic ordered when it is possible. 
Thank you for helping us fixing this bug!!

**Comment by marcelabc** [comment]
Resend: https://github.com/liferay-objects/liferay-portal/pull/1203

**Pull request closed without merging**
