### PR TITLE
LPS-161069 Objects is an special case because the scope of this ResourceAction is the current company. No resourcePermissions can exist in other companies

### PR DESCRIPTION
**Pull request by achaparro**
cc/ @lortiz89 @gabrielwas

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:test:relevant

**Review by gabrielwas — APPROVED** [review]
LGTM :)

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
@marcelabc is in charge to check these failures

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
@marcelabc can we forward this?

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
