### PR TITLE
LPS-150121

### PR DESCRIPTION
**Pull request by mbowerman**
Related Issue: https://issues.liferay.com/browse/LPS-150121

/cc @SelenaAungst

https://issues.liferay.com/browse/LPS-150121

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @mbowerman, can you please check if these failures are related to your changes? Thanks

**Comment by danvb112** [comment]
Thanks, @miltonmc! @mbowerman @SelenaAungst I will close this PR due to Milton's explanation

**Comment by danvb112** [comment]
Solved by: https://github.com/liferay-forms/liferay-portal/pull/1577

**Pull request closed without merging**
