### PR TITLE
LPS-195679

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
**Only the last commit needs revision because the others have already been merged**

This commit fix the problem related [here](https://liferay.slack.com/archives/CLCD3DQLF/p1695181236207969?thread_ts=1695177525.885379&cid=CLCD3DQLF) .

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Review by gabrielwas — APPROVED** [review]
LGTM :) Thx for the quick fix, @pedro-oliveira446 !

**Comment by gabrielwas** [comment]
@pedro-oliveira446 rebase it with Brian's repo and sent it again. You can straight forward it

**Pull request closed without merging**
