### PR TITLE
LPS-164803 Fix test to ensure that only afterAdd action is executed when a object entry is created

### PR DESCRIPTION
**Pull request by seltong**

### CODE REVIEW

**Review by MarinhoFeliphe — APPROVED** [review]

**Comment by seltong** [comment]
ci:relevant

**Comment by seltong** [comment]
ci:relevant

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:forward

**Comment by seltong** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/125304

**Pull request closed without merging**
