### PR TITLE
LPS-146127 Add support to truncate the text if the field type is a String

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-146127

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉 
The presented code is Good to Go. We just need to fix the issues reported by the CI.

**Review by marcelabc — CHANGES_REQUESTED** [review]
Could you fix the baseline issue, please?

**Comment by danvb112** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM !

**Comment by marcelabc** [comment]
Hey @danvb112, could you check if the CI results are flaky or not? The automated tests failed twice, maybe it is related.

**Comment by marcelabc** [comment]
This PR is good to go regarding the code, but must investigate the tests failures before forwarding.

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
ci:test:object

**Comment by rodrigocunhaa** [comment]
ci:stop

**Comment by rodrigocunhaa** [comment]
Resent here: https://github.com/liferay-objects/liferay-portal/pull/374

**Pull request closed without merging**
