### PR TITLE
LPD-30217 Embed the Object Entry's permissions in the nestedFields parameter for GET request

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://liferay.atlassian.net/browse/LPD-30217

### CODE REVIEW

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:object

**Comment by marcelabc** [comment]
Let's see the CI results before sending to the Headless team :+1:

**Comment by carolmariaabb** [comment]
https://github.com/liferay-headless/liferay-portal/pull/2146

**Pull request closed without merging**
