### PR TITLE
LPS-148242 Cover company and individual view permission with integration tests

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**
See also https://github.com/brianchandotcom/liferay-portal/pull/114155#issuecomment-1058617303

### CODE REVIEW

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
