### PR TITLE
LPS 139281

### PR DESCRIPTION
**Pull request by interaminense**
- LPS-139167 Migrate default user permission test
- LPS-139167 Now delete long running TokenCompanyTest which is covered by IsolationAcrossCompaniesTest anyway
- LPS-139062 Update macros to use variable
- LPS-139108 Update the teardown
- LPS-139108 Add property to skip the instance
- LPS-139111 Update parameter for the test
- LPS-139120 Update the site name
- LPS-139121 Update the test to skip the instance
- LPS-139073 Unify filters views
- LPS-139073 Update locator
- LPS-139073 Update case
- LPS-139073 Modify locator to make it stable
- LPS-138664 Update English texts to avoid confusion between firstName, userName and screenName when translated to other languages - Now these texts to be shown are more specific and provide more meaning -> field.first-name=First Name -> field.user-name=User Name -> field.screen-name=Screen Name
- LPS-138664 regen
- LPS-139158 Test added to replace FilterByCategoryAndSubtype
- LPS-139158 SF
- LPS-139018 Take into account the collection items to set totalItems
- LPS-139018 Remove unused additional props
- LPS-139018 Extract to display context and set activeDelta too
- LPS-138888 Include upgrade tests in Lima suite
- LPS-139202 Remove redundant steps
- LPS-139202 Modify macro to make it reusable
- LPS-139202 Update cases
- LPS-139202 Use no loading function
- LPS-139105 Update test stub names
- LPS-139194 Remove feature flag
- LPS-139107 Migrate script file related to information template to own folder
- LPS-139107 Update macro
- LPS-139107 Migrate fragment code files to own folder
- LPS-139107 Update macros
- LPS-139107 Update case
- LPS-139107 Remove deprecated files
- LPS-139063 Add key to SelectorButtonList
- LPS-138827 Automate CreateObject#CannotLeaveLabelFieldBlank
- LPS-138829 Automate CreateObject#CannotLeaveTypeFieldBlank
- LRCI-2502 SF
- LPS-135156 Implements a method to get parentIds list by typeSettings keyword.
- LPS-135156 buildService
- LPS-135156 Implements isChildSelected method using new service method.
- LPS-135156 rename, to match the var name you used, and this is the better name
- LPS-135156 regen
- LPS-138914 Adds configuration category for Template
- LPS-138914 Adds configuration category language key
- LPS-138914 Adds configuration for widget template available language types
- LPS-138914 Adds configuration language keys, copied from JournalWebConfiguration
- LPS-138914 Adds configuration as request attribute in edit render commands
- LPS-138914 Remove duplicate method.
- LPS-138914 Uses configuration to decide available language types in widget template edition.
- LPS-138914 Ensure the current template language type is included in available types.
- LPS-138914 Filter unsupported language types from the configuration.
- LPS-138914 Fix: inappropriate and unnecessary var assignation.
- LPS-138914 Adds the ability to set language type using a parameter in the widget template edition.
- LPS-138914 Removes templates for non existing info field types.
- LPS-138914 Removes date template.
- LPS-138914 buildLang
- LPS-138914 Uses constructor to pass the necessary parameters, in that way we are avoiding null pointers
- LPS-138914 Rename to match with category key
- LPS-138914 Rename to widget templates
- LPS-138914 SF - Refactor
- LPS-138914 buildLang
- LPS-138914 wordsmith
- LPS-138914 regen
- LPS-139183 Remove redundant generateInstanceId function
- LPS-139201 Remove redundant slash
- LPS-139201 Modify macro to make it reusable
- LPS-139077 Reduce mergePages' algorithm complexity
- LPS-77699 Update Translations
- COMMERCE-7214 Fix upgrade process
- LPS-138675 Remove unused module
- LPS-138675 Remove unused language keys
- LPS-138675 buildLang
- LPS-138675 Remove test
- LRQA-69835 customized error message tests
- LPS-138737 buildRest
- LPS-138737 Add actions property for ListTypeDefinition
- LPS-138737 Show delete dropdown item
- LPS-138737 Add delete action
- LPS-138737 Rename
- LPS-138737 Also remove list type entries when removing the list type definition
- LPS-138737 Create test
- LPS-138738 Add deleteListTypeEntry endpoint
- LPS-138738 deleteListTypeEntry endpoint
- LPS-138738 Adjust test
- LPS-138738 Add actions property for ListTypeEntry
- LPS-138738 Show delete dropdown item
- LPS-138738 Add delete action
- LPS-138737 can you verify this works
- LPS-138737 Usual order
- LPS-138737 match headless-delivery-impl/src/main/java/com/liferay/headless/delivery/internal/dto/v1_0/util/RatingUtil.java
- LPS-139199 Create new method allowing to list active object definitions
- LPS-139199 buildService
- LPS-139199 Adjust to list object definitions active and approved
- COMMERCE-7219 Update reference to admin account portlet
- COMMERCE-7219 Add account-api to build.gradle
- LPS-136040 Use PortalUtil to fetch the appropriate ids and use it in the portlet URL parameter
- LPS-136040 SF
- COMMERCE-7035 Add property portal.acceptance
- COMMERCE-7035 Auto SF
- LRQA-69492 - Fix ProcessBuilderKaleoDesigner#ConnectorHasDefaultName test
- LPS-134021 Lowercase data attributes keys, so we avoid React warnings
- Auto SF
- Regen
- LPS-124256 liferay-portal: build.properties: search-experiences
- LPS-124256 search-experiences: app: Initial commit
- LPS-124256 remove this until we need it
- LPS-124256 wordsmith
- LPS-124256 add test.properties later
- LPS-124256 add lfrbuild files
- LPS-124256 initial
- LPS-124256 regen
- LPS-136868 commerce-product-service: Make Commerce products searchable on non-Commerce search pages
- LPS-139218 Build service
- LPS-139219 buildR
- LPS-139218 New method to get site navigation menu by name
- LPS-139218 Check if we have a valid id, otherwise fallback to the name
- LPS-139218 Adds language keys
- LPS-139218 Change to use name instead of ID
- LPS-139219 Add supbtype as property
- LPS-139219 Also add the property to the schema
- LPS-139219 Take into account the key when importing
- LPS-139219 Change definitions in site initializer
- LPS-139219 Fallback to the DDMStructureKey if the DDMStructure is not found
- LPS-139219 SF
- LPS-138809 Add CannotLeaveObjectLabelFieldBlank Test
- LPS-138809 SF
- LPS-138809 Small improvement
- LPS-137955 Fix test by adding an asset before editing
- LPS-137955 Unquarantine test
- LPS-137955 Clean up other test to use global test site
- LPS-139187 Unquarantine test
- LPS-138945 Adjust size of state and task nodes
- LPS-138945 Fix condition to display comma
- LPS-138945 Add lang key
- LPS-138945 buildLang
- LPS-138945 Apply Workflow Instance Tracker to instance items on Metrics
- LPS-138945 Create flag to enable Workflow Instance Tracker on Metrics
- LPS-138945 Apply flag to control exhibition of Track Workflow option on kebab menu
- LPS-138945 Increase retry assert time to 10 seconds
- Revert "LPS-139219 SF"
- LPS-137424 Added parenthesis to each where clause generated
- LPS-138818 Add CanCreateBooleanField Test
- LPS-138821 Add CanCreateIntegerField Test
- LPS-138817 Add CanCreateBigDecimalField Test
- LPS-138820 Add CanCreateDoubleField Test
- LPS-138818 SF
- LRAC-8551, LRAC-8552 Adding comment with bug tickets
- LRQA-68532 Add test for viewing production WC in publications
- LPS-138839 Add CanUpdateObjectScopeBeforePublished Test
- LPS-138839 SF
- LPS-138824 Add FieldNameIsAutofilled Test
- LPS-138824 SF
- LPS-138845 Add CanUpdateObjectPanelCategoryKeyAfterPublished Test
- LPS-138845 SF
- LPS-138834 Add KeywordAndTextDisplayedForStringTypeField Test
- LPS-138834 SF
- LPS-139151 Make getCollectionSupportedFilters request every time a collection changes and add loading state for CollectionFilterGeneralPanel
- LPS-139151 Make getCollectionSupportedFilters request every time a collection changes and add loading state for CollectionAppliedGeneralPanel
- LPS-139151 Avoid unneeded requests
- LRAC-8627 Add test to filter segment distribution by number
- LRAC-8627 Add refactor
- LRAC-8627 Add bug ticket
- LPS-138557 Reserve locale variable for the current portal locale and add articleLocale variable to store the current journal article's locale analogously to articleGroupId variable
- LPS-138557 Rely on themeDisplay to get current locale in order to avoid null request objects
- LPS-138939 Create layout screen
- LPS-138939 Add layout react components
- LPS-138939 Create SidePanelContent component
- LPS-138939 Create CustomSelect component
- LPS-138939 Create Panel component
- LPS-138939 Add util to normalize languageId
- LPS-138939 Add css to nav-link and fix height of side panel content
- LPS-138939 Remove outdated generated types
- LPS-138939 SF
- LPS-139281 Do not allow adding the field more than once on the layout structure
- LPS-139281 buildLang

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:reevaluate:1297401_274

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
resent to: https://github.com/liferay-objects/liferay-portal/pull/112

**Pull request closed without merging**
