### PR TITLE
LPS-140522 Add ThreadLocal to skip permission

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-140522

Follow-up: https://github.com/liferay-objects/liferay-portal/pull/1480

### CODE REVIEW

**Comment by mateussgn** [comment]
I considered the [comment](https://github.com/liferay-objects/liferay-portal/pull/1480#issuecomment-1380576882) made by @marcelabc and tried to tie everything together.

@marcelabc, could you double-check my changes? Just to make sure it won't affect yours.

**Comment by mateussgn** [comment]
ci:stop

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:object

**Comment by marcelabc** [comment]
Just started reviewing :)

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Pull request closed without merging**
