### PR TITLE
LPS-143232 Add alert when the object is seted to Hide Widget

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-143232

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:reevaluate:1347401_494

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Pull request closed without merging**
