### PR TITLE
LPD-33303 Add test cases for sending localized notifications to guest users

### PR DESCRIPTION
**Pull request by devpedrotavares**
Related ticket: [LPD-35681](https://liferay.atlassian.net/browse/LPD-35681)

[LPD-35681]: https://liferay.atlassian.net/browse/LPD-35681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by linolaoj — APPROVED** [review]

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
ci:report:13288217

**Comment by devpedrotavares** [comment]
ci:forward:force

**Comment by devpedrotavares** [comment]
ci:forward:force

**Pull request closed without merging**
