### PR TITLE
LPS-147409 Remove Feature Flag to apply ObjectViewSortColumn on Object Views

### PR DESCRIPTION
**Pull request by mateussgn**
Related Issue: https://issues.liferay.com/browse/LPS-147409

Related issue: https://issues.liferay.com/browse/LPS-147409

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @mateussgn, can you please check if these failures are related to your changes? Thanks

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
LGTM :D

**Comment by liferay-forms** [comment]
Hey @mateussgn, can you please check if these failures are related to your changes? Thanks

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:forward

**Pull request closed without merging**
