### PR TITLE
LPS-164803 Fix test

### PR DESCRIPTION
**Pull request by seltong**

### CODE REVIEW

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
@seltong feel free to forward it to Brian

**Comment by seltong** [comment]
ci:forward

**Comment by seltong** [comment]
ci:forward

**Comment by seltong** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/124299

**Pull request closed without merging**
