### PR TITLE
LPS-175828 Remove Feature Flag of OldValues

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPS-175828

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Hey @MarinhoFeliphe, could you review this PR please?

**Review by MarinhoFeliphe — APPROVED** [review]

**Comment by p-albuquerque** [comment]
Directly sent: https://github.com/brianchandotcom/liferay-portal/pull/130928

**Pull request closed without merging**
