### PR TITLE
LPS-164530 Error message is displayed when a field Picklist is created

### PR DESCRIPTION
**Pull request by daiazius**
Related issue: https://issues.liferay.com/browse/LPS-164530

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:stop

**Comment by naraandrade** [comment]
@daiazius Resent [here](https://github.com/liferay-objects/liferay-portal/pull/1185), please see the commits.

**Comment by danvb112** [comment]
@daiazius, as Nara is on vacation now, I sent a new PR with the conflicts resolved here https://github.com/liferay-objects/liferay-portal/pull/1194

**Pull request closed without merging**
