### PR TITLE
LPD-29392

### PR DESCRIPTION
**Pull request by vngoliveira**
[LPD-28166](https://liferay.atlassian.net/browse/LPD-28166)

[LPD-28166]: https://liferay.atlassian.net/browse/LPD-28166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by vngoliveira** [comment]
ci:test:sf

**Comment by vngoliveira** [comment]
ci:test:sf

**Comment by vngoliveira** [comment]
Hey team!
Now the PR is ready to be reviewed by you. The backend and frontend parts are complete and have their respective tests implemented.

**Comment by vngoliveira** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
just started reviewing! :cherry_blossom:

**Review by rebsilva — APPROVED** [review]
LGTM! :tada: great work @vngoliveira :cherry_blossom:

**Comment by vngoliveira** [comment]
ci:test:sf

**Comment by vngoliveira** [comment]
ci:test:object

**Comment by vngoliveira** [comment]
ci:test:sf

**Comment by vngoliveira** [comment]
ci:test:relevant

**Review by rebsilva — APPROVED** [review]
LGTM!

**Comment by vngoliveira** [comment]
ci:test:sf

**Comment by vngoliveira** [comment]
ci:test:relevant

**Comment by vngoliveira** [comment]
ci:test:object

**Comment by marcelabc** [comment]
Resend: https://github.com/liferay-objects/liferay-portal/pull/3590

**Pull request closed without merging**
