### PR TITLE
LPS-150239 Remove feature flags from user story LPS-147792

### PR DESCRIPTION
**Pull request by mateussgn**
Related Issue: https://issues.liferay.com/browse/LPS-150239

Related issue: https://issues.liferay.com/browse/LPS-150239

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @mateussgn, can you please check if these failures are related to your changes? Thanks

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @mateussgn, can you please check if these failures are related to your changes? Thanks

**Comment by marcelabc** [comment]
hey @mateussgn, the same tests failed  2x. Could check them, please?

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
@marcelabc about the functional tests I'll talk with QA to understand better, I've noticed the tests aren't finding an element, I had run them locally but I didn't get which element is not found.

**Comment by liferay-forms** [comment]
Hey @mateussgn, can you please check if these failures are related to your changes? Thanks

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @mateussgn, can you please check if these failures are related to your changes? Thanks

**Comment by mateussgn** [comment]
ci:reevaluate:1377401_1649

**Comment by mateussgn** [comment]
I'm on it. Running tests locally.

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @mateussgn, can you please check if these failures are related to your changes? Thanks

**Comment by mateussgn** [comment]
ci:reevaluate:1307401_3018

**Comment by mateussgn** [comment]
ci:close

**Comment by mateussgn** [comment]
Resent on: https://github.com/liferay-objects/liferay-portal/pull/571

**Pull request closed without merging**
