### PR TITLE
LPS-162856 Semver

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**
Related issue: https://issues.liferay.com/browse/LPS-162856

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
The fails are not related.

cc: @marcelabc

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by MarinhoFeliphe** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/123099

**Pull request closed without merging**
