### PR TITLE
LPS-163637 Fix the condition

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://issues.liferay.com/browse/LPS-163637

Follow-up: https://github.com/brianchandotcom/liferay-portal/pull/123591
I had to fix one change from Brian's code refactoring.

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:forward

**Comment by marcelabc** [comment]
ci:forward

**Comment by marcelabc** [comment]
ci:reevaluate:1387401_3909

**Comment by marcelabc** [comment]
ci:forward

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:reevaluate:1257401_4734

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
