### PR TITLE
LPS-170051 - The user should not be allowed to sort or filter attachment fields

### PR DESCRIPTION
**Pull request by Artartur**
[LPS-170051](https://issues.liferay.com/browse/LPS-170051)

### CODE REVIEW

**Comment by Artartur** [comment]
ci:test:sf

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:relevant

**Review by naraandrade — CHANGES_REQUESTED** [review]
Hi @Artartur, this is not the ideal solution for the issue. In this case, you're just avoiding showing the error message, when what we actually should do is to not allow the user to create default sorts and default filters for fields of type Attachment and Rich Text. Also, we need to hide the sort symbol in the views page for those same field types. If we don't allow creating default sort for the field we also shouldn't allow sorting directly in the views page. Thanks :)

**Comment by naraandrade** [comment]
Hey @Artartur, I'll close this PR for now. Feel free to send a new one with the changes requested. Thanks for your contribution :)

**Pull request closed without merging**
