### PR TITLE
LPS-197872 Object Node is not standard

### PR DESCRIPTION
**Pull request by larissacribeiro**
Related Issue: [LPS-197872](https://liferay.atlassian.net/browse/LPS-197872)

### CODE REVIEW

**Comment by marcelabc** [comment]
Hey @naraandrade,
I'm assigning this PR to you because it is frontend. Feel comfortable assigning to anybody from your squad :+1:

**Comment by rebsilva** [comment]
just started reviewing! :cherry_blossom:

**Review by rebsilva — APPROVED** [review]
LGTM! :tada: Great job @larissacribeiro! Next time, since these were small changes and related to each other, you can make only one commit instead of two :cherry_blossom:

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:object

**Comment by rebsilva** [comment]
ci:forward:force

**Pull request closed without merging**
