### PR TITLE
LPD-28688

### PR DESCRIPTION
**Pull request by vngoliveira**
[LPD-28688](https://liferay.atlassian.net/browse/LPD-28688)

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:object

**Comment by marcelabc** [comment]
ci:report:19589787

**Comment by marcelabc** [comment]
Hey @vngoliveira,
Can you analyze the unique failures, please? (run it locally to check if it is failing).

**Comment by marcelabc** [comment]
Hey @danvb112 
Since you were the one who reviewed the last PR related to this test, could you please help us review this one?

**Comment by vngoliveira** [comment]
Hey @marcelabc and @danvb112 
About the ObjectActions#CanInactivateAction, it is passing locally; the ObjectFields#CanMappedFormulaFieldOnPages is failing locally, in my PR branch and master as well, with a different error -> `Element is not present at "//div[contains(@class,'dnd-tbody')]//*[contains(text(),'1234')]" ` from the reported.

**Comment by danvb112** [comment]
Hey sorry for the delay, I'll start the review now :smile:

**Comment by vngoliveira** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
Hey @danvb112, can you review it again?

**Review by danvb112 — APPROVED** [review]
LGTM! :tada:

**Comment by danvb112** [comment]
ci:test:playwright

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:stop

**Comment by vngoliveira** [comment]
ci:test:sf

**Comment by vngoliveira** [comment]
ci:test:relevant

**Comment by vngoliveira** [comment]
ci:test:playwright

**Comment by vngoliveira** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:forward:force

**Pull request closed without merging**
