### PR TITLE
LPS-169220 No error message is displayed When a validation is not valid

### PR DESCRIPTION
**Pull request by diogomelo09**
[LPS-169220](https://issues.liferay.com/browse/LPS-169220)

### CODE REVIEW

**Comment by diogomelo09** [comment]
ci:test:relevant

**Comment by diogomelo09** [comment]
ci:test:relevant

**Comment by diogomelo09** [comment]
ci:test:relevant

**Comment by diogomelo09** [comment]
ci:test:relevant

**Comment by diogomelo09** [comment]
ci:test:relevant

**Review by p-albuquerque — CHANGES_REQUESTED** [review]
You need to keep using the old Exception class `ObjectValidationRuleScriptException`
But its only will works, when you create a ExceptionMapper of this class, inside `object-rest-impl`

UPDATE: 
Not needed anymore

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
I'm closing this PR because it was sent to https://github.com/brianchandotcom/liferay-portal/pull/127459/

**Pull request closed without merging**
