### PR TITLE
LPD-27469 [Test Fix] Define flushInterval setting

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://liferay.atlassian.net/browse/LPD-27469

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by carolmariaabb** [comment]
The test is passing [here](https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/898280/consoleFull):

image

**Comment by carolmariaabb** [comment]
Manually forwarded: https://github.com/brianchandotcom/liferay-portal/pull/150959

**Pull request closed without merging**
