### PR TITLE
LPS-197863 Add FF in front end and rename

### PR DESCRIPTION
**Pull request by murilostodolni**
Related: https://liferay.atlassian.net/browse/LPS-197863

### CODE REVIEW

**Review by naraandrade — APPROVED** [review]

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
ci:test:object

**Comment by murilostodolni** [comment]
ci:test:stable

**Comment by victorhcunha** [comment]
ci:test:stable

**Comment by murilostodolni** [comment]
ci:forward:force

**Pull request closed without merging**
