### PR TITLE
LPS-175709 Relationship Tab Don't Disappears When the Object is Inactive

### PR DESCRIPTION
**Pull request by tototrinh**
Hi Team,
Please help review this PR and leave your comments. Thanks.
Ticket: https://issues.liferay.com/browse/LPS-175709
cc @thienquach87

### CODE REVIEW

**Comment by marcelabc** [comment]
Just started reviewing :)

**Review by gabrielwas — APPROVED** [review]
LGTM :D Thanks for the contribution, @tototrinh

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:test:object

**Comment by gabrielwas** [comment]
ci:reevaluate:1267401_8407

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
resent in https://github.com/liferay-objects/liferay-portal/pull/1910

**Pull request closed without merging**
