### PR TITLE
LPS-164019

### PR DESCRIPTION
**Pull request by alinedoleron**
Ticket: https://issues.liferay.com/browse/LPS-164019

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:sf

**Review by rebsilva — APPROVED** [review]
LGTM! :cherry_blossom: Great work @alinedoleron!

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
Hi @naraandrade, do you think those issues are related to this PR?

**Comment by naraandrade** [comment]
If it's all good with the PR, please add the "Good to Go" label and you can send it directly to Brian.

**Comment by alinedoleron** [comment]
> > Hi @naraandrade, do you think those issues are related to this PR?
> 
> Hi @alinedoleron, they are not related. There are several back-end integration tests failing in the last few weeks, and all of them have the same error in common `java.lang.ClassNotFoundException: com.liferay.object.model.ObjectDefinition#68097 cannot be found by com.liferay.object.service_1.0.104`. We already have tickets open for them and we suspect that they all have the same cause, but we are still working to fix them.

Thank you for the clarification, @naraandrade!

**Comment by alinedoleron** [comment]
Manually forwarded to Brian https://github.com/brianchandotcom/liferay-portal/pull/124128

**Pull request closed without merging**
