### PR TITLE
LPS-163588 If a product is published or saved as draft, it's not visible on the products list and cannot be searched

### PR DESCRIPTION
**Pull request by seltong**
Related issue: https://issues.liferay.com/browse/LPS-163588

### CODE REVIEW

**Comment by seltong** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by seltong** [comment]
@naraandrade sure, I will do it

**Pull request closed without merging**
