### PR TITLE
LPS-154071 Remove Headless and Service for queueEntry And enable messageListener

### PR DESCRIPTION
**Pull request by gustavolimav**

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:relevate

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
Just started reviewing :)

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
resent here https://github.com/liferay-objects/liferay-portal/pull/683

**Pull request closed without merging**
