### PR TITLE
LPS-139259 Render blocks with their proper layout

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
@marcelabc

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcelabc** [comment]
fwd: https://github.com/brianchandotcom/liferay-portal/pull/107423

**Comment by guilhermedcamacho** [comment]
Sent directly to Brian in this [PR](https://github.com/brianchandotcom/liferay-portal/pull/107446)

**Pull request closed without merging**
