### PR TITLE
LPS-201143 In Model Builder change Uncategorized to Default

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPS-201143](https://liferay.atlassian.net/browse/LPS-201143)

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Review by mateussgn — APPROVED** [review]
LGTM! 🎉

**Comment by mateussgn** [comment]
Hey @MarinhoFeliphe, could you please double-check this PR?

**Review by MarinhoFeliphe — CHANGES_REQUESTED** [review]
Hey @pedro-oliveira446 I've found only one place that I believe you missed a small change, please see my comments!

Nice job!

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM!! :tada:

**Comment by pedro-oliveira446** [comment]
ci:forward:force

**Pull request closed without merging**
