### PR TITLE
LPS-184535 SF

### PR DESCRIPTION
**Pull request by seltong**
Follow-up:  https://github.com/brianchandotcom/liferay-portal/commit/cb9fbde5150bf61a29cf3309600f7ab5e3e1495c

### CODE REVIEW

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:object

**Comment by marcelabc** [comment]
ci:reevaluate:1277401_8462

**Comment by marcelabc** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:forward:force

**Pull request closed without merging**
