### PR TITLE
LPS-146618 Update eslintrc.js to prevent unnecessary changes in d.ts files

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-146618

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@danvb112 I merged this manually.

**Comment by danvb112** [comment]
Thanks @brianchandotcom!

**Pull request closed without merging**
