### PR TITLE
LPS-162459,LPS-162456

### PR DESCRIPTION
**Pull request by rodrigopaulino**

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
Hey, @carolmariaabb. You just need to review the last two commits. The other ones you already did on my previous attempt to send this code. Thanks in advance.

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Review by carolmariaabb — APPROVED** [review]
❤️

**Comment by rodrigopaulino** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:reevaluate:1377401_5259

**Comment by rodrigopaulino** [comment]
ci:reevaluate:1377401_5259

**Comment by rodrigopaulino** [comment]
Manually forwarded: https://github.com/brianchandotcom/liferay-portal/pull/123713

**Pull request closed without merging**
