### PR TITLE
LPD-21807 Use the objectFolderId to compare as the objectFolderExternalReferenceCode can be edited

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://liferay.atlassian.net/browse/LPD-21807

### CODE REVIEW

**Review by G-Sa — APPROVED** [review]
LGTM :tada:

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
