### PR TITLE
LPS-159483 Remove Feature Flag for LPS-159052

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://issues.liferay.com/browse/LPS-159483

### CODE REVIEW

**Review by rodrigopaulino — APPROVED** [review]
LGTM! 🎉

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by rodrigopaulino** [comment]
I believe this can be manually forwarded.

**Comment by carolmariaabb** [comment]
ci:reevaluate:1267401_5325

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Manually forwarded: https://github.com/brianchandotcom/liferay-portal/pull/124137

**Comment by carolmariaabb** [comment]
ci:close

**Pull request closed without merging**
