### PR TITLE
LPS-149112 Adapt View Builder to support new Column Label

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-149112

Hello Reviwer! This PR is Related to Story: [As a power user, I want to create an alias for a column on view builder](https://issues.liferay.com/browse/LPS-147792)

[LPS-149112](https://issues.liferay.com/browse/LPS-149112) - Add second column in the view builder
[LPS-149113](https://issues.liferay.com/browse/LPS-149113) - Change the icons to dropdown
[LPS-149114](https://issues.liferay.com/browse/LPS-149114) - Create modal for edition

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:forward

**Comment by liferay-forms** [comment]
Hey @danvb112, can you please check if these failures are related to your changes? Thanks

**Pull request closed without merging**
