### PR TITLE
LPS-172145 Remove all calls for Liferay.ThemeDisplay.getDefaultLanguageId() and use the defaultLanguageId exported on contants.ts in object-web-module

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-172145

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
@danvb112 Please, make sure this PR doesn't overwrite what you've done on https://github.com/liferay-objects/liferay-portal/pull/1872. 

The SF failures are related to some .d.ts files you shouldn't commit.

**Review by naraandrade — CHANGES_REQUESTED** [review]
@danvb112 Please, make sure this PR doesn't overwrite what you've done on https://github.com/liferay-objects/liferay-portal/pull/1872. 

The SF failures are related to some .d.ts files you shouldn't commit.

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:forward

**Pull request closed without merging**
