### PR TITLE
LPD-23804 Verify if ObjectValidation errorMessage matches user language

### PR DESCRIPTION
**Pull request by rijema**
Sending here a test for an old LPD

https://liferay.atlassian.net/browse/LPD-23804

### CODE REVIEW

**Comment by linolaoj** [comment]
Hi @rijema as we talked earlier today, let's run the tests of the class locally to make sure the other tests are not affected.

**Comment by rijema** [comment]
Hi @linolaoj , no other test is being affected. Currently we're facing 6 failing tests with or without my fix. I also updated the code to suit better the alphabetical order. Thx!

**Review by rijema — COMMENTED** [review]
Called the local _userLocalService to update the language to follow the private objects order.

**Review by linolaoj — APPROVED** [review]

**Comment by linolaoj** [comment]
ci:forward

**Pull request closed without merging**
