### PR TITLE
LPD-23164

### PR DESCRIPTION
**Pull request by rijema**
Before sending PR, I'm creating this one to run the suites.

### CODE REVIEW

**Comment by rijema** [comment]
ci:test:relevant

**Comment by rijema** [comment]
Previous one: https://github.com/brianchandotcom/liferay-portal/pull/149276

**Comment by rijema** [comment]
Last PR: https://github.com/liferay-objects/liferay-portal/pull/3244

**Comment by rijema** [comment]
ci:test:objects

**Comment by rijema** [comment]
ci:test:object

**Comment by rijema** [comment]
ci:test:relevant

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM!! :tada:

@rijema Nice job!!

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Pull request closed without merging**
