### PR TITLE
LPS-199363 Picklist key autocomplete with special characters even though they cannot be used

### PR DESCRIPTION
**Pull request by larissacribeiro**
Related Issue: [LPS-199363](https://liferay.atlassian.net/browse/LPS-199363)

### CODE REVIEW

**Comment by larissacribeiro** [comment]
ci:stop

**Comment by larissacribeiro** [comment]
ci:test:sf

**Review by igor-franca — APPROVED** [review]
Thanks for this PR, good job @larissacribeiro!

**Comment by igor-franca** [comment]
ci:test:object

**Comment by igor-franca** [comment]
ci:test:relevant

**Comment by igor-franca** [comment]
ci:forward:force

**Comment by igor-franca** [comment]
ci:forward:force

**Comment by igor-franca** [comment]
ci:forward:force

**Comment by larissacribeiro** [comment]
ci:forward:force

**Comment by larissacribeiro** [comment]
Manually forwarded here: https://github.com/brianchandotcom/liferay-portal/pull/143012

**Pull request closed without merging**
