### PR TITLE
LPS-188853 Object Folder

### PR DESCRIPTION
**Pull request by murilostodolni**
Related:

https://liferay.atlassian.net/browse/LPS-188851
https://liferay.atlassian.net/browse/LPS-188852
https://liferay.atlassian.net/browse/LPS-188854
https://liferay.atlassian.net/browse/LPS-188855

@gabrielwas could you review this commit https://github.com/liferay-objects/liferay-portal/pull/2384/commits/05397444765a3e60474b6a837d1b51fc42174adb down, please?

### CODE REVIEW

**Review by gabrielwas — COMMENTED** [review]
LGTM :)

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
ci:test:object

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by murilostodolni** [comment]
ci:test:environments

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
ci:test:object

**Comment by murilostodolni** [comment]
ci:forward:force

**Comment by murilostodolni** [comment]
ci:forward:force

**Comment by marcelabc** [comment]
ci:forward:force

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:forward:force

**Comment by murilostodolni** [comment]
ci:forward:force

**Comment by murilostodolni** [comment]
Forward manually: https://github.com/brianchandotcom/liferay-portal/pull/138595

**Comment by murilostodolni** [comment]
ci:close

**Pull request closed without merging**
