### PR TITLE
LPS-158866 Account Restrictions on object details page shold be disabled

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-158866

### CODE REVIEW

**Comment by mateussgn** [comment]
Should I make this same restriction on the Rest API side? If yes, I'll resend the PR.

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
@mateussgn yes, we should prevent it from the API side too. Can you implement it?

You can check the "publish" behavior. It's quite the same.

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Hey, @mateussgn. Let me know when you fix the SF errors. :)

**Comment by mateussgn** [comment]
ci:test:relevant

**Review by rodrigopaulino — APPROVED** [review]
LGTM! 🎉

**Comment by rodrigopaulino** [comment]
ci:forward

**Pull request closed without merging**
