### PR TITLE
LPS-202728

### PR DESCRIPTION
**Pull request by igor-franca**
Related to:

[LPS-202728](https://liferay.atlassian.net/browse/LPS-202728)
https://github.com/liferay-forms/liferay-portal/pull/2403

### CODE REVIEW

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Review by alinedoleron — COMMENTED** [review]
Hi @icgsbr. There's a conflict here.

**Comment by alinedoleron** [comment]
> @igor-franca

Sorryyyyyy!!!! 😄

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:test:stable

**Comment by igor-franca** [comment]
ci:forward:force

**Pull request closed without merging**
