### PR TITLE
LPS-180487 Default values info alert is missing a link to documentation

### PR DESCRIPTION
**Pull request by larissacribeiro**
**Related Issue**: [**LPS-180487**](https://issues.liferay.com/browse/LPS-180487)

### CODE REVIEW

**Review by cgmonte — CHANGES_REQUESTED** [review]
Hi, @larissacribeiro! Thanks for sending this :smiley: Could you please squash all changes to just one commit? You can add @diogomelo09 as a [co-author](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) so both of you appear as authors.

**Comment by larissacribeiro** [comment]
ci:test:object
 ci:test:relevant

**Comment by larissacribeiro** [comment]
ci:test:object

**Comment by larissacribeiro** [comment]
ci:test:relevant

**Review by cgmonte — APPROVED** [review]
LGMT!

**Comment by cgmonte** [comment]
ci:forward

**Pull request closed without merging**
