### PR TITLE
LPS-182813 Remove feature flag for LPS-143068

### PR DESCRIPTION
**Pull request by rebsilva**
Related Issue: https://issues.liferay.com/browse/LPS-182813

:warning: Don't send this before all the requirements for the FF to be removed are done. You can know more about it [here](https://liferay.slack.com/archives/C026UR5976G/p1685454423064169).

Thanks for the review! :cherry_blossom:

### CODE REVIEW

**Comment by samuelromeiro** [comment]
Blocked because we are waiting QA and product validation.

**Comment by rebsilva** [comment]
ci:test:sf

**Review by murilostodolni — APPROVED** [review]
LGTM 🎉

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Comment by samuelromeiro** [comment]
The story is closed. 
PR is unblocked 🥳

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
I will run the relevant again as @andreefarias asked.

**Comment by rebsilva** [comment]
QA reviewed the failing tests and everything is fine!

**Comment by rebsilva** [comment]
ci:forward:force

**Comment by murilostodolni** [comment]
ci:forward:force

**Pull request closed without merging**
