### PR TITLE
LPS-171272 [SiteInitializer] Update ObjectAction by ERC

### PR DESCRIPTION
**Pull request by joseabelenda**
- LPS-171272 Implement service and localService methods
- LPS-171272 Regen buildService
- LPS-171272 Adjust tests
- LPS-171272 Change rest-openapi.yaml
- LPS-171272 Regen buildRest
- LPS-171272 Prevent NPE
- LPS-171272 Add ERC to DTO
- LPS-171272 Fix rest tests
- LPS-171272 Adjust rest tests
- LPS-171272 Ignore GraphQL tests
- LPS-171272 Update BundleSiteInitializer
- LPS-171272 Update sites resources

### CODE REVIEW

**Comment by joseabelenda** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
Just started reviewing :)

**Comment by joseabelenda** [comment]
ci:test:object

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:stable

**Comment by marcelabc** [comment]
I'm double-checking how the team should proceed regarding adding the ERC for the Object Action: if it should be scoped by the company or by Object Definition.

**Comment by marcelabc** [comment]
Hi @joseabelenda
It was confirmed that the ERC should be referenced by the Object Definition. I will refactor this PR :+1: 
Thank you!

**Comment by marcelabc** [comment]
Resent: https://github.com/liferay-objects/liferay-portal/pull/1632
cc: @joseabelenda

**Pull request closed without merging**
