### PR TITLE
LPS-137846 Add flag for validate object field name when calling from update

### PR DESCRIPTION
**Pull request by interaminense**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Already fixed in this [commit](https://github.com/brianchandotcom/liferay-portal/pull/105987/files#diff-a50d68735e9840b6a835fed264e1b77700dcf952afe1eb61018ab8462a691a16L164)
cc: @gabrielwas , @interaminense

**Pull request closed without merging**
