### PR TITLE
LPS-164950 Create FF to filter the Formula and MultiSelectPicklist businessType

### PR DESCRIPTION
**Pull request by danvb112**
Related Issues: 
https://issues.liferay.com/browse/LPS-165644
https://issues.liferay.com/browse/LPS-164950

Hello @alinedoleron, I sent in this PR the creation of two Feature flags from different stories related to the Formula Field field and the Multi-Select Picklist field, to avoid conflicts and speed up the development process

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:relevant

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by danvb112** [comment]
ci:forward

**Comment by danvb112** [comment]
ci:forward

**Pull request closed without merging**
