### PR TITLE
LPS-157056 Specify maxValue and minValue for Integer and Long Integer and maxValue, minValue and decimalPartMaxLength for Precision Decimal field types of Objects

### PR DESCRIPTION
**Pull request by ruben-pulido**
Hi team!

This PR sets the maximum and minimum values for Integer, Long Integer and Precision Decimal field types, as well as the decimalPartMaxLength for Precision Decimal, so validation can be performed when mapping Numeric Input Fields in the Page Editor to Objects fields of these types.

For Decimal, we would need to specify these values as well, for which this [task](https://issues.liferay.com/browse/LPS-157056) has been created.

Thank you!

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
Hi @ruben-pulido! This PR looks good to me!

But I could see that some discussions are still in progress [in this thread](https://liferay.slack.com/archives/C031NTPALAV/p1655462961354069) on slack. Maybe we should get to a conclusion about it first before forwarding this PT, what do you think? 

We can try to schedule a meeting together along with @mateussgn. Let me know. Thx!

**Comment by gabrielwas** [comment]
@ealonso of course, we could. About long integer and precision decimal, we're aligned. 
For this PR, I'm just still wondering about the integer max/min value.

@mateussgn told us these values:

**Integer**
Maximum value: 2147483647
Minimum value: -2147483648

In this PR, the values are:

**Integer**
Maximum value: BigDecimal.valueOf(999_999_999)
Minimum value: BigDecimal.valueOf(-999_999_999)


Am I missing something?

**Comment by ruben-pulido** [comment]
Hi @gabrielwas!
Thanks for looking into it.

@mateussgn provided these values after the PR was opened, which is why the PR does not use them yet.

Can update them yourself and forward it to Brian?
Otherwise I can do it later.

**Comment by gabrielwas** [comment]
Of course, @ruben-pulido! Thanks for the quick answer!

@mateussgn can you do it, please?

**Comment by ruben-pulido** [comment]
Hi @gabrielwas @mateussgn 
Since the PR has unresolved conflicts I'm going to resolve them, update the PR with the new values @mateussgn provided for Integer and forward it to Brian

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ruben-pulido** [comment]
ci:forward

**Pull request closed without merging**
