### PR TITLE
LPS-180662 Notification templates form is not responsive

### PR DESCRIPTION
**Pull request by Valmir-unicap**
Related issue: https://issues.liferay.com/browse/LPS-180662?filter=55034

### CODE REVIEW

**Review by rebsilva — CHANGES_REQUESTED** [review]
Hi @Valmir-unicap, thanks for your work! Could you please explain me why you chose 40? Also shouldn't this be fixed too? The other part is fixed but this isn't:

Screenshot from 2023-04-05 14-31-10

**Comment by Valmir-unicap** [comment]
hello @rebsilva silva, I chose 40% because it better adjusts the responsiveness of the page, when zooming from 90% to 67%. As it was before, these zooms were breaking the page. In cases 50% to 25% I realized now that it needs to be treated too.

**Comment by rebsilva** [comment]
Thanks for you explanation @Valmir-unicap! I will wait you to send the rest of the fix so I can review it again ok? Thanks!

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:test:object

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
Just started reviewing! :cherry_blossom:

**Review by rebsilva — APPROVED** [review]
LGTM! :tada:

**Comment by rebsilva** [comment]
The tests failing are not related, so I will forward the PR!

**Comment by rebsilva** [comment]
ci:forward

**Pull request closed without merging**
