### PR TITLE
LPS-185031 Allow creation of update object action in unpublished object definitions

### PR DESCRIPTION
**Pull request by devpedrotavares**
Related issue: [LPS-185031](https://issues.liferay.com/browse/LPS-185031)

### CODE REVIEW

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Comment by carolmariaabb** [comment]
@devpedrotavares could you please fix the test `com.liferay.object.service.test.ObjectActionLocalServiceTest.testAddObjectAction`?

**Comment by devpedrotavares** [comment]
ci:test:sf

**Comment by devpedrotavares** [comment]
ci:test:relevant

**Review by carolmariaabb — APPROVED** [review]

**Comment by devpedrotavares** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
