### PR TITLE
LPS-195451 Call get instead of fetch in ObjectDefinitionResourceImpl#getObjectDefinitionByExternalReferenceCode

### PR DESCRIPTION
**Pull request by G-Sa**
Related to [LPS-195451](https://liferay.atlassian.net/browse/LPS-195451)

### CODE REVIEW

**Comment by G-Sa** [comment]
ci:test:relevant

**Comment by G-Sa** [comment]
Since this could impact a lot of tests and it is a simple change, i'm running tests before the code reviews finish

**Comment by G-Sa** [comment]
@marcelabc, just so you know, there were no unique failures according to the the testray CSV files from [objects](https://test-1-1.liferay.com/job/generate-testray-csv/7646/) and [relevant](https://test-1-1.liferay.com/job/generate-testray-csv/7647/)

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by G-Sa** [comment]
ci:forward:force

**Pull request closed without merging**
