### PR TITLE
LPS-138740 buildLang

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
sent to Brian here: https://github.com/brianchandotcom/liferay-portal/pull/107156

**Comment by mateussgn** [comment]
I'll close this one. Already merged here https://github.com/brianchandotcom/liferay-portal/pull/107156

**Comment by mateussgn** [comment]
ci:close

**Pull request closed without merging**
