### PR TITLE
LPD-26252 Pass the string length when using setClob method

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://liferay.atlassian.net/browse/LPD-26252

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:sf

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marco-leo** [comment]
@carolmariaabb Fantastic

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
