### PR TITLE
LPS-185676 [FE] As an Object Admin, I want to manage relationships in my model

### PR DESCRIPTION
**Pull request by rebsilva**
Related Issue: https://liferay.atlassian.net/browse/LPS-185676

Hello Reviewer! :cherry_blossom: 

This PR has all the commits necessary for the story _As an Object Admin, I want to manage relationships in my model_

Please review only the last commit since the others were reviewed here: https://github.com/liferay-objects/liferay-portal/pull/2604

Thanks!

### CODE REVIEW

**Comment by rebsilva** [comment]
@naraandrade can you please review the last commit? Thanks!

**Comment by rebsilva** [comment]
ci:test:object

**Review by naraandrade — APPROVED** [review]

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/141355

**Pull request closed without merging**
