### PR TITLE
LPD-16072 Use appropriate date pattern for HSQL and DB2

### PR DESCRIPTION
**Pull request by devpedrotavares**
Related ticket: [LPD-16072](https://liferay.atlassian.net/browse/LPD-16072)

### CODE REVIEW

**Review by G-Sa — APPROVED** [review]
LGTM

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
ci:report:2543510129

**Comment by devpedrotavares** [comment]
ci:report:2543511415

**Comment by devpedrotavares** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
ci:test:object

**Comment by devpedrotavares** [comment]
ci:report:2544232660

**Comment by devpedrotavares** [comment]
ci:forward

**Pull request closed without merging**
