### PR TITLE
LPS-138492 Change the usage of name field to label field in Forms and Display Pages

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:reevaluate:1307401_197

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Resent here: https://github.com/liferay-objects/liferay-portal/pull/82

**Comment by rodrigocunhaa** [comment]
ci:close

**Pull request closed without merging**
