### PR TITLE
LPS-154582 Move some object-web React components to new object-js-components-web module

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-154582

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
Hey @naraandrade, @rodrigopaulino and @gabrielwas, I've created the new module `object-js-components-web` suggested by you on https://github.com/liferay-objects/liferay-portal/pull/649, could you please take a look and see if it's all right? Thanks! :smile:

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — CHANGES_REQUESTED** [review]
Hi @danvb112, it looks good to me :) But I think it would be better to do a rebase when these [changes](https://github.com/brianchandotcom/liferay-portal/pull/118135) sync with master because they will likely generate some conflicts with your changes.

**Comment by naraandrade** [comment]
Just saw the conflicts were already identified lol

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:forward

**Comment by danvb112** [comment]
ci:forward

**Pull request closed without merging**
