### PR TITLE
[TS] LPS-162236

### PR DESCRIPTION
**Pull request by jcampoy**
https://issues.liferay.com/browse/LPS-162236

### CODE REVIEW

**Comment by jcampoy** [comment]
ci:test:sf

**Comment by jcampoy** [comment]
ci:test:relevant

**Comment by jcampoy** [comment]
ci:test:relevant

**Comment by jcampoy** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
@jcampoy Thanks a lot for the contribution! 

@marcelabc @MarinhoFeliphe I think we can accept this as a temporary fix, but remember we should consider how to search over all the system fields. Is there any ticket created for this? If not, can any of you create it? Thx!

**Comment by MarinhoFeliphe** [comment]
@gabrielwas,

got it! I'm going to review his changes today, 

> Is there any ticket created for this?

I didn't found a ticket with this bug description, I'll ask for the QA team to create it.

cc: @marcelabc

**Comment by jcampoy** [comment]
Hi @gabrielwas , 
you are welcome! IMHO For a complete fix we should considere to search with ES, it would be better even from the performance point of view, however this is the minimal fix with the existent code to add the ID in the data-base searches.

If you have any question about the solution, let me know! thank you for the review!

Jose

**Comment by gabrielwas** [comment]
Hi @jcampoy! 

Yep, we used to retrieve entries based on ES (we still index them). But we're implementing features like aggregation and formula fields that perform some operations over field values and ES is not that good for this kind of processing. So, for now, we've decided to use DB directly. We considered using a hybrid approach (ES + DB), but it's still under analysis. 

Thanks again for the suggestion!

**Comment by MarinhoFeliphe** [comment]
Taking a look.

**Comment by MarinhoFeliphe** [comment]
Resent here: https://github.com/liferay-objects/liferay-portal/pull/1058

**Pull request closed without merging**
