### PR TITLE
LPS-178448 Change namings of field sets when mapping objects

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-178448)

This is a follow up task to https://issues.liferay.com/browse/LPS-176815 which enables the mapping of related items in collection providers.

Based on the designs of the story, the naming of the definitions should include "Fields" for the object definition that is being shown in the collection provider, and "Relationship Fields" for related definition

## Change summary:

* Change the order of the field sets based on design. Fields for the object definition should come before basic information
* Add translated label to the field sets

## Test Scenario

* Create two objects, and add a one to many relationship to them. An example can be Country and Cities, where a city belongs to a country
* Create several countries and cities
* Add a collection fragment to a page and configure it so that it shows cities
* Add a fragment to the collection provider and map it
* The fields for city should be available as a fieldset under "City Fields"
* The fields for country should be available as a fieldset under "Country Relationship Fields"

Screenshot 2023-03-14 at 11 55 20

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
@jkappler 

I'm gonna review this pull request as soos as possible, thanks for your contribution!

Best Regards,
Feliphe

**Comment by jkappler** [comment]
thanks @MarinhoFeliphe!

**Review by MarinhoFeliphe — CHANGES_REQUESTED** [review]
@jkappler 

could you please try to define two 1:M between the same object definitions?

for example:

Assignee -> Employee 1:M Ticket
Reporter -> Employee 1:M Ticket

we need to make sure that the list of relationship fields will be listed based on the relationship name to avoid confusing, for example:

Assignee relationship fields

...

Reporter relationship fields

...

instead of:

Employee relationship fields

...

Employee relationship fields

...

Thank you!
Feliphe

**Comment by jkappler** [comment]
Hi @MarinhoFeliphe, changed according to your comments, I didn't reorder the fieldsets, since now I don't know if we want to. Let me know what you think.

Also, maybe we'll want to remove the relationships under the child object in the future?

Thanks as always!

Screenshot 2023-03-21 at 16 11 04

**Review by MarinhoFeliphe — APPROVED** [review]
@jkappler  LGTM!! :tada:

thanks for your contribution!

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by jkappler** [comment]
Thanks to you @MarinhoFeliphe!

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
