### PR TITLE
LPS-196920 It is possible to exit the modal while publishing Objects in Model Build

### PR DESCRIPTION
**Pull request by Artartur**
Related Issue: [LPS-196920](https://liferay.atlassian.net/browse/LPS-196920)

### CODE REVIEW

**Comment by Artartur** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Comment by naraandrade** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/142462

**Pull request closed without merging**
