### PR TITLE
LPD-23594 Keep the checkbox selected if the setting cannot be deactivated

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://liferay.atlassian.net/browse/LPD-23594

### CODE REVIEW

**Review by rebsilva — APPROVED** [review]
LGTM! :cherry_blossom:

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:stable

**Comment by danvb112** [comment]
ci:forward:force

**Pull request closed without merging**
