### PR TITLE
LPS-175174

### PR DESCRIPTION
**Pull request by murilostodolni**
Related: https://issues.liferay.com/browse/LPS-175174

### CODE REVIEW

**Comment by murilostodolni** [comment]
Hey @rebsilva could you review this commit 6a3cfed30695248164497e2ad324e0bdbf144d76, please?

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Review by rebsilva — APPROVED** [review]
LGTM! :tada: :purple_heart:

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
ci:test:object

**Comment by murilostodolni** [comment]
QA CI Approved: https://liferay.slack.com/archives/C048YNC5GRK/p1676459054282299

**Comment by murilostodolni** [comment]
Forwarding manually: https://github.com/brianchandotcom/liferay-portal/pull/130350

**Comment by murilostodolni** [comment]
ci:close

**Pull request closed without merging**
