### PR TITLE
LPS-180861 Add integration tests to ensure that is possible use actions with modifiable system objects

### PR DESCRIPTION
**Pull request by seltong**
Related issue: https://issues.liferay.com/browse/LPS-180861

### CODE REVIEW

**Comment by seltong** [comment]
This pull request is blocked by https://github.com/brianchandotcom/liferay-portal/pull/132885.

If this pull request is reviewed before the https://github.com/brianchandotcom/liferay-portal/pull/132885 is merged, can we merge the commits from these pull requests?

cc: @samuelromeiro and @gabrielwas

**Comment by seltong** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
@seltong can you rebase it? Thx

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:object

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:object

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Please see: https://github.com/liferay-objects/liferay-portal/pull/2126

**Pull request closed without merging**
