### PR TITLE
LPD-28483

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM!! :tada:

**Comment by gabrielwas** [comment]
c:test:relevant

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:forward

**Comment by gabrielwas** [comment]
resent here https://github.com/liferay-objects/liferay-portal/pull/3489

**Pull request closed without merging**
