### PR TITLE
LPS-190890 Add feature flag

### PR DESCRIPTION
**Pull request by ccorreagg**

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Review by gabrielwas — APPROVED** [review]
LGTM!

**Comment by gabrielwas** [comment]
Thx for the contribution @ccorreagg. Let's just wait for the CI results.

**Comment by ccorreagg** [comment]
I don't think we have added any failure, so I am forwarding to Brian

**Comment by ccorreagg** [comment]
ci:forward:force

**Pull request closed without merging**
