### PR TITLE
LPS-198290 Remove if clause to verify always the permissions when deleting an object entry

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:object

**Comment by 4lejandrito** [comment]
Hey guys see https://github.com/liferay-objects/liferay-portal/pull/3015.

**Comment by 4lejandrito** [comment]
ci:close

**Pull request closed without merging**
