### PR TITLE
LPS-195167 Storage Folder is not being predefined by default in the attachment field

### PR DESCRIPTION
**Pull request by Artartur**
Related Issue: [LPS-195167](https://liferay.atlassian.net/browse/LPS-195167)

### CODE REVIEW

**Comment by marcelabc** [comment]
Hey @cgmonte ,
I'm assigning this PR to you because it is frontend. Feel comfortable assigning to anybody from your squad :+1:

**Review by cgmonte — COMMENTED** [review]
the added `useEffect` created a render loop in my machine on selecting the Attachment field type:

screenshot-1700584184

Please check if this is not happening in you environment as well.

**Comment by Artartur** [comment]
ci:test:sf

**Review by cgmonte — CHANGES_REQUESTED** [review]
Hey, Arthur, the infinite loop rendering still happens. Take a look again please.

**Comment by Artartur** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:object

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
