### PR TITLE
LPS-182546 Object's errors in the Page Editor when changing instance default language

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-182546

Hi Team 👋 
I have found several bugs related to localization in the Info Framework when the site default locale is not the same as the instance default one.
I have grouped those related to Objects in a ticket --> https://issues.liferay.com/browse/LPS-182546
Please could you review it?
Thank you so much!

### CODE REVIEW

**Comment by istvangergely** [comment]
Hi @guilhermedcamacho,

I was wondering if you had the opportunity to check this pull request. It would be great to finish this as soon as possible because we need the fix for a customer's go-live which has already passed the deadline.

Thank you in advance!
István

**Review by guilhermedcamacho — APPROVED** [review]
LGTM!

**Comment by guilhermedcamacho** [comment]
I just need to check the CI results now before forward this to Brian. I will let you guys know in a few hours.

**Comment by guilhermedcamacho** [comment]
ci:forward:force

**Pull request closed without merging**
