### PR TITLE
LPD-18455 if the user is the guest user it can be null, so add a new method to get the proper user

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
-----
Fix an issue with display pages and objects for guest users.

Proposed Solution
-----
Creates a new method where we are using fetch method to get the user and if it is null, return the guest user.

### CODE REVIEW

**Review by gabrielwas — APPROVED** [review]
LGTM. Thx for the contribution, @ealonso!

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:test:object

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:report:2542437466

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
