### PR TITLE
LPS-179097 Evaluate Parent Object terms

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPS-179097

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
@p-albuquerque [see](https://github.com/p-albuquerque/liferay-portal/pull/51)

**Comment by p-albuquerque** [comment]
Resent in: https://github.com/liferay-objects/liferay-portal/pull/1989

**Pull request closed without merging**
