### PR TITLE
LPD-17928

### PR DESCRIPTION
**Pull request by gabrielwas**
https://liferay.atlassian.net/browse/LPD-17928

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:test:object

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:report:2539535571

**Comment by carolmariaabb** [comment]
ci:report:2539497750

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by gabrielwas** [comment]
Resent here: https://github.com/liferay-objects/liferay-portal/pull/3109

**Comment by samuelromeiro** [comment]
Resend in here https://github.com/liferay-objects/liferay-portal/pull/3111

**Pull request closed without merging**
