### PR TITLE
LPD-36054 When filtering localized fields from a relationship, also include the localization table in the SQL join query

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://liferay.atlassian.net/browse/LPD-36054

### CODE REVIEW

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:report:32605427

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
