### PR TITLE
LPS-147532 Adapt the method to show the 'Relationship' option in specifics scenarios

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://issues.liferay.com/browse/LPS-147532

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Review by mateussgn — APPROVED** [review]

**Comment by mateussgn** [comment]
LGTM! 🎉

**Comment by gabrielwas** [comment]
LGTM!

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:forward

**Comment by marcelabc** [comment]
I'm going to fix the issues.

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
I changed the label because I fixed the major issue.

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
