### PR TITLE
LPS-137866 Validate integer and long type size to prevent wrong data save

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-137866

This is a follow-up PR regarding some changes required by Brian on this [PR](https://github.com/brianchandotcom/liferay-portal/pull/111771).

### CODE REVIEW

**Comment by mateussgn** [comment]
This is a follow-up PR regarding some changes required by Brian [on this PR](https://github.com/brianchandotcom/liferay-portal/pull/111771).

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Hey @mateussgn, 
Some integration tests failed twice, could you please check if they are flaky or not?
The tests:
com.liferay.object.service.test.ObjectEntryLocalServiceTest.testUpdateObjectEntry
com.liferay.object.service.test.ObjectEntryLocalServiceTest.testAddObjectEntry

**Comment by mateussgn** [comment]
Sure @marcelabc. I'm already taking a look at it.

**Comment by marcelabc** [comment]
This PR is good to go regarding the code, but must investigate the tests failures before forwarding.

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
I'm fixing the tests.

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:object

**Comment by mateussgn** [comment]
ci:close

**Comment by mateussgn** [comment]
Resent on https://github.com/liferay-objects/liferay-portal/pull/377

**Pull request closed without merging**
