### PR TITLE
LPS-148190 Order matters in the UI

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://issues.liferay.com/browse/LPS-148190

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:reevaluate:1297401_1856

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:forward

**Comment by gabrielwas** [comment]
ci:forward

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
