### PR TITLE
[TS] [Urgent] LPD-18008 Make "or" filters in GraphQL work correctly with Object Entry queries

### PR DESCRIPTION
**Pull request by mbowerman**
Marked urgent because our client reported that this is heavily impacting their users' ability to search.

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:object

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
Hey @mbowerman ,

Would it be necessary also adding the parenthesis in [this predicate](https://github.com/liferay/liferay-portal/blob/f182f5eea86bf0b9e935e5012555cce5a5c4da24/modules/apps/object/object-service/src/main/java/com/liferay/object/service/impl/ObjectEntryLocalServiceImpl.java#L711)?

**Comment by marcelabc** [comment]
Hey @mbowerman,
Would it be possible to add an integration test, please?

**Comment by mbowerman** [comment]
Hello @ccorreagg , @marcelabc,

I've force-pushed a change to add the parentheses to the other predicate that you mentioned, and I've added an integration test as well.

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:object

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:report:2541433828

**Comment by marcelabc** [comment]
ci:report:2541433851

**Review by marcelabc — APPROVED** [review]
LGTM 🎉
Thank you for your collaboration @mbowerman !

**Comment by marcelabc** [comment]
ci:forward:force

**Pull request closed without merging**
