### PR TITLE
LPD-37412 Extract modals from ViewObjectDefinitions to its own component to improve code readability

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://liferay.atlassian.net/browse/LPD-37412

Hey @rebsilva, This PR doesn't need unit or functional tests as I'm just rewriting the existing code, so all the tests we already have will be needed to cover this PR

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:sf

**Review by rebsilva — APPROVED** [review]
LGTM! :tada:

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:forward:force

**Pull request closed without merging**
