### PR TITLE
LPS-201584 Make the default placeholder for Select fields have localization

### PR DESCRIPTION
**Pull request by rebsilva**
Related Issue: https://liferay.atlassian.net/browse/LPS-201584

### CODE REVIEW

**Review by igor-franca — APPROVED** [review]

**Comment by igor-franca** [comment]
ci:test:object

**Comment by igor-franca** [comment]
ci:test:relavant

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:stop

**Comment by rebsilva** [comment]
i'll resend this because the ci tests are not working properly, thanks!

**Pull request closed without merging**
