### PR TITLE
LPS-162456

### PR DESCRIPTION
**Pull request by rodrigopaulino**

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Review by carolmariaabb — APPROVED** [review]

**Comment by rodrigopaulino** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by rodrigopaulino** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:reevaluate:1257401_4587

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by rodrigopaulino** [comment]
ci:forward

**Comment by rodrigopaulino** [comment]
ci:reevaluate:1307401_4637

**Comment by rodrigopaulino** [comment]
Resent https://github.com/liferay-objects/liferay-portal/pull/1068

**Pull request closed without merging**
