### PR TITLE
LPS-205374 Unique field constraint is not site-scoped

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:object

**Comment by guilhermedcamacho** [comment]
See #3041

**Review by pedro-oliveira446 — APPROVED** [review]

**Comment by pedro-oliveira446** [comment]
ci:forward:force

**Pull request closed without merging**
