### PR TITLE
LPS-172454 Add new register for the new created mapper

### PR DESCRIPTION
**Pull request by kiwm**
Related Issue: https://issues.liferay.com/browse/LPS-172454

### CODE REVIEW

**Comment by kiwm** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Just started reviewing :)

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Hi @kiwm, 
There is a [PR](https://github.com/brianchandotcom/liferay-portal/pull/129166) that was merged on master today and is breaking all the Objects Poshi tests. We should wait for the [fix](https://github.com/liferay-objects/liferay-portal/pull/1662) to be merged to get a realist result from CI. Thanks!

**Comment by kiwm** [comment]
ci:test:relevant

**Comment by kiwm** [comment]
ci:test:sf

**Comment by kiwm** [comment]
ci:stop

**Comment by kiwm** [comment]
ci:test:sf

**Comment by kiwm** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by epark18** [comment]
ci:test:relevant

**Comment by epark18** [comment]
ci:test:object

**Comment by epark18** [comment]
Rerunning tests due to a random failure in most recent results.

**Comment by epark18** [comment]
ci:test:relevant
ci:test:object

**Comment by epark18** [comment]
ci:test:object

**Comment by epark18** [comment]
Results look good to me

**Comment by kiwm** [comment]
Renset here: [#129623](https://github.com/brianchandotcom/liferay-portal/pull/129623)

**Pull request closed without merging**
