### PR TITLE
LPS-158366

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:upgrade

**Comment by diogocordeiro** [comment]
ci:test:upgrade-all

**Comment by mateussgn** [comment]
ci:reevaluate:1367401_1644

**Comment by gabrielwas** [comment]
@mateussgn the build mentioned in https://github.com/liferay-objects/liferay-portal/pull/838#issuecomment-1192883737 has to finish first so we can run `ci:reevaluate`.

Build: [upstream build](https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/3582)

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:reevaluate:1367401_1644

**Comment by gabrielwas** [comment]
ci:forward

**Pull request closed without merging**
