### PR TITLE
LPD-22720 remove FF

### PR DESCRIPTION
**Pull request by linolaoj**
This is the rebase of https://github.com/liferay-objects/liferay-portal/pull/3393

Related issue: https://liferay.atlassian.net/browse/LPD-5446

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by rijema** [comment]
ci:reevaluate:1407401_9782

**Comment by rijema** [comment]
ci:test:relevant

**Comment by rijema** [comment]
ci:stop

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:stop

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:object

**Comment by guilhermedcamacho** [comment]
See #3431

**Pull request closed without merging**
