### PR TITLE
LPS-201521 - Import/Export Object Folder Integration Tests

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://liferay.atlassian.net/browse/LPS-201521

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by G-Sa** [comment]
ci:test:relevant

**Comment by G-Sa** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by G-Sa** [comment]
ci:test:stable

**Review by G-Sa — APPROVED** [review]

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
This code is different from this PR: https://github.com/liferay-objects/liferay-portal/pull/2979

**Pull request closed without merging**
