### PR TITLE
Remove Feature Flag LPS-164278 | LPS-166838

### PR DESCRIPTION
**Pull request by murilostodolni**
https://issues.liferay.com/browse/LPS-167267
https://issues.liferay.com/browse/LPS-164830

### CODE REVIEW

**Comment by murilostodolni** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
Manually forwarding: https://github.com/brianchandotcom/liferay-portal/pull/126687

**Pull request closed without merging**
