### PR TITLE
LPD-38024 [Test Fix] testDeleteCompanyObjectFolders

### PR DESCRIPTION
**Pull request by JhossephG**
Test fix from: https://liferay.atlassian.net/issues/LPD-38024

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Review by guilhermedcamacho — APPROVED** [review]

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Hey @JhossephG, can you check if `ObjectFolderLocalServiceTest` passed the CI results? If so, please forward the PR to Brian.

**Comment by JhossephG** [comment]
It passed, I'll forward. Thanks!

**Comment by JhossephG** [comment]
ci:forward:force

**Comment by JhossephG** [comment]
ci:forward:force

**Comment by JhossephG** [comment]
ci:forward

**Comment by JhossephG** [comment]
ci:forward:force

**Pull request closed without merging**
