### PR TITLE
LPS-167257 Add integration tests for LPS-164801

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://issues.liferay.com/browse/LPS-167257

### CODE REVIEW

**Comment by carolmariaabb** [comment]
This PR depends on https://github.com/liferay-objects/liferay-portal/pull/1299

**Comment by marcelabc** [comment]
I'm removing the label since the https://github.com/brianchandotcom/liferay-portal/pull/125758 was merged

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:reevaluate:1387401_4671

**Comment by carolmariaabb** [comment]
Forwarded manually: https://github.com/brianchandotcom/liferay-portal/pull/125813

**Pull request closed without merging**
