### PR TITLE
LPS-158994

### PR DESCRIPTION
**Pull request by gabrielwas**
Solved conflicts from https://github.com/liferay-objects/liferay-portal/pull/891

cc @LuisOrtiz89 @achaparro

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by LuisOrtiz89** [comment]
ci:reevaluate:1277401_5068

**Comment by gabrielwas** [comment]
ci:reevaluate:1387401_3789

**Comment by samuelromeiro** [comment]
Hey @LuisOrtiz89, can you take a look to see if the tests that are failing are related to your changes? If not, I feel that we can send manually to Brian :)

**Comment by LuisOrtiz89** [comment]
ci:test:db-partition

**Comment by susanchen3** [comment]
:detective: Reviewed, there are some db partition integration test failures, [full logs here](https://testray.liferay.com/reports/production/logs/2022-09/test-1-30/test-portal-acceptance-pullrequest(master)/4734/modules-integration-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0).

com.liferay.portal.db.partition.test.DBPartitionUtilTest > testForEachCompanyId
```
     [exec] com.liferay.portal.db.partition.test.DBPartitionUtilTest > testForEachCompanyId FAILED
     [exec]     java.lang.AssertionError: [270, 274, 275, 276, 277, 278, 279] expected:<3> but was:<7>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
```
com.liferay.portal.db.partition.test.DBPartitionTest > testUpdateIndexes
```
     [exec] com.liferay.portal.db.partition.test.DBPartitionTest > testUpdateIndexes FAILED
     [exec]     java.sql.SQLSyntaxErrorException: Table 'TestTable' already exists
     [exec]     	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
```
com.liferay.portal.db.partition.test.DBPartitionTest > testUpgrade
```
     [exec] com.liferay.portal.db.partition.test.DBPartitionTest > testUpgrade FAILED
     [exec]     array lengths differed, expected.length=3 actual.length=13; arrays first differed at element [2]; expected:<987654321> but was:<123456789>
     [exec]     	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:78)
```

**Comment by LuisOrtiz89** [comment]
ci:close

**Pull request closed without merging**
