### PR TITLE
LPS-176408 Sort

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
@jkappler 

I forgot to test this case below:

Given: 

- Book M:M Author
- Define the relationship on Book side

we know that from Book side we will be able to see the related authors, but will we be able to see all author's books?

Best Regards,
Feliphe Marinho

**Comment by jkappler** [comment]
Hi @MarinhoFeliphe, now I'm unsure. Let's put this PR on hold for the moment and I will do more tests. Thanks for bringing this up!

**Comment by MarinhoFeliphe** [comment]
@jkappler 

Please feel free to contact me if you need help

Thank you!

**Comment by jkappler** [comment]
Hi @MarinhoFeliphe, please see https://github.com/liferay-objects/liferay-portal/pull/1797

**Comment by jkappler** [comment]
ci:close

**Pull request closed without merging**
