### PR TITLE
LPS-149119 Get and retrieve label attribute from ObjectViewColumns by API call

### PR DESCRIPTION
**Pull request by mateussgn**
Related Issue: https://issues.liferay.com/browse/LPS-149119

Related issue: https://issues.liferay.com/browse/LPS-149119

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @mateussgn, can you please check if these failures are related to your changes? Thanks

**Comment by liferay-forms** [comment]
Hey @mateussgn, can you please check if these failures are related to your changes? Thanks

**Comment by liferay-forms** [comment]
Hey @mateussgn, can you please check if these failures are related to your changes? Thanks

**Comment by mateussgn** [comment]
ci:reevaluate:1367401_839

**Comment by marcelabc** [comment]
I'm fixing the baseline.

**Pull request closed without merging**
