### PR TITLE
LPD-8485 / LPD-8486 / LPD-8487 Remove unused Reference

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:object

**Comment by guilhermedcamacho** [comment]
ci:test:headless

**Comment by linolaoj** [comment]
ci:help

**Comment by linolaoj** [comment]
ci:test:object-db-integration

**Pull request closed without merging**
