### PR TITLE
LPS-161513 Add NotificationTermContributor for each system objects

### PR DESCRIPTION
**Pull request by murilostodolni**
Related: https://issues.liferay.com/browse/LPS-161513

### CODE REVIEW

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
ci:test:relevant

**Review by rodrigopaulino — CHANGES_REQUESTED** [review]
Hey, @murilostodolni. Nice catch.
Could you add the feature flag to not register this service?
Thx

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
ci:test:relevant

**Review by rodrigopaulino — APPROVED** [review]
LGTM! 🎉

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:reevaluate:1387401_3381

**Comment by rodrigopaulino** [comment]
ci:forward

**Comment by rodrigopaulino** [comment]
ci:forward

**Comment by rodrigopaulino** [comment]
ci:forward

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by rodrigopaulino** [comment]
Manually forwarded: https://github.com/brianchandotcom/liferay-portal/pull/123287

**Pull request closed without merging**
