### PR TITLE
LPS-160475 Fix the cascade deletion type for M-M relationship

### PR DESCRIPTION
**Pull request by marcelabc**
Follow up: https://github.com/brianchandotcom/liferay-portal/pull/122899

### CODE REVIEW

**Comment by liferay-objects** [comment]
I added the label "High Priority" because I'm fixing integration tests will fail after this review/merge: https://github.com/brianchandotcom/liferay-portal/pull/122899

**Comment by marcelabc** [comment]
I added the label "High Priority" because I'm fixing integration tests will fail after this review/merge: https://github.com/brianchandotcom/liferay-portal/pull/122899

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Send directly to BChan: https://github.com/brianchandotcom/liferay-portal/pull/122990

**Pull request closed without merging**
