### PR TITLE
LPS-162130

### PR DESCRIPTION
**Pull request by evanilson-santana**
https://issues.liferay.com/browse/LPS-162130
https://issues.liferay.com/browse/LPS-185815
https://issues.liferay.com/browse/LPS-184539

### CODE REVIEW

**Comment by murilostodolni** [comment]
PR already approved [here](https://github.com/liferay-objects/liferay-portal/pull/2156) and [here](https://github.com/liferay-objects/liferay-portal/pull/2106).

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
ci:stop

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
ci:test:object

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
same erorr [here](https://liferay.slack.com/archives/C1SJ64S9X/p1685450989961389)

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
ci:close

**Pull request closed without merging**
