### PR TITLE
LPS-188372 Using the user account entry groups to calculate permissions

### PR DESCRIPTION
**Pull request by seltong**
Related issue: [LPS-190878](https://liferay.atlassian.net/browse/LPS-190878)

### CODE REVIEW

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Comment by seltong** [comment]
ci:test:object

**Comment by seltong** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
