### PR TITLE
LPS-139160 It is possible to delete an Object (Custom and System) via API after it was published

### PR DESCRIPTION
**Pull request by mlan0**

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mlan0** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Just started reviewing :)

**Comment by guilhermedcamacho** [comment]
Sent directly to Brian in this [PR](https://github.com/brianchandotcom/liferay-portal/pull/107385)

**Pull request closed without merging**
