### PR TITLE
LPS-158761 Fix filter date value validation to Aggregation Field and Custom View

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-158761

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
@naraandrade can you take a look, please?! :D

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by liferay-workflow — CHANGES_REQUESTED** [review]
@danvb112 I think we shouldn't let the user try to edit a date filter, as we don't allow them to change anything in the filter at this point. You can check that with Gabriel or someone from Product just to confirm that.

**Comment by naraandrade** [comment]
> @danvb112 I think we shouldn't let the user try to edit a date filter, as we don't allow them to change anything in the filter at this point. You can check that with Gabriel or someone from Product just to confirm that.

I commented with the wrong account lol

**Review by naraandrade — CHANGES_REQUESTED** [review]
I commented with the wrong account and cannot delete it lol

**Comment by danvb112** [comment]
Hey @naraandrade, we already discussed this with the product team, in fact in the case of Create Date and Modified Date, we didn't allow editing in Custom View, it had already been fixed, but it happened again because of the withdrawal of FF from the System Fields story. I will add this fix here in this PR.

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
