### PR TITLE
LPS-201591 Remove unnecessary page-wide reloading when adding a new object field, layout, relationship, view and validation

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://liferay.atlassian.net/browse/LPS-201591

### CODE REVIEW

**Comment by rebsilva** [comment]
hey @danvb112, there are some conflicts on this PR, could you please rebase and send again so i can review it? thanks!

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:object

**Comment by rebsilva** [comment]
just started reviewing! :cherry_blossom:

**Comment by rebsilva** [comment]
hey @danvb112, i'll go ahead and already welcome you back! :cherry_blossom: 

just to let you know that this PR has some conflicts with the main code and i couldn't review it. i thought of resolving the conflicts myself but so many things happened that were critical that i didn't have the time, i'm sorry about that :crying_cat_face:

when you have the time to solve the conflicts let me know, so i can review this right away! thanks a lot!

**Pull request closed without merging**
