### PR TITLE
LPS-140233 Remove objectEntries that have any relationship from list

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-140233

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
Taking a look at this

**Comment by MarinhoFeliphe** [comment]
Resent here #851

**Pull request closed without merging**
