### PR TITLE
[TS] LPS-161392

### PR DESCRIPTION
**Pull request by jcampoy**
https://issues.liferay.com/browse/LPS-161392

Previous history https://github.com/liferay-objects/liferay-portal/pull/964 and  https://github.com/liferay-objects/liferay-portal/pull/1022

### CODE REVIEW

**Comment by jcampoy** [comment]
@seltong , I have rebased https://github.com/liferay-objects/liferay-portal/pull/1022

**Comment by jcampoy** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:forward

**Pull request closed without merging**
