### PR TITLE
LPS-159448 Use backend filter operators instead of a static list on the frontend

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-159448

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Review by MarinhoFeliphe — APPROVED** [review]

**Comment by danvb112** [comment]
ci:forward

**Pull request closed without merging**
