### PR TITLE
LPS-169966 [Test-fix] Updating teardown in Object testcases

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LPS-169966

### CODE REVIEW

**Comment by magjed4289** [comment]
ci:test:object:nocompile

**Comment by magjed4289** [comment]
ci:test:object:nocompile

**Comment by magjed4289** [comment]
ci:forward

**Review by xbrianlee — APPROVED** [review]

**Comment by xbrianlee** [comment]
ci:forward

**Pull request closed without merging**
