### PR TITLE
LPS-180610 Apply LPS-167253 Feature Flag

### PR DESCRIPTION
**Pull request by mateussgn**
Related issues:
https://issues.liferay.com/browse/LPS-180610
https://issues.liferay.com/browse/LPS-180618

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:stop

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:object

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:stop

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:object

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
@danvb112 I made changes and updated the PR, can you review it again?

**Comment by mateussgn** [comment]
ci:test:sf

**Review by danvb112 — APPROVED** [review]
LGTM! :tada:

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by mateussgn** [comment]
Hey @naraandrade, are you testing this PR along with another one?
I'm asking because @danvb112 already reviewed :)

**Comment by mateussgn** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
