### PR TITLE
LPS-196352 User cannot change any system object action property via UI, except the label

### PR DESCRIPTION
**Pull request by seltong**
Related issue: [LPS-196352](https://liferay.atlassian.net/browse/LPS-196352)

My changes starts from [this commit](https://github.com/liferay-objects/liferay-portal/pull/2622/commits/bec2a85feac9b29af099002c6a8324921cda8706)

### CODE REVIEW

**Comment by seltong** [comment]
ci:test:sf

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
@seltong Just an issue with the SF. Could you please take a look?

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:object

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
Resent here: https://github.com/liferay-objects/liferay-portal/pull/2637

**Pull request closed without merging**
