### PR TITLE
LPS-170647 Add External Reference Code in Picklists Entries

### PR DESCRIPTION
**Pull request by guilhermedcamacho**
Related issue: https://issues.liferay.com/browse/LPS-170647

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Hey @mateussgn , please check the CI results. Thanks!

**Comment by mateussgn** [comment]
I checked them and asked for QA help on the slack channel. For now, it seems they are not related.

**Comment by mateussgn** [comment]
Directly sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/129422

**Comment by mateussgn** [comment]
ci:close

**Pull request closed without merging**
