### PR TITLE
[TS] LPS-166595 Query all fields

### PR DESCRIPTION
**Pull request by TaiPhamLR**
Dear team,
This is the PR for the ticket https://issues.liferay.com/browse/LPS-166595. Please help me to review this and leave your comments.
Thanks,
Tai.
cc @sontruongces

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
LGTM :D @danvb112 do you agree with the fix?

**Comment by gabrielwas** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:reevaluate:1397401_1308

**Comment by carolmariaabb** [comment]
ci:forward

**Review by danvb112 — APPROVED** [review]
LGTM!

**Comment by danvb112** [comment]
ci:forward

**Comment by pyoo47** [comment]
ci:reevaluate:1317401_5654

**Comment by gabrielwas** [comment]
ci:reevaluate:1317401_5654

**Comment by danvb112** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
Unrelated Failures

Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/125526

**Comment by carolmariaabb** [comment]
ci:close

**Pull request closed without merging**
