### PR TITLE
LPS-163914 Add "company.id" property when registering ItemInfo services so that we avoid returning Object-related services for the wrong company

### PR DESCRIPTION
**Pull request by mbowerman**
Please see detailed issue information and steps to reproduce at https://issues.liferay.com/browse/LPS-163914

/cc @liferay-core-infra

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@mbowerman Please avoid using Stream as its performance is bad.

Tina

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@mbowerman I merged this and put it in the temp branch too.

**Pull request closed without merging**
