### PR TITLE
LPS-168235 Adapt integration tests to make sure it is possible to use the ObjectDefinition api

### PR DESCRIPTION
**Pull request by seltong**

### CODE REVIEW

**Comment by seltong** [comment]
ci:test:relevant

**Review by MarinhoFeliphe — APPROVED** [review]
Very nice!!

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/126143

**Pull request closed without merging**
