### PR TITLE
LPS-202193 | master

### PR DESCRIPTION
**Pull request by carolmariaabb**
Follow-up: https://github.com/liferay-objects/liferay-portal/pull/2887

Jira Issue: https://liferay.atlassian.net/browse/LPS-202193

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
