### PR TITLE
LPD-35901 Revert changes to only send fileBase64 as a nested field

### PR DESCRIPTION
**Pull request by devpedrotavares**
Related ticket: [LPD-35901](https://liferay.atlassian.net/browse/LPD-35901)

[LPD-35901]: https://liferay.atlassian.net/browse/LPD-35901?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by linolaoj — APPROVED** [review]

**Comment by linolaoj** [comment]
ci:test:objects

**Comment by linolaoj** [comment]
ci:test:object

**Comment by devpedrotavares** [comment]
ci:report:7439010

**Comment by devpedrotavares** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
ci:test:object

**Comment by devpedrotavares** [comment]
ci:test:object

**Comment by devpedrotavares** [comment]
ci:report:8250864

**Comment by devpedrotavares** [comment]
ci:report:8271497

**Pull request closed without merging**
