### PR TITLE
LPS-144873 Fix integration tests

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: [LPS-144868](https://issues.liferay.com/browse/LPS-144868) [LPS-144872](https://issues.liferay.com/browse/LPS-144872) [LPS-144873](https://issues.liferay.com/browse/LPS-144873)

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
Just started reviewing :)

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:stop

**Comment by marcelabc** [comment]
ci:stop

**Comment by gabrielwas** [comment]
Just started reviewing :)

**Pull request closed without merging**
