### PR TITLE
LPD-30142 Primary key from modifiable system objects have to starts with l_

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPD-30142

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by rijema** [comment]
ci:test:sf

**Comment by rijema** [comment]
ci:test:sf

**Comment by rijema** [comment]
FYI @p-albuquerque https://liferay.slack.com/archives/C19PWQ74J/p1726547814105259?thread_ts=1726547805.974819&cid=C19PWQ74J.

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Pull request closed without merging**
