### PR TITLE
LPS-163672

### PR DESCRIPTION
**Pull request by mbowerman**
Please see the LPS description for a detailed explanation and steps to reproduce the issue: https://issues.liferay.com/browse/LPS-163672

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
