### PR TITLE
LPS-167875 Avoid null pointer exception if listTypeEntry don't exist

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
---
Prevent undesired errors on content page editor when a list type entry doesn't exist

Proposed Solution
---
Prevent null pointer exception returning an empty string if the  list type entry doesn't exist

[Link](https://issues.liferay.com/browse/LPS-167875)

### CODE REVIEW

**Comment by gabrielwas** [comment]
Thanks for the contribution, @ealonso! LGTM

**Comment by gabrielwas** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1387401_4746

**Comment by ealonso** [comment]
ci:forward

**Comment by silasbsi** [comment]
ci:forward

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
BPM QAs checked the unique failures and they are not related to the changes. Forwarding to Brian.

**Comment by gabrielwas** [comment]
Sent to Brian here https://github.com/brianchandotcom/liferay-portal/pull/126205

**Comment by Lucas2691** [comment]
Thanks @gabrielwas

**Pull request closed without merging**
