### PR TITLE
LPS-170026 Typo for Aggregation Filter Types

### PR DESCRIPTION
**Pull request by Valmir-unicap**
Related issue: https://issues.liferay.com/browse/LPS-170026

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Review by naraandrade — CHANGES_REQUESTED** [review]
Hi @Valmir-unicap, we already have language keys `is-not-equal-to` and `is-equal-to` with the correct values. You can just simply delete the keys `equals-to` and `not-equals-to`, just remember to update all the places where they're being used to use the first ones that I mentioned. Thanks :)

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Pull request closed without merging**
