### PR TITLE
LPD-35068 add `themeId` field to `StyleBookEntry`

### PR DESCRIPTION
**Pull request by thiago-buarqque**
@gabrielwas 

Resent from https://github.com/liferay-platform-experience/liferay-portal/pull/730
Ticket: https://liferay.atlassian.net/browse/LPD-35068

# Goal
To add a new field to the `StyleBookEntry` entity to keep track of the theme in which the Style Book was based on.

# Approach

Modify style-book-service module and make sure previous versions of Liferay  get the required upgrade for the tables.

## Future tickets

In the future we will be using the `themeId` field to fetch the theme's name and the frontend token definition so that the Style Book can be created based on the provided tokens.

-----
### Original Description
https://liferay.atlassian.net/browse/LPD-35068
Modified based on https://github.com/liferay-platform-experience/liferay-portal/pull/712  

cc: @SelenaAungst

### CODE REVIEW

**Comment by gabrielwas** [comment]
@thiago-buarqque LGTM!

**Review by gabrielwas — APPROVED** [review]

**Comment by thiago-buarqque** [comment]
@gabrielwas Running CI and forwarding it to Brian. Thanks Gabriel!

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Pull request closed without merging**
