### PR TITLE
LPS-178473 Fix getRelationshipValue and _getRelationshipId methods and fix matcher Pattern

### PR DESCRIPTION
**Pull request by DaneszLR**
Hi Team!

This pull request is related to https://github.com/liferay-objects/liferay-portal/pull/1941 as a first pull request with a description.
This pull request is also related to https://github.com/liferay-objects/liferay-portal/pull/1956 but with the conflicts resolved and the logic fixed.

Related also to https://github.com/liferay-objects/liferay-portal/pull/2008 which got closed because something else needed to be fixed beforehand, that made the code not work

Slack thread regarding the last issue: https://liferay.slack.com/archives/C5E1CRLJY/p1682432830072949

Best regards,
Dani

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Just started reviewing :)

**Comment by marcelabc** [comment]
Hey @DaneszLR, thank you so much for contributing to our team :smile: 
I adapted the code to the object's pattern. Please, see https://github.com/liferay-objects/liferay-portal/pull/2149.
let me know if you have any question!

**Pull request closed without merging**
