### PR TITLE
LPS-160348 Remove FF of many-to-many relationships between the same object

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://issues.liferay.com/browse/LPS-160348

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:forward

**Comment by naraandrade** [comment]
@marcelabc we have some conflicts in this branch :/

**Comment by marcelabc** [comment]
ci:test:sf

**Review by danvb112 — APPROVED** [review]
LGTM! :tada:

**Comment by danvb112** [comment]
ci:forward

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:reevaluate:1257401_4786

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
@marcelabc We have some conflicts in this branch. Could you please take a look? Thanks :)

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
sent to brian: https://github.com/brianchandotcom/liferay-portal/pull/124153

**Comment by marcelabc** [comment]
sent to brian: https://github.com/brianchandotcom/liferay-portal/pull/124153

**Pull request closed without merging**
