### PR TITLE
LPS-157214 Remove FF of Notification Queue

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPS-157214

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:forward

**Comment by p-albuquerque** [comment]
ci:forward

**Comment by gabrielwas** [comment]
ci:forward

**Pull request closed without merging**
