### PR TITLE
LPS-181071 Fix inconsistent loading of relationship tab in notification template

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://liferay.atlassian.net/browse/LPS-181071

### CODE REVIEW

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — CHANGES_REQUESTED** [review]
Great job, @danvb112! But I noticed that every time we try to filter the columns in the tables or copy one of terms, the section is being collapsed. Could you take a look at it, please?

**Comment by danvb112** [comment]
Hey @naraandrade, Thanks for noticing that, I switched from `onClick` to `onExpandedChange`, that should fix the issue :smile:

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Comment by danvb112** [comment]
Sent to: https://github.com/brianchandotcom/liferay-portal/pull/138144

**Pull request closed without merging**
