### PR TITLE
LPS-189550 Remove Feature Flag from LPS-181431 Organizations as System Objects

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://liferay.atlassian.net/browse/LPS-189550

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:object

**Review by p-albuquerque — APPROVED** [review]

**Comment by mateussgn** [comment]
ci:test:object

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by samuelromeiro** [comment]
Blocked until fix this bug: [LPS-189671](https://liferay.atlassian.net/browse/LPS-189671)

**Review by MarinhoFeliphe — APPROVED** [review]

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:object

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM!! :tada:

**Comment by MarinhoFeliphe** [comment]
ci:forward:force

**Pull request closed without merging**
