### PR TITLE
LPS-178404 Objects filter id returns all the results when inserting a string on contains at getRaylifeClaimsPage

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPS-178404](https://issues.liferay.com/browse/LPS-178404)

### CODE REVIEW

**Review by MarinhoFeliphe — CHANGES_REQUESTED** [review]

**Comment by MarinhoFeliphe** [comment]
@pedro-oliveira446 very nice!

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Review by MarinhoFeliphe — APPROVED** [review]

**Comment by MarinhoFeliphe** [comment]
@pedro-oliveira446 we have a failure related to semantic versioning [here](https://testray.liferay.com/home/-/testray/case_results/2253985998?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2253976460%26cur%3D1%26delta%3D200%26tab%3Druns%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc), please run gw baseline in **objects-api** and put the changes in another commit with the message "Semver"

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Pull request closed without merging**
