### PR TITLE
LPS-189722 Show all ObjectDefinition DTOFields in Import/Export center

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPS-189722

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Review by mateussgn — APPROVED** [review]
LGTM! 🎉

**Comment by mateussgn** [comment]
Hey, @guilhermedcamacho, could you double-check this PR?

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Review by guilhermedcamacho — CHANGES_REQUESTED** [review]

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:object

**Comment by guilhermedcamacho** [comment]
Hey @p-albuquerque , once the object suite has been completed, can you check for CI related errors for this and relevant suite?

**Comment by p-albuquerque** [comment]
ci:forward:force

**Pull request closed without merging**
