### PR TITLE
[TS] LPS-196306 Tags and Categories are not linked when adding Account Nested objects via API

### PR DESCRIPTION
**Pull request by dcarrillolf**
Related issue: https://liferay.atlassian.net/browse/LPS-196306

### CODE REVIEW

**Comment by dcarrillolf** [comment]
This is our first approach to the problem that can solve it, but I do not know if there are some other cases not taken into account.

- Reused private methods from DefaultObjectEntryManagerImpl.java in ObjectRelationshipExtensionProvider.java.

Thank you

**Comment by crodriguezy** [comment]
@marcelabc @guilhermedcamacho were you able to take a look at this PR? Please take into account this is a priority coming from an LXC customer.
Thank you!

**Comment by guilhermedcamacho** [comment]
> @marcelabc @guilhermedcamacho were you able to take a look at this PR? Please take into account this is a priority coming from an LXC customer.
> 
> Thank you!

I will review it today, sorry for the delay.

**Comment by guilhermedcamacho** [comment]
Just started reviewing :)

**Comment by samuelromeiro** [comment]
Hey @crodriguezy, have this ticket followed the escalation process? Can you inform the customer that is requesting this? We are working on some other priorities righ now and I would like to understand how this ticket was flagged as a priority.

**Comment by dcarrillolf** [comment]
Hello everyone, this PR was moved to headless.
Thank you very much

**Pull request closed without merging**
