### PR TITLE
LPS-195657 | master

### PR DESCRIPTION
**Pull request by leilanyaragao**
Jira Issue: https://liferay.atlassian.net/browse/LPS-195657

### CODE REVIEW

**Comment by leilanyaragao** [comment]
ci:test:object

**Comment by murilostodolni** [comment]
This PR is blocked waiting for response of this [theard](https://liferay.slack.com/archives/C026UR5976G/p1694808425388099?thread_ts=1694185301.607349&cid=C026UR5976G).

**Comment by murilostodolni** [comment]
Hey @leilanyaragao 

As discussed in this thread. We need refactor to follow the approach aligned.  I will close this PR for now, ok? Let me know if you have questions.

Thank you

**Comment by murilostodolni** [comment]
ci:close

**Pull request closed without merging**
