### PR TITLE
LPS-176005 Change filter to allow setting predefined values ​​on System Object Fields

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPS-176005](https://issues.liferay.com/browse/LPS-176005)
[LPS-176006](https://issues.liferay.com/browse/LPS-176006)

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Review by rebsilva — APPROVED** [review]
LGTM! Great work @pedro-oliveira446 :tada: :cherry_blossom:

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Comment by pedro-oliveira446** [comment]
Resent here : https://github.com/brianchandotcom/liferay-portal/pull/131266

**Pull request closed without merging**
