### PR TITLE
LPS-171435 Translation on System Fields is not working with the auto generated view

### PR DESCRIPTION
**Pull request by carolmariaabb**
Follow-up: https://github.com/liferay-objects/liferay-portal/pull/1590

https://issues.liferay.com/browse/LPS-171435

### CODE REVIEW

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Manually forwarded: https://github.com/brianchandotcom/liferay-portal/pull/128859

**Pull request closed without merging**
