### PR TITLE
LPS-163843 Get back the Scripting Console with groovy scripts for Server Administrator 

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://issues.liferay.com/browse/LPS-163843

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Review by rodrigopaulino — APPROVED** [review]
Nice job, @carolmariaabb! 👏🏻 
LGTM

**Comment by gabrielwas** [comment]
Nice jobs!

@rodrigopaulino @carolmariaabb do we know who the owner of this component is?

**Comment by rodrigopaulino** [comment]
Hey, @carolmariaabb. Would you please ask the U&SM team's review? Also, please let them know what made us change this by showing the discussion about current scripting executor and LXC (this can be done over Slack). Thx!

**Comment by carolmariaabb** [comment]
Sent to https://github.com/liferay-usm/liferay-portal/pull/764

**Pull request closed without merging**
