### PR TITLE
LPS-198587 Refactor the MultiSelect component to no longer use BaseSelect

### PR DESCRIPTION
**Pull request by danvb112**
Related issue: [LPS-198587](https://liferay.atlassian.net/browse/LPS-198587)

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:object

**Comment by rebsilva** [comment]
just started reviewing!

**Review by rebsilva — APPROVED** [review]
LGTM! :tada: Amazing job @danvb112! :cherry_blossom:

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:object

**Comment by danvb112** [comment]
Sent to: https://github.com/liferay-objects/liferay-portal/pull/2823

**Pull request closed without merging**
