### PR TITLE
LPS-168029 Fix Relationship Field exhibition in TableFDSView

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPS-168029

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@p-albuquerque a8e7917865813c14892083bd824d7fd8e61ad839

I merged this to master and the temp branch

**Comment by carolmariaabb** [comment]
ci:close

**Pull request closed without merging**
