### PR TITLE
LPS-198587 Refactor the MultiSelect component to no longer use BaseSelect and fix all related poshi tests

### PR DESCRIPTION
**Pull request by andreefarias**
Related issue: [LPS-198587](https://liferay.atlassian.net/browse/LPS-198587)
**Ticket**: [LPS-201095](https://liferay.atlassian.net/browse/LPS-201095)

## Refactor:
Change the structure (macro/paths) to click or assert the input correctly.

## Testcases fixed: 
Several tests fixed (include the singleSelect)

image

### CODE REVIEW

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
ci:test:object

**Comment by andreefarias** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
Sent to: https://github.com/brianchandotcom/liferay-portal/pull/143551

**Pull request closed without merging**
