### PR TITLE
 LPS-164939 Error message is not displayed when trying to add a special character to key in Picklist

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**
Related issue: h[ttps://issues.liferay.com/browse/LPS-164939](https://issues.liferay.com/browse/LPS-164939)

### CODE REVIEW

**Comment by GabrielHenriquedev** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Review by danvb112 — APPROVED** [review]
LGTM :tada:

**Comment by danvb112** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:reevaluate:1307401_5504

**Comment by GabrielHenriquedev** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by GabrielHenriquedev** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Opened a QA Request to check if the failures are related: https://liferay.slack.com/archives/C048YNC5GRK/p1670244722787699

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/127240

**Pull request closed without merging**
