### PR TITLE
LPS-194197 Validation tab header is not showing

### PR DESCRIPTION
**Pull request by larissacribeiro**
Related Issue: [LPS-194197](https://liferay.atlassian.net/browse/LPS-194197)

### CODE REVIEW

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by alinedoleron** [comment]
ci:test:forward

**Comment by alinedoleron** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
