### PR TITLE
LPS-137592 Integrate Picklist with Forms

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-137592

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Just started reviewing :)

**Comment by guilhermedcamacho** [comment]
ci:stop

**Comment by guilhermedcamacho** [comment]
Resent on #118

**Comment by guilhermedcamacho** [comment]
ci:close

**Pull request closed without merging**
