### PR TITLE
LPS-164006 Remove FF of LPS-152650

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPS-164006

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:reevaluate:1327401_6439

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Resent https://github.com/liferay-objects/liferay-portal/pull/1326

**Comment by carolmariaabb** [comment]
ci:close

**Pull request closed without merging**
