### PR TITLE
LPS-171700 Implement integration tests for ObjectActionResource

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPS-171700

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:help

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
LGTM!! :tada:

**Comment by p-albuquerque** [comment]
ci:forward

**Comment by p-albuquerque** [comment]
Resent in: https://github.com/brianchandotcom/liferay-portal/pull/128204

**Pull request closed without merging**
