### PR TITLE
LPS-179976 Create Object Definition Resources without create a user

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-179976

### CODE REVIEW

**Comment by mateussgn** [comment]
@gabrielwas Can you review these added modifications?

**Comment by gabrielwas** [comment]
In Review :)

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:object

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:object

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:object

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:object

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
Hey @marcelabc, could you review this PR?

**Comment by mateussgn** [comment]
ci:close

**Pull request closed without merging**
