### PR TITLE
LPS-187375 Fix integration tests

### PR DESCRIPTION
**Pull request by carolmariaabb**
Related Issues: 
https://liferay.atlassian.net/browse/LPS-189230
https://liferay.atlassian.net/browse/LPS-187169

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
