### PR TITLE
LPS-149051 Notification Queue

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPS-149051

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:reevaluate:1337401_1985

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:stop

**Comment by gabrielwas** [comment]
resent here: https://github.com/liferay-objects/liferay-portal/pull/777

**Pull request closed without merging**
