### PR TITLE
LPS-166558 - changed index that indicates which box should be deleted

### PR DESCRIPTION
**Pull request by HenriquePereiraa**
LPS: https://issues.liferay.com/browse/LPS-166558

I changed the index that indicates which box should be excluded, because before the code was getting the index of the position of the tab (tabIndex) and not of the box (boxIndex). This way, it leaves the fields of this box free again

### CODE REVIEW

**Comment by gabrielwas** [comment]
@alinedoleron @danvb112 could any of you take a look here, please? Thx

**Review by danvb112 — APPROVED** [review]
LGTM! :tada:

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:forward

**Pull request closed without merging**
