### PR TITLE
LPS-140335 Show only approved object entries on item selector

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-140335

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Hey @mateussgn , can you recheck if you had commit all changes generated by buildService?
The error says:
**Detected build services changes. See above build services log for more information. Make sure to commit in all build services results.**

**Comment by mateussgn** [comment]
Sure, if not I'll build it again to make sure everything was committed.

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
@guilhermedcamacho All tests had passed, can I forward this PR?

**Review by guilhermedcamacho — APPROVED** [review]

**Comment by guilhermedcamacho** [comment]
ci:forward

**Pull request closed without merging**
