### PR TITLE
LPS-142893 Add tests for the Clob type

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Hey @marcelabc , Looks good, just a minor stuff, I wouldn't change the class `ObjectDefinitionLocalServiceTest.java`, as it seems that these testes were not made with the intention to stress all kinds of field types here. This kind of tests were made in `ObjectEntryLocalServiceTest.java` where they tested all kinds of fields including Blob type (you already added Clob type correctly there). What do you think?

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
