### PR TITLE
LPD-30312 Selected node style does not persist when dragging an unselected node in the Model Builder

### PR DESCRIPTION
**Pull request by larissacribeiro**
Related Issue: [LPD-30312]( https://liferay.atlassian.net/browse/LPD-30312)

[LPD-30312]: https://liferay.atlassian.net/browse/LPD-30312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by larissacribeiro** [comment]
ci:test:sf

**Comment by larissacribeiro** [comment]
ci:test:sf

**Review by igor-franca — APPROVED** [review]

**Comment by igor-franca** [comment]
ci:test:playwright

**Comment by igor-franca** [comment]
ci:test:object

**Comment by igor-franca** [comment]
ci:test:relevant

**Comment by larissacribeiro** [comment]
ci:test:object

**Comment by larissacribeiro** [comment]
The failures are unrelated.

**Comment by larissacribeiro** [comment]
ci:forward

**Pull request closed without merging**
