### PR TITLE
LPS-197333 Remove feature flag of story LPS-187695

### PR DESCRIPTION
**Pull request by devpedrotavares**
Related ticket: [LPS-197333](https://liferay.atlassian.net/browse/LPS-197333)

### CODE REVIEW

**Review by murilostodolni — APPROVED** [review]
LGTM 🎉

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
