### PR TITLE
LPS-201551 Also validate if the field already contains data when creating a new ObjectValidationRule, not just when updating

### PR DESCRIPTION
**Pull request by carolmariaabb**
Related Issue: https://liferay.atlassian.net/browse/LPS-201551

### CODE REVIEW

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:test:stable

**Comment by carolmariaabb** [comment]
ci:test:stable

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
