### PR TITLE
LPS-193250 Publish all Children Objects in a row during their Root Object publication. Block standalone publication for children Objects

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPS-193250

Starts in: [8c0cf18](https://github.com/liferay-objects/liferay-portal/pull/2505/commits/8c0cf18e4e168dd606e81cc9cf511aa22cce7eb9)

### CODE REVIEW

**Review by mateussgn — APPROVED** [review]
LGTM! 🎉

**Comment by mateussgn** [comment]
Hey @MarinhoFeliphe , could you please double-check this PR?

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
Resent here: https://github.com/liferay-objects/liferay-portal/pull/2523

**Pull request closed without merging**
