### PR TITLE
LPS-188851 Create ObjectModel DTO and endpoints

### PR DESCRIPTION
**Pull request by murilostodolni**
Related: https://liferay.atlassian.net/browse/LPS-188851

### CODE REVIEW

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
ci:test:object

**Review by seltong — APPROVED** [review]
LGTM

**Comment by murilostodolni** [comment]
ci:stop

**Comment by murilostodolni** [comment]
ci:close

**Comment by murilostodolni** [comment]
CI relevant broke. Resent to: https://github.com/liferay-objects/liferay-portal/pull/2300

**Pull request closed without merging**
