### PR TITLE
LPS-200746 Remove possibility of sending outdated properties to SET_SELECTED_OBJECT_RELATIONSHIP_EDGE

### PR DESCRIPTION
**Pull request by igor-franca**
related [ticket](https://liferay.atlassian.net/browse/LPS-200746)

### CODE REVIEW

**Comment by igor-franca** [comment]
ci:test:sf

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:object

**Comment by igor-franca** [comment]
ci:forward:force

**Pull request closed without merging**
