### PR TITLE
LPS-175319 It must be fetched by ERC field in order to work with other implementations of ObjectEntryManager

### PR DESCRIPTION
**Pull request by guilhermedcamacho**
Related ticket: https://issues.liferay.com/browse/LPS-175319

### CODE REVIEW

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:reevaluate:1267401_7615

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Manually forwarded to [brianchandotcom#130317](https://github.com/brianchandotcom/liferay-portal/pull/130317)

**Pull request closed without merging**
