### PR TITLE
[Technical debt] LPS-172602 Highlight the selected option in the dropdown of Selects 

### PR DESCRIPTION
**Pull request by alinedoleron**
https://issues.liferay.com/browse/LPS-172602

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:object

**Comment by alinedoleron** [comment]
ci:reevaluate:1337401_2720

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:stop

**Comment by alinedoleron** [comment]
QA approved: 
https://liferay.slack.com/archives/C048YNC5GRK/p1675276884154329?thread_ts=1675109718.025009&cid=C048YNC5GRK

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — CHANGES_REQUESTED** [review]
@alinedoleron just a small change. We need to display the selected option with the same style that hovered options are displayed to follow [lexicon's standards](https://liferay.design/lexicon/core-components/dropdowns/#default). Thanks :)

**Comment by alinedoleron** [comment]
> > @alinedoleron just a small change. We need to display the selected option with the same style that hovered options are displayed to follow [lexicon's standards](https://liferay.design/lexicon/core-components/dropdowns/#default). Thanks :)
> 
> It's about the Clay implementation, @alinedoleron opened a [thread](https://liferay.slack.com/archives/C04CPMRMXAL/p1675342727107009) about it.

It'll be fixed on this https://github.com/liferay/clay/issues/5341 =D

**Comment by alinedoleron** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/129769

**Pull request closed without merging**
