### PR TITLE
LPS-185815 Validate Salesforce storage type can only be defined with company scope

### PR DESCRIPTION
**Pull request by murilostodolni**
Related: https://issues.liferay.com/browse/LPS-185815

### CODE REVIEW

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
ci:test:object

**Comment by murilostodolni** [comment]
ci:test:relevant

**Review by carolmariaabb — APPROVED** [review]
LGTM! 🎉

**Comment by murilostodolni** [comment]
ci:test:object

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
Sent to: https://github.com/liferay-objects/liferay-portal/pull/2164

**Comment by murilostodolni** [comment]
ci:close

**Pull request closed without merging**
