### PR TITLE
LPS-135870 Make Form Field required when Object Field is required

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Hey @mlan0 , the error below pointed by automated tests seems to be related to this PR. Could you take a look on it?

[exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:dynamic-data-mapping:dynamic-data-mapping-form-evaluator-impl:compileTestJava'.

**Comment by mlan0** [comment]
Resent on #99

**Pull request closed without merging**
