### PR TITLE
LPS-155405 Object API endpoint not using plural label

### PR DESCRIPTION
**Pull request by TaiPhamLR**
Hi team, please help me review this PR for the ticket [LPS-155405](https://issues.liferay.com/browse/LPS-155405) and give your comments. 
Thanks,
Tai.

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
@seltong Just reminding you to review this PR :)

**Comment by seltong** [comment]
Hi @TaiPhamLR, sorry for delay.

I talked to the team and we came to the conclusion that [this](https://issues.liferay.com/browse/LPS-155405) ticket is not a bug (a perceived bug at most). We cannot use the Plural label for this case because it is mutable. 

The long term solution will be the API builder, where the users will have full control on which RESTContextPath to use. This solution will be applied by Headless team.

I'm closing the pull request, but feel free to ask if you have any question.

Thank you

**Pull request closed without merging**
