### PR TITLE
LPS-158870 Fix predefinedValues convertion to JSON

### PR DESCRIPTION
**Pull request by seltong**

### CODE REVIEW

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:object

**Comment by brianchandotcom** [comment]
@seltong see e52fbd86e23eb917da22b06c3e031f5aca58aadd

I didn't cherry pick e52fbd86e23eb917da22b06c3e031f5aca58aadd to the temp branch, just your commit.

But I think this is good enough. Please test master. Thx.

**Comment by gabrielwas** [comment]
@seltong could you solve the conflicts?

**Comment by MarinhoFeliphe** [comment]
I Closed because it was cherry-picked by Brian Chan.

**Pull request closed without merging**
