### PR TITLE
LPS-164439

### PR DESCRIPTION
**Pull request by alinedoleron**
Ticket: https://issues.liferay.com/browse/LPS-164439

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:stop

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:reevaluate:1387401_4635

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:reevaluate:1327401_6461

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:forward

**Comment by naraandrade** [comment]
@alinedoleron the results were [checked with QA](https://liferay.slack.com/archives/C048YNC5GRK/p1667839532231919), you can send this PR directly to Brian.

**Comment by alinedoleron** [comment]
PR sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/125946

**Pull request closed without merging**
