### PR TITLE
LPS-172575 The deletion type not working when relating Custom Object by Site with Custom Object by Company

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPS-172575](https://issues.liferay.com/browse/LPS-172575)

### CODE REVIEW

**Comment by marcelabc** [comment]
Just started reviewing :)

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
Resent here : https://github.com/brianchandotcom/liferay-portal/pull/130857

**Pull request closed without merging**
