### PR TITLE
LPS-164070 Use Control Panel group for Object PanelApps

### PR DESCRIPTION
**Pull request by balazssk**
Motivation
=======
[LPS-164070](https://issues.liferay.com/browse/LPS-164070)
Currently the Object PanelApp URLs reference the site the link was generated on instead of the Control Panel. this can result in Localisation issue

Proposed Solution
========
If I understand correctly, Objects are Globally scoped entities, so it would be best to use the Control Panel group to avoid any group specific conflicts. I've followed the pattern set by DepotAdminPanelApp to achieve this.

Steps to Verify
========

1. Go to Control Panel > Instance Settings > Localization > Language
2. Add Italian (Italy) (move from Available to Current)
3. Save Localization
4. Go to GUEST site (Liferay DXP)
5. Go to Menu > Configuration > Site Settings > Localization
6. Set Define a custom default language and additional available languages for this site
7. Change Default Language to Italian
8. Save
9. Go to Control Panel > Objects
10. Create new Object (fill out the fields with "test")
11. Click Save

**Expected behaviour:** Object is created
**Actual behaviour:** "An error occurred." Alert is displayed. (Logs indicate missing en_US localisation)

References to existing code
========
The same logic was applied in [DepotAdminPanelApp](https://github.com/liferay/liferay-portal/blob/master/modules/apps/depot/depot-web/src/main/java/com/liferay/depot/web/internal/application/list/DepotAdminPanelApp.java#L70)

Alternative Solutions that were discarded (if applies)
========
Could have changed [PortalImpl](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/util/PortalImpl.java#L7451) to add a new category to this check, but given Objects is a module, I did not want to introduce a magic String here.

### CODE REVIEW

**Comment by balazssk** [comment]
ci:test:relevant

**Review by rodrigopaulino — COMMENTED** [review]
Hi, @balazssk. Thanks a lot for the detailed description and all the information you've provided with the fix.
Just one thing to add... Not all objects' panel apps are scoped by company. The object entry one depends on the object definition scope field value and it is registered dynamically [here](https://github.com/liferay/liferay-portal/blob/4d087767da18b2fbdeea48b705a9dc12b623e594/modules/apps/object/object-web/src/main/java/com/liferay/object/web/internal/deployer/ObjectDefinitionDeployerImpl.java#L347-L355).
Have you considered this on your solution?

Thanks.

**Comment by balazssk** [comment]
Thanks for the help @rodrigopaulino ,
I think https://github.com/liferay-objects/liferay-portal/pull/1115/commits/0d156f94a8c88ac114a5bc1412c7245b85a9006c should solve this

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by balazssk** [comment]
Hi @rodrigopaulino ,
I'm unfamiliar with the Objects REST API
Can you please give a me reproduction steps to understand your use case?

Thanks

**Comment by marcelabc** [comment]
Hi @balazssk, how are you doing?
Following the previous orientation, could you move the verification to the local service side?
Since the problem is related to the creation of an Object Definition, you could look at the classes ObjectDefinitionResourceImpl.java (post method) and ObjectDefinitionServiceImpl.java or ObjectDefinitionLocalServiceImpl.java.  

Let me know if you need any help! Thanks :smile:

**Comment by balazssk** [comment]
Hi @marcelabc ,
I think the background validation is working as intended. 
It throws the correct Exception when the data being validated is incorrect
https://github.com/liferay/liferay-portal/blob/master/modules/apps/object/object-service/src/main/java/com/liferay/object/service/impl/ObjectDefinitionLocalServiceImpl.java#L1412

**Comment by balazssk** [comment]
ci:reopen

**Comment by marcelabc** [comment]
Hi @balazssk, 
Sorry for the delay in answering you. I understand what you mean, so we can move forward with this solution!
Thank you again for contributing :smile:

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
Hey @balazssk 
The CI has been unstable lately, so if you see that the errors are unrelated, you can manually move forward to Brian, okay?

**Comment by marcelabc** [comment]
ci:reevaluate:1377401_5742

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
