### PR TITLE
LPS-185060 Suppress unnecessary joins while performing aggregations

### PR DESCRIPTION
**Pull request by guilhermedcamacho**
Follow-up: https://github.com/liferay-objects/liferay-portal/pull/2117

Related Issue: https://liferay.atlassian.net/browse/LPS-185061

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:object

**Review by carolmariaabb — APPROVED** [review]
LGTM! 🎉

**Comment by guilhermedcamacho** [comment]
ci:forward:force

**Comment by guilhermedcamacho** [comment]
Hey @carolmariaabb , I only sent a small change in the method `_getPrimaryKeyColumn` to use getTableName() instead of getName()

**Comment by timpak** [comment]
ci:test:object-db

**Comment by timpak** [comment]
ci:test:object-db-partition

**Comment by JhossephG** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Manually forwarded to [brianchandotcom#143324](https://github.com/brianchandotcom/liferay-portal/pull/143324)

**Pull request closed without merging**
