### PR TITLE
LPS-183792

### PR DESCRIPTION
**Pull request by gabrielwas**
Related Issues:
https://liferay.atlassian.net/browse/LPS-188894
https://liferay.atlassian.net/browse/LPS-183792

### CODE REVIEW

**Comment by gabrielwas** [comment]
Hey @seltong. The test that failed in https://github.com/liferay-objects/liferay-portal/pull/2293 are related. Could you check, please?

**Comment by seltong** [comment]
@gabrielwas are you talking about the ObjectDefinitionResourceTests?

The `LocalFile.ObjectCustomValidation#CanDefineExpressionOperators` test just failed in my pr, I'll check without my changes.

**Comment by seltong** [comment]
As you can see [here](https://testray.liferay.com/reports/production/logs/2023-06/test-1-25/test-portal-acceptance-pullrequest(master)/1687/modules-integration-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0), the ObjectDefinitionResourceTests are failing because of some changes [here](https://github.com/liferay/liferay-portal/blob/595169c9906669d124a1491845eb75c0b357e009/modules/apps/object/object-service/src/main/java/com/liferay/object/internal/definition/util/ObjectDefinitionUtil.java#L28-L46) and [here](https://github.com/liferay/liferay-portal/blob/84b1281cdf3225c5f84129f26c4f50ec25533d41/modules/apps/object/object-service/src/main/java/com/liferay/object/service/impl/ObjectDefinitionLocalServiceImpl.java#L1670-L1676) made related to the modifiable.

**Comment by seltong** [comment]
I ran the `LocalFile.ObjectCustomValidation#CanDefineExpressionOperators` test without my commits, but the test failed. It seems not related to the changes in https://github.com/liferay-objects/liferay-portal/pull/2293

Please let me know if I'm missing something

**Pull request closed without merging**
