### PR TITLE
LPS-196798 Add autosave for Object Fields, Definitions and Relationships in Model Builder using onBlur prop

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://liferay.atlassian.net/browse/LPS-196798

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:sf

**Review by naraandrade — CHANGES_REQUESTED** [review]
Hi @danvb112 Just a really small change needed.

**Review by naraandrade — APPROVED** [review]

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by victorhcunha** [comment]
ci:test:object

**Comment by danvb112** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:forward:force

**Comment by danvb112** [comment]
ci:test:sf

**Pull request closed without merging**
