### PR TITLE
LPS-203702

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:playwright

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
resent here: https://github.com/brianchandotcom/liferay-portal/pull/145254

**Comment by cgmonte** [comment]
resent [here](https://github.com/liferay-objects/liferay-portal/pull/2952), trying to fix stable error.

**Pull request closed without merging**
