### PR TITLE
LPS-201565 Quotation marks end after the period in an error message

### PR DESCRIPTION
**Pull request by larissacribeiro**
**Related Issue**: [LPS-201565](https://liferay.atlassian.net/browse/LPS-201565)

### CODE REVIEW

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
@larissacribeiro please also fix the message in the related test [ObjectFieldLocalServiceTest](https://github.com/carolmariaabb/liferay-portal/blob/e03dbf1a58ce8761ecd270df3bde8f1ae0f088e0/modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/service/test/ObjectFieldLocalServiceTest.java#L309-L380). Thanks!

**Comment by larissacribeiro** [comment]
Just did, @carolmariaabb. Thank you! 😄

**Comment by larissacribeiro** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:forward:force

**Pull request closed without merging**
