### PR TITLE
LPD-35776 Avoid blank page when getAllObject Folders returns undefined in View Object Definition

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://liferay.atlassian.net/browse/LPD-35776

### CODE REVIEW

**Comment by rebsilva** [comment]
hi @danvb112, i don't know if you will have time today but the sf is failing, could you please take a look?
if you can't, i will take care of it soon, thanks!

**Comment by danvb112** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
taking a look! :cherry_blossom:

**Review by rebsilva — APPROVED** [review]
LGTM! :tada:

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:playwright

**Comment by rebsilva** [comment]
taking a look at the tests failures

**Comment by rebsilva** [comment]
the failures don't seem related, i will only run the relevant again to send the PR

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
all the failures are not related even on relevant, can i send directly to brian @marcelabc? or is better to see if the relevant will pass this time?

**Comment by rebsilva** [comment]
ci:forward:force

**Pull request closed without merging**
