### PR TITLE
LPS-140233 Filter entries related when the relationship is many-to-many type

### PR DESCRIPTION
**Pull request by marcelabc**
Related Issue: https://issues.liferay.com/browse/LPS-140233

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @marcelabc, can you please check if these failures are related to your changes? Thanks

**Comment by marcelabc** [comment]
Hi @gabrielwas, how are you doing?
Could you give details related to the label added?

**Comment by gabrielwas** [comment]
@marcelabc do you have any updates about it? Thx

**Pull request closed without merging**
