### PR TITLE
LPS-147108 [FE] Consider new type (Attachment) when adding a new field

### PR DESCRIPTION
**Pull request by miltonmc**

### CODE REVIEW

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
Starting the review :)

**Comment by miltonmc** [comment]
ci:test:sf

**Review by danvb112 — APPROVED** [review]
LGTM! :tada:

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:stop

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:forward

**Pull request closed without merging**
