### PR TITLE
LPS-174544 Create and Publish Bookmarks ObjectDefinition while Portal rise up

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPS-174544

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Waiting the PR related to the ticket [LPS-176689](https://issues.liferay.com/browse/LPS-176689) be sent.

**Comment by guilhermedcamacho** [comment]
Just started reviewing.

**Comment by seltong** [comment]
Resent here: https://github.com/liferay-objects/liferay-portal/pull/1861

**Pull request closed without merging**
