### PR TITLE
LPS-144874 LPS-144875 LPS-144876

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: [LPS-144874](https://issues.liferay.com/browse/LPS-144874) [LPS-144875](https://issues.liferay.com/browse/LPS-144875) [LPS-144876](https://issues.liferay.com/browse/LPS-144876)

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
LGTM :D

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
