### PR TITLE
LPS-205939 Fix creation of picklist states as an objectDefinition field

### PR DESCRIPTION
**Pull request by G-Sa**
Related issue: [LPS-205939](https://liferay.atlassian.net/browse/LPS-205939)

### CODE REVIEW

**Comment by G-Sa** [comment]
ci:test:relevant

**Comment by G-Sa** [comment]
ci:test:object

**Comment by marcelabc** [comment]
Reviewing the CI results.

**Comment by marcelabc** [comment]
I'm testing an improvement in the code.

**Comment by marcelabc** [comment]
Resend: https://github.com/liferay-objects/liferay-portal/pull/3040

**Pull request closed without merging**
