### PR TITLE
LPS-188851 Create ObjectFolder DTO

### PR DESCRIPTION
**Pull request by murilostodolni**
Related:
https://liferay.atlassian.net/browse/LPS-188851
https://liferay.atlassian.net/browse/LPS-188855

In Roles:
-------------------------------
screenshot-1688996506

screenshot-1688996533

In API Rest:
-------------------------------
screenshot-1688996562

### CODE REVIEW

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
Hey @gabrielwas 
Could you review this?

**Review by gabrielwas — CHANGES_REQUESTED** [review]
Can you split the commits and leave the permission part to send with the model PR? Thx

cc @marcelabc

**Comment by murilostodolni** [comment]
Resent to: https://github.com/liferay-objects/liferay-portal/pull/2349

**Pull request closed without merging**
