### PR TITLE
LPS-206413 Verify if the instance is initialized

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://liferay.atlassian.net/browse/LPS-206413

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:object

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:forward

**Comment by marianoalvarosaiz** [comment]
@marcelabc , @carolmariaabb this pull doesn't fix the issue, initial.deployment is only used for verifiers. In fact, if you open the failing tests you can see that the issue is still reproducible, see https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/890492/testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXMLLog/

/cc @achaparro

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:report:2502824915

**Comment by carolmariaabb** [comment]
ci:report:2503403427

**Comment by marcelabc** [comment]
ci:forward:force

**Pull request closed without merging**
