### PR TITLE
LPS-150369 Dedupe form field logic

### PR DESCRIPTION
**Pull request by miltonmc**
Related Issue: https://issues.liferay.com/browse/LPS-150369

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
ci:test:relevant

**Review by danvb112 — APPROVED** [review]
LGTM!

Amazing refactoring @miltonmc!

**Comment by liferay-forms** [comment]
Hey @miltonmc, can you please check if these failures are related to your changes? Thanks

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
Hey @miltonmc, can you check these conflicts?

**Comment by marcelabc** [comment]
Hey @miltonmc, the branch still has conflicts :confused:

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Pull request closed without merging**
