### PR TITLE
LPD-25836 User notifications triggered by object actions are not received by users when their role is assigned through a User Group

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPD-25836](https://liferay.atlassian.net/browse/LPD-25836)

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM!! :tada:

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Pull request closed without merging**
