### PR TITLE
LPS-162822 Inline, rename and keep it simple

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-162822

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:forward

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:forward

**Comment by mateussgn** [comment]
Directly sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/126073

**Comment by mateussgn** [comment]
ci:close

**Pull request closed without merging**
