### PR TITLE
LPS-162972 SF

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://issues.liferay.com/browse/LPS-162972

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by crodriguezy** [comment]
hi, is this PR ready to move forward? There is a customer waiting for the fix. Thanks!

**Comment by marcelabc** [comment]
Send to BChan: https://github.com/brianchandotcom/liferay-portal/pull/124745

**Pull request closed without merging**
