### PR TITLE
LPS-157561 Show author column on custom views

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-157561

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:forward

**Comment by gabrielwas** [comment]
ci:reevaluate:1357401_1929

**Comment by mateussgn** [comment]
ci:forward

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:forward

**Pull request closed without merging**
