### PR TITLE
Lpd 34974 Content of the manage picklist button does not fit inside the button container in some languages

### PR DESCRIPTION
**Pull request by igor-franca**
Related Issue: https://liferay.atlassian.net/browse/LPD-34974
Follow up from https://github.com/liferay-objects/liferay-portal/pull/3665

### CODE REVIEW

**Comment by igor-franca** [comment]
ci:test:playwright

**Comment by igor-franca** [comment]
ci:test:relevant

**Comment by larissacribeiro** [comment]
the failures are unrelated and the test has passed 🎉

**Comment by larissacribeiro** [comment]
ci:forward

**Comment by larissacribeiro** [comment]
ci:stop

**Comment by larissacribeiro** [comment]
ci:forward:force

**Pull request closed without merging**
