### PR TITLE
LPS-159536 Add status attribute for Notification Queue Entries

### PR DESCRIPTION
**Pull request by mateussgn**
Related issues:
 https://issues.liferay.com/browse/LPS-159535
 https://issues.liferay.com/browse/LPS-159536

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:upgrade

**Comment by mateussgn** [comment]
Resend, based on the modifications suggested here: https://github.com/liferay-objects/liferay-portal/pull/868

**Comment by mateussgn** [comment]
ci:test:relevant

**Review by rodrigopaulino — APPROVED** [review]
Awesome. Good job, @mateussgn!

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:forward

**Comment by rodrigopaulino** [comment]
@mateussgn, apparently this has a SF issue.

**Comment by mateussgn** [comment]
ci:forward

**Comment by rodrigopaulino** [comment]
ci:forward

**Pull request closed without merging**
