### PR TITLE
LPS-175321 trigger: "On After Attachment download" does not work

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPS-175321](https://issues.liferay.com/browse/LPS-175321)

### CODE REVIEW

**Review by carolmariaabb — CHANGES_REQUESTED** [review]

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Pull request closed without merging**
