### PR TITLE
LPS-170680 Reorganize and simplify the EditNotificationTemplate code

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-170680

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
@danvb112 we'll have to wait for https://github.com/liferay-objects/liferay-portal/pull/1523 to be merged, because of conflicts.

**Comment by danvb112** [comment]
ci:test:relevant

**Review by naraandrade — CHANGES_REQUESTED** [review]
@danvb112 There are some conflicts in this branch (even though GitHub is not accusing them). Also, could you rename the commits 3, 4 and 5 adjusting "your component" to "its own component"? You did right in the first two :) Thanks!

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:forward

**Comment by naraandrade** [comment]
ci:forward

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/127995

**Pull request closed without merging**
