### PR TITLE
LPD-21601 | LPD-21603 - Make organization roles available for notifications

### PR DESCRIPTION
**Pull request by devpedrotavares**
Related tickets: [LPD-21601](https://liferay.atlassian.net/browse/LPD-21601), [LPD-21603](https://liferay.atlassian.net/browse/LPD-21603)

### CODE REVIEW

**Review by G-Sa — APPROVED** [review]
LGTM :tada:

**Review by carolmariaabb — APPROVED** [review]
LGTM! 🎉

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
