### PR TITLE
LPD-16074 Add default order in related models providers for consistency

### PR DESCRIPTION
**Pull request by devpedrotavares**
Related: [LPD-16074](https://liferay.atlassian.net/browse/LPD-16074)

As requested, this PR takes a different approach to fixing the test, by adding a default sort when fetching related models.

### CODE REVIEW

**Review by G-Sa — APPROVED** [review]

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:report:2548722461

**Comment by carolmariaabb** [comment]
ci:report:2548736676

**Comment by carolmariaabb** [comment]
ci:test:stable

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
