### PR TITLE
LPS-152733 Create a storage type field for Object Definition

### PR DESCRIPTION
**Pull request by guilhermedcamacho**
Related issue: https://issues.liferay.com/browse/LPS-152733

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Review by marcelabc — CHANGES_REQUESTED** [review]
Hey @guilhermedcamacho, how are you doing?
The CI pointed out a baseline error and there is a rebase error. Could you please fix? 

Also, I have one question: Why did you not include this property in the PUT/UPDATE methods?

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
> Hey @guilhermedcamacho, how are you doing? The CI pointed out a baseline error and there is a rebase error. Could you please fix?
> 
> Also, I have one question: Why did you not include this property in the PUT/UPDATE methods?

I'm fine, thanks @marcelabc 
I fixed the baseline error.
Regarding the question related to update method, we have a rule to not allow this property being changed after the object is created. I created a validation in Rest layer to enforce that to the API user, thanks for raising this concern.

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
See [brianchandotcom@117156](https://github.com/brianchandotcom/liferay-portal/pull/117156)

**Pull request closed without merging**
