### PR TITLE
LPS-164093 Apply notifications constants to use

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**
Hi @rodrigopaulino,

you can start the review from f708f54f07280a6e152fc5012ccfe0ecad449b0e

I joined the changes of these two ticket due to this [Brian's comment](https://github.com/brianchandotcom/liferay-portal/pull/123888#issuecomment-1264767076)

Thank you!

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Review by rodrigopaulino — APPROVED** [review]
LGTM! 🎉 
Thanks a lot, @MarinhoFeliphe. You're awesome!

**Comment by MarinhoFeliphe** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/124161

**Pull request closed without merging**
