### PR TITLE
LPD-22831

### PR DESCRIPTION
**Pull request by rijema**

### CODE REVIEW

**Comment by linolaoj** [comment]
Hi @rijema, did you run the baseline task?

**Comment by rijema** [comment]
Yes, Lino =)

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by rijema** [comment]
Hi @linolaoj . Waiting Testray to revive for me to analyse these failures.

**Review by linolaoj — APPROVED** [review]

**Comment by rijema** [comment]
ci:test:relevant

**Comment by rijema** [comment]
ci:test:relevant

**Comment by rijema** [comment]
ci:test:object

**Comment by rijema** [comment]
ci:test:relevant

**Comment by rijema** [comment]
ci:test:relevant

**Comment by rijema** [comment]
ci:stop

**Comment by rijema** [comment]
ObjectEntry failing test not related as you can see through this history:

https://testray.liferay.com/#/project/34754/routines/34756/build/12500321/case-result/12506107/history?page=1

Thanks.

**Pull request closed without merging**
