### PR TITLE
LPS-175527 Create endpoint to retrieve the comments related to an Object's entry through API

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPS-175527](https://issues.liferay.com/browse/LPS-175527)

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Comment by MarinhoFeliphe** [comment]
Closing this pr for while until the this task be prioritized so we can review other details like permissions for example.

**Pull request closed without merging**
