### PR TITLE
LPD-17030 Counting object entries only for guest user

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:object

**Comment by thallescezar** [comment]
ci:report:2535115765

**Comment by thallescezar** [comment]
ci:report:2535122299

**Comment by thallescezar** [comment]
Failed tests are not related

**Comment by thallescezar** [comment]
ci:forward:force

**Pull request closed without merging**
