### PR TITLE
LPS-202062 Send notification to user admin after reached maximum number of guest user object entry

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:object

**Review by thallescezar — APPROVED** [review]

**Comment by guilhermedcamacho** [comment]
ci:stop

**Comment by guilhermedcamacho** [comment]
ci:close

**Comment by guilhermedcamacho** [comment]
See #2971

**Pull request closed without merging**
