### PR TITLE
LPS-200045 Fix unrelated test failures

### PR DESCRIPTION
**Pull request by devpedrotavares**
Related issue: [LPS-200045](https://liferay.atlassian.net/browse/LPS-200045)

### CODE REVIEW

**Review by seltong — APPROVED** [review]
LGTM! :tada:

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by devpedrotavares** [comment]
Sent directly: https://github.com/brianchandotcom/liferay-portal/pull/143089

**Pull request closed without merging**
