### PR TITLE
LPS-162139 Fix testGetObjectDefinition

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by p-albuquerque** [comment]
Resent [here](https://github.com/liferay-objects/liferay-portal/pull/1124), with the last task.

**Comment by p-albuquerque** [comment]
ci:close

**Pull request closed without merging**
