### PR TITLE
LPD-28108 Create functional test to verify if translated picklist item will be displayed on forms

### PR DESCRIPTION
**Pull request by danvb112**
Related Issues:
https://liferay.atlassian.net/browse/LPD-29049
https://liferay.atlassian.net/browse/LPD-29391

### CODE REVIEW

**Review by rebsilva — APPROVED** [review]
LGTM! :tada: thanks for taking care of this @danvb112 :cherry_blossom:

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:playwright

**Comment by danvb112** [comment]
ci:test:playwright

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:playwright

**Comment by danvb112** [comment]
Playwright are not failing anymore! :tada: :rocket:

**Comment by danvb112** [comment]
ci:forward

**Pull request closed without merging**
