### PR TITLE
LPS-186368 Update test to take into account actions

### PR DESCRIPTION
**Pull request by victorg1991**
Just a minor update for including the action check in the test

### CODE REVIEW

**Review by guilhermedcamacho — APPROVED** [review]

**Comment by guilhermedcamacho** [comment]
Hey @victorg1991 , the CI errors are not related, can you send it directly to Brian? Thanks!

**Comment by victorg1991** [comment]
Sure I will @guilhermedcamacho Thanks for the review :)

**Comment by carolmariaabb** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/137158

**Comment by victorg1991** [comment]
Hey @carolmariaabb this pr is already merged sorry i forgot to close it🥲

**Pull request closed without merging**
