### PR TITLE
LPS-189481 Create on after root context update trigger

### PR DESCRIPTION
**Pull request by devpedrotavares**
Related tickets:
* [LPS-195683](https://liferay.atlassian.net/browse/LPS-195683)
* [LPS-195685](https://liferay.atlassian.net/browse/LPS-195685)
* [LPS-195686](https://liferay.atlassian.net/browse/LPS-195686)

### CODE REVIEW

**Comment by devpedrotavares** [comment]
Fixed minor conflicts

**Comment by devpedrotavares** [comment]
ci:test:sf

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
ci:forward:force

**Pull request closed without merging**
