### PR TITLE
LPD-5392 - Turn Root Model FF into release mode

### PR DESCRIPTION
**Pull request by G-Sa**
Related to: [LPD-5392](https://liferay.atlassian.net/browse/LPD-5392)

### CODE REVIEW

**Comment by marcelabc** [comment]
The product team is reviewing the FF label and description.

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
Hey @G-Sa 
Please remove the flag `Blocked` when Brian merges the integration tests and the product team approves the last story.

**Comment by carolmariaabb** [comment]
I will close this PR for now, since the ticket is back In progress.

**Pull request closed without merging**
