### PR TITLE
LPS-160648 Avoid code repetition when using useContext in object View and Layout 

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-160648

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:forward

**Comment by naraandrade** [comment]
Reviewed at: https://github.com/liferay-objects/liferay-portal/pull/914

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:forward

**Comment by danvb112** [comment]
ci:forward

**Comment by danvb112** [comment]
ci:forward

**Comment by danvb112** [comment]
ci:forward

**Pull request closed without merging**
