### PR TITLE
LPS-159034 Avoid Stored XSS on Objects details page

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-159034

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Review by rodrigopaulino — COMMENTED** [review]
Hey, @danvb112. Wouldn't calling `getLabel()` return the XML of the label attribute?

**Comment by danvb112** [comment]
Hey @rodrigopaulino, yes, but when we only get the label, the script doesn't run. For some reason the problem happens when we try to return the localized label, when we pass a Locale or a languageId as a parameter to `getLabel`, the script executes.

**Comment by rodrigopaulino** [comment]
> Hey @rodrigopaulino, yes, but when we only get the label, the script doesn't run. For some reason the problem happens when we try to return the localized label, when we pass a Locale or a languageId as a parameter to `getLabel`, the script executes.

I understand. Would it be helpful then to just escape the label returned from `getLabel(locale)` by using something like `HtmlUtil.escape`?
Let me know. 😄

**Comment by danvb112** [comment]
Hey @rodrigopaulino, I didn't know about `HtmlUtil.escape`, and it worked perfectly! Thanks for the sugestion! :smile:

**Comment by danvb112** [comment]
ci:test:sf

**Review by rodrigopaulino — APPROVED** [review]
LGTM, @danvb112! 👏🏻 
Good job 🎉

**Comment by danvb112** [comment]
ci:forward

**Comment by danvb112** [comment]
ci:forward

**Pull request closed without merging**
