### PR TITLE
LPS-162085 Add test to assure that the objectEntry's values are being cached in finderPath

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://issues.liferay.com/browse/LPS-162085

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:reevaluate:1257401_4631

**Comment by gabrielwas** [comment]
@marcelabc can you check if the failed tests are related, please?

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:forward

**Review by gabrielwas — APPROVED** [review]

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Pull request closed without merging**
