### PR TITLE
LPS-146898

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPS-146898

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Just started reviewing :)

**Comment by marcelabc** [comment]
Please, don't forward this PR. I'm reviewing.

**Comment by marcelabc** [comment]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
