### PR TITLE
LPS-197833 Handle case where the userId is not populated

### PR DESCRIPTION
**Pull request by carolmariaabb**
Related Issue: https://liferay.atlassian.net/browse/LPS-197833

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:reevaluate:1367401_4252

**Comment by carolmariaabb** [comment]
ci:reevaluate:1367401_4252

**Comment by carolmariaabb** [comment]
ci:test:stable

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
