### PR TITLE
LPS-187202 Add delete action

### PR DESCRIPTION
**Pull request by alinedoleron**
Ticket: https://issues.liferay.com/browse/LPS-187202

### CODE REVIEW

**Review by rebsilva — APPROVED** [review]
LGTM! :purple_heart: :tada:

**Comment by rebsilva** [comment]
The failing tests don't seem related, but since the stable failed i will run the CI again

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
