### PR TITLE
LPS-156259 Block groovy script creation on LXC

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-156259

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:forward

**Comment by mateussgn** [comment]
ci:forward

**Comment by rodrigopaulino** [comment]
ci:stop

**Comment by rodrigopaulino** [comment]
@mateussgn, could you please run [com.liferay.object.service.test.ObjectActionLocalServiceTest.testAddObjectActionWithConditionExpression](https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/157509//testReport/com.liferay.object.service.test/ObjectActionLocalServiceTest/testAddObjectActionWithConditionExpression) locally. This apparently is related to your PR. Thx.

**Comment by rodrigopaulino** [comment]
In fact, can you please run all objects tests to confirm no one fails? Thanks.

**Comment by mateussgn** [comment]
It's true, was related to my changes. Now it's fixed.

**Comment by mateussgn** [comment]
ci:forward

**Comment by mateussgn** [comment]
The failures don't seem to be related to my changes, I'll run the tests again.

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:reevaluate:1317401_4633

**Comment by rodrigopaulino** [comment]
@mateussgn, could you please bring this ([modules-integration-mysql57-jdk8/1/1](https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/182668//consoleText)) to the CI channel on Slack to understand its cause? Thanks!

**Comment by mateussgn** [comment]
ci:reevaluate:1317401_4633

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:forward

**Comment by mateussgn** [comment]
ci:close

**Comment by rodrigopaulino** [comment]
Can you link here the new PR? Thx.

**Comment by mateussgn** [comment]
Resent here: https://github.com/liferay-objects/liferay-portal/pull/933

**Pull request closed without merging**
